Update a11y focal, add links to accounts
OpenLiberty/open-liberty pull request #13608
Opened 2020-08-24 13:52 UTC by mbroz2

@steven1046 is the new a11y focal and will need to provide a11y approvals

Add links to each approvers github account.

2020-08-24 13:55 UTC, tevans78 approved these changes

2020-08-24 13:58 UTC, tevans78 requested changes
People links are not right, should be https://github.com/steven1046

2020-08-24 14:10 UTC, mbroz2 commented on .github/ISSUE_TEMPLATE/feature.md
> +- [ ] **Accessibility** - ([Steven Zvonek](https://github.com/orgs/OpenLiberty/people/steven1046)). Accessibility testing is complete or N/A. Approver adds label focalApproved:accessibility to the Ep
seems like it might depend on permissions; changed links to point directly at account

2020-08-24 14:43 UTC, gscottj commented
Thanks!

2020-08-24 15:03 UTC, tevans78 approved these changes
Looks good

2020-09-03 04:01 UTC, mbroz2 commented
@tevans78 since our templates don't have copyright headers, I'm guessing the right thing to do here is to just force merge?

2020-09-08 23:32 UTC, merged