Fix for checkFFDC failures on Java 15
OpenLiberty/open-liberty pull request #13986
Opened 2020-09-16 19:24 UTC by Yushan-Lin

Fixes #13946 
Java 15 has additional field "message" in the ffdc log.

2020-09-16 19:24 UTC, Yushan-Lin commented
#build

2020-09-16 19:27 UTC, Yushan-Lin commented
Java 15: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_LnxVMPhKEeqwgKOHPUEi3Q

2020-09-17 16:04 UTC, fmhwong commented
@Yushan-Lin Do you know why we have a message field in just Java 15?  What does it contain?

2020-09-17 16:24 UTC, Yushan-Lin commented
@fmhwong on Java 15 the NPE thrown outputs an ffdc log with the message field:
`"message":"Cannot invoke \"String.toString()\" because \"myString\" is null"`

2020-09-22 19:17 UTC, Yushan-Lin commented
@fmhwong For Java 15, the exception thrown has a message `"message":"Cannot invoke \"String.toString()\" because \"myString\" is null"` while lower Java versions does not have the message. In FFDC JSON logs, the message field will appear as long as the message is not null.

2020-09-22 19:34 UTC, fmhwong requested changes
See comments

2020-09-22 19:35 UTC, fmhwong commented on dev/com.ibm.ws.logging.json_fat/fat/src/com/ibm/ws/logging/json/fat/JSONEventsTest.java
> +        ArrayList<String> ffdcKeysOptionalList = new ArrayList<String>(Arrays.asList("message"));
I am suggesting to keep `checkFfdc()` for Java 14 and lower.  Create a new method for Java 15 and make the message field mandatory.

2020-09-22 20:25 UTC, Yushan-Lin commented
#build

2020-09-22 22:14 UTC, fmhwong commented
@Yushan-Lin Can you request a Java15 build?

2020-09-23 13:44 UTC, Yushan-Lin commented
Java 15: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_iOgHgP2aEeqZosoAJ-GPIQ

2020-09-24 13:17 UTC, fmhwong approved these changes
LGTM

2020-09-24 13:31 UTC, Yushan-Lin commented
#run-libby-bot

2020-09-24 13:32 UTC, merged