add grpc tests
OpenLiberty/open-liberty pull request #14132
Opened 2020-09-24 00:46 UTC by epj

fixes #14131

2020-09-30 18:04 UTC, epj commented
#libbybot

2020-09-30 18:04 UTC, epj commented
#build

2020-09-30 18:31 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.invalidkeepalivew.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
Update description

2020-09-30 18:32 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.invaliduseplaintext.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
Also here

2020-09-30 18:33 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.keepalivew.false.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
Also here

2020-09-30 18:33 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.keepalivew.true.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
here

2020-09-30 18:33 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.maxmetasize.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
sorry :-)

2020-09-30 18:34 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.useplaintext.false.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
...

2020-09-30 18:35 UTC, loriadi requested changes
A couple of small changes to the server xml descriptions

2020-09-30 18:35 UTC, loriadi commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.useplaintext.true.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
...

2020-10-01 12:29 UTC, epj commented on dev/com.ibm.ws.grpc_fat/publish/files/grpc.client.invalidkeepalivew.server.xml
> +<server description="FAT configuration for gRPC Server with no grpc elements">
updated desc

2020-10-01 12:48 UTC, epj commented
#libbybot

2020-10-01 12:48 UTC, epj commented
build errors are in StoreServicesRESTClientTests unrelated to my changes

2020-10-01 14:32 UTC, loriadi approved these changes
Thanks, Evan!

2020-10-01 14:35 UTC, merged