Ensure restfulWSClient-3.0 feature works
OpenLiberty/open-liberty pull request #14182
Opened 2020-09-26 03:26 UTC by andymc12

For now the restfulWSClient will load everything that the server does - eventually we will split this up better.

2020-09-26 03:26 UTC, andymc12 commented
#build

2020-09-29 13:36 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.restfulWS-3.0.feature
> + com.ibm.websphere.appserver.org.eclipse.microprofile.config-1.4, \
You already have that line

2020-09-29 13:41 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.internal.restfulWS-3.0.feature
> + com.ibm.websphere.appserver.org.eclipse.microprofile.config-1.4, \
Also, that feature depends on cdi-1.2 and tolerates 2.0 ... you're pulling in cdi-3.0

2020-09-29 20:02 UTC, andymc12 commented
#build

2020-10-09 21:19 UTC, andymc12 commented
Updated so that there is actually a difference between the `restfulWS-3.0` and `restfulWSClient-3.0` features - and added a test to verify that a RESTful client is useable with only the `restfulWSClient-3.0` feature. New #build

2020-10-09 21:36 UTC, WhiteCat22 requested changes

2020-10-09 21:36 UTC, WhiteCat22 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigImpl.java
> +        new Throwable("ANDY: Config.getConfigSources").printStackTrace();
"ANDY"

2020-10-09 21:36 UTC, WhiteCat22 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigProviderResolverImpl.java
> +        new Throwable("ANDY: ConfigProviderResolverImpl.getBuilder").printStackTrace();
ANDY

2020-10-09 21:36 UTC, WhiteCat22 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/config/ConfigSourceImpl.java
> +        new Throwable("ANDY: ConfigSourceImpl.getName").printStackTrace();
ANDY

2020-10-09 21:49 UTC, WhiteCat22 approved these changes

2020-10-12 14:42 UTC, andymc12 commented
#build

2020-10-12 15:08 UTC, andymc12 commented
Minor tweak - new #build

2020-10-12 21:48 UTC, andymc12 commented
Missed the mailImpl-2.0 feature - new #build

2020-10-13 13:23 UTC, andymc12 commented
#run-libby-bot

2020-10-13 13:23 UTC, merged