Latest mp config
OpenLiberty/open-liberty pull request #14275
Opened 2020-10-01 16:57 UTC by tevans78

#build

2020-10-02 13:34 UTC, tevans78 commented
#build

2020-10-05 15:18 UTC, tevans78 commented
#build

2020-10-06 08:29 UTC, Joseph-Cass requested changes
LGTM other than the one request 👍

2020-10-06 08:29 UTC, Joseph-Cass commented on dev/com.ibm.ws.microprofile.config.1.4_fat/fat/src/com/ibm/ws/microprofile/config14/test/Config14Tests.java
>      public void testBadObserver20() throws Exception {
This test will be covered by the 2.0 FAT bucket

2020-10-06 09:57 UTC, tevans78 commented
#build

2020-10-07 10:32 UTC, Joseph-Cass approved these changes
Looks good :)

2020-10-07 10:32 UTC, tevans78 commented
#run-libby-bot

2020-10-07 10:33 UTC, merged