Application context path does not end with a slash
OpenLiberty/open-liberty pull request #14400
Opened 2020-10-08 19:42 UTC by pmd1nh

getContextPath() should return a context path of the application.  The context path starts with a "/" character but does not end with a "/" character.

Check, remove the trailing slash (if applicable), and also log a WARNING for developer to fix it.  The flow is not interrupted.

2020-10-08 19:44 UTC, pmd1nh commented
#build      #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2020-10-08 21:47 UTC, dmuelle requested changes
See my suggestions, ping me with any questions, thanks.

2020-10-08 21:47 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash=CWWWC0005W: The {0} context root of the application {1} can not end with a slash.
suggested edit:

The {0} context root path of the {1} application cannot end with a slash ( / ).

2020-10-08 21:47 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash.explanation=The context root path starts with a '/' character but does not end with a '/' character.
Suggested edit:
The context root path of the application starts with a slash ( / ) but cannot end with a slash.

2020-10-08 21:47 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash.useraction=Remove the ending '/' of the application's context root.
Suggested edit:
Remove the slash ( / ) at the end of the application's context root path.

2020-10-08 21:48 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash.explanation=The context root path starts with a '/' character but does not end with a '/' character.
It would be better if the explanation can say _why_ the root path can't end in a slash

2020-10-09 14:08 UTC, pmd1nh commented
@dmuelle I updated with your suggestion.  Pls re-review.  Thanks!

2020-10-09 14:36 UTC, andrea-pichler commented
Hi @pmd1nh 
for dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
please consider changing
from:
context.root.can.not.end.with.slash=CWWWC0005W: The {0} context root of the {1} application **can not** end with a slash (/).
to:
context.root.can.not.end.with.slash=CWWWC0005W: The {0} context root of the {1} application **cannot** end with a slash (/).
Thank you,
Andrea

2020-10-12 13:59 UTC, dmuelle requested changes
Thanks for making changes- just a couple more suggestions and a question

2020-10-12 13:59 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash=CWWWC0005W: The {0} context root of the {1} application can not end with a slash (/).
suggested edit
**change**
The {0} context root of the {1} application can not end with a slash (/).
**To**
The {0} context root of the {1} application cannot end with a slash (/).

2020-10-12 13:59 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash.explanation=According to the servlet doc, the context root path of the application starts with a slash (/) but cannot end with a slash.
In this explanation- what is "the servlet doc"? Is it the servlet specification? Or the API documentation?

2020-10-12 13:59 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +context.root.can.not.end.with.slash.useraction=Remove the ending '/' of the application's context root.
I think this last one still needs an edit. Let me know if there are problems with my previous suggestion and I can revise if needed

2020-10-13 15:23 UTC, pmd1nh commented
@dmuelle I updated the messages with your suggestions.  Thanks!

2020-10-13 15:36 UTC, dmuelle approved these changes
LGTM

2020-10-20 21:38 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2020-10-21 18:58 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2020-10-27 23:08 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-04-15 15:48 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-04-15 17:37 UTC, pnicolucci approved these changes

2021-04-16 15:29 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-04-21 14:36 UTC, pmd1nh commented
Tests: |   | 77106 tests, 0 failures, 0 errors
-- | -- | --

2021-04-21 14:37 UTC, pmd1nh commented
#run-libby-bot

2021-04-21 14:39 UTC, merged