add security.appbnd_test from CL to OL
OpenLiberty/open-liberty pull request #14443
Opened 2020-10-12 17:14 UTC by Zech-Hein

For #14313

2020-10-12 17:14 UTC, Zech-Hein commented
#build

2020-10-12 17:19 UTC, tevans78 requested changes

2020-10-12 17:19 UTC, tevans78 commented on dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/delegation/DefaultDelegationProviderTest.java
> + * IBM Confidential
Please remove ASAP

2020-10-12 17:21 UTC, Zech-Hein commented on dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/delegation/DefaultDelegationProviderTest.java
> + * IBM Confidential
ok, will do

2020-10-13 09:25 UTC, tevans78 commented on dev/com.ibm.ws.security.appbnd_test/test/com/ibm/ws/security/appbnd/internal/authorization/AppBndAuthorizationTableServiceTest.java
> + * Copyright (c) 2020 IBM Corporation and others.
Is this date correct? The file above says 2017, 2020 so I would have expected the test classes to be the same?

2020-10-13 15:56 UTC, tevans78 approved these changes

2020-10-13 17:53 UTC, Zech-Hein commented
#run-libby-bot

2020-10-13 17:55 UTC, merged