Add lease renewal time
OpenLiberty/open-liberty pull request #14841
Opened 2020-11-05 16:09 UTC by jonhawkes

fixes #14815 
#build

2020-11-05 19:27 UTC, dmuelle requested changes

2020-11-05 19:27 UTC, dmuelle commented on dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
> +lease.renewal.time.desc=The percentage of the lease length after which the lease is renewed
Suggested edit:

`The percentage of the duration of the recovery log lease that passes before the lease is renewed`

2020-11-09 10:25 UTC, jonhawkes commented
#build 
#run-libby-bot

2020-11-09 14:03 UTC, dmuelle approved these changes
LGTM

2020-11-09 14:58 UTC, andrea-pichler commented
No message review requested from L2

2020-11-10 06:48 UTC, jonhawkes commented
#build 
#run-libby-bot

2020-11-10 20:41 UTC, merged