Re-enable Reactive-based SSE TCK Tests - with fix to SseSubscription
OpenLiberty/open-liberty pull request #14990
Opened 2020-11-16 20:02 UTC by andymc12

2020-11-16 20:02 UTC, andymc12 commented
#build

2020-11-17 10:18 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/public/mpRestClient-1.4/com.ibm.websphere.appserver.mpRestClient-1.4.feature
> + com.ibm.websphere.appserver.mpConfig-1.4; ibm.tolerates:="1.3,2.0"
Please remove this tolerates. MicroProfile 4.0 features are not compatible with earlier versions.

2020-11-17 10:20 UTC, tevans78 requested changes
Please remove toleration of MP Config 2.0. MicroProfile 4.0 features are not compatible with earlier versions.

2020-12-08 21:36 UTC, andymc12 commented
Removed toleration and upgrading reactive streams from 1.0.2 to 1.0.3.  New #build

2021-04-01 16:01 UTC, closed without merging