update liberty wssecurity and saml sso prereqs
OpenLiberty/open-liberty pull request #15053
Opened 2020-11-19 17:22 UTC by arunavemulapalli

Making prereq updates required to update wsSecurity, wsSecuritySaml and samlWeb features and runtime to work with latest levels of cxf/ws-security (3.3.x) , wss4j (2.3.0) and opensaml(3.4.5).

2020-11-20 04:10 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.cxf,com.ibm.ws.security.saml.sso_fat

2020-11-23 04:52 UTC, arunavemulapalli commented
#build

2020-11-23 14:25 UTC, andrea-pichler commented
No L2 message review needed for translations

2020-11-23 21:21 UTC, arunavemulapalli commented
#build

2020-11-24 15:28 UTC, arunavemulapalli commented
#run-libby-bot

2020-11-24 23:08 UTC, neuwerk requested changes
Let me know when you have the renames updated. By and large these are minor changes, sorry for the shear number of them, but I wanted to make sure you didn't miss any.

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.ehcache.ehcache-107.3.8.1/bnd.overrides
> +Archiver-Version:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.cryptacular.cryptacular/build.gradle
> + * Copyright (c) 2019 IBM Corporation and others.
```suggestion
 * Copyright (c) 2020 IBM Corporation and others.
```

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.cryptacular.cryptacular/bnd.overrides
> +Archiver-Version:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-web.2.3.0/bnd.overrides
> +Build-Jdk:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-web.2.3.0/bnd.bnd
> +# Copyright (c) 2019 IBM Corporation and others.
```suggestion
# Copyright (c) 2020 IBM Corporation and others.
```

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-stax.2.3.0/bnd.overrides
> +Build-Jdk:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-policy-stax.2.3.0/bnd.overrides
> +Build-Jdk:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-dom.2.3.0/bnd.overrides
> +Build-Jdk:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-common.2.3.0/bnd.overrides
> +Build-Jdk:
Are these necessary?

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-common.2.3.0/bnd.bnd
> +# Copyright (c) 2019 IBM Corporation and others.
```suggestion
# Copyright (c) 2020 IBM Corporation and others.
```

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-policy.2.3.0/bnd.overrides
> + @${repo;org.apache.wss4j:wss4j-policy;2.3.0}!/*xml,\
```suggestion
 @${repo;org.apache.wss4j:wss4j-policy;2.3.0}!/*xml
```

2020-11-24 23:08 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.wss4j-policy.2.3.0/bnd.overrides
> +Build-Jdk:
Are these necessary?

2020-11-25 02:13 UTC, arunavemulapalli commented on dev/com.ibm.ws.net.shibboleth.utilities.java.support.7.5.1/bnd.overrides
> +Built-By:
Probably not. these files are copied from the existing projects

2020-11-25 02:16 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.cxf-rt-security-saml.3.3/bnd.overrides
> +Specification-Version:
not sure. I can clean these up (if I don't see any use for these)when we move them to 3.4.1?

2020-11-25 02:17 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.cxf-rt-security-saml.3.3/build.gradle
> + * Copyright (c) 2019 IBM Corporation and others.
I think I already updated these

2020-11-25 02:17 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.cxf-rt-security.3.3/bnd.bnd
> +# Copyright (c) 2019 IBM Corporation and others.
done

2020-11-25 04:07 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.wss4j-policy.2.3.0/bnd.overrides
> +Build-Jdk:
removed these for now.

2020-11-25 04:27 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.cxf-rt-ws-security.3.3/.classpath
> +	<classpathentry kind="lib" path="/com.ibm.ws.org.apache.cxf-rt-security.3.3/build/libs/com.ibm.ws.org.apache.cxf-rt-security.3.3.6.jar"/>
right. updated it

2020-11-25 04:51 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.cxf-rt-ws-security.3.3/src/org/apache/cxf/ws/security/cache/CXFEHCacheReplayCache.java
> +public class CXFEHCacheReplayCache extends EHCacheReplayCache implements BusLifeCycleListener {
nothing changed. I just had to recompile this class

2020-11-25 04:54 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.neethi/bnd.overrides
> +# Copyright (c) 2019 IBM Corporation and others.
I don't think this is new.

2020-11-25 05:08 UTC, arunavemulapalli commented on dev/com.ibm.ws.org.apache.wss4j-ws-security-stax.2.3.0/bnd.overrides
> +Build-Jdk:
removed these for now

2020-11-25 05:13 UTC, arunavemulapalli commented
#build

2020-11-25 16:14 UTC, arunavemulapalli commented
#build

2020-11-25 19:45 UTC, neuwerk approved these changes
Looks good, so long as the PB passes and you update that one buildpath entry.

2020-11-25 19:45 UTC, neuwerk commented on dev/com.ibm.ws.org.opensaml.opensaml.messaging.impl.3.4.5/bnd.bnd
> +    com.ibm.ws.org.opensaml.opensaml-messaging.api.3.4.5;version=latest, \
```suggestion
    com.ibm.ws.org.opensaml.opensaml.messaging.api.3.4.5;version=latest, \
```

2020-11-25 22:11 UTC, arunavemulapalli commented
#build

2020-11-28 14:54 UTC, arunavemulapalli commented
#run-libby-bot

2020-11-28 14:55 UTC, arunavemulapalli commented
#build

2020-11-30 15:31 UTC, arunavemulapalli commented
#build

2020-12-01 14:56 UTC, arunavemulapalli commented
latest pb looks good except one unrelated test failure. merging.

2020-12-01 14:57 UTC, merged

2021-04-01 14:14 UTC, arunavemulapalli commented
fixed #13395