Avoid NPE in case where an app handler is unset
OpenLiberty/open-liberty pull request #15070
Opened 2020-11-20 14:30 UTC by brenthdaniel

2020-11-20 14:30 UTC, brenthdaniel commented
#build

2020-11-20 19:55 UTC, tjwatson requested changes

2020-11-20 19:55 UTC, tjwatson commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/StartAction.java
> +        ApplicationHandler handler = _aii.getHandler();
I would make this `final`

2020-11-20 19:55 UTC, tjwatson commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/StartAction.java
>              ApplicationMonitoringInformation ami = handler.setUpApplicationMonitoring(_aii);
I don't see how an NPE is prevented here when `handler==null`. Did you intend to return early from the `if (handler == null)` check above?

2020-11-20 20:46 UTC, brenthdaniel commented
#build

2020-11-20 20:53 UTC, tjwatson approved these changes

2020-11-23 19:10 UTC, brenthdaniel commented
#run-libby-bot

2020-11-24 15:05 UTC, merged