add addStrictTransportSecurityHeader metatype prop
OpenLiberty/open-liberty pull request #15223
Opened 2020-12-08 17:18 UTC by wtlucy

For #13515

2020-12-08 19:04 UTC, dmuelle requested changes

2020-12-08 19:04 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +addStrictTransportSecurityHeader.desc=Enables the HTTP Strict Transport Security (HSTS) header for HTTPS responses and allows a value for that header to be set. For example: "max-age=31536000;include
Enables the HTTP Strict Transport Security (HSTS) header for HTTPS responses and allows a value to be set for that header, for example: "max-age=31536000;includeSubDomains". HSTS can also be configured in the web.xml file by setting the "com.ibm.ws.webcontainer.ADD_STS_HEADER_WEBAPP" context parameter.

2020-12-08 19:04 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +redirectToRelativeUrl.desc=Send redirect response to a relative URL location without processing it. Set this property to true to send redirect response without converting the URL to an absolute locat
suggested edit:
Send a redirect response to a relative URL location without processing the URL. Set this property to true to send a redirect response without converting the URL to an absolute location. 

I wonder if the first sentence is necessary? Kinda says the same thing twice

2020-12-08 20:08 UTC, dmuelle approved these changes

2020-12-08 20:30 UTC, wtlucy commented
#build

2020-12-09 15:32 UTC, wtlucy commented
#build

2020-12-10 13:21 UTC, wtlucy commented
#run-libby-bot

2020-12-10 13:23 UTC, merged