Set batch-2.0 and related features to beta
OpenLiberty/open-liberty pull request #15274
Opened 2020-12-11 03:56 UTC by cgianfra

Stage all Jakarta Batch related features for inclusion in beta
Add batch-2.0 and batchManagement-2.0 to EE9 convenience feature

2020-12-11 03:56 UTC, cgianfra commented
#build

2020-12-11 13:46 UTC, jhanders34 requested changes

2020-12-11 13:46 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/jakartaee-9.0/io.openliberty.jakartaee-9.0.feature
> + io.openliberth.batchManagement-2.0,\
batchManagement was not part of the convenience feature in 8.  Is there a reason for it to be part of it in 9?  liberty is spelled wrong for the feature though.  If you want it to be in the beta image for Jakarta 9 and it doesn't belong in the convenience feature, you should add it to `dev/build.image/profiles/jakartaee9/features.xml`.  Confirm with @tevans78

2020-12-11 13:46 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/batchManagement-2.0/io.openliberty.batchManagement-2.0.feature
>  -files=bin/batchManager.bat, \
If you don't have batchManager 1.0 also in your environment, batchManager scripts won't work I believe.  As such maybe batchManager shouldn't be marked beta, yet?  Is it needed for the CTS?

2020-12-11 16:12 UTC, cgianfra commented
#build

2020-12-11 17:50 UTC, jhanders34 approved these changes

2020-12-13 04:14 UTC, jhanders34 commented
#libby

2020-12-13 04:14 UTC, merged