Fix setter to include env var for JSON log field serverName
OpenLiberty/open-liberty pull request #15393
Opened 2021-01-04 05:15 UTC by ellen-lau

fixes: #15342

#build

`CollectorJsonHelpers` implemented some new setters for the `hostName` and `serverName` fields in `20.0.0.9`. These setters were utilized in `JsonLogHandler` to set the correct `hostName` and `serverName` after checking to see if the `CONTAINER_HOST/CONTAINER_NAME` environment variables are used. The `CollectorJsonHelpers.setServerName()` is incorrectly set to use the default server name.

2021-01-07 18:08 UTC, ellen-lau commented
#build

2021-01-08 10:07 UTC, ellen-lau commented
#build

2021-01-08 21:40 UTC, pgunapal commented on dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/ContainerEnvVarTest.java
> +/**
Its missing the copyright header.

2021-01-08 21:40 UTC, pgunapal commented on dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/ContainerEnvVarTest.java
> +        assertTrue("Could not find one or more of the set env vars CONTAINER_HOST and CONTAINER_NAME", foundEnvVars);
It would be helpful if you can specify which env var were not found.

2021-01-08 21:41 UTC, pgunapal requested changes
Looks good, just minor changes.

2021-01-08 21:44 UTC, pgunapal commented on dev/com.ibm.ws.logstash.collector_fat/fat/src/com/ibm/ws/logstash/collector/tests/ContainerEnvVarTest.java
> +    private static LibertyServer server = LibertyServerFactory.getLibertyServer("ContainerEnvServer");
Same as above, can just add `@Server("ContainerEnvServer")`, and not use `LibertyServerFactory.getLibertyServer("ContainerEnvServer");`

2021-01-08 23:26 UTC, ellen-lau commented
#run-libby-bot

2021-01-08 23:26 UTC, ellen-lau commented
#build

2021-01-09 22:41 UTC, ellen-lau commented
#build

2021-01-09 22:41 UTC, ellen-lau commented
#run-libby-bot

2021-01-11 05:37 UTC, ellen-lau commented
#run-libby-bot
#build

2021-01-11 18:45 UTC, pgunapal approved these changes
LGTM

2021-01-11 20:31 UTC, ellen-lau commented
Linking the completed build here: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_6BRaEFPGEeuFI6_BZVYvOw&tab=com.ibm.team.build.web.ui.internal.editors.result.test.TestProvider

2021-01-11 20:32 UTC, merged