Update xmlWS-3.0 to beta
OpenLiberty/open-liberty pull request #15415
Opened 2021-01-05 18:32 UTC by neuwerk

This PR updates the xmlWS-3.0 related features to be in `kind=beta` and adds the `xmlWSClient-3.0` feature to the `jakartaeeClient-9.0` and the `xmlWS-3.0` feature to the `jakartaee-9.0` feature

2021-01-05 19:59 UTC, jhanders34 requested changes

2021-01-05 19:59 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.cdi3.0-xmlws3.0.feature
> +edition=core
edition=core should be edition=base for all of these.

2021-01-05 20:11 UTC, jhanders34 approved these changes

2021-01-05 20:35 UTC, neuwerk commented
#build

2021-01-07 17:16 UTC, neuwerk commented
#build

2021-01-09 14:42 UTC, merged