Issue #11777: Add prepareJSPThreadCount to the metatype.
OpenLiberty/open-liberty pull request #15474
Opened 2021-01-11 15:11 UTC by pnicolucci

fixes #11777

2021-01-12 17:47 UTC, pnicolucci commented
#run-libby-bot

2021-01-12 19:55 UTC, pnicolucci commented
#run-libby-bot

2021-01-13 13:10 UTC, pnicolucci commented
#build

2021-01-13 16:14 UTC, ManasiGandhi requested changes
Few edit suggestions.

2021-01-13 16:14 UTC, ManasiGandhi commented on dev/com.ibm.ws.jsp/resources/OSGI-INF/l10n/metatype.properties
> +prepareJSPThreadCount.name=The number of threads to use when translating and compiling JSPs on startup.
Change,
"The number of threads to use when translating and compiling JSPs on startup."
to,
"The number of threads to use when you translate and compile JSPs on startup."

2021-01-13 16:14 UTC, ManasiGandhi commented on dev/com.ibm.ws.jsp/resources/OSGI-INF/l10n/metatype.properties
> +prepareJSPThreadCount=When prepareJSPs is enabled this configuration specifies the number of threads used.
Change,
"When prepareJSPs is enabled this configuration specifies the number of threads used."
to,
"When prepareJSPs is enabled, this configuration specifies the number of threads used."

2021-01-13 18:03 UTC, pnicolucci commented
Thanks @ManasiGandhi I've made those changes.

2021-01-13 18:04 UTC, pnicolucci commented
Looks like the build failed @ManasiGandhi  so I need to change a couple of things with the labels as they are too long. Let me push up some edits and see if you're ok with it.

2021-01-13 18:09 UTC, pnicolucci commented
#build

2021-01-13 20:57 UTC, skasund commented
L2 message review not required

2021-01-14 00:32 UTC, pnicolucci commented
#build

2021-01-15 23:54 UTC, pnicolucci commented
#build

2021-01-17 16:45 UTC, pnicolucci commented
#build

2021-01-19 18:02 UTC, pnicolucci commented
@ManasiGandhi  any comments on this? I had to rework a bit due to the length limitations.

2021-01-19 18:29 UTC, pnicolucci commented
Talked with Manasi and she told me she was ok to merge so doing so.

2021-01-19 18:55 UTC, wtlucy approved these changes

2021-01-19 18:55 UTC, pnicolucci commented
#run-libby-bot

2021-01-19 18:58 UTC, merged