13027 - cache the SSLContext and SSLSocketFactory
OpenLiberty/open-liberty pull request #15534
Opened 2021-01-13 21:44 UTC by WhiteCat22

Cache the SSLContext and the SSLSocket Factory, then get the SSLContext from JSSEHelper and compare against our cached copy each request to determine if we need to refresh our cached SSLSocketFactory

We need to do this because JSSEHelper only caches the SSLContext. Calling SSLContext.getSocketFactory() creates a new SSLSocketFactory every time. So, we need to cache the socket factory for re-use, but also the SSLContext so that we can compare it against the current SSLContext. If they are not equal, then the SSL config has changed and we need to get the new SSLContext and cache the new SSLSocketFactory to support dynamic SSL updates.

2021-01-13 21:45 UTC, WhiteCat22 commented
#run-libby-bot
#build

2021-01-13 22:09 UTC, acdemyers approved these changes

2021-01-14 04:02 UTC, andymc12 requested changes

2021-01-14 04:02 UTC, andymc12 commented on dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/security/JaxRsSSLManager.java
> +    private static SSLContext sslContext = null;
Wouldn't we want this to be a Map too? (Map<String, SSLContext>) It seems like we might have more than one SSLContext configured for a given server, and if we just have one static field, then we might always skip the cache (i.e. app1 uses context1, then app2 uses context2 forcing a swap of the sslContext field, etc.).

2021-01-14 04:02 UTC, andymc12 commented on dev/com.ibm.ws.jaxrs.2.0.security/src/com/ibm/ws/jaxrs20/appsecurity/security/JaxRsSSLManager.java
> +            }
see above comments about using a Map for sslContext.

2021-01-14 16:49 UTC, WhiteCat22 commented
#run-libby-bot
#build

2021-01-14 22:22 UTC, andymc12 approved these changes
LGTM - thanks @WhiteCat22!

2021-01-21 15:25 UTC, WhiteCat22 commented
Testing is complete, this solved the issue of persistent TLS connections breaking while also supporting dynamic ssl config changes without having to restart the server.

2021-01-21 20:41 UTC, merged