Migrate additional JPA Query fat test cases.
OpenLiberty/open-liberty pull request #15660
Opened 2021-01-25 20:37 UTC by jgrassel

Migrate additional Query Fats to Open Liberty.

2021-01-25 20:38 UTC, jgrassel commented
#build

2021-01-26 15:49 UTC, dazey3 requested changes
Just make sure all the database files get the same changes and looks good to me! Thanks!

2021-01-26 15:49 UTC, dazey3 commented on dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/ddl/WEB-INF/classes/JPA_SVLQUERY_POPULATE_DB2.ddl
> +INSERT INTO ${schemaname}.JPATASKBEAN (TASKID,COST,DESCRIPTION,NAME,PROJECT_PROJID) VALUES (1010,123.45,'Design','Design',1000);
I think this change should be also made in the HSQL/INFORMIX/MYSQL/SYBASE DDL files for SQLQuery

2021-01-26 19:50 UTC, jgrassel commented
#runlibbybot

2021-01-26 19:50 UTC, jgrassel commented
#run-libby-bot

2021-01-26 20:24 UTC, dazey3 approved these changes
LGTM!

2021-01-26 21:10 UTC, merged