Migrate more JPA Query FAT to OL
OpenLiberty/open-liberty pull request #15836
Opened 2021-02-08 20:44 UTC by jgrassel

Migrated the rest of the LoopQuery (Ano) JPA Query FAT to Open Liberty.

2021-02-08 20:44 UTC, jgrassel commented
#build

2021-02-08 23:18 UTC, jgrassel commented
#run-libby-bot
#build

2021-02-09 17:02 UTC, dazey3 requested changes
Couple minor things to note

2021-02-09 17:43 UTC, jgrassel commented on dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_001_Servlet.java
> +    }
I thought about that, but decided against it.  This is testing how a JPQL is translated into SQL and the results generated.  It should be the same regardless whether it's container managed or resource-local.  Considering how long JPA tests are running, I felt that only going with AM-JTA is sufficient.

2021-02-09 17:43 UTC, jgrassel commented on dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_001_Servlet.java
> +    private SetupQueryTestCase setup = null;
Sure.

2021-02-09 17:56 UTC, jgrassel commented on dev/com.ibm.ws.jpa_spec10_query_fat/test-applications/svlquery/src/com/ibm/ws/query/web/loopqueryano/JULoopQueryAnoTest_001_Servlet.java
> +    private SetupQueryTestCase setup = null;
Removed AM-RL and the CM-TS injections.

2021-02-09 19:38 UTC, dazey3 approved these changes
Looks fine

2021-02-09 19:55 UTC, jgrassel commented
#run-libby-bot

2021-02-09 19:55 UTC, merged