Add retry for slow request timing test failures
OpenLiberty/open-liberty pull request #16137
Opened 2021-03-04 17:37 UTC by ellen-lau

fixes: #15748

#build

Added a retry for slow requests in test cases: `testMaxSlowRequestTimingWarnings`, `testSlowReqSampleRateZero`, `testTimingLocalInheritsGlobalConfig`, and `testTimingGlobalConfigFollowsLocal` in the case of a slow request not being detected.

2021-03-05 17:45 UTC, ellen-lau commented
#build

2021-03-05 19:39 UTC, pgunapal requested changes

2021-03-05 19:39 UTC, pgunapal commented on dev/com.ibm.ws.request.timing_fat/fat/src/com/ibm/ws/request/timing/fat/SlowRequestTiming.java
> +            createRequest("?sleepTime=3000");
I believe the sleep here should be 13000 (13 secs).

2021-03-08 14:39 UTC, pgunapal approved these changes
LGTM

2021-03-08 17:14 UTC, ellen-lau commented
#run-libby-bot

2021-03-08 17:32 UTC, merged