Enable test that was never enabled
OpenLiberty/open-liberty pull request #16143
Opened 2021-03-05 11:31 UTC by benjamin-confino

2021-03-05 11:31 UTC, benjamin-confino commented
#build

2021-03-05 11:46 UTC, Azquelt approved these changes

2021-03-05 14:15 UTC, Azquelt commented on dev/com.ibm.ws.cdi.ejb_fat/fat/src/com/ibm/ws/cdi/ejb/apps/aroundconstruct/interceptors/ConstructInterceptor.java
>          Class<?> declaringClass = context.getConstructor().getDeclaringClass();
This line can go as well now.

2021-03-05 14:20 UTC, Azquelt approved these changes

2021-03-05 14:22 UTC, Azquelt requested changes
Changes look good but need to reenable the disabled test.

2021-03-05 14:30 UTC, Azquelt approved these changes

2021-03-08 10:12 UTC, benjamin-confino commented
#run-libby-bot

2021-03-08 10:13 UTC, merged