Issue 16250: Fix NPE with bad KRB5PrincipalName
OpenLiberty/open-liberty pull request #16304
Opened 2021-03-19 22:06 UTC by kristip17

Fixes #16250 

In Java 8, we ended up in

2021-03-19 22:10 UTC, kristip17 commented
@build

2021-03-19 22:10 UTC, kristip17 commented
#build

2021-03-22 13:04 UTC, kristip17 commented
Build failures are known issues in other buckets. I ran a Java8 personal build as well to confirm that my new test ran successfully.

2021-03-22 13:16 UTC, jvanhill approved these changes

2021-03-22 16:51 UTC, kristip17 commented
#build
#libby

2021-03-23 14:46 UTC, kristip17 commented
#build
#libby

2021-03-23 18:18 UTC, dmuelle requested changes
see my comments in line, let me know if any questions, thanks

2021-03-23 18:18 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_CACHE_CWWKS4347E.useraction=Ensure that a valid Kerberos principal is specified, and that the Kerberos credential cache (ccache) is not expired.
to be parallel with the explanation, suggest:

Ensure that a valid Kerberos principal is specified and that the Kerberos credential cache (ccache) is valid and not expired.

2021-03-23 18:18 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_KEYTAB_CWWKS4348E=CWWKS4348E: Kerberos login failed with the {0} Kerberos principal and the {1} Kerberos keytab. A Kerberos ticket was not found.
identify that the keytab is a file:

Kerberos login failed with the {0} Kerberos principal and the {1} Kerberos keytab file.

2021-03-23 18:18 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_KEYTAB_CWWKS4348E.explanation=Either the specified Kerberos principal is invalid, or the Kerberos keytab is invalid.
Either the specified Kerberos principal or the Kerberos keytab file is invalid.

2021-03-23 18:18 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_KEYTAB_CWWKS4348E.useraction=Ensure that a valid Kerberos principal is specified, and that a valid Kerberos keytab containing the Kerberos principal is specified.
suggested edit :
Ensure that a valid Kerberos keytab file that contains a valid Kerberos principal is specified.

2021-03-23 18:18 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_DEFAULT_KEYTAB_CWWKS4349E=CWWKS4349E: Kerberos login failed with the {0} Kerberos principal and the default Kerberos keytab. A Kerberos ticket was not found.
suggest to add "file" to keytab and pattern the messages as suggested in the previous comments

2021-03-24 12:55 UTC, dmuelle requested changes
Upon re-reading, I think it needs a couple minor changes

2021-03-24 12:55 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_KEYTAB_CWWKS4348E.useraction=Ensure that a valid Kerberos keytab file that contains a valid Kerberos principal is specified.
Looking at this again, have a slightly different suggestion:

Ensure that a valid Kerberos keytab file  is specified and that it contains a valid Kerberos principal.

2021-03-24 12:55 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_DEFAULT_KEYTAB_CWWKS4349E.explanation=Either the specified Kerberos principal is invalid, or the default Kerberos keytab is invalid.
Either the specified Kerberos principal or the default Kerberos keytab file is invalid.

2021-03-24 12:55 UTC, dmuelle commented on dev/com.ibm.ws.security.kerberos.auth/resources/com/ibm/ws/security/kerberos/auth/internal/resources/KerberosMessages.nlsprops
> +KRB5_LOGIN_FAILED_DEFAULT_KEYTAB_CWWKS4349E.useraction=Ensure that a valid Kerberos keytab file that contains a valid Kerberos principal is specified.
Ensure that a valid Kerberos keytab file is specified and that it contains a valid Kerberos principal.

2021-03-24 14:33 UTC, dmuelle approved these changes
LGTM

2021-03-24 15:05 UTC, kristip17 commented
#libby

2021-03-24 15:06 UTC, merged