Refactor SRTServletRequest to enable dynamic proxies
OpenLiberty/open-liberty pull request #16470
Opened 2021-04-01 20:26 UTC by andymc12

JAX-RS 3.0 (RESTEasy) injects `HttpServletRequest` instances using dynamic Java proxies that delegate to SRTServletRequest40. This causes problems with the existing web container code because it cannot cast a proxy (that implements the same interfaces as the SRTServletRequest40) to a SRTServletRequest40 or SRTServletRequest - this is because you cannot cast a proxy to a class - only an interface.

The solution I've proposed here is to create interfaces `ISRTServletRequest` and `ISRTServletRequest40` to define the methods needed - then the proxy can implement those interfaces and the casts will succeed.

While the main changes here are in the web container code, there are also some changes to security code and the JAX-RS code.

2021-04-01 20:26 UTC, andymc12 commented
#build

2021-04-02 19:04 UTC, andymc12 commented
#build

2021-04-02 19:45 UTC, jhanders34 requested changes

2021-04-02 19:45 UTC, jhanders34 commented on dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/util/ServletUtil.java
> +		//while (!(requestClass.isAssignableFrom(r.getClass())))
Any reason this commented out code that you added should stay in?

2021-04-02 19:45 UTC, jhanders34 commented on dev/com.ibm.ws.webcontainer.servlet.4.0/src/com/ibm/ws/webcontainer40/srt/ISRTServletRequest40.java
> +public interface ISRTServletRequest40 {
Should this interface extend ISRTServletRequest so you don't have to cast to both if you need methods on each of them?

2021-04-02 20:56 UTC, andymc12 commented
#build

2021-04-02 20:58 UTC, jhanders34 approved these changes

2021-04-07 16:25 UTC, andymc12 commented
#build

2021-04-12 15:35 UTC, pmd1nh approved these changes

2021-04-13 18:29 UTC, andymc12 commented
#libby

2021-04-13 18:29 UTC, merged