permit IBM JDK for Oracle 21c JDBC driver kerberos
OpenLiberty/open-liberty pull request #16559
Opened 2021-04-09 20:54 UTC by njr-11

fixes #16307

2021-04-09 21:13 UTC, njr-11 commented
#build

2021-04-09 21:38 UTC, KyleAure approved these changes

2021-04-09 23:16 UTC, KyleAure requested changes
I think we need to do some more testing to be sure that the Oracle 21c driver did actually break their dependency on the Oracle JDK.

2021-04-14 14:36 UTC, KyleAure approved these changes
Tested and working on Windows, Linux and Mac machines.  This looks like a safe change, but going to look into this failing when forwardable tickets are enabled.

2021-04-14 14:49 UTC, merged