wsSecuritySaml and samlWeb feature updates (2nd try)
OpenLiberty/open-liberty pull request #16725
Opened 2021-04-22 15:22 UTC by arunavemulapalli

for #16472

2021-04-22 17:29 UTC, arunavemulapalli commented
#run-libby-bot

2021-04-22 17:30 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat

2021-04-26 18:26 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat

2021-04-27 19:03 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat

2021-04-29 23:30 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat,com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml

2021-05-06 18:04 UTC, skasund commented
L2 message review completed

2021-05-11 19:53 UTC, jhanders34 requested changes
I focused on the feature updates.  In general new features should start with io.openliberty instead of com.ibm.websphere.appserver.   I added comments for some of the new features about that, but not all of them.  I have some additional concerns about how the singleton features are selected for saml, but hopefully what I have provided will handle that. Will want to go over things again after some of these updates.

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.2.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jaxws-2.2)))", \
I believe this should be servlet 3, 3.1 and 4.0 and should have features listed of JAXWS-2.2 tolerates 2.3 in the feature list and com.ibm.websphere.appserver.wsSecurity1.1.internal.jaxws-2.2 and tolerate 2.3.

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.3.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=com.ibm.websphere.appserver.jaxws-2.3))", \
This can be rolled in the other auto feature like I mentioned.  We will need a servlet-5.0 version of the auto feature of course.

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.wsSecuritySaml1.1-jaxws2.2.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jaxws-2.2)))", \
Similarly this should be servlet 3, 3.1, and 4.0 and then do the same as the wsSecurity auto feature.  Since it is a new feature it should start with io.openliberty instead of com.ibm.websphere.appserver

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.samlWeb2.0.internal.ee9.opensaml-2.6.feature
> +symbolicName = com.ibm.websphere.appserver.samlWeb2.0.internal.ee9.opensaml-2.6
ee9 will not depend on 2.6.  It should be depending on 3.4, but transformed of course.  Again since it is a new feature it should start with io.openliberty instead of com.ibm.websphere.appserver

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wsSecurity1.1.internal.jaxws-2.2.feature
> + com.ibm.websphere.appserver.wss4j-1.0
For the tolerates I mentioned earlier, you will need to have this feature and the 2.3 one include jaxrs-2.2 and 2.3 respectively.

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/wsSecurity-1.1/com.ibm.websphere.appserver.wsSecurity-1.1.feature
> +  org.apache.wss4j.common.ext; type="third-party", \
Is this dependent on which one is selected?  If it is using the old one will this actually work correctly?  Do we need to expose these third party APIs?

2021-05-11 19:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/wsSecuritySaml-1.1/com.ibm.websphere.appserver.wsSecuritySaml-1.1.feature
> + com.ibm.websphere.appserver.jaxws-2.2; ibm.tolerates:=2.3, \
You will need to have an auto feature for servlet 3, 3.1 and 4 in order to make this work correctly since there is no jaxws-3.0, but it is called xmlWS-3.0.

2021-05-12 13:48 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/public/wsSecurity-1.1/com.ibm.websphere.appserver.wsSecurity-1.1.feature
> +  org.apache.wss4j.common.ext; type="third-party", \
Yes. We tested this and it works with both old and new features. I think we need to expose these third party APIs ( if not, the applications using wss4j callback handler implementation to retrieve passwords for username tokens or private keys will not work..)

2021-05-12 13:59 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/public/wsSecuritySaml-1.1/com.ibm.websphere.appserver.wsSecuritySaml-1.1.feature
> + com.ibm.websphere.appserver.jaxws-2.2; ibm.tolerates:=2.3, \
Right. These feature file changes mainly I did this way to quickly test the feature/runtime updates that I've been doing for ws-security/saml and samlWeb. I understand that I have to go through one more cycle of these feature file changes (auto features to depend on servlet feature level like you are suggesting..) to properly fit the Jakarta EE9 model right after the transformation of the new runtime completes..

2021-05-12 15:53 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.2.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jaxws-2.2)))", \
Doing post this PR

2021-05-12 15:54 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.wsSecurity1.1-jaxws2.3.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=com.ibm.websphere.appserver.jaxws-2.3))", \
Doing post this PR

2021-05-12 15:54 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.wsSecuritySaml1.1-jaxws2.2.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jaxws-2.2)))", \
Doing post this PR

2021-05-12 15:55 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.samlWeb2.0.internal.ee9.opensaml-2.6.feature
> +symbolicName = com.ibm.websphere.appserver.samlWeb2.0.internal.ee9.opensaml-2.6
Will do post this PR

2021-05-12 15:56 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/wsSecuritySaml-1.1/com.ibm.websphere.appserver.wsSecuritySaml-1.1.feature
> + com.ibm.websphere.appserver.jaxws-2.2; ibm.tolerates:=2.3, \
Will do post this PR

2021-05-12 15:57 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/com.ibm.websphere.appserver.wsSecurity1.1.internal.jaxws-2.2.feature
> + com.ibm.websphere.appserver.wss4j-1.0
Will be done post this PR

2021-05-13 23:17 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat

2021-05-14 01:06 UTC, jhanders34 requested changes

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +singleton=true
Auto features are not singletons and do not need WLP-DisableAllFeatures-OnConflict settings.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +  com.ibm.websphere.appserver.servlet-3.0; ibm.tolerates:="3.1,4.0", \
I thought we talked about removing servlet and appsecurity from the auto feature and only having it in the samlWeb-2.0 feature.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +  io.openliberty.samlWeb2.0.internal.opensaml-2.6; ibm.tolerates:=3.4
Why is this tolerating 3.4?  I didn't think we could use 3.4 with jaxrs 2.2

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> + com.ibm.ws.security.saml.wab.2.0, \
These are already in the internal ee-6 feature for samlWeb.  Why do they need to be here also?

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.3.feature
> +-include= ~${workspace}/cnf/resources/bnd/feature.props
Mostly same comments as the 2.2 version of this feature except for this one correctly doesn't have the tolerates issue.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.wsSecurity1.1-jaxws2.2.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jaxws-2.2)))", \
As we talked about the OR ( | ) is not needed here.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.wsSecurity1.1-jaxws2.2.feature
> +  com.ibm.websphere.appserver.internal.slf4j-1.7.7, \
Why not have slf4j in the wsSecurity.internal.jaxws-2.2 feature instead of here?

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.wsSecurity1.1-jaxws2.3.feature
> +  com.ibm.websphere.appserver.httpcommons-1.0
Why not have httpcommons-1.0 in the wsSecurity.internal.jaxws-2.3 feature instead of here?

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-2.3.feature
> +WLP-DisableAllFeatures-OnConflict: true
The true will be added automatically by the tooling.  You do not need to set it.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-3.4.feature
> +WLP-DisableAllFeatures-OnConflict: false
WLP-DisableAllFeatures-OnConflict should be removed.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/samlWeb-2.0/com.ibm.websphere.appserver.samlWeb-2.0.feature
> -  io.openliberty.samlWeb2.0.internal.ee-6.0; ibm.tolerates:="9.0"
Why is this removed?  Nothing will work if this is removed.

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-2.2.feature
> +edition=core
This should be base, not core

2021-05-14 01:06 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +edition=core
This should be base not core

2021-05-14 20:35 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +singleton=true
removed this auto feature

2021-05-14 20:35 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +  com.ibm.websphere.appserver.servlet-3.0; ibm.tolerates:="3.1,4.0", \
removed this auto feature

2021-05-14 20:36 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +  io.openliberty.samlWeb2.0.internal.opensaml-2.6; ibm.tolerates:=3.4
removed this auto feature

2021-05-14 20:36 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> + com.ibm.ws.security.saml.wab.2.0, \
removed this auto feature

2021-05-14 20:37 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.3.feature
> +-include= ~${workspace}/cnf/resources/bnd/feature.props
removed this auto feature

2021-05-14 20:37 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.wsSecurity1.1-jaxws2.2.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=com.ibm.websphere.appserver.jaxws-2.2)))", \
removed this auto feature

2021-05-14 20:39 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.wsSecurity1.1-jaxws2.2.feature
> +  com.ibm.websphere.appserver.internal.slf4j-1.7.7, \
moved the slf4j feature to internal and removed this auto feature

2021-05-14 20:40 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.wsSecurity1.1-jaxws2.3.feature
> +  com.ibm.websphere.appserver.httpcommons-1.0
moved this httpcommons feature to the mentioned internal private feature. Also removed this auto feature

2021-05-14 20:41 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-2.3.feature
> +WLP-DisableAllFeatures-OnConflict: true
done

2021-05-14 20:42 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.samlWeb2.0.internal.opensaml-3.4.feature
> +WLP-DisableAllFeatures-OnConflict: false
done

2021-05-14 20:42 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/public/samlWeb-2.0/com.ibm.websphere.appserver.samlWeb-2.0.feature
> -  io.openliberty.samlWeb2.0.internal.ee-6.0; ibm.tolerates:="9.0"
added it back

2021-05-14 20:42 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.wsSecurity1.1.internal.jaxws-2.2.feature
> +edition=core
done

2021-05-14 20:43 UTC, arunavemulapalli commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.samlWeb2.0-jaxws2.2.feature
> +edition=core
removed this auto feature

2021-05-14 22:02 UTC, jhanders34 approved these changes

2021-05-14 23:31 UTC, arunavemulapalli commented
#run-libby-bot

2021-05-14 23:32 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.saml.sso_fat

2021-05-19 15:03 UTC, arunavemulapalli commented
the feature checker changes are in release. Merging this PR.

2021-05-19 15:03 UTC, merged

2021-05-19 21:40 UTC, wraschke commented
This causes builds to fail with the following during Gradle assembling:

`> Task :com.ibm.ws.security.saml.websso.2.0:compileJava FAILED
error  : Cannot find /error/com.ibm.ws.org.apache.commons.codec;version=latest Not found in [bnd-cache [/home/jazz_build/Build/jbe/build/open-liberty/dev/cnf/cache/5.3.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/home/jazz_build/Build/jbe/build/open-liberty/dev/cnf/local, storage=Local, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/Build/jbe/build/open-liberty/dev/cnf/local, storage=Release, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmartifactory/repository, storage=RemoteSource, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmartifactory/repository, storage=RemotePublic, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmartifactory/repository, storage=RemoteIBM, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmjava/repository, storage=IBMInternalJava, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.m2/repository, storage=RemotePublish, inited=true, redeploy=false]]
error  : com.ibm.ws.org.apache.commons.codec;version=latest Not found in [bnd-cache [/home/jazz_build/Build/jbe/build/open-liberty/dev/cnf/cache/5.3.0/bnd-cache r/w=false], MavenBndRepository [localRepo=/home/jazz_build/Build/jbe/build/open-liberty/dev/cnf/local, storage=Local, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/Build/jbe/build/open-liberty/dev/cnf/local, storage=Release, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmartifactory/repository, storage=RemoteSource, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmartifactory/repository, storage=RemotePublic, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmartifactory/repository, storage=RemoteIBM, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.ibmjava/repository, storage=IBMInternalJava, inited=true, redeploy=false], MavenBndRepository [localRepo=/home/jazz_build/.m2/repository, storage=RemotePublish, inited=true, redeploy=false]]`

So we will revert this PR.

2021-10-12 14:54 UTC, arunavemulapalli commented
for #12449