Remove the check message from metric monitor bundle. We check for a server start after which implies all necessary bundles have started
OpenLiberty/open-liberty pull request #16782
Opened 2021-04-27 00:30 UTC by Channyboy

fixes #16763

2021-04-27 01:03 UTC, Channyboy commented
#build
#run-libby-bot

2021-04-27 12:55 UTC, fmhwong commented on dev/com.ibm.ws.request.timing.monitor_fat/fat/src/com/ibm/ws/request/timing/monitor/fat/RequestTimingMetricsTest.java
> +        String logMsg = server.waitForStringInLogUsingMark("CWWKF0011I");
The check for `CWWKF0011I` should be moved to the setUp() as the server is started up once for the entire class.  If another test case ran before this and it set the log mark, this message won't be seen again.

2021-04-27 12:56 UTC, fmhwong requested changes
See comment

2021-04-27 14:57 UTC, Channyboy commented
#build 
#run-libby-bot

2021-04-28 02:11 UTC, fmhwong approved these changes
LGTM

2021-04-28 14:53 UTC, merged