Response output may not close at end of dispatch forward
OpenLiberty/open-liberty pull request #16811
Opened 2021-04-27 20:11 UTC by pmd1nh

https://github.com/OpenLiberty/open-liberty/issues/16053

2021-04-27 20:13 UTC, pmd1nh commented
#build       #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-04-28 15:09 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-05-03 14:13 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-05-04 13:42 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-05-04 14:17 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-05-05 14:42 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-05-06 15:24 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-06-08 19:39 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-06-09 14:50 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS

2021-06-10 14:12 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS

2021-06-11 13:42 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS

2021-06-14 14:47 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS

2021-06-23 16:08 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS

2021-06-24 19:28 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_lWAS

2021-09-22 16:04 UTC, pmd1nh commented
#build

2021-09-22 16:18 UTC, dmuelle requested changes
a few minor suggestions

2021-09-22 16:18 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +closeWrappedResponseOutputAfterForward.desc=When this property is set to true, the wrapped response's output stream will be closed before exiting the dispatch forward.  The default value is false. Fo
When this property is set to true, the wrapped response's output stream will be closed before exiting the dispatch forward
--->
When this property is set to true, the output stream from the wrapped response is closed before it exits the dispatch forward.

2021-09-22 16:18 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
>  excludeAllHandledTypesClasses.name=Disable returning handlesTypes parameters
Disable returning handlesTypes parameters
--->
Disable the return of handlesTypes parameters

2021-09-22 16:18 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +closeWrappedResponseOutputAfterForward.name=Close wrapped response output after forward
Close wrapped response output after forward
--->
Close wrapped-response output after forward

2021-09-22 16:28 UTC, dmuelle approved these changes
LGTM

2021-09-23 14:07 UTC, pmd1nh commented
#build       #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-09-24 15:14 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-09-27 13:51 UTC, pmd1nh commented
#build #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-09-28 13:06 UTC, pmd1nh commented
#build

2021-09-29 00:50 UTC, pmd1nh commented
#build

2021-09-29 15:41 UTC, pmd1nh commented
#build 
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

2021-10-01 13:45 UTC, pmd1nh commented
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

2021-10-01 17:16 UTC, pmd1nh commented
Updated test application

2021-10-01 17:16 UTC, pmd1nh commented
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

2021-10-04 14:21 UTC, pmd1nh commented
#build
#spawn.fullfat.buckets=com.ibm.ws.webcontainer.servlet.4.0_fat

2021-10-05 14:02 UTC, pmd1nh commented
test_nonWrapResponse_closeOutputStreamAfterForward | 1 | 0 | 0 | 1 s | 1
-- | -- | -- | -- | -- | --
test_wrapResponse_closeOutputStreamAfterForward | 1 | 0 | 0 | 0 s | 2
test_nonWrapResponse_closeOutputStreamAfterForward_EE9_FEATURES | 1 | 0 | 0 | 1 s | 3
test_wrapResponse_closeOutputStreamAfterForward_EE9_FEATURES | 1 | 0 | 0 | 0 s | 4
 

2021-10-05 14:34 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/resources/WEB-INF/web.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Add copyright header.

2021-10-05 14:50 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer.servlet.4.0_fat/test-applications/CloseWrappedResponseOutputForward.war/resources/WEB-INF/web.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Add copyright header

2021-10-05 14:50 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +closeWrappedResponseOutputAfterForward.desc=When this property is set to true, the output stream from the wrapped response is closed before it exits the dispatch forward. The default value is false.
Can you just add a newline here to satisfy git?

2021-10-05 14:50 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer.servlet.4.0_fat/fat/src/com/ibm/ws/fat/wc/tests/WCCloseWrappedResponseOutputAfterForwardTest.java
> +/*******************************************************************************
My understanding of this test is you're only testing the `true` scenario for all servlet versions. Can we also test the default behavior for servlet 5.0 and default value for previous servlet versions?

2021-10-05 15:15 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
> +    //21.0.0.11
Also this release isn't correct.

2021-10-05 15:16 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer/src/com/ibm/wsspi/webcontainer/WCCustomProperties.java
> +            CLOSE_WRAPPED_RESPONSE_OUTPUT_AFTER_FORWARD = Boolean.valueOf(WebContainer.getWebContainerProperties().getProperty("com.ibm.ws.webcontainer.closewrappedresponseoutputafterforward", "true"
This won't go out in 21.0.0.11 so we need to update.

2021-10-05 16:51 UTC, pnicolucci approved these changes

2021-10-05 16:53 UTC, pmd1nh commented
#build       #spawn.fullfat.buckets=com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2021-10-06 14:06 UTC, pmd1nh commented
Tests: |   | 84435 tests, 0 failures, 1 errors
-- | -- | --

one unrelated error in:

com.ibm.ws.security.wim.registry_fat FAT tests | 59 | 0 | 1 |  
-- | -- | -- | -- | --




com.ibm.ws.fat.wc.tests.WC5CloseWrappedResponseOutputAfterForwardTest | 2 | 0 | 0 | 2 s | 26
-- | -- | -- | -- | -- | --
test_50nonWrapResponse_closeOutputStreamAfterForward_EE9_FEATURES | 1 | 0 | 0 | 2 s | 1
test_50wrapResponse_closeOutputStreamAfterForward_EE9_FEATURES | 1 | 0 | 0 | 0 s | 2
 



com.ibm.ws.fat.wc.tests.WCCloseWrappedResponseOutputAfterForwardTest | 4 | 0 | 0 | 3 s | 23
-- | -- | -- | -- | -- | --
test_nonWrapResponse_closeOutputStreamAfterForward | 1 | 0 | 0 | 1 s | 1
test_wrapResponse_closeOutputStreamAfterForward | 1 | 0 | 0 | 0 s | 2
test_nonWrapResponse_closeOutputStreamAfterForward_EE9_FEATURES | 1 | 0 | 0 | 1 s | 3
test_wrapResponse_closeOutputStreamAfterForward_EE9_FEATURES | 1 | 0 | 0 | 0 s | 4
 

2021-10-06 14:07 UTC, pmd1nh commented
#run-libby-bot

2021-10-06 14:07 UTC, merged