Randy modified changes
OpenLiberty/open-liberty pull request #16828
Opened 2021-04-28 15:48 UTC by randyclee

#build

2021-04-28 18:21 UTC, randyclee commented
Fixes: https://github.com/OpenLiberty/open-liberty/issues/13681

2021-05-05 17:49 UTC, donbourne requested changes

2021-05-05 17:49 UTC, donbourne commented on dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceJoinerTest.java
> +    protected static final int threadsToRun = 5;
looks like you are defining threadsToRun here and in the testPrintStackTraceMultipleThreads method

2021-05-05 17:49 UTC, donbourne commented on dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceJoinerTest.java
> +                      server.setMarkToEndOfLog(messagesLog);
here you're setting the mark on the messages log, but then later in this method, on line 153, you are looking for the log content in the console log.

2021-05-05 17:49 UTC, donbourne commented on dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceJoinerTest.java
> +                      server.setMarkToEndOfLog(messagesLog);
you probably shouldn't be doing this from each thread... would make more sense to do this mark before you spawn the threads.

2021-05-05 17:49 UTC, donbourne commented on dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceJoinerTest.java
> +    public void testPrintStackTraceMultipleThreads() throws Exception {
this test needs more than 3 (or 5) threads to do one hit each to check for concurrency problems.  I'd suggest you have 5 threads and make each run in a loop making, say, 1000 hits each... then in your asserts you can check that you got expected number of events, and check each of the 5000 events to make sure they all have the same number of lines in their stack trace.  you could also check to make sure you have exactly 1000 messages from each thread.

2021-05-05 17:49 UTC, donbourne commented on dev/com.ibm.ws.logging_fat/fat/src/com/ibm/ws/logging/fat/StackTraceJoinerTest.java
> +              Thread.sleep(500);
you'd be better off keeping a reference to each of the threads you start and using Thread.join to wait for each of the threads to complete.

2023-07-04 14:45 UTC, closed without merging