the wrapper login module needs to return true/false
OpenLiberty/open-liberty pull request #16948
Opened 2021-04-29 15:17 UTC by utle

The Kerberos login wrapper module needs to return the true/false result from the JDK since some of the JDK version do not throw an exception when login/commit failed.

The Kerberos service can check the result returns from the Kerberos login wrapper and issue the best possible error message.

2021-04-29 15:24 UTC, utle commented
#build

2021-04-29 15:34 UTC, utle commented
#build 
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.wim.adapter.ldap_fat,com.ibm.ws.jdbc_fat_krb5,com.ibm.ws.jdbc_fat

2021-04-29 22:51 UTC, kristip17 approved these changes

2021-04-30 12:44 UTC, utle commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.wim.adapter.ldap_fat,com.ibm.ws.jdbc_fat_krb5,com.ibm.ws.jdbc_fat

2021-04-30 14:43 UTC, utle commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.spnego_fat,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat.spnego,com.ibm.ws.security.wim.adapter.ldap_fat,com.ibm.ws.jdbc_fat_krb5,com.ibm.ws.jdbc_fat

2021-04-30 15:16 UTC, mswatosh requested changes
Since the OpenJDK login module provides it's own LoginExceptions, we should be checking for false in the Krb5LoginModuleWrapper if `isIBMJdk8` is true and throwing a LoginException there.

2021-04-30 15:43 UTC, utle commented
> Since the OpenJDK login module provides it's own LoginExceptions, we should be checking for false in the Krb5LoginModuleWrapper if `isIBMJdk8` is true and throwing a LoginException there.

I handle that in the KerberosService where we have to throw an exception for other reasons.

2021-04-30 20:51 UTC, mswatosh commented
login and commit can't return false with the OpenJDK Krb5LoginModule so we don't need to do the check for openJDK, also it's fine for the Krb5LoginModuleWrapper to return `true`, since `false` would mean skip the LoginModule, which isn't an option here. So the only options are `true` if Authentication succeeds, or throw `LoginException` if the login fails. We really just need to correct the IBM JDK8 krb5LoginModule violating the LoginModule Interface by returning `false` when it should be throwing a `LoginException`

Once we address that, then we could catch any `LoginException` thrown by the LoginModule, and provide a more Liberty-specific (and translatable) message, with the original `LoginException` as the cause. There we could use knowledge of what the user has set in configuration to give a better hint (e.g. if the user only has a ccache set we can tell them to check that) while still keeping the original exception.

Let me know if you want me to clarify further

2021-05-01 21:24 UTC, utle commented
> login and commit can't return false with the OpenJDK Krb5LoginModule so we don't need to do the check for openJDK, also it's fine for the Krb5LoginModuleWrapper to return `true`, since `false` would mean skip the LoginModule, which isn't an option here. So the only options are `true` if Authentication succeeds, or throw `LoginException` if the login fails. We really just need to correct the IBM JDK8 krb5LoginModule violating the LoginModule Interface by returning `false` when it should be throwing a `LoginException`
> 
> Once we address that, then we could catch any `LoginException` thrown by the LoginModule, and provide a more Liberty-specific (and translatable) message, with the original `LoginException` as the cause. There we could use knowledge of what the user has set in configuration to give a better hint (e.g. if the user only has a ccache set we can tell them to check that) while still keeping the original exception.
> 
> Let me know if you want me to clarify further

IBM Krb5LoginModule return false for failure and clearly document it. However, what you suggest is the same thing what I have now. I choose to do it in the KerberosService instead since we already have the logic to issue the best possible error message. I don't want to call or duplicate that logic in the wrapper.

2021-05-02 02:59 UTC, utle commented
The more I think about it. We should open a JDK issue and let them fix it so we do not have to do anything here and make it consistent with OpenJDK. Close this PR.

2021-05-02 02:59 UTC, closed without merging