Port Embeddable JPA tests to OpenLiberty
OpenLiberty/open-liberty pull request #17165
Opened 2021-05-14 19:10 UTC by dazey3

for #6321

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

2021-05-14 19:11 UTC, dazey3 commented
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.spec10.embeddable_fat

2021-05-14 19:27 UTC, jgrassel requested changes
Many files are missing headers.  Also, I didn't see changes to any of the .github/test-categories/JPA* files, which you need to add your new test bucket to one of them.

2021-05-14 19:27 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/test-applications/embeddable/nested/src/com/ibm/ws/jpa/embeddable/nested/model/Embeddable01.java
> +package com.ibm.ws.jpa.embeddable.nested.model;
Missing the standard header, this is the case for all of these model classes by the looks of it.

2021-05-14 19:27 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/test-applications/embeddable/nested/web/embeddableNestedWeb.war/WEB-INF/classes/META-INF/orm-nested.xml
> +<entity-mappings xmlns="http://java.sun.com/xml/ns/persistence/orm" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Missing headers (IBM copyright, license, etc) here too.

2021-05-14 19:27 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/test-applications/embeddable/relationship/ejb/embeddableRelationshipEjb.jar/META-INF/orm-relationship.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Missing headers

2021-05-14 19:27 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/test-applications/embeddable/relationship/src/com/ibm/ws/jpa/embeddable/relationship/model/BiM2MOwnerEmbed.java
> +package com.ibm.ws.jpa.embeddable.relationship.model;
Model types here also missing headers

2021-05-14 19:27 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_fat/test-applications/embeddable/relationship/web/embeddableRelationshipWeb.war/WEB-INF/classes/META-INF/orm-relationship.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Missing header

2021-05-24 15:42 UTC, jgrassel approved these changes

2021-05-24 19:04 UTC, dazey3 commented
#run-libby-bot

2021-05-24 19:10 UTC, merged