17444 el varags matching
OpenLiberty/open-liberty pull request #17447
Opened 2021-06-07 16:13 UTC by volosied

Currently a draft.

fixes #17444

2021-06-07 16:16 UTC, volosied commented on dev/com.ibm.ws.org.apache.jasper.el/src/org/apache/el/util/ReflectionUtil.java
> +            }
Per the comment in the method description, this method was out of sync with the one in Util.java.  I added the relevant portions this method to have it matching again.

2021-06-07 16:17 UTC, volosied commented on dev/com.ibm.ws.org.apache.jasper.el/src/org/apache/el/util/ReflectionUtil.java
> +        }
Same as before for MatchResult. Keep Util.java and RelfectionUtil.java in sync.

2021-06-07 16:22 UTC, volosied commented
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.el.3.0_fat,com.ibm.ws.jsf.2.2_fat

2021-06-07 18:40 UTC, epj requested changes
The Tomcat fix also includes tests.  The tests (or equivalents that fit our harness) should be added to our FAT in this PR also.

2021-06-10 15:11 UTC, volosied commented
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.el.3.0_fat,com.ibm.ws.jsf.2.2_fat

2021-06-11 17:52 UTC, epj approved these changes

2021-06-11 19:03 UTC, wtlucy approved these changes

2021-06-22 19:05 UTC, volosied commented
#build #spawn.fullfat.buckets=com.ibm.ws.jsf.2.3_fat,com.ibm.ws.jsp.2.3_fat,com.ibm.ws.el.3.0_fat,com.ibm.ws.jsf.2.2_fat

2021-06-23 20:43 UTC, volosied commented
#run-libby-bot

2021-07-01 18:30 UTC, merged

2021-08-27 16:45 UTC, volosied commented
I labelled the issue as release bug, but I think this PR should also have it.