Permission added in order to run EE9 specific tests
OpenLiberty/open-liberty pull request #17547
Opened 2021-06-15 19:49 UTC by BerksanAtes

fixes #17544

2021-06-15 19:50 UTC, BerksanAtes commented
#build

2021-06-16 14:22 UTC, neuwerk requested changes

2021-06-16 14:22 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.clientcontainer_fat/fat/src/com/ibm/ws/jaxws/clientcontainer/fat/AppClientTest.java
> +    // @Test
Why are these commented out?

2021-06-16 14:42 UTC, BerksanAtes commented
#build

2021-06-21 16:46 UTC, neuwerk approved these changes
Thanks for doing this!

2021-06-21 18:06 UTC, BerksanAtes commented
#libbybot

2021-06-21 18:06 UTC, merged