Allow backslash in BasicRegistry entities
OpenLiberty/open-liberty pull request #17992
Opened 2021-07-28 17:49 UTC by ryanesch

2021-07-28 20:48 UTC, jvanhill requested changes

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
> +        assumeTrue(!isOpenJDK11());
```suggestion
```

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
> +        assumeTrue(!isOpenJDK11());
```suggestion
```

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
> +     * Validate fix for OLGH10461, where a PatternSyntaxException (unclosed group near index N)
Update javadoc for test.

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
> +     * Validate fix for OLGH10461, where a PatternSyntaxException (unclosed group near index N)
Update javadoc for test.

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/publish/files/basic.server.xml.orig
> +        <user name="dan\" password="danspassword" />
Update copyright.

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/publish/servers/com.ibm.ws.security.registry.basic.fat/server.xml
> +        <user name="dan\" password="danspassword" />
update copright

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
> +        assertEquals(1, result.getList().size());
Add failure message.

2021-07-28 20:48 UTC, jvanhill commented on dev/com.ibm.ws.security.registry.basic_fat/fat/src/com/ibm/ws/security/registry/basic/fat/FATTest.java
> +        assertEquals(1, result.getList().size());
Add failure message.

2021-07-28 21:10 UTC, jvanhill approved these changes

2021-07-28 21:10 UTC, ryanesch commented
#build

2021-07-29 21:00 UTC, ryanesch commented
#run-libby-bot

2021-07-29 21:00 UTC, merged