18068 jax release cc after service invoke
OpenLiberty/open-liberty pull request #18126
Opened 2021-08-10 11:23 UTC by benjamin-confino

2021-08-10 13:47 UTC, andymc12 requested changes
@benjamin-confino Thanks so much for this fix.  The new test files are missing copyright headers and some of the other files need the copyright date changed to 2021, but otherwise this looks good.  Thanks again!

2021-08-10 18:55 UTC, benjamin-confino commented
#build

2021-08-10 18:56 UTC, andymc12 approved these changes

2021-08-11 13:13 UTC, benjamin-confino commented
#run-libby-bot

2021-08-11 13:14 UTC, merged