promote catalog persistence in collective to the current server version
OpenLiberty/open-liberty pull request #18280
Opened 2021-08-20 21:34 UTC by lavenal

This PR is to fix a bug in the collective catalog persistence file which contains a bookmark that was created by an earlier Open Liberty server but the bookmark was removed in the later Open Liberty server.

2021-08-23 19:13 UTC, skasund commented
L2 message review completed

2021-08-25 14:21 UTC, lavenal commented
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_ixEokAQTEeyB1uNHimT5CA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

2021-08-26 21:05 UTC, ManasiGandhi requested changes
A few edit suggestions.

2021-08-26 21:05 UTC, ManasiGandhi commented on dev/com.ibm.ws.ui/resources/com/ibm/ws/ui/internal/resources/UIMessages.nlsprops
> +CATALOG_FILE_PROMOTED_TO_CURRENT_VERSION=CWWKX1070I: The Admin Center default catalog was loaded from COLLECTIVE persistence created by an earlier server version. The catalog has reloaded using a cop
Change,
"The Admin Center default catalog was loaded from COLLECTIVE persistence created by an earlier server version. The catalog has reloaded using a copy from the current server version."
to,
"The Admin Center default catalog was loaded from COLLECTIVE persistence that is created by an earlier server version. The catalog is reloaded by using a copy from the current server version."

2021-08-26 21:05 UTC, ManasiGandhi commented on dev/com.ibm.ws.ui/resources/com/ibm/ws/ui/internal/resources/UIMessages.nlsprops
> +CATALOG_FILE_PROMOTED_TO_CURRENT_VERSION.explanation=The product converted the Admin Center default catalog to the current server version. The copy in the COLLECTIVE persistence will be loaded by sub
Change,
"The product converted the Admin Center default catalog to the current server version. The copy in the COLLECTIVE persistence will be loaded by subsequent access to persisted storage."
to,
"The product converted the Admin Center default catalog to the current server version. The copy in the COLLECTIVE persistence is loaded by subsequent access to the persisted storage."

2021-08-26 21:27 UTC, k8vance88 approved these changes

2021-08-26 22:33 UTC, lavenal commented on dev/com.ibm.ws.ui/resources/com/ibm/ws/ui/internal/resources/UIMessages.nlsprops
> +CATALOG_FILE_PROMOTED_TO_CURRENT_VERSION=CWWKX1070I: The Admin Center default catalog was loaded from COLLECTIVE persistence created by an earlier server version. The catalog has reloaded using a cop
Thanks and changed per review!

2021-08-26 22:33 UTC, lavenal commented on dev/com.ibm.ws.ui/resources/com/ibm/ws/ui/internal/resources/UIMessages.nlsprops
> +CATALOG_FILE_PROMOTED_TO_CURRENT_VERSION.explanation=The product converted the Admin Center default catalog to the current server version. The copy in the COLLECTIVE persistence will be loaded by sub
Thanks and changed per review comment.

2021-08-27 12:52 UTC, ManasiGandhi approved these changes

2021-08-27 13:00 UTC, lavenal commented
New personal build with ID review changes: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_qPKzMAbDEeyB1uNHimT5CA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

2021-08-30 13:04 UTC, lavenal commented
#build

2021-08-31 03:08 UTC, lavenal commented
#run-libby-bot

2021-08-31 14:07 UTC, lavenal commented
The failure in PB is not related to the code changes.

2021-08-31 14:07 UTC, merged