Check for HAM/config provider more efficiently
OpenLiberty/open-liberty pull request #18399
Opened 2021-09-01 14:47 UTC by jdmcclur

When enabling mp-4.0 there is a small regression compared to mp-3.3 due to bringing in appsecurity-3.0 and needing to check for jaspic. This is an attempt to address that in BuildBridgeIfNeeded. 

1. Checking for getModulePropertiesUtils().isHttpAuthenticationMechanism() first before the getConfigProvider call, because it is faster (see #2) and can avoid the sync on the whole method.
2. Caching the results of isHttpAuthenticationMechanism() true/false so it doesn't have to check every time
3. Updating the unit tests to work with these changes.

2021-09-01 14:47 UTC, jdmcclur commented
#build

2021-09-23 14:04 UTC, jdmcclur commented
A lot of FATS failed, so may need to rethink this - haven't had time to investigate yet.

2021-10-06 16:46 UTC, jdmcclur commented
#build

2021-10-06 16:47 UTC, jdmcclur commented
#libby

2021-10-18 11:40 UTC, jhanders34 requested changes
Yeah the code will work this way, but I would suggest getting rid of the returns.  Instead of return on the first one, just do an else to the rest of it where it is doing the synchronized.  Similarly I would suggest that for the since return statement that you swap the if condition and put the remaining logic in the == null condition instead.  The code will be much cleaner.

Can you also do a double check synchronize to avoid the synchronization if it is already set?
```
        AuthConfigProvider authConfigProvider = providerFactory.getConfigProvider(JASPIC_LAYER_HTTP_SERVLET, appContext, (RegistrationListener) null);
        if (authConfigProvider == null) {
            // Synchronized since checking if there is a provider and registering one need to be done as a single atomic operation.
            synchronized (this) {
                authConfigProvider = providerFactory.getConfigProvider(JASPIC_LAYER_HTTP_SERVLET, appContext, (RegistrationListener) null);
                if (authConfigProvider == null) {
```

2021-10-18 12:00 UTC, jhanders34 commented on dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtils.java
> +        if (isHam == null) {
I don't think this will work.  The call for getting the http authentication mechanism is on a ThreadLocal so it can be different per thread.  Also this class is a singleton.  A new instance would not be created when there is a config change that could change the http authentication mechanism.

2021-10-18 13:56 UTC, jdmcclur commented on dev/com.ibm.ws.security.javaeesec/src/com/ibm/ws/security/javaeesec/properties/ModulePropertiesUtils.java
> +        if (isHam == null) {
OK, bummer. If we can't speed up this check, not sure the other change is really worth it. It would probably still help my scenario, but would slow down a scenario where there is an authConfigProvider I think.

2021-11-15 23:09 UTC, jhanders34 approved these changes

2021-12-02 21:42 UTC, jdmcclur commented
@jhanders34 @vijaysun-omr @utle 

I looked at this some more. It looks like the change helps my case (no jaspic/authconfigprovider) by ~1.5%. However, I think it would regress a scenario where there is an authconfigprovider configured by ~0.5%. So, the question is, do many customers use jaspic? Is this a big deal to regress it? Thoughts?

2021-12-03 15:06 UTC, utle commented
We are not aware of that many customers using the jaspic provider. Can you give a little detail why we regress for jaspic customers?

2021-12-03 15:20 UTC, jdmcclur commented
@utle - Yes, because of the way I switched things around to avoid the sync lock on the method, it now always does this check first `getModulePropertiesUtils().isHttpAuthenticationMechanism()`

Before, it didn't do this check if an authconfigprovider is already in the cache. This is a pretty minor regression though. Maybe 0.5%.

2021-12-03 18:55 UTC, utle commented
> @utle - Yes, because of the way I switched things around to avoid the sync lock on the method, it now always does this check first `getModulePropertiesUtils().isHttpAuthenticationMechanism()`
> 
> Before, it didn't do this check if an authconfigprovider is already in the cache. This is a pretty minor regression though. Maybe 0.5%.

I am ok with the minor regression since we do not have that many customer using JASPI provider.

2021-12-06 17:19 UTC, jdmcclur commented
#libby

2021-12-06 17:19 UTC, jdmcclur commented
#build

2021-12-06 19:40 UTC, utle approved these changes

2021-12-06 21:42 UTC, jdmcclur commented
fixes issue #19567

2021-12-07 11:17 UTC, merged