add kerberos trace to spnegofat1
OpenLiberty/open-liberty pull request #18804
Opened 2021-09-29 21:59 UTC by Zech-Hein

add `com.ibm.ws.security.kerberos*=all=enabled` trace for better debugging in s4u2 tests

2021-09-29 21:59 UTC, Zech-Hein commented
#build

2021-09-30 13:16 UTC, utle approved these changes

2021-09-30 13:37 UTC, utle requested changes
`Change kerberos* and spnego* to kerbers.* and spnego.*`

2021-09-30 20:23 UTC, utle approved these changes

2021-10-01 14:38 UTC, merged