Issue 18828: Remove Oracle Ldap refs from FATs
OpenLiberty/open-liberty pull request #18830
Opened 2021-10-01 19:40 UTC by kristip17

Fixes #18828

Removed the oracle ldap call to Consul.

Updated the port variable in the server.xml files or we get a `AttributeValidationException`. In those tests, we dynamic update the config to the UnboundId server. We could update the tests to create the Ldap server from scratch and remove it from the server.xml, but this was the least churn.

2021-10-01 22:14 UTC, kristip17 commented
#build

2021-10-04 13:03 UTC, kristip17 commented
I ran with a local and remote PB. Most failures seemed to be known intermittent issues. On one PB (only 1), I saw an acme_fat failure. I opened a separate bug to review it -- 287091. It may be expected behavior when there's a hiccup with Pebble/Docker, but I want to confirm.

2021-10-04 13:03 UTC, kristip17 commented
#libby

2021-10-04 14:18 UTC, jvanhill requested changes
Update copyrights in:

- dev/com.ibm.ws.com.unboundid/resources/SunOne.ldif
- ...ldap_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/CommonLocalLDAPServerSuite.java
- ...p_fat/fat/src/com/ibm/ws/security/wim/adapter/ldap/fat/LDAPRegistryDynamicUpdateTest.java 
- ...dap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.multipleldaps/server.xml
- ...t/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.attrMappingVar4/server.xml
- ....ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun.default/server.xml
- ....adapter.ldap_fat/publish/servers/com.ibm.ws.security.wim.adapter.ldap.fat.sun/server.xml
- ...registry_fat/fat/src/com/ibm/ws/security/wim/registry/fat/CommonLocalLDAPServerSuite.java

2021-10-04 15:49 UTC, jvanhill approved these changes

2021-10-04 16:16 UTC, kristip17 commented
Last push was updating the copyright dates.

2021-10-04 16:17 UTC, kristip17 commented
#libby

2021-10-04 16:17 UTC, merged