Switch EE 9.1 to GA
OpenLiberty/open-liberty pull request #19017
Opened 2021-10-18 12:00 UTC by tevans78

Switch EE 9.1 features and packages to GA
#build

2021-10-27 17:06 UTC, tevans78 commented
#build

2021-10-27 20:17 UTC, jhanders34 approved these changes

2021-10-27 20:17 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWSDefaultExceptionMapper-1.0.feature
> +kind=ga
This shouldn't be enabled until mpMetrics-4.0 goes to GA right?

2021-10-27 20:19 UTC, jhanders34 requested changes
I marked approve instead of request changes.  Sorry about that.

2021-10-28 10:53 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWSDefaultExceptionMapper-1.0.feature
> +kind=ga
agreed

2021-10-28 16:49 UTC, tevans78 commented
#build

2021-10-29 15:18 UTC, jhanders34 requested changes

2021-10-29 15:18 UTC, jhanders34 commented on dev/io.openliberty.org.eclipse.microprofile.contextpropagation.1.3/bnd.bnd
> +  com.ibm.websphere.javaee.annotation.1.3;version=latest,\
In reality these should be Jakarta EE 9 dependencies instead of EE8.  They will mean nothing to the MP 5.0 APIs.  You should be able to remove them all since the version of the API doesn't matter to mpContextPropagation anyway since it does version=!

2021-10-29 16:54 UTC, tevans78 commented
#build

2021-11-01 14:49 UTC, jhanders34 approved these changes

2021-11-01 16:31 UTC, tevans78 commented
#build

2021-11-02 10:28 UTC, tevans78 commented
New PB: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_HxboMDu_EeygsrM6ShizkA

2021-11-03 14:30 UTC, tevans78 commented
This combined CL-OL PB was green: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_ngkcMDv7EeygsrM6ShizkA

2021-11-03 17:53 UTC, mbroz2 approved these changes

2021-11-03 17:54 UTC, tevans78 commented
#libby

2021-11-03 17:54 UTC, merged