Enable JPA configuration to pass persistence parameters to EntityManagerFactory creation
OpenLiberty/open-liberty pull request #19036
Opened 2021-10-19 16:33 UTC by dazey3

for #15979 

Adds JPA Container changes to integrate property passing to EntityManagerFactory creation
Adds new JPA FAT to test this new feature

2021-10-19 16:34 UTC, dazey3 commented
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat

2021-10-20 14:40 UTC, tkburroughs approved these changes

2021-10-21 16:29 UTC, jgrassel requested changes

2021-10-21 16:29 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/test-applications/defaultproperties/ejb/defaultpropertiesEjb.jar/META-INF/ibm-ejb-jar-bnd.xml
> +        <resource-ref name="jdbc/JPA_JTA_DS"     binding-name="jdbc/JPA_JTA_DS" />
These resource refs needed?  You're not using them in persistence.xml.

Considering how jpa runtime integration processing changes if you choose to use a "java:comp/env" datasource, I think it might be a good idea to have some tests which use global JNDI name and some which use resource-refs.

2021-10-21 16:29 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.jpaconfig_fat.common/test-applications/overridepersistencecontext/ejb/overridepersistencecontextEjb.jar/META-INF/ejb-jar.xml
> +            <resource-ref>
Again, resource refs, if we're going to use them, then use them, otherwise remove the entries from the ejb-jar.xml and ibm-ejb-jar-bnd.xml

2021-10-22 23:16 UTC, dazey3 commented
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat

2021-10-25 11:28 UTC, jgrassel approved these changes

2021-10-25 14:43 UTC, dazey3 commented
#run-libby-bot

2021-10-25 14:53 UTC, merged