Migrate JPA Spec 2.0 DerivedIdentity/Util to OL
OpenLiberty/open-liberty pull request #19090
Opened 2021-10-21 20:16 UTC by jgrassel

Migrate JPA 2.0 Spec buckets Util and Derived Identity to Open Liberty, and rename the JPA Spec 2.0 fat project to `com.ibm.ws.jpa.tests.spec20_fat`

To reduce increased exec time due to enabling test containers, broke out several sub-buckets into their own test projects:
```
com.ibm.ws.jpa.tests.spec20.entitymanager_fat
com.ibm.ws.jpa.tests.spec20.ordercolumn_fat
com.ibm.ws.jpa.tests.spec20.querylockmode_fat
com.ibm.ws.jpa.tests.spec20_fat
```

2021-10-21 20:16 UTC, jgrassel commented
#build

2021-10-25 15:58 UTC, dazey3 requested changes

2021-10-25 15:58 UTC, dazey3 commented on dev/com.ibm.ws.jpa.tests.spec20_fat/fat/src/com/ibm/ws/jpa/spec20/JPA20DerivedIdentity_WEB.java
> +package com.ibm.ws.jpa.spec20;
It looks like the package name is still `com.ibm.ws.jpa.spec20`. Can we get this update to `com.ibm.ws.jpa.tests.spec20` to match the new project name?

2021-10-25 15:58 UTC, dazey3 commented on dev/com.ibm.ws.jpa.tests.spec20_fat/publish/servers/JPA20UtilEJBServer/server.xml
> +    <library id="JDBCLib" fat.modify="true" apiTypeVisibility="+third-party">
Is the thirdparty visibility necessary? This probably should update to use the format of `AnonymousJDBCLib` most of our other FAT use (see `com.ibm.ws.jpa.tests.spec10.inheritance_fat.common\publish\servers\JPA10InheritanceEJBServer\server.xml` or `com.ibm.ws.jpa.tests.spec10.query_fat.common\publish\servers\JPA10QueryServer\server.xml`)

2021-10-25 15:58 UTC, dazey3 commented on dev/com.ibm.ws.jpa.tests.spec20_fat/publish/servers/JPA20Server/bootstrap.properties
> +# Copyright (c) 2017 IBM Corporation and others.
Maybe do a search/replace for "2017 IBM Corporation" -> "2021 IBM Corporation"

2021-10-26 13:14 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec20_fat/fat/src/com/ibm/ws/jpa/spec20/JPA20DerivedIdentity_WEB.java
> +package com.ibm.ws.jpa.spec20;
Yep, I'll do that.

2021-11-01 12:50 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec20_fat/publish/servers/JPA20UtilEJBServer/server.xml
> +    <library id="JDBCLib" fat.modify="true" apiTypeVisibility="+third-party">
Good catch, fixing that too.

2021-11-01 12:50 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec20_fat/publish/servers/JPA20Server/bootstrap.properties
> +# Copyright (c) 2017 IBM Corporation and others.
Hmm, only if there's tet changes inside the files.  I don't think moving a file is enough to change its copyright date.

2021-11-02 13:41 UTC, jgrassel commented
#build
#run-libby-bot

2021-11-02 13:44 UTC, jgrassel commented
#run-libby-bot  - forgot to update JPA_2 to include the breakout jpa spec20 buckets.

2021-11-02 15:01 UTC, jgrassel commented
#run-libby-bot

2021-11-02 15:45 UTC, jgrassel commented
#run-libby-bot. updated copyright dates on files.

2021-11-02 21:31 UTC, dazey3 requested changes
small fix to the existing Entity class being moved

2021-11-02 21:31 UTC, dazey3 commented on dev/com.ibm.ws.jpa.tests.spec20.entitymanager_fat/build.gradle
> + * Copyright (c) 2019 IBM Corporation and others.
Copyright (c) 2021 IBM Corporation and others.

2021-11-02 21:31 UTC, dazey3 commented on dev/com.ibm.ws.jpa.tests.spec20.entitymanager_fat/fat/src/com/ibm/ws/jpa/tests/spec20/entitymanager/FATSuite.java
> + * Copyright (c) 2020 IBM Corporation and others.
Copyright (c) 2021 IBM Corporation and others.

2021-11-02 21:31 UTC, dazey3 commented on dev/com.ibm.ws.jpa.tests.spec20.entitymanager_fat/test-applications/entitymanager/src/com/ibm/ws/jpa/entitymanager/model/JPA20EntityManagerDetachEntity.java
> +package com.ibm.ws.jpa.entitymanager.model;
Need a header on this file

2021-11-03 14:33 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.spec20.entitymanager_fat/test-applications/entitymanager/src/com/ibm/ws/jpa/entitymanager/model/JPA20EntityManagerDetachEntity.java
> +package com.ibm.ws.jpa.entitymanager.model;
Fixed

2021-11-03 14:33 UTC, jgrassel commented
#run-libby-bot
#build

2021-11-03 14:34 UTC, dazey3 approved these changes
LGTM

2021-11-04 13:23 UTC, merged