18581 - iterate on the RESTfulWS-3.0 endpoint introspector
OpenLiberty/open-liberty pull request #19117
Opened 2021-10-24 21:38 UTC by WhiteCat22

#18581 

I improved the dump introspector to print out the servlet mapping (which was previously missing).

2021-10-24 22:52 UTC, WhiteCat22 commented
#build

I do have 1 more thing I'd like to improve. Ideally, I'd like to find a way to get the `ServletConfig` from a JAX-RS Dynamic feature so I can port this introspector back to `jaxrs-2.0` and `jaxrs-2.1`.

Barring that, there may be a better spot to call `logEndpoints()` from than `ServletContainerDispatcher`.

I mainly picked `ServletContainerDispatcher` because we already override it in OpenLiberty, rather than pull in another overlay class.

2021-10-26 02:47 UTC, WhiteCat22 commented
#build

2021-10-27 02:26 UTC, WhiteCat22 commented
#build #run-libby-bot

2021-10-27 15:34 UTC, andymc12 requested changes

2021-10-27 15:34 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                        resource = Thread.currentThread().getContextClassLoader().loadClass(clazz);
This (getting a classloader) needs to be in a doPriv.  The loadClass might also... I'd suggest creating a new static method that loads the class from the TCCL and it can do both in a doPriv if a security manager is present.

2021-10-27 15:34 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                                // get the @Consumes MediaTypes
This code will only get the `@Consumes`/`@Produces` annotations from the method, but we should also get it from the class, since that would apply to all method that don't have those annotations.

2021-10-27 15:34 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                        e.printStackTrace();
Let's not print the stack to the logs.  If auto-FFDC is enabled, that is good.  We could also print it to the introspector output - something like:
```
ERROR WHILE INTROSPECTING - ClassNotFoundException: <SomeClass>
at ...
```

2021-10-27 15:34 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +            Tr.info(tc, "unable to find LibertyResteasyEndpointLoggingIntrospector");
This either needs to be a debug message or needs to be translated.

2021-10-27 15:34 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ServletContainerDispatcher.java
> +      RestfulWSUtils.logEndpoints(servletConfig); // Liberty Change
Just to avoid adding code to overlays, I wonder if this could be put into the `RESTfulServletContainerInitializer` or somewhere else?

2021-10-27 21:12 UTC, WhiteCat22 commented on dev/io.openliberty.org.jboss.resteasy.common/src/org/jboss/resteasy/plugins/server/servlet/ServletContainerDispatcher.java
> +      RestfulWSUtils.logEndpoints(servletConfig); // Liberty Change
I'd like to iterate on that in the future, right now I'm not sure how to get the `ServletConfig` in the `RESTfulServletContainerInitializer` nor in a JAXRS Dynamic Feature.

2021-10-27 21:24 UTC, andymc12 requested changes
Getting much closer.  This is looking really good.  Thanks!

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                        String classConsumes[] = getAnnotationValue(resource, Consumes.class, String[].class);
```suggestion
                        String[] classConsumes = getAnnotationValue(resource, Consumes.class, String[].class);
```

This looks like C style arrays - Java styling prefers the bracket to be near to the type to make clear that the type is an array of Strings.

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                        String classProduces[] = getAnnotationValue(resource, Produces.class, String[].class);
```suggestion
                        String[] classProduces = getAnnotationValue(resource, Produces.class, String[].class);
```

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                                String consumes[] = getAnnotationValue(m, Consumes.class, String[].class);
```suggestion
                                String[] consumes = getAnnotationValue(m, Consumes.class, String[].class);
```

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +                                String produces[] = getAnnotationValue(m, Produces.class, String[].class);
```suggestion
                                String[] produces = getAnnotationValue(m, Produces.class, String[].class);
```

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +    public static Class<?> loadClass(String clazz, StringBuffer sb) {
Can we make this private?  Or at least non-public?  Otherwise somebody else could invoke the method to make an unauthorized call to loadClass.

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +    public static Method[] getMethods(Class<?> clazz) {
Same thing here - non-public.

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +            }
(1) Can we add support for PATCH?
(2) In the future, we may also want to log custom HTTP verbs.

2021-10-27 21:24 UTC, andymc12 commented on dev/io.openliberty.org.jboss.resteasy.common/src/io/openliberty/restfulWS/utils/RestfulWSUtils.java
> +            } catch (InvocationTargetException e) {}
Can we consolidate this?  Maybe use a multi-catch (like `catch (NoSuchMethodException | SecurityException | ...)`) or just catch `Exception`?

2021-10-27 21:44 UTC, andymc12 approved these changes
Changes look good - thanks again!

2021-10-27 21:49 UTC, WhiteCat22 commented
#run-libby-bot #build

2021-10-28 14:59 UTC, merged