concurrent-2.0 should not tolerate mpContextPropagation 1.0
OpenLiberty/open-liberty pull request #19160
Opened 2021-10-27 20:53 UTC by njr-11

concurrent-2.0 is from Jakarta EE 9, which shouldn't interoperate with mpContextPropagation-1.0

2021-10-27 20:53 UTC, njr-11 commented
#build

2021-10-28 10:30 UTC, jhanders34 approved these changes

2021-10-28 11:18 UTC, jhanders34 requested changes
Yeah this won't work because of eeCompatible conflicts.  Going to have to change to io.openliberty.org.eclipse.microprofile.contextPropagation-1.3 and update that feature to have the jar file in the lib dir instead of of dev/api until we GA MP 5.0.

2021-10-28 16:50 UTC, njr-11 commented
#build
#run-libby-bot

2021-11-10 21:47 UTC, njr-11 commented
not needed because it was included in a different pull

2021-11-10 21:47 UTC, closed without merging