Split LDAP Kerberos bucket in 2 projects for slow Windows
OpenLiberty/open-liberty pull request #19163
Opened 2021-10-27 22:12 UTC by kristip17

Split the bucket so FULL mode FAT can complete on slow Windows runs. I suspect running the ApacheDS KDC/LDAP with the test is making generally slow Windows runs extra slow for this bucket.

I added an `...ldap_fat.krb5.2` project and split the `FatSuite` between the two projects. After testing, the LITE bucket timed out once, so I moved a LITE test over to the new project as well.

RTC 286705

2021-10-27 22:12 UTC, kristip17 commented
#build

2021-10-29 16:01 UTC, jvanhill requested changes
You need to update the ../.github/test-categories/SECURITY_4 file to add the new bucket. I also would prefer if you named the original bucket with .1 as well.

2021-10-29 20:13 UTC, jvanhill requested changes
Two updates to the project name in build files.

2021-10-29 20:13 UTC, jvanhill commented on dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/bnd.bnd
> +	com.ibm.ws.security.wim.adapter.ldap_fat.krb5;version=latest
```suggestion
	com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1;version=latest
```

2021-10-29 20:13 UTC, jvanhill commented on dev/com.ibm.ws.security.wim.adapter.ldap_fat.krb5.2/build.gradle
> +    project(':com.ibm.ws.security.wim.adapter.ldap_fat.krb5'),
```suggestion
    project(':com.ibm.ws.security.wim.adapter.ldap_fat.krb5.1'),
```

2021-10-29 20:19 UTC, jvanhill approved these changes

2021-10-31 20:57 UTC, kristip17 commented
#libby

2021-10-31 20:57 UTC, merged