mpOpenApi-2.0 merging fixes
OpenLiberty/open-liberty pull request #19218
Opened 2021-11-02 19:18 UTC by Azquelt

* Detect extension clashes
* Return the correct application path when a merge clash occurs

Fixes #19215 
Fixes #19214

2021-11-02 19:26 UTC, Azquelt commented
#build
#libby

2021-11-03 00:55 UTC, dmuelle requested changes

2021-11-03 00:55 UTC, dmuelle commented on dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
> +OPENAPI_MERGE_PROBLEM_EXTENSION_CLASH=The {0} extension key from the {1} module clashes with the same extension key from the {2} module. {1} will not be merged.
per IBM style, avoid future tense

{1} will not be merged
--->
{1} cannot be merged

2021-11-03 00:55 UTC, dmuelle commented on dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
> +OPENAPI_MERGE_PROBLEM_EXTENSION_CLASH.useraction=Either change one of the conflicting modules to remove the extension or configure the mpOpenApi-2.0 feature to exclude one of them.
Suggested edit:

Either change one of the conflicting modules to remove the extension or configure the mpOpenApi-2.0 feature to exclude one of the modules.

2021-11-03 10:32 UTC, Azquelt commented
Thank you @dmuelle, I have made both changes.

2021-11-03 10:32 UTC, Azquelt commented
#build
#libby

2021-11-03 10:37 UTC, tevans78 approved these changes

2021-11-03 13:50 UTC, dmuelle requested changes

2021-11-03 13:50 UTC, dmuelle commented on dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
> +OPENAPI_MERGE_PROBLEM_PATH_CLASH.useraction=Either change one of the conflicting modules or configure the mpOpenApi-2.0 feature to exclude one of the modules. This problem can be caused if servers ar
suggested edit:
... This problem might occur if servers are included in the OpenAPI document and the server URL does not end with the context root of the application. For example, when the application is accessed at a different URL through a reverse proxy.

2021-11-03 13:50 UTC, dmuelle commented on dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
> +OPENAPI_MERGE_PROBLEM_PATH_CLASH=The {0} path from the {1} module clashes with a path from the {2} module. {1} cannot be merged.
{1} cannot be merged.
-->
The  {1} module cannot be merged.

2021-11-03 13:50 UTC, dmuelle commented on dev/io.openliberty.microprofile.openapi.internal.common/resources/io/openliberty/microprofile/openapi/internal/resources/OpenAPI.nlsprops
> +OPENAPI_MERGE_PROBLEM_EXTENSION_CLASH=The {0} extension key from the {1} module clashes with the same extension key from the {2} module. {1} cannot be merged.
{1} cannot be merged.
-->
The {1} module cannot be merged.

2021-11-03 15:13 UTC, Azquelt commented
#build
#libby

2021-11-03 17:02 UTC, dmuelle approved these changes
LGTM

2021-11-04 10:24 UTC, merged