Serviceability: Print Http header contents
OpenLiberty/open-liberty pull request #19238
Opened 2021-11-03 20:30 UTC by una-tapa

2021-11-03 20:49 UTC, una-tapa commented
Not ready for review.  Need to run the build. 
#build

2021-11-04 14:55 UTC, barbj commented
@una-tapa Can I get a copy of a trace that has the new data in it?  I don't think I've seen one yet.

2021-11-05 15:04 UTC, una-tapa commented
@barbj  Thanks for checking. I've uploaded it here.   Please search "Http Header.." just like Traditional WebSphere. 

[Internal link] 
https://ibm.box.com/s/8mvodi0umsr019a55thujsyum5nd7b1q

2021-11-05 21:22 UTC, una-tapa commented
#build

2021-11-07 14:38 UTC, una-tapa commented
The 2nd build with automated test no longer contain collective related error.  It only had GUI errors.

2021-11-07 14:42 UTC, una-tapa commented
Cross reference: Serviceability items: 
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=268816

2021-11-09 18:25 UTC, barbj requested changes
I'd like to see you change the following:
1. change the name of the servletRequestInfo method to be more descriptive of what the method is doing.  Something like getServletRequestInfoAsString perhaps?
2. the servletRequestInfo method should be static
3. move the servletRequestInfo method from WebAppSecurityCollaboratorImpl to new class in the same package.  Call it something that is descriptive of what it is for.  ServletRequestInfoDebug perhaps?  Then, wrap the code in servletRequestInfo with a tc.isDebugEnabled().  This will allow a customer who doesn't want their header information emitted in a trace to turn off tracing of the new class.  If you don't do this, they'd have to turn off the entire WebAppSecurityCollaboratorImpl, which may not be desirable.

servletRequestInfo could either still return the String (or not) and the caller emits it to the trace, or change it so that servletRequestInfo does the emitting to the trace itself.  The advantage of the latter is that you would be able to turn on JUST header trace and it would be obvious what class you could turn off to disable the tracing.

2021-11-10 01:33 UTC, una-tapa commented
#build

2021-11-10 02:13 UTC, una-tapa commented
Added `@Trivial` to print only "Http header..".  It is much cleaner. 

The sample trace is uploaded to the box folder:  https://ibm.ent.box.com/folder/149534450992?s=8mvodi0umsr019a55thujsyum5nd7b1q

- When the header information is printed - trace.log `V3`
- When the header information output is turned off by `com.ibm.ws.webcontainer.security.ServletRequestInfoDebug=off`  `trace-print-header-off.log` 
 
#build

2021-11-10 16:12 UTC, barbj approved these changes
The code looks good.  However, I see some kind of issue with the "class turned off" trace.  When the class is turned off, the WebAppSecurityCollaboratorImpl stopped tracing too.  I don't see anything in the code that you updated that would have caused this problem.  I think that we need to consult RAS to find out what's up.  I'm approving this update.

2021-11-10 18:51 UTC, una-tapa commented
#libby  to see if copyright can be re-checked.

2021-11-10 18:56 UTC, una-tapa commented
Build came out with two errors.  Both are irrelevant to the Web/Sec trace.  

(1) Weld exception 
<br>[11/10/21, 3:42:35:417 PST] 0000003b com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0002E: An exception occurred while starting the application securityejbjarInWarEarM01. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.WeldException: java.lang.IllegalArgumentException: Wrong type at constant pool index

(2) server shutdown timeout 
java.lang.Exception: Errors/warnings were found in server com.ibm.ws.ui.tool.javaBatch_fat.gui logs:
 <br>[11/10/21, 8:15:09:059 PST] 0000009a com.ibm.ws.runtime.update.internal.RuntimeUpdateManagerImpl  W CWWKE1106W: 1 shutdown operations did not complete during the quiesce period.

2021-11-10 19:09 UTC, una-tapa commented
#libbybot

2021-11-11 14:07 UTC, una-tapa commented
I just realized there's AI analysis tool for the build error.  Looking at the analysis,  all the errors have been known prior to this PR.

2021-11-16 13:47 UTC, una-tapa commented
The integration branch was locked and reopen.  Submitting the build after rebase. 
#build

2021-11-17 21:54 UTC, una-tapa commented
#build

2021-11-18 14:35 UTC, una-tapa commented
#libbybot

2021-11-18 14:37 UTC, una-tapa commented
Only one error from the build that is already triaged as RTC287799.  Merging.

2021-11-18 14:37 UTC, merged