Adding OpenTracing-3.0 fat bucket for JakartaEE 9
OpenLiberty/open-liberty pull request #19296
Opened 2021-11-09 14:41 UTC by tonyreigns

Recreated the 2.x fat bucket for OT.30 for more coverage.

2021-11-09 14:41 UTC, tonyreigns commented
#build

2021-11-09 15:48 UTC, fmhwong commented on dev/io.openliberty.opentracing.3.x_fat/bnd.bnd
> +    io.openliberty.opentracing.2.0.internal;version=latest, \
io.openliberty.opentracing.2.0.internal.jakarta

2021-11-09 16:22 UTC, fmhwong requested changes
Can you take a look of the comments?

2021-11-09 16:22 UTC, fmhwong commented on dev/io.openliberty.opentracing.3.x_fat/bnd.bnd
> +    com.ibm.websphere.javaee.servlet.3.1;version=latest, \
remove?  since we have servlet-5.0 below

2021-11-09 16:22 UTC, fmhwong commented on dev/io.openliberty.opentracing.3.x_fat/bnd.bnd
> +    com.ibm.websphere.javaee.jaxrs.2.1;version=latest, \
restfulWS-3.0

2021-11-09 16:22 UTC, fmhwong commented on dev/io.openliberty.opentracing.3.x_fat/bnd.bnd
> +    com.ibm.websphere.javaee.cdi.2.0;version=latest, \
remove

2021-11-09 16:22 UTC, fmhwong commented on dev/io.openliberty.opentracing.3.x_fat/test-applications/mpOpenTracing/src/io/openliberty/opentracing/internal/test/mpot/POJO.java
> +import javax.enterprise.context.ApplicationScoped;
jakarta?

2021-11-09 16:22 UTC, fmhwong commented on dev/io.openliberty.opentracing.3.x_fat/fat/src/io/openliberty/opentracing/internal/test/FATUtilsSpans.java
> +import javax.json.JsonNumber;
jakarta?

2021-11-09 21:31 UTC, tonyreigns commented
#build

2021-11-10 15:17 UTC, tonyreigns commented
#build

2021-11-10 16:10 UTC, fmhwong approved these changes
LGTM

2021-11-16 14:27 UTC, tonyreigns commented
#build

2021-11-18 14:43 UTC, tonyreigns commented
#build

2021-11-19 18:29 UTC, tonyreigns commented
#run-libby-bot

2021-11-19 18:30 UTC, merged