remove atomic service reference
OpenLiberty/open-liberty pull request #19424
Opened 2021-11-21 20:23 UTC by benjamin-confino

2021-11-21 20:24 UTC, benjamin-confino commented
#build

2021-11-23 10:18 UTC, benjamin-confino commented
#build

2021-11-30 17:53 UTC, tjwatson requested changes

2021-11-30 17:53 UTC, tjwatson commented on dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
>      public void activate(ComponentContext cc) {
No need for an empty activate method.  You should delete this method.

2021-11-30 17:53 UTC, tjwatson commented on dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
>          cdiRuntime = null;
There is no need to null out this mandatory reference on deactivate.  I suggest deleting this whole method.

2021-11-30 17:53 UTC, tjwatson commented on dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
>      private CDIRuntime cdiRuntime;
Make `defaultMOS` and `cdiRuntime` final, remove `cdiService`  and add an `@Activate` constructor that sets these final values with constructor injection:

```java
@Activate
public CDIManagedObjectService(@Reference CDIService cdiService,
                               @Reference DefaultManagedObjectService defaultMOS) {
    this.cdiRuntime =  (CDIRuntime) cdiService;
    this.defaultMOS = defaultMOS;
}
```

The default for reference is static and mandatory, no need to name the reference.  Keep it simple.

2021-11-30 17:55 UTC, tjwatson commented on dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
> +    @Reference(name = "defaultManagedObjectService", service = DefaultManagedObjectService.class, cardinality = ReferenceCardinality.MANDATORY)
Forgot to mention this.  Delete the two `@Reference` set methods when using constructor injection for the references.

2021-12-05 21:41 UTC, benjamin-confino commented
#build

2021-12-16 13:03 UTC, tjwatson approved these changes
My comment is a nit.  It would be more clear to not check for null.  I'm fine merging as is, but if you have time it would be good to remove the null check.

2021-12-16 13:03 UTC, tjwatson commented on dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/managedobject/CDIManagedObjectService.java
> +        return cdiRuntime != null && cdiRuntime.isModuleCDIEnabled(mmd);
No need to have a check for null here.

2021-12-16 13:04 UTC, benjamin-confino commented
#build

2021-12-20 11:11 UTC, benjamin-confino commented
#run-libby-bot

2021-12-20 11:12 UTC, merged