Added wait till server quiesce for windows platform
OpenLiberty/open-liberty pull request #19436
Opened 2021-11-22 16:52 UTC by BerksanAtes

Fixes #19138

2021-11-22 19:01 UTC, BerksanAtes commented
SOE PB link -> https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_I61rgEu-Eeyptbrb2YKsmA

2022-01-11 15:17 UTC, BerksanAtes commented
#run-libby-bot

2022-01-11 18:14 UTC, neuwerk requested changes
See comments above! Over all looks good, just some simple changes needed to clean things up a tiny bit.

2022-01-11 18:14 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/endpoint/AbstractJaxWsWebEndpoint.java
>      public void invoke(HttpServletRequest request, HttpServletResponse response) throws ServletException {
Would it be possible to just add final modifiers to the method signatures so you don't have instantiate new variables?

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/build.gradle
> +    'org.apache.wink:wink-common:1.4',
I don't think you need the JAX-RS dependencies now you've split the FATs.

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/files/GlobalHandlerFeatureOnly/WithoutUserBundle/server.xml.ee9
> +    <logging traceSpecification="*=info:logservice=all:app.manager=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all"/>
can you remove this trace line just to keep things cleaner?

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/files/GlobalHandlerFeatureOnly/WithoutUserBundle/server.xml
> +    <logging traceSpecification="*=info:logservice=all:app.manager=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all"/>
can you remove this trace line just to keep things cleaner?

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/files/GlobalHandlerFeatureOnly/WithUserBundle/server.xml.ee9
> +    <logging traceSpecification="*=info:logservice=all:app.manager=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all"/>
can you remove this trace line just to keep things cleaner?

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/files/GlobalHandlerFeatureOnly/WithUserBundle/server.xml
> +    <logging traceSpecification="*=info:logservice=all:app.manager=all:com.ibm.ws.webcontainer*=all:com.ibm.wsspi.webcontainer*=all"/>
can you remove this trace line just to keep things cleaner?

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/files/GlobalHandlerFeatureOnly/Default/server.xml.ee9
> +    <logging traceSpecification="*=info:logservice=all:app.manager=all"/>
can you remove this trace line just to keep things cleaner?

2022-01-11 18:14 UTC, neuwerk commented on dev/io.openliberty.ws.jaxws.global.handler.internal_fat/publish/files/GlobalHandlerFeatureOnly/Default/server.xml
> +    <logging traceSpecification="*=info:logservice=all:app.manager=all"/>
can you remove this trace line just to keep things cleaner?

2022-01-11 18:29 UTC, BerksanAtes commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/endpoint/AbstractJaxWsWebEndpoint.java
>      public void invoke(HttpServletRequest request, HttpServletResponse response) throws ServletException {
done

2022-01-11 20:44 UTC, neuwerk approved these changes
Changes look good! Thanks so much for doing this @BerksanAtes!!

2022-01-20 17:54 UTC, jim-krueger reviewed
I hate to even mention this (considering how many files are in this PR), but I believe you need to change the copyright dates to 2022.  Sorry

2022-01-21 17:24 UTC, jim-krueger approved these changes

2022-01-21 21:17 UTC, BerksanAtes commented
#run-libby-bot

2022-01-21 21:23 UTC, merged