Create a TCK results file to upload
OpenLiberty/open-liberty pull request #19447
Opened 2021-11-23 15:29 UTC by benjamin-confino

2021-11-23 15:29 UTC, benjamin-confino commented
#build

2021-11-23 15:47 UTC, tevans78 commented
@benjamin-confino ignore that long message from LibbyBot, that isn't working properly

2021-11-25 11:42 UTC, yasmin-aumeeruddy requested changes
Other than adding a space between the test suite name and timestamp, it all looks good!

2021-11-25 11:42 UTC, yasmin-aumeeruddy commented on dev/fattest.simplicity/src/componenttest/topology/utils/TestSuiteResult.java
> +        strBuild.append("Test suite: " + name +  timestamp);
```suggestion
        strBuild.append("Test suite: " + name +  " "  +  timestamp);
```

2021-11-25 11:43 UTC, benjamin-confino commented
#build

2021-11-26 09:06 UTC, yasmin-aumeeruddy approved these changes

2021-11-26 10:09 UTC, benjamin-confino commented
#run-libby-bot

2021-11-26 10:46 UTC, tevans78 approved these changes

2021-11-26 10:48 UTC, merged