Initial implementation of JAX-RS 3.1 (still using RESTEasy for 3.0) and TCK FAT
OpenLiberty/open-liberty pull request #19465
Opened 2021-11-23 22:49 UTC by andymc12

- This adds the 3.1 feature code and updates the autofeatures.
- It points to a snapshot build of the JAX-RS 3.1 APIs.
- In includes the snapshot of the TCK running as a FAT.
- All translation files copied over from the 3.0 implementation.
- The implementation is using the 3.0 (transformed) version of RESTEasy.

Part of epic issue #18739.

2021-11-23 22:49 UTC, andymc12 commented
#build

2021-11-24 11:41 UTC, ramkumar-k-9286 commented
It seems like there are no English messages to review in this issue.

Adding the `ID Review not needed` label. If this is not correct please let me know.

Regards,
Ramkumar

2021-11-29 17:17 UTC, jim-krueger approved these changes

2021-11-29 19:41 UTC, WhiteCat22 approved these changes

2021-11-30 21:18 UTC, skasund commented
L2 message review not required

2021-12-01 13:53 UTC, tevans78 requested changes
Please wait for the feature to at least be prioritzed before merging this.

2021-12-06 17:26 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.0-xmlBinding3.0.feature
>   osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.xmlBinding-3.0))"
This PR should go in after https://github.com/OpenLiberty/open-liberty/pull/19534
That will make a `xmlBinding-4.0` feature should be available (even if it is still based on 3.0) and so this auto-feature should take that into account.

2021-12-06 17:28 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.1.feature
> +-features=com.ibm.websphere.appserver.eeCompatible-9.0, \
Similarly, #19534 will make `eeCompatible-10.0` available

2021-12-06 17:31 UTC, tevans78 commented on dev/io.openliberty.jakarta.rest.3.1.internal_fat_tck/publish/servers/FATServer/server.xml
> +        <feature>xmlBinding-3.0</feature>
Use EE 10 features

2021-12-06 21:37 UTC, andymc12 commented
Last build failed due to missing an Apache HTTP Client 3.1 class - explicitly adding that into the pom.xml - new #build

2021-12-17 23:49 UTC, andymc12 commented
This currently cannot be merged because the `arquillian-support-jakarta-2.0` feature depends on `servlet-5.0`, and fails when testing with EE10 features. I opened https://github.com/OpenLiberty/liberty-arquillian/pull/114 which would resolve issue https://github.com/OpenLiberty/liberty-arquillian/issues/113 - once that issue is resolved and pulled in to Liberty, then development on this PR could continue.

2022-08-17 19:42 UTC, jim-krueger commented
Closing,  changes updated and merged under #20505

2022-08-17 19:42 UTC, closed without merging