OpenTracing - Error handling when span starting fails so requests continue
OpenLiberty/open-liberty pull request #19461
Opened 2021-11-23 19:12 UTC by tonyreigns

Errors when a span is started are now caught so the request continues and the trace error is outputted rather than the entire request failing due to a failed trace.

See issue: #17875

2021-11-23 19:19 UTC, wraschke commented
#run-libby

2021-11-23 20:34 UTC, tonyreigns commented
#build

2021-11-24 15:24 UTC, fmhwong requested changes
Can you add a FAT?

2021-11-24 15:50 UTC, fmhwong commented
@tonyreigns As discuss, please limit the number of error messages printed to the log.

2022-01-13 19:19 UTC, tonyreigns commented
#build

2022-01-19 16:17 UTC, fmhwong commented on dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingClientFilter.java
> +            try{
Can you fix the indent with 4 space?   Please don't use tab.

2022-01-19 16:18 UTC, fmhwong commented on dev/com.ibm.ws.opentracing.1.1/src/com/ibm/ws/opentracing/OpentracingClientFilter.java
> +                if(!spanErrorLogged) {
We usually have a space after `if`

2022-01-19 18:37 UTC, fmhwong requested changes
Is `OPENTRACING_COULD_NOT_START_SPAN` a new message?  I don't see it added to `Opentracing.nlsprops`.  Also what is the Exception you are going to catch?  Can we narrow it down a bit as you're just catching all `Error`s.  I worry that once an Error is thrown, we will hide all other `Error` and `Exception`.

2022-01-24 20:06 UTC, tonyreigns commented
#build

2022-01-26 02:35 UTC, tonyreigns commented
#build

2022-01-27 18:49 UTC, fmhwong approved these changes
LGTM

2022-01-27 18:50 UTC, fmhwong commented
@tonyreigns You might need a message review.

2022-02-01 16:16 UTC, tonyreigns commented
#build

2022-02-01 19:34 UTC, tonyreigns commented
#libby

2022-02-08 19:59 UTC, skasund commented
L2 message review completed

2022-02-08 20:06 UTC, tonyreigns commented
#build

2022-02-09 15:19 UTC, tonyreigns commented
#libby

2022-02-09 16:02 UTC, merged