featureUtility installServerFeatures user feature bug
OpenLiberty/open-liberty pull request #19635
Opened 2021-12-14 00:42 UTC by jjiwooLim

- extractFeature(String filename) was not extracting feature name correctly from the filename. 
    - user features doesn't necessarily have the same version as the Liberty version. i.e) userfeature-1.0 instead of userfeature-21.0.0.9

- getFeaturesToInstall(Collection<String> requiredFeatures, boolean download):
    - user features that are listed in server.xml can have extensions as `[extension:featureName]`. e.g) `<feature>myExt:userfeature-1.0</feature>`
    - need to pass in the feature name without the extension

- containFeature(Map<String, ProvisioningFeatureDefinition> installedFeatures, String feature):
    - Liberty feature manifest doesn't require `IBM-ShortName` [(reference)](https://www.ibm.com/docs/en/was-liberty/base?topic=manually-liberty-feature-manifest-files) . User feature might not have this header. Checking the required header `Subsystem-SymbolicName` first to see if the features are already installed.

2021-12-14 01:36 UTC, jjiwooLim commented
#build

2021-12-14 20:25 UTC, jjiwooLim commented
#build

2021-12-15 16:52 UTC, jacobwdv requested changes
Looks good! Some suggestions / questions.

2021-12-15 16:52 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
> +	 * extractFeature(appSecurity-3.0-19.0.0.8.esa) returns appSecurity-3.0
add a description to the @return part of this javadoc.

2021-12-15 16:52 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
> +		String[] split = filename.split("-");
if we aren't checking for filename == null i would just add that to the javadoc on line 628 that it can't be null.

2021-12-15 16:52 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
> +		if (split.length > 2) {
should this be `>=2` or `>1`? I'm thinking of a test string like `"appSecurity-3.0.19.0.0.8.esa"` which would return `appSecurity`.

2021-12-15 16:52 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/AbstractDirector.java
> +        if (feature.contains(":") && feature.split(":").length == 2)
```suggestion
        if (feature.split(":").length == 2)
```

2021-12-16 18:53 UTC, jjiwooLim commented
#build

2021-12-16 18:54 UTC, jjiwooLim commented
#libby-bot

2021-12-16 19:30 UTC, jacobwdv approved these changes
Looks good to me!

2021-12-23 22:18 UTC, merged