19630 ignore designated
OpenLiberty/open-liberty pull request #19634
Opened 2021-12-14 00:18 UTC by tbitonti

Work in progress.
Initial implementation of an "ignore designated class" application class loader mechanism.

2021-12-14 00:19 UTC, tbitonti commented
#build

2021-12-14 14:10 UTC, tjwatson commented on dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
> +        InputStream inputStream = AppClassLoader.class.getResourceAsStream(FORBIDDEN_PROPERTIES);
Use try-with-resource/finally here to manage the inputstream closing

2021-12-14 14:10 UTC, tjwatson commented on dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
> +            throw new ClassNotFoundException(name);
As the comment suggests, we could give a more detailed error message.  In most cases the JVM is going to catch the CNFE, forget the message and then throw a NoClassDefFoundError with only the class name, so having a more detailed message gives little value besides Class.forName and direct ClassLoader.loadClass calls by the applications.

2021-12-14 14:10 UTC, tjwatson commented on dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
> +        String jndiLookupClassName = "org.apache.logging.log4j.core.lookup.JndiLookup";
Why is this not contained in the properties file we include?

2021-12-14 14:10 UTC, tjwatson commented on dev/com.ibm.ws.classloading/src/com/ibm/ws/classloading/internal/AppClassLoader.java
> +    private static final Set<String> forbiddenClasses = new HashSet<>();
Make this an unmodifiable set in the static block below instead of assigning it to a modifiable set here.

2021-12-14 14:25 UTC, tjwatson requested changes
I see little value in having some hard-coded classes directly in the `.java` code and in the `.properties` file contained in the bundle.  In both cases the class name is hard coded and the classloading bundle must be rebuilt to update the forbidden class set.

Is the design to not have a `.properties` file in the classloading bundle?  Instead have a hard-coded set in the `.java` code and be able to load the `.properties` file from a fragment of classloading?  I have my doubts that is the intention.  If so then I suggest we need more comments in the code indicating the intent.  I also suggest that `java.lang.ClassLoader.getResources(String)` is used to allow multiple fragments to supply the set, otherwise only the "first" fragment will win which is unpredictable.

2021-12-14 17:13 UTC, tbitonti commented
#build

2021-12-14 22:25 UTC, tjwatson commented
#build
#libby

2021-12-15 14:38 UTC, tjwatson approved these changes
I approve, but should be reviewed by another for the changes I made.  We have a good build, but we should add a test.  I'll work on that now, but we could consider merging this now I think.

2021-12-15 15:56 UTC, jaridk approved these changes

2021-12-15 16:02 UTC, NottyCode approved these changes

2021-12-15 16:10 UTC, merged