Remove any empty strings in hideMessageids
OpenLiberty/open-liberty pull request #19689
Opened 2021-12-22 21:32 UTC by Channyboy

#build

2021-12-23 19:02 UTC, Channyboy commented
#build

2021-12-29 19:49 UTC, Channyboy commented
#build

2021-12-30 01:36 UTC, Channyboy commented
#build 
Failures scene in first two builds are related to a dependency upgrade on build machines for finding bugs.  The bugs found were not a result of this PR.
Reverting to original commit.

2022-01-04 18:33 UTC, fmhwong commented on dev/com.ibm.ws.logging/src/com/ibm/ws/logging/internal/impl/BaseTraceService.java
> +        hideMessageids = trConfig.getMessagesToHide().stream().filter(s -> !s.equals("")).map(s -> s).collect(Collectors.toList());
I'd use `s.isEmpty()` since it is a bit faster than `s.equals("")`

2022-01-04 18:40 UTC, fmhwong requested changes
See comments

2022-01-04 19:29 UTC, Channyboy commented
#build

2022-01-04 21:05 UTC, fmhwong approved these changes
LGTM

2022-01-05 19:03 UTC, Channyboy commented
Errors/Warnings are related to original explanation made earlier where find bugs are triggered (for many components) due to a dependency change. Not Test failures.
#libby

2022-01-05 19:07 UTC, merged