Update restConnector features for mpOpenApi-3.0
OpenLiberty/open-liberty pull request #19818
Opened 2022-01-14 17:33 UTC by Azquelt

Make the OpenAPI documentation for the restconnector config and validation endpoints work with mpOpenApi-3.0.

This was missed during the development of mpOpenApi-3.0.

Fixes #19796

2022-01-14 17:40 UTC, Azquelt commented
#build

2022-01-14 20:28 UTC, nmittles approved these changes
The changes look good to me.  My only comment is for updating copyright years for the following:

com.ibm.ws.rest.handler.config_fat/bnd.bnd
com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigOpenApiSchemaTest.java
com.ibm.ws.rest.handler.config_fat/fat/src/com/ibm/ws/rest/handler/config/fat/ConfigRESTHandlerJCATest.java
com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateDataSourceTest.java
com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJCATest.java com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJMSTest.java
io.openliberty.rest.handler.config.openapi.common/bnd.bnd
io.openliberty.rest.handler.validator.openapi.2.0/bnd.bnd

2022-01-17 16:17 UTC, Azquelt commented
I didn't update the copyright date on the files where I'd only made very minor changes.

Looking over the files mentioned though, I should have updated it on ValidateJCETest and VaildateDataSourceTest.

2022-01-17 16:22 UTC, Azquelt commented
#libby
#build

2022-01-18 10:30 UTC, tevans78 commented on dev/com.ibm.ws.rest.handler.validator_fat/fat/src/com/ibm/ws/rest/handler/validator/fat/ValidateJMSTest.java
> +import static com.ibm.ws.rest.handler.validator.fat.FATSuite.assertClassEquals;
Copyright date

2022-01-18 15:54 UTC, tevans78 requested changes

2022-01-18 15:54 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationConfigSchema-3.0.feature
> +symbolicName=com.ibm.websphere.appserver.configValidationConfigSchema-3.0
Consider naming this `io.openliberty.configValidationConfigSchema-3.0`

2022-01-18 15:54 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationValidatorSchema-3.0.feature
> +symbolicName=com.ibm.websphere.appserver.configValidationValidatorSchema-3.0
Consider naming this `io.openliberty.configValidationValidatorSchema-3.0`

2022-01-18 15:54 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationConfigSchema-3.0.feature
> +symbolicName=com.ibm.websphere.appserver.configValidationConfigSchema-3.0
All new features should follow the `io.openliberty...` naming scheme

2022-01-18 15:54 UTC, tevans78 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationValidatorSchema-3.0.feature
> +symbolicName=com.ibm.websphere.appserver.configValidationValidatorSchema-3.0
All new features should follow the `io.openliberty...` naming scheme

2022-01-18 15:58 UTC, Azquelt commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.configValidationConfigSchema-3.0.feature
> +symbolicName=com.ibm.websphere.appserver.configValidationConfigSchema-3.0
Thanks, I always forget that when I start by copying an existing feature :(

2022-01-18 16:09 UTC, Azquelt commented
Updated feature names.
#build
#libby

2022-01-18 16:53 UTC, tevans78 approved these changes

2022-01-19 10:17 UTC, merged