Remove beta guards for JPA default properties feature
OpenLiberty/open-liberty pull request #19872
Opened 2022-01-20 18:49 UTC by dazey3

for #15979

Signed-off-by: Will Dazey <dazeydev.3@gmail.com>

2022-01-20 19:53 UTC, tkburroughs requested changes

2022-01-20 19:53 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.container.core/src/com/ibm/ws/jpa/management/JPAPUnitInfo.java
> +        // Add default persistence properties supplied from JPAComponent configuration
Please remove the now unused import of com.ibm.ws.kernel.productinfo.ProductInfo;

2022-01-27 16:10 UTC, dazey3 commented
#build #spawn.fullfat.buckets=com.ibm.ws.jpa.tests.jpaconfig_jpa_2.1_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_2.2_fat,com.ibm.ws.jpa.tests.jpaconfig_jpa_3.0_fat

2022-01-27 16:26 UTC, tkburroughs approved these changes

2022-01-27 16:26 UTC, tkburroughs commented
#run_libby

2022-01-27 16:26 UTC, tkburroughs commented
#run-libby

2022-01-28 15:46 UTC, merged