Add ASMHelper to decouple appserver code from ASM version opcode cons…
OpenLiberty/open-liberty pull request #19907
Opened 2022-01-24 22:19 UTC by jgrassel

Whenever ASM is updated, it often includes a version update in the form of Opcodes.ASM#, which code consuming ASM must update.  An update which is easy to overlook.

I've added `com.ibm.ws.asm.ASMHelper` (as part of Liberty's ASM bundle) to provide Liberty with a utility class to ease some of the pain:
```
    /**
     * Returns the constant representing the current version of ASM.
     *
     * @return
     */
    public final static int getCurrentASM();
```

I've found that certain instrumentation classes are too primordial (ant.instrumentation draws from `ant_build.js/build.gradle`, which uses the raw maven coordinates for asm, to benefit from this.  It may be possible to work around this, but that is for a future update.  For those, I went and updated the referenced ASM level to `Opcodes.ASM9'.

2022-01-24 22:19 UTC, jgrassel commented
#build

2022-01-25 14:49 UTC, jgrassel commented
#build

2022-01-25 15:19 UTC, jhanders34 requested changes

2022-01-25 15:19 UTC, jhanders34 commented on dev/com.ibm.ws.org.objectweb.asm/src/com/ibm/ws/asm/ASMHelper.java
> + * Copyright (c) 2010, 2013 IBM Corporation and others.
Copyright should be 2022

2022-01-25 15:19 UTC, jhanders34 commented on dev/com.ibm.ws.org.objectweb.asm/src/com/ibm/ws/asm/ASMHelper.java
> +package com.ibm.ws.asm;
Ideally this package would be io.openliberty.asm

2022-01-25 15:19 UTC, jhanders34 commented on dev/com.ibm.ws.org.objectweb.asm/bnd.overrides
A comment in bnd.bnd or bnd.overrides to instruct people to update the CURRENT_ASM field in ASMHelper if the version is changed to a new major version would be very helpful.  Somewhere near where the version is specified.

2022-02-02 21:16 UTC, jgrassel commented
#run-libby-bot
#build

2022-02-03 15:31 UTC, jgrassel commented
#run-libby-bot
#build

2022-02-03 16:19 UTC, jhanders34 approved these changes

2022-02-04 16:46 UTC, merged