Replace prohobited terms
OpenLiberty/open-liberty pull request #19988
Opened 2022-02-01 05:20 UTC by anjumfatima90

2022-02-01 05:20 UTC, anjumfatima90 commented
#build

2022-02-06 04:29 UTC, anjumfatima90 commented
#build

2022-03-22 20:22 UTC, mbroz2 commented
#build

2022-05-19 04:26 UTC, mbroz2 approved these changes
@pnicolucci @volosied does jsf-2.2 still see updates?   I couldn't find instances of this in 2.3 or beyond so it seems it's been resolved upstream in new versions.

2022-05-23 20:07 UTC, anjumfatima90 commented
#build

2022-05-23 20:08 UTC, volosied commented
Hi, @mbroz2,  I addressed the terms in https://github.com/OpenLiberty/open-liberty/pull/20993 and 

As for  jsf-2.0 and jsf-2.2, we have a copy of the source code in CL/OL, respectfully.  As for 2.3 and 3.0, we pull in the code via the jars (uploaded to artifactory).  

JSF should all comply now with the terms in Liberty and in the open source ( https://issues.apache.org/jira/browse/MYFACES-4435 )

2022-05-24 13:52 UTC, mbroz2 requested changes
Some minor tweaks to help ensure we don't loose any context in the comments.

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/conf/authn/remoteuser-internal-authn-config.xml
> +    <!-- Uncomment/configure to install username, and/or match expressions. -->
```suggestion
    <!-- Uncomment/configure to install username restrictions (allowing/blocking lists), and/or match expressions. -->
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/conf/global.xml
> +    Algorithm that override or merge with library defaults. Normally you can leave
```suggestion
    Algorithm restrictions (allowing/blocking lists) that override or merge with library defaults. Normally you can leave
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/conf/intercept/consent-intercept-config.xml
> +    Attribute release attribute IDs, and match expressions to determine
```suggestion
    Attribute release attribute IDs restrictions (allowing/blocking lists), and match expressions to determine 
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/dist/conf/authn/remoteuser-internal-authn-config.xml.dist
> +    <!-- Uncomment/configure to install username, and/or match expressions. -->
```suggestion
    <!-- Uncomment/configure to install username restrictions (allowing/blocking lists), and/or match expressions. -->
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/dist/conf/global.xml.dist
> +    Algorithm that override or merge with library defaults. Normally you can leave
```suggestion
    Algorithm restrictions (allowing/blocking lists) that override or merge with library defaults. Normally you can leave
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/3.3.1/dist/conf/intercept/consent-intercept-config.xml.dist
> +    Attribute release attribute IDs, and match expressions to determine
```suggestion
    Attribute release attribute IDs restrictions (allowing/blocking lists), and match expressions to determine 
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/4.1.0/conf/authn/remoteuser-internal-authn-config.xml
> +    <!-- Uncomment/configure to install username, and/or match expressions. -->
```suggestion
    <!-- Uncomment/configure to install username restrictions (allowing/blocking lists), and/or match expressions. -->
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/4.1.0/conf/global.xml
> +    Algorithm that override or merge with library defaults. Normally you can leave
```suggestion
    Algorithm restrictions (allowing/blocking lists) that override or merge with library defaults. Normally you can leave
```

2022-05-24 13:52 UTC, mbroz2 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/4.1.0/conf/intercept/consent-intercept-config.xml
> +    Attribute release attribute Ids, and match expressions to determine
```suggestion
    Attribute release attribute IDs restrictions (allowing/blocking lists), and match expressions to determine 
```

2022-05-24 19:34 UTC, anjumfatima90 commented on dev/com.ibm.ws.security.saml.sso_fat.common/shibboleth-idp/4.1.0/conf/intercept/consent-intercept-config.xml
> +    Attribute release attribute Ids, and match expressions to determine
done!

2022-05-24 19:36 UTC, mbroz2 approved these changes

2022-05-25 16:32 UTC, anjumfatima90 commented
#libby

2022-05-26 14:06 UTC, merged