Initial commit for time based rollover in access logging
OpenLiberty/open-liberty pull request #20035
Opened 2022-02-03 19:34 UTC by ellen-lau

2022-02-03 19:48 UTC, ellen-lau commented
#build

2022-02-08 19:57 UTC, skasund commented
L2 message review completed

2022-02-11 14:41 UTC, helyarp reviewed
Suggested changes to log.access.rollover.start.time.desc. The other messages have 100 (green) quality scores.

2022-02-11 14:41 UTC, helyarp commented on dev/com.ibm.ws.transport.http/resources/OSGI-INF/l10n/metatype.properties
> +log.access.rollover.start.time.desc=The scheduled time of day when logs should first rollover. The rollover interval duration will begin at rollover start time. Valid values follow a 24-hour ISO-8601
Suggested changes to remove "should" and "will," to change "rollover" (noun) to "roll over" (verb), and to use "zeros" not "zeroes":

The scheduled time of day for logs to first roll over. The rollover interval duration begins at rollover start time. Valid values follow a 24-hour ISO-8601 datetime format of HH:MM, where 00:00 represents midnight. Padding zeros are required.

2022-02-17 19:10 UTC, ellen-lau commented
#build

2022-02-28 18:49 UTC, ellen-lau commented
#build

2022-03-02 05:34 UTC, mrsaldana approved these changes
LGTM, thanks for the work here!

2022-03-02 05:34 UTC, mrsaldana commented on dev/com.ibm.ws.transport.http/resources/OSGI-INF/metatype/metatype.xml
> +            id="rolloverInterval" required="false" type="String" ibm:type="duration(m)" default="-1" ibm:beta="true">
The log.rollover.interval.too.short.warning specifies that the interval cannot be less than one minute long, yet here the default is being set to -1. This might be a confusing configuration design for customers. This warning also specifies that the default value is 1 minute.

2022-03-02 05:34 UTC, mrsaldana commented on dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/logging/internal/AccessLogger.java
> +    private static final long ROLLOVER_INTERVAL_DEFAULT = 1440;
The current default of the metatype is set to -1, perhaps this interval should be set to the default of the metatype?

2022-03-02 05:36 UTC, mrsaldana requested changes
Actually, one last ask. Can you update the range on the copyright for these classes to reflect the current year 2022?

2022-03-02 13:15 UTC, ellen-lau commented
#run-libby-bot

2022-03-02 13:27 UTC, mrsaldana approved these changes
Thanks for updating, LGTM now

2022-03-02 13:31 UTC, ellen-lau commented
#run-libby-bot

2022-03-02 13:31 UTC, ellen-lau commented
#build

2022-03-10 12:41 UTC, helyarp reviewed
Looks good!

2022-05-02 18:50 UTC, ellen-lau commented
#build

2022-05-03 18:00 UTC, ellen-lau commented
The error in the build (a UI fat failure, is unrelated to the code changes

2022-05-03 18:01 UTC, merged