Move TCK Results info to method in MvnUtils
OpenLiberty/open-liberty pull request #20066
Opened 2022-02-08 14:43 UTC by yasmin-aumeeruddy

The info required for the TCK Results generator had previously been generated in the TCK launchers but has now been moved to a single method in the MvnUtils file.

2022-02-08 14:44 UTC, yasmin-aumeeruddy commented
#build

2022-02-08 20:20 UTC, yasmin-aumeeruddy commented
#build

2022-02-08 22:08 UTC, yasmin-aumeeruddy commented
#build

2022-02-08 22:53 UTC, yasmin-aumeeruddy commented
#build

2022-02-09 14:57 UTC, Yas-Franco commented
#build

2022-02-10 17:33 UTC, tevans78 commented on dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/fat/src/com/ibm/ws/concurrent/mp/v1_2/fat/tck/MPContextPropagationTCKLauncher.java
> + * Copyright (c) 2018,2021,2022 IBM Corporation and others.
max two years lists - first, last
```suggestion
 * Copyright (c) 2018 ,2022 IBM Corporation and others.
```

2022-02-10 17:34 UTC, tevans78 commented on dev/com.ibm.ws.concurrent.mp.1.2_fat_tck/fat/src/com/ibm/ws/concurrent/mp/v1_2/fat/tck/MPContextPropagationTCKLauncher.java
> + * Copyright (c) 2018,2021,2022 IBM Corporation and others.
same comment for the other files!

2022-02-10 17:42 UTC, tevans78 requested changes
A few minor things to tidy up

2022-02-10 17:42 UTC, tevans78 commented on dev/com.ibm.ws.concurrent.mp_fat_tck/fat/src/com/ibm/ws/concurrent/mp/fat/tck/MPConcurrencyTCKLauncher.java
> +        resultInfo.put("results_type", "MicroProfile");
results_type added twice

2022-02-10 17:42 UTC, tevans78 commented on dev/com.ibm.ws.concurrent.mp_fat_tck/fat/src/com/ibm/ws/concurrent/mp/fat/tck/MPConcurrencyTCKLauncher.java
> +        resultInfo.put("feature_name", "1.0");
is this a name or a version?

2022-02-10 17:42 UTC, tevans78 commented on dev/com.ibm.ws.concurrent.mp_fat_tck/fat/src/com/ibm/ws/concurrent/mp/fat/tck/MPConcurrencyTCKLauncher.java
> +        resultInfo.put("feature_name", "1.0");
```suggestion
        resultInfo.put("feature_version", "1.0");
```

2022-02-10 17:42 UTC, tevans78 commented on dev/com.ibm.ws.microprofile.config.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/config/tck/ConfigTCKLauncher.java
> + * Copyright (c) 2017,2022 IBM Corporation and others.
strictly there should be space between the two
```suggestion
 * Copyright (c) 2017, 2022 IBM Corporation and others.
```

2022-02-10 17:42 UTC, tevans78 commented on dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +        Map<String, String> resultInfo = MvnUtils.getResultInfo(server);
you didn't update the copyright date on this file ... and some of the others

2022-02-10 17:42 UTC, tevans78 commented on dev/io.openliberty.jakarta.concurrency.3.0_fat_tck/fat/src/io/openliberty/jakarta/enterprise/concurrent/tck/ConcurrentTckLauncher.java
> +        assertEquals(0, result);
interesting that not all of the TCKs have this assert? is it needed? should it be consistent across all of them?

2022-02-11 14:41 UTC, tevans78 approved these changes

2022-02-14 10:54 UTC, yasmin-aumeeruddy commented
#libby

2022-02-14 11:32 UTC, merged