Add security headers filter to OpenAPI UI
OpenLiberty/open-liberty pull request #20260
Opened 2022-02-24 16:08 UTC by arturdzm

2022-02-24 16:09 UTC, arturdzm commented
link #288858

2022-02-28 12:01 UTC, Azquelt requested changes

2022-02-28 12:01 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.openapi.ui/bnd.bnd
> +  ../com.ibm.ws.openapi.ui/swagger-ui/dist;filter:=!*.html, \
This change looks wrong. A while ago for #19931, we decided to stop including the source maps in the built jar because they're quite large and this change would undo that.

Could you remove this change (and the corresponding changes in the other two bnd files)?

2022-02-28 12:01 UTC, Azquelt commented on dev/com.ibm.ws.openapi.ui.private/src/com/ibm/ws/openapi/filter/OpenAPIFilter.java
> +	}
The indentation here is wrong because you've got a tab instead of spaces.

2022-02-28 12:01 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.openapi.ui/resources/WEB-INF/web.xml
> +    <filter-class>com.ibm.ws.microprofile.openapi.servlet.filter.OpenAPIUIFilter</filter-class>
The copyright headers on all the web.xml files should be updated to `2017, 2022`

2022-02-28 14:08 UTC, arturdzm commented
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_Cae1IJcmEeyylMvVD7B-oA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

2022-03-01 14:05 UTC, arturdzm commented
Thank you for review @Azquelt I'ved updated the files and here is a new build
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=__iUdcJifEeyylMvVD7B-oA&tab=com.ibm.team.build.web.ui.internal.editors.result.activity.ActivitiesProvider

2022-03-01 14:26 UTC, Azquelt approved these changes
Looks good, thanks @arturdzm

2022-03-01 15:05 UTC, arturdzm commented
#libby

2022-03-01 16:09 UTC, merged

2022-03-01 18:35 UTC, arturdzm commented
OLGH#20293