Initial drop of componenttest public API and provider API source
OpenLiberty/open-liberty pull request #20396
Opened 2022-03-11 11:32 UTC by tevans78

2022-03-11 12:13 UTC, tevans78 commented
#libby

2022-03-11 17:37 UTC, tevans78 commented
#build

2022-03-14 14:10 UTC, tevans78 commented
#build

2022-03-14 15:49 UTC, tevans78 commented
#build

2022-03-16 16:16 UTC, tevans78 commented
#build

2022-03-16 17:12 UTC, tevans78 commented
#build

2022-03-16 17:13 UTC, tevans78 commented
PB: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_CR5CoKVEEeyLpORmV0nVgA

2022-03-18 19:34 UTC, jhanders34 requested changes
I do not want to add 1400+ files to fattest.simplicity when we can do so much less.  In the end with some cleanup of existing fattest.simplicity classes and removal of some unused methods, you only need 7 classes instead of 1400+.  I have added the necessary changes in the review comments with suggestions to make it easy to see what needs to be changed.  If I did not comment on a class, that classes can be removed.

The only other change that needs to be made is in the com.ibm.ws.fat.util.Props class:

        `properties.put("simplicity.version", Topology.SIMPLICITY_VERSION);`

should change to something like:

        `properties.put("simplicity.version", "2.0");`

and the import of Topology removed.

If WebSphere Liberty requires some additional classes then those classes should only be added to the WebSphere Liberty side so as not to pollute Open Liberty's source.

2022-03-18 19:34 UTC, jhanders34 commented on dev/com.ibm.ws.common.encoder/bnd.bnd
> -	org.jmock:jmock;strategy=exact;version=2.5.1, \
This change seemed out of place and unrelated.  What led to doing this change?

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/bnd.bnd
> +	com.ibm.websphere.simplicity.wsadmin.*
```suggestion
	com.ibm.websphere.simplicity.configuration
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> +    protected ConnectorType connType;
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> +    }
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> +    }
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> +
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> +                || ((this.host == null) && (other.host != null)) || ((this.host != null) && (!this.host.equalsIgnoreCase(other.host)))
```suggestion
        if(((this.host == null) && (other.host != null)) || ((this.host != null) && (!this.host.equalsIgnoreCase(other.host)))
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> +    		nci.setConnType(connType);
```suggestion
     * @param port The port to connect to
     * @param user The user name to use when connecting
     * @param password The password to use when connecting
     * @return Cloned ConnectionInfo
     * @throws CloneNotSupportedException
     */
    public Object clone(int port, String user, String password) throws CloneNotSupportedException {
    	ConnectionInfo nci = (ConnectionInfo)this.clone();
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/LocalFile.java
> +public class LocalFile extends RemoteFile {
Keep this file.

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ConnectionInfo.java
> + * Copyright (c) 2011 IBM Corporation and others.
```suggestion
 * Copyright (c) 2011,2022 IBM Corporation and others.
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/Machine.java
>  import com.ibm.websphere.simplicity.provider.commandline.local.LocalCommandLineProvider;
```suggestion
```

And remove the `RemoteCommand executeAsync(String cmd, String[] parameters, String workDir, Properties envVars) throws Exception` method

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/ProgramOutput.java
> +public class ProgramOutput {
Keep this file.

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/ConfigurationProvider.java
> + * Copyright (c) 2011 IBM Corporation and others.
```suggestion
 * Copyright (c) 2011,2022 IBM Corporation and others.
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/ConfigurationProvider.java
> +
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/ConfigurationProvider.java
> +import com.ibm.websphere.simplicity.log.Log;
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/FormattedProperties.java
> + * Copyright (c) 2011 IBM Corporation and others.
```suggestion
 * Copyright (c) 2011,2022 IBM Corporation and others.
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/FormattedProperties.java
> +import com.ibm.websphere.simplicity.BootStrappingProperty;
```suggestion
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/FormattedProperties.java
> +                if (property.indexOf(BootStrappingProperty.DATA.toString()) == -1) {
```suggestion
                if (property.indexOf("data") == -1) {
```

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/configuration/PropertiesConfigurationProvider.java
> +public class PropertiesConfigurationProvider extends ConfigurationProvider {
Keep this file.

2022-03-18 19:34 UTC, jhanders34 commented on dev/fattest.simplicity/src/com/ibm/websphere/simplicity/log/Log.java
> +public class Log {
Keep this file.

2022-03-18 20:11 UTC, jhanders34 commented
It looks like there are some additional changes needed to clean up dead code in some of the FAT projects.  I hadn't updated some of the settings in fattest.simplicity bnd when I originally ran with the changes outlined in the PR review.

Additional changes that are needed:

- com.ibm.ws.logging.htpel.fat.CommonTasks, need to remove `void removeUnusedServers(Cell cell, Set<Server> excludedServers) throws Exception`, `void remove(Server server) throws Exception` and `void startServer(Server serverToStart) throws Exception` methods.  The imports will also need to be removed that are no longer used with the removal of those methods.

- io.openliberty.wsoc.util.WebServerControl, add:
```
    enum ProcessStatus {
        RUNNING, STOPPED
    };
```
and remove the `com.ibm.websphere.simplicity.runtime.ProcessStatus` import.

Additionally it looks like:

```
com.ibm.ws.componenttest:com.ibm.componenttest.common:1.0.0
com.ibm.ws.componenttest:com.ibm.ws.topology.helper:1.0.0
com.ibm.ws.componenttest:fat.harness:1.0.0
```
are not needed and `com.ibm.ws.componenttest:fat.util:1.0.0` only has 4 classes so it would make sense to add the source for those 4 classes as part of this PR as well.  It looks like the UnitConverter method may not be used so its source may not need to be added.

2022-03-29 16:39 UTC, tevans78 commented
#build

2022-04-03 11:15 UTC, jhanders34 approved these changes
I am marking it approved.  I am not sure why there are copyright updates for the com.ibm.websphere.simplicity.config files in this PR, but I can live with them.  I do agree that a squash should be done of at least the first 3 commits in the PR.

2022-04-04 09:23 UTC, tevans78 commented
@jhanders34 I have now squashed, rebased and removed those extra copyright changes from the config package.
#build

2022-04-05 10:20 UTC, tevans78 commented
#build

2022-04-05 16:00 UTC, tevans78 commented
#build

2022-04-06 09:54 UTC, tevans78 commented
Finally got a green PB so good to merge

2022-04-06 09:54 UTC, tevans78 commented
#libby

2022-04-08 09:03 UTC, merged