287420-validate-user-input-json
OpenLiberty/open-liberty pull request #20462
Opened 2022-03-15 10:43 UTC by sarinjacobsunny

287420: Filter un-sanitised user input.

2022-03-15 16:04 UTC, k8vance88 requested changes
All files with copywrite statements need to have the latest date appended to the end. For example, if it says 2015 then you should add 2015, 2022.  If there are 2 dates, replace the last one with 2022.

2022-03-15 16:04 UTC, k8vance88 commented on dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/v1/CatalogAPI.java
> +
This change looks unnecessary. Can we remove this?

2022-03-15 16:04 UTC, k8vance88 commented on dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/utils/Utils.java
> +// import com.google.gson.Gson;
remove the commented out imports

2022-03-15 16:04 UTC, k8vance88 commented on dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/utils/Utils.java
> +        // TODO: Delete sysout.
delete this

2022-03-15 16:17 UTC, k8vance88 commented
Sarin, you should create a git issue and link it to for this PR.

2022-03-16 08:32 UTC, sarinjacobsunny commented on dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/rest/v1/CatalogAPI.java
> +
Removed extra space.

2022-03-16 08:35 UTC, sarinjacobsunny commented on dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/utils/Utils.java
> +// import com.google.gson.Gson;
Removed commented imports.

2022-03-16 08:35 UTC, sarinjacobsunny commented on dev/com.ibm.ws.ui/src/com/ibm/ws/ui/internal/v1/utils/Utils.java
> +        // TODO: Delete sysout.
Removed sysout

2022-03-16 08:38 UTC, sarinjacobsunny commented
> All files with copywrite statements need to have the latest date appended to the end. For example, if it says 2015 then you should add 2015, 2022. If there are 2 dates, replace the last one with 2022.

Copyright texts updated.

2022-03-16 09:26 UTC, sarinjacobsunny commented
> Sarin, you should create a git issue and link it to for this PR.

Open liberty ticket created.
https://github.com/OpenLiberty/open-liberty/issues/20479

2022-03-16 14:38 UTC, k8vance88 commented
#build

2022-03-16 14:40 UTC, k8vance88 commented
#run-libby-bot

2022-03-16 14:44 UTC, k8vance88 approved these changes

2022-03-17 14:10 UTC, sarinjacobsunny commented
#build

2022-03-18 08:25 UTC, sarinjacobsunny commented
#run-libby-bot

2022-03-18 11:08 UTC, sarinjacobsunny commented
#build

2022-05-18 16:25 UTC, sarinjacobsunny commented
#build

2022-05-19 16:16 UTC, sarinjacobsunny commented
#build

2022-06-27 11:10 UTC, sarinjacobsunny commented
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_kIbTIPVwEey3m9ea3wJj4A

2022-07-05 14:17 UTC, k8vance88 approved these changes
LGTM

2022-07-07 19:23 UTC, sarinjacobsunny commented
#run-libby-bot

2022-07-10 15:51 UTC, sarinjacobsunny commented
#run-libby-bot

2022-07-10 15:52 UTC, merged