Policy related Changes are moved to CXF 3.4
OpenLiberty/open-liberty pull request #20483
Opened 2022-03-16 17:22 UTC by BerksanAtes

Fixes #20439

2022-03-16 17:24 UTC, BerksanAtes commented
#build

2022-03-21 19:52 UTC, BerksanAtes commented
#build

2022-03-23 22:22 UTC, BerksanAtes commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

2022-03-24 15:29 UTC, neuwerk requested changes

2022-03-24 15:29 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/src/org/apache/cxf/jaxws/interceptors/SwAOutInterceptor.java
> +//  Begin copied over from CXF 2.6.2
Can you mark with `LIberty Change` as well? Should follow the format of the others.

2022-03-24 15:29 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxws.3.2/src/org/apache/cxf/jaxws/interceptors/SwAOutInterceptor.java
> +//  Begin copied over from CXF 2.6.2
Same as above, include `Liberty Change`

2022-03-24 15:29 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyEngineImpl.java
> +        String skipPolicyCheck = System.getProperty("cxf.ignore.unsupported.policy");
Add `Liberty Change`  to this

2022-03-24 15:29 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.ws.policy.3.2/src/org/apache/cxf/ws/policy/PolicyVerificationInInterceptor.java
> +
Add `Liberty Change` to this

2022-03-24 15:29 UTC, neuwerk commented on dev/com.ibm.ws.wssecurity_fat.wsscxf.1/fat/src/com/ibm/ws/wssecurity/fat/cxf/x509migtoken/CxfX509MigTests.java
> +    @AllowedFFDC(value = { "org.apache.cxf.ws.policy.PolicyException" }, repeatAction = { JakartaEE9Action.ID })
I'm concerned about these changes. It doesn't seem correct that xmlWS-3.0's tests generate one FFDC, when the other runs generate a different FFDC. Updating the the FFDC can be OK in certain situations, but I don't think this `@AllowedFFDC` should be necessary. I think we need to investigate why one is getting one version and the other is getting another.

2022-03-24 18:35 UTC, sawadood approved these changes
The property changes look good!

2022-03-24 18:37 UTC, neuwerk approved these changes

2022-03-24 19:28 UTC, BerksanAtes commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.1

2022-03-25 13:06 UTC, BerksanAtes commented
#run-libby-bot

2022-03-25 13:07 UTC, merged