OIDC Back-channel logout: Various intermediate enhancements
OpenLiberty/open-liberty pull request #20496
Opened 2022-03-17 16:23 UTC by ayoho

OP support added:
- Adds `sid` claim to all ID tokens the OP creates
- Adds `backchannelLogoutRequestTimeout` config attribute
    - Just added to the metatype - nothing is reading or using it yet
- Removes `backchannelLogoutSupported` config attribute
- Discovery:
    - In beta mode, will always return `backchannel_logout_supported` with a value of `true`
    - In beta mode, will always return `backchannel_logout_session_supported` with a value of `true`
- Framework laid for sending back-channel logout requests, but no real functionality 

RP supported added (OIDC and social):
- Adds `backchannelLogoutSupported` config attribute
- Adds `backchannelLogoutSessionRequired` config attribute
- Logout token validation:
    - Updated to require a `sid` claim in the logout token if `backchannelLogoutSessionRequired="true"`

2022-03-17 16:34 UTC, ayoho commented
#libby

2022-03-17 18:05 UTC, ayoho commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2

2022-03-17 18:18 UTC, ayoho commented
#libby

2022-03-17 21:01 UTC, dmuelle requested changes
ID review- two minor suggestions

2022-03-17 21:01 UTC, dmuelle commented on dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
> +LOGOUT_TOKEN_SID_REQUIRED_BUT_MISSING=CWWKS1551E: The logout token is missing the "sid" claim but the OpenID Connect client {0} requires it.
```suggestion
LOGOUT_TOKEN_SID_REQUIRED_BUT_MISSING=CWWKS1551E: The logout token is missing the "sid" claim but the {0} OpenID Connect client requires it.
```

2022-03-17 21:01 UTC, dmuelle commented on dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
> +LOGOUT_TOKEN_SID_REQUIRED_BUT_MISSING.explanation=The OpenID Connect client requires that the logout token must contain a session ID to identify the OpenID Connect client session with the OpenID Conn
```suggestion
LOGOUT_TOKEN_SID_REQUIRED_BUT_MISSING.explanation=The OpenID Connect client requires that the logout token contains a session ID to identify the OpenID Connect client session with the OpenID Connect provider.
```

2022-03-17 21:19 UTC, ayoho commented
#libby

2022-03-17 21:19 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.clients.common/resources/com/ibm/ws/security/openidconnect/clients/common/resources/OidcClientMessages.nlsprops
> +LOGOUT_TOKEN_SID_REQUIRED_BUT_MISSING.explanation=The OpenID Connect client requires that the logout token must contain a session ID to identify the OpenID Connect client session with the OpenID Conn
@dmuelle Just pushed a new commit

2022-03-18 16:44 UTC, dmuelle approved these changes
LGTM thanks

2022-03-23 20:04 UTC, teddyjtorres commented on dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/metatype/metatype.xml
> +         <AD id="backchannelLogoutSessionRequired" name="internal" description="internal use only" required="false" type="Boolean" default="false" ibm:beta="true" />
To reflect current design, these should remain internal for GA.

2022-03-28 14:16 UTC, teddyjtorres commented on dev/com.ibm.ws.security.social/resources/OSGI-INF/metatype/metatype.xml
> +        <AD id="backchannelLogoutSessionRequired" name="internal" description="internal use only" required="false" type="Boolean" default="false" ibm:beta="true" />
To reflect current design, these should remain internal for GA.

2022-03-28 14:19 UTC, teddyjtorres approved these changes

2022-03-28 15:27 UTC, merged