Split JWT builder/consumer trustStoreRef metatype description for clarification
OpenLiberty/open-liberty pull request #20612
Opened 2022-03-28 16:55 UTC by ayoho

The `trustStoreRef` metatype description in the JWT bundle is overloaded and used by both the builder and consumer. However only one part of the description applies to the builder and the other part applies to the consumer. This splits the description so the builder and consumer can have accurate descriptions reflecting their own functionality.

2022-03-28 16:55 UTC, ayoho commented
#build

2022-03-28 17:02 UTC, barbj approved these changes
Looks great!

2022-04-01 14:36 UTC, skasund commented
L2 message review not required.

2022-04-01 16:06 UTC, dmuelle requested changes, later dismissed
ID review: a couple suggestions

2022-04-01 16:06 UTC, dmuelle commented on dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
> +trustStoreRef.consumer.desc=A keystore containing the public key necessary for verifying a signature of the JWT token.
```suggestion
trustStoreRef.consumer.desc=A keystore that contains the public key that can verify a signature of the JWT token.
```

2022-04-01 16:06 UTC, dmuelle commented on dev/com.ibm.ws.security.jwt/resources/OSGI-INF/l10n/metatype.properties
> +trustStoreRef.builder.desc=A keystore containing the key management key that is used to encrypt the Content Encryption Key of a JWE.
```suggestion
trustStoreRef.builder.desc=A keystore that contains the key management key that is used to encrypt the Content Encryption Key of a JWE.
```

2022-04-01 19:16 UTC, ayoho commented
#libby

@dmuelle Suggestions incorporated

2022-04-12 14:48 UTC, merged