Fix-outputVersion-schemaVersion-options
OpenLiberty/open-liberty pull request #20628
Opened 2022-03-29 19:10 UTC by jimblye

Fixes issue #20627

Changes

**Generator.java:**

  - Updated showUsageInfo():  The feature list tools and the schema list tools share the same message file.  The code was using an exclusion set to exclude options that did not apply to the schemaGen tools.  I replaced the exclusion set with set of applicable command line options (basically an inclusion set.  **Server**SchemaGen also explicity specifies the options to include.) 
     - Problem with exclusion set.  If someone adds a message, unrelated to schemaGen, it won't be excluded.  
     - Side effect:  This removes the compactoutput option from the help.  Though compactoutput does not appear to be used.  The option would have been and still is rejected from the command line as a bad argument.  Also the SchemaWriter doesn't support the option, and I don't know what it would mean in the schemaGen case to produce compact output.  I assume this was an option in the feature list tools.

**GeneratorOptions.java:**
 - Explicitly set default values when instantiating SchemaVersion and OutputVersion.  Previously, it passed in "", which got defaulted to v1.

 - Validate options entered for schemaVersion and outputVersion.  Invalid options previously caused an IllegalArgumentException which displayed a stack dump in the terminal window.

java -jar ws-schemagen.jar -schemaVersion=2.5 fred
CWWKG0036E: Error generating schema: 2.5
java.lang.IllegalArgumentException: 2.5
	at com.ibm.websphere.metatype.SchemaVersion.getEnum(SchemaVersion.java:41)
	at com.ibm.ws.config.schemagen.internal.GeneratorOptions.processArgs(GeneratorOptions.java:102)
	at com.ibm.ws.config.schemagen.internal.Generator.createSchema(Generator.java:102)
	at com.ibm.ws.config.schemagen.internal.Generator.main(Generator.java:84)
 
- Immediately stop parsing when invalid option found.
- If 2 non-hyphenated options are entered, the first is simply ignored.   I changed this to flag the first non-hyphenated option as a bad argument.

**ConfigOptions.nlsprops**

Updated **encoding** option description to include default encoding which is UTF-8.

**OutputVersion.java & SchemaVersion.java**

   - Problem: User must enter the version exactly as expected.  For OutputVersion, that means they need to enter OutputVersion=1, while for SchemaVersion they must enter  SchemaVersion=1.0.  Not only is it inconsistent, but 1 should be acceptable for meaning 1.0 and vice versa.
   - Solution:  I added a getNormalizedVersion method which is used to strip spaces and to strip the ".0" 

    - What might not be kosher is that I changed the first SchemaVersion enum value from 1.0 to 1 in order to be consistent with OutputVersion.    That keeps the  getNormalizedVersion methods the same.  An alternative would be for SchemaVersion.getNormalizedVersion() to add ".0" when version "1" is specified.   Note.  The documentation is a little weird when it comes to these options.  It only lists --schemaVersion=1.1 and --outputVersion=2 as options.   There is no mention that you could enter  --schemaVersion=1.0 and --outputVersion=1 nor does it say what those options do. They just happen to be the default.   It's as if we had existing behavior and we wanted to add a new option, and so we added v1 and v2.  We defaulted to v1 and only told anyone about v2.   The default should be documented as well as the explicit v1 options (which are the default), though I'm not exactly sure how to describe what the default options do.  They seem to be the opposite of the "v2" options.  So maybe a proper description could be derived from the new version descriptions?

**SchemaGeneratorOptions.java**
   - This class was using the internal representation of the OutputVersion and SchemaVersion enum values; i.e. it was using String instead of OutputVersion and SchemaVersion.

I added new getters, to retrieve OutputVersion and SchemaVersion instead of getting the String form of the version.   IT would have been better to replace the APIs, rather than add new ones, but I wasn't sure I was allowed to do that.
  I could not find anywhere else in Liberty code where schemaVersion from package com.ibm.websphere.metatype is used outside of the schemaGen code.

**SchemaGeneratorImpl.java**

  - Now passes OutputVersion and SchemaVersion command line options to the SchemaWriter.  Previously, the SchemaWriter had no awareness of the values entered on the command line.

2022-03-29 19:40 UTC, jimblye commented
#build #libby

2022-03-30 20:29 UTC, jimblye commented
#build #libby

2022-03-31 21:25 UTC, jimblye commented
#build #libby

2022-04-01 13:34 UTC, jimblye commented
#build #libby

2022-04-01 14:37 UTC, skasund commented
L2 message review completed

2022-04-01 16:09 UTC, dmuelle requested changes
ID review: one minor suggestion

2022-04-01 16:09 UTC, dmuelle commented on dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
> +schemagen.info.schema.file.created=CWWKG0109I: The schema was created in file [{0}].
```suggestion
schemagen.info.schema.file.created=CWWKG0109I: The schema was created in the  [{0}] file.
```

2022-04-04 22:09 UTC, jimblye commented on dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
> +schemagen.info.schema.file.created=CWWKG0109I: The schema was created in file [{0}].
Done

2022-04-14 22:01 UTC, jimblye commented
@dmuelle   - I made the changes you requested.  Anything else needed to move this forward?

2022-04-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.config/resources/com/ibm/ws/config/internal/resources/ConfigMessages.nlsprops
> +schemagen.info.schema.file.created=CWWKG0109I: The schema was created in [{0}] file.
```suggestion
schemagen.info.schema.file.created=CWWKG0109I: The schema was created in the [{0}] file.
```

2022-04-15 13:08 UTC, dmuelle commented
@jimblye - sorry I missed this when you made the edit- but it's still missing "the"- see my new comment. As soon as that edit is done, I'll approve and add the Id Reviewed label and that is all that's required from an ID perspective

2022-04-15 13:41 UTC, dmuelle approved these changes
LGTM thanks

2022-04-15 13:47 UTC, jimblye commented
#build
because I added "the" to a message

2022-04-15 13:48 UTC, jimblye commented
#libby

2022-04-15 13:48 UTC, merged