Silo JAX-RS 2.0 from importing later versions of CXF.
OpenLiberty/open-liberty pull request #20654
Opened 2022-03-31 03:02 UTC by neuwerk

The jaxrs-2.0 feature doesn't limit the version of CXF to less that CXF 3.2, when the feature itself provides 3.1.x, and this will break functionality if newer versions of CXF are available on the same server instances.

2022-03-31 03:07 UTC, neuwerk commented
#build

2022-03-31 18:36 UTC, neuwerk commented
#build

2022-04-01 14:57 UTC, skasund commented
L2 message review completed

2022-04-01 16:30 UTC, dmuelle requested changes
ID review- made a few suggestions. Let me know if you have any questions, thanks

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.provider.no.public.ctor=CWWKW0100W: The JAX-RS Provider class, {0} in the application contains no public constructor. The server will ignore this provider.
```suggestion
warn.provider.no.public.ctor=CWWKW0100W: The  {0} JAX-RS Provider class in the application contains no public constructor. The server ignores this provider.
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.provider.no.public.ctor.explanation=The JAX-RS specification requires that provider classes must contain at least one public constructor for the JAX-RS container implementation to invoke. The sp
```suggestion
warn.provider.no.public.ctor.explanation=The JAX-RS specification requires that provider classes must contain at least one public constructor for the JAX-RS container implementation to invoke. The specified provider class does not contain a public constructor, so the server ignores it.
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.servlet.specified.without.application.explanation=The web.xml must specify an Application init-param element when declaring JAX-RS servlets.  For more information, see the Knowledge Center: http
```suggestion
warn.servlet.specified.without.application.explanation=The web.xml file must specify an Application init-param element when it declares JAX-RS servlets.  For more information, see the following IBM Docs topic: https://www.ibm.com/docs/en/was-nd/9.0.5?topic=SSAW57_9.0.5/com.ibm.websphere.nd.multiplatform.doc/ae/twbs_jaxrs_configwebxml.html
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.servlet.specified.without.application=CWWKW0101W: The web.xml in the {0} module specifies a servlet with name of {1} and class of {2} but does not specify required Application initialization par
```suggestion
warn.servlet.specified.without.application=CWWKW0101W: The web.xml file in the {0} module specifies a servlet with name of {1} and class of {2} but does not specify the required Application initialization parameter.
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.servlet.specified.without.application.useraction=Update the web.xml to include the required init-param element to specify the Application class in this module.
```suggestion
warn.servlet.specified.without.application.useraction=Update the web.xml file to include the required init-param element to specify the Application class in this module.
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.servlet.specified.with.invalid.application=CWWKW0102W: The web.xml in the {0} module specifies a servlet with name of {1} that declares an invalid Application class in the initialization paramet
```suggestion
warn.servlet.specified.with.invalid.application=CWWKW0102W: The web.xml file in the {0} module specifies a servlet with the name of {1} that declares an invalid Application class in the initialization parameter.  The {2} class is not a subclass of javax.ws.rs.Application.
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.servlet.specified.with.invalid.application.explanation=The web.xml must specify an init-param element with the param-name of "javax.ws.rs.Application" and the param-value of an application class
```suggestion
warn.servlet.specified.with.invalid.application.explanation=The web.xml file must specify an init-param element with the param-name of javax.ws.rs.Application and the param-value of an application class that extends javax.ws.rs.Application. For more information, see the following IBM Docs topic: https://www.ibm.com/docs/en/was-nd/9.0.5?topic=SSAW57_9.0.5/com.ibm.websphere.nd.multiplatform.doc/ae/twbs_jaxrs_configwebxml.html
```

2022-04-01 16:30 UTC, dmuelle commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.servlet.specified.with.invalid.application.useraction=Update the web.xml to specify an Application subclass in this module.
```suggestion
warn.servlet.specified.with.invalid.application.useraction=Update the web.xml file to specify an Application subclass in this module.
```

2022-04-05 20:04 UTC, neuwerk commented
#build

2022-04-06 14:27 UTC, neuwerk commented
#build

2022-04-08 15:02 UTC, WhiteCat22 requested changes

2022-04-08 15:02 UTC, WhiteCat22 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsConcurrent-1.0.feature
>  visibility=private
`com.ibm.websphere.appserver.jaxrsConcurrent-1.0` implies jaxrs + concurrent-1.0, I think this should be renamed to `com.ibm.websphere.appserver.jaxrs-2.0_Concurrent-1.0` or something similar to capture the version of both jaxrs and concurrent, whereas previously it was "both" versions of jax-rs with concurrent-1.0

2022-04-08 15:02 UTC, WhiteCat22 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsConcurrent-2.1.feature
> +symbolicName=com.ibm.websphere.appserver.jaxrsConcurrent-2.1
`com.ibm.websphere.appserver.jaxrsConcurrent-2.1` implies jaxrs + concurrent-2.1, I think this should be renamed to `com.ibm.websphere.appserver.jaxrs-2.1_Concurrent-1.0` .....

2022-04-08 15:02 UTC, WhiteCat22 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsConcurrent-1.0.feature
>  -features=com.ibm.websphere.appserver.contextService-1.0
Line below this...

I'd like to rename the 2.x bundle to 2.0 since there is a new dedicated bundle for 2.1

2022-04-08 15:02 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.1.concurrent/bnd.bnd
> +  org.apache.cxf.*;version="[3.2,4)", \
should this be `org.apache.cxf.jaxrs.*` like above?

2022-04-08 15:02 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.1.server/resources/com/ibm/ws/jaxrs20/server/internal/resources/JaxRsServerMessages.nlsprops
> +warn.provider.no.public.ctor=CWWKW0100W: The JAX-RS Provider class, {0} in the application contains no public constructor. The server will ignore this provider.
@dmuelle FWIW, these messages already exists and are already shipped. Thomas is just dupicating/moving them since he's breaking out these 2 features from sharing this code.

Are we even allowed to change them without POC approval since they are existing messages?

2022-04-08 15:02 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.x.concurrent/bnd.bnd
> +  org.apache.cxf.*;version="[3.0.2,3.2)", \
is this for jaxrs-2.0 only now? If so, I'd like to see the bundle renamed from 2.x -> 2.0.

2022-04-08 19:25 UTC, neuwerk commented on dev/com.ibm.ws.jaxrs.2.1.concurrent/bnd.bnd
> +  org.apache.cxf.*;version="[3.2,4)", \
unfortunately, it can't be because it it uses a core CXF package. :/

2022-04-08 21:54 UTC, WhiteCat22 approved these changes

2022-04-08 21:54 UTC, WhiteCat22 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/com.ibm.websphere.appserver.jaxrsConcurrent-2.1.feature
> +symbolicName=com.ibm.websphere.appserver.jaxrsConcurrent-2.1
alternatively `com.ibm.websphere.appserver.jaxrsConcurrent-1.0_ee8`

2022-04-08 21:57 UTC, WhiteCat22 requested changes

2022-04-08 21:57 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.0.concurrent/bnd.bnd
>  Bundle-Description: IBM JAX-RS-2.X Concurrency support; version=${bVersion}
needs to be 2.0

2022-04-08 21:57 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.1.server/bnd.bnd
> +   org.apache.cxf.*;version="[3.0,4)", \
[3.2,4) <3

2022-04-08 21:59 UTC, WhiteCat22 approved these changes

2022-04-08 22:25 UTC, neuwerk commented
#build

2022-04-12 14:12 UTC, dmuelle approved these changes

2022-04-12 14:22 UTC, neuwerk commented
#run-libby-bot

2022-04-12 14:23 UTC, merged