Allow artifactory substitution override
OpenLiberty/open-liberty pull request #20682
Opened 2022-04-01 16:05 UTC by KyleAure

Fixes #20679

2022-04-01 21:48 UTC, tabishop approved these changes

2022-04-04 07:31 UTC, websterc87 commented on dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
> +                                   + "or force this test to use the a local docker host using fat.test.use.remote.docker=true.");
I think this might want to be fat.test.use.remote.docker=false,

Setting remote.docker=true to use a local docker makes little sense

2022-04-04 07:32 UTC, websterc87 requested changes
Code looks functional but minor fix needed to log message.

2022-04-04 14:48 UTC, KyleAure commented on dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java
> +                                   + "or force this test to use the a local docker host using fat.test.use.remote.docker=true.");
Nice catch.  It should have been `false`

2022-04-04 18:28 UTC, KyleAure commented
@websterc87 I have made the requested changes if you would like to review.

2022-04-04 18:28 UTC, KyleAure commented
In the meantime let's start doing some automated tests.
#build

2022-04-05 13:59 UTC, websterc87 approved these changes
Looks better now

2022-04-05 15:13 UTC, KyleAure commented
The basic build passed with no change in behavior in our builds.
Running the two error paths to ensure that the properties are honored, and we fail properly: 
1. Set fat.test.use.artifactory.substitution=false 
    - Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_bXKRgLToEey_l6cwP43xMA
    - Result:
2. Set fat.test.use.remote.docker=false and fat.test.use.artifactory.substitution=true
    - Build: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_muO3cLToEey_l6cwP43xMA
    - Result:

2022-04-08 14:18 UTC, KyleAure commented
#libbybot

2022-04-08 14:21 UTC, merged