Improve JWT cache performance
OpenLiberty/open-liberty pull request #20733
Opened 2022-04-06 21:13 UTC by ayoho

Moves where we cache the JWT context for JWT consumers to after we perform the actual validation of the token.

2022-04-06 21:15 UTC, ayoho commented
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0

2022-04-06 22:00 UTC, jdmcclur commented
Adam, I think you'll also need to move
```
JwtContext jwtContext = getJwtContextFromCache(jwtString, config);
```

2022-04-07 16:44 UTC, ayoho commented
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0

2022-04-13 16:37 UTC, jhanders34 commented on dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/CacheValue.java
> +
I suggest something like:

```
    public CacheValue(Object value) {
        this(value, 0);
    }

    public CacheValue(Object value, long clockSkew) {
        this.value = value;
        this.createdAt = System.currentTimeMillis();
        if (clockSkew > 0) {
            this.createdAt -= clockSkew;
        }
    }
```
This avoids having to store clockSkew and calculate below.

2022-04-13 21:29 UTC, ayoho commented
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2

2022-04-14 15:34 UTC, ayoho commented
#libby
#build

2022-04-15 17:13 UTC, ayoho commented
#libby
#build

2022-04-18 15:59 UTC, ayoho commented
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2

2022-04-18 21:50 UTC, jhanders34 commented on dev/com.ibm.ws.security.common/test/com/ibm/ws/security/common/structures/CacheValueTest.java
> +package com.ibm.ws.security.common.structures;
Copyright missing

2022-04-18 21:51 UTC, jhanders34 commented on dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/CacheValue.java
> +import java.util.Objects;
Copyright probably should be updated.

2022-04-18 22:03 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
> +    public JwtCache(long timeoutInMilliSeconds) {
Probably should update the copyright year.

2022-04-18 23:09 UTC, jhanders34 requested changes
I think this can be much cleaning with the suggested changes.  If you have any questions about my review comments let me know.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
> +        if (cacheValue == null || isJwtExpired(cacheValue)) {
I think this method should simply be:
```suggestion
    public Object get(@Sensitive String jwt, String configId) {
        JwtCacheKey key = getCacheKey(jwt, configId);
        return super.get(key);
    }
```

Note that I took the synchronized off since the get method is already synchronized creating the key doesn't need to be synchronized.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
> +        super.put(key, cacheValue, clockSkew);
Similarly I suggest:

```suggestion
    public void put(@Sensitive String jwt, String configId, JwtContext value, long clockSkew) {
        JwtCacheKey key = getCacheKey(jwt, configId);
        super.put(key, value, clockSkew);
    }

    @Override
    protected CacheValue createCacheValue(Object jwtContext, long clockSkew) {
        return JwtCacheValue(jwtContext, clockSkew);
    }
```

Note the removal of synchronized again.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCache.java
> +            if (cacheValue == null || isJwtExpired(cacheValue)) {
I suggest removing this method and the is JwtExpired method completely.  You will see how I get around this method needing to exist in the other comments.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.common/src/com/ibm/ws/security/common/structures/SingleTableCache.java
> +    }
```suggestion
    public synchronized void put(@Sensitive Object key, Object value, long clockSkew) {
        lookupTable.put(key, createCacheValue(value, clockSkew));
    }

    protected CacheValue createCacheValue(Object value, long clockSkew) {
        return new CacheValue(value, clockSkew);
    }
```

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCacheKey.java
> +public class JwtCacheKey {
No reason for this to be public.  Might as well make it default visibility, i.e. no keyword.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCacheKey.java
> +
Is there any value in having these methods?  If not, I suggest removing them.  The equals below can just reference the fields instead of the get methods.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.jwt/src/com/ibm/ws/security/jwt/internal/JwtCacheValue.java
> +    }
```suggestion
class JwtCacheValue extends CacheValue {

    private final long clockSkew;

    public JwtCacheValue(Object value, long clockSkew) {
        super(value, clockSkew);
        this.clockSkew = clockSkew;
    }
    @FFDCIgnore(MalformedClaimException.class)
    @Override
    public boolean isExpired(long timeoutInMilliseconds) {
        if (super.isExpired(timeoutInMilliseconds) {
            return true;
        }
        JwtContext jwtContext = (JwtContext) getValue();
        JwtClaims jwtClaims = jwtContext.getJwtClaims();
        if (jwtClaims == null) {
            return true;
        }
        long jwtExp = 0;
        try {
            NumericDate expirationTime = jwtClaims.getExpirationTime();
            if (expirationTime == null) {
                return true;
            }
            jwtExp = expirationTime.getValueInMillis();
        } catch (MalformedClaimException e) {
            if (TraceComponent.isAnyTracingEnabled() && tc.isDebugEnabled()) {
                Tr.debug(tc, "Caught exception getting expiration time for JWT: " + e);
            }
            return true;
        }
        return (System.currentTimeMillis() > (jwtExp + clockSkew));
    }
```

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +public class AccessTokenCacheKey {
Doesn't need to be public

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +
Seems we shouldn't need these get methods.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/UserApiCacheKey.java
> +    }
Again remove the getter methods and make the class not public.

2022-04-18 23:09 UTC, jhanders34 commented on dev/com.ibm.ws.security.social/src/com/ibm/ws/security/social/tai/TAIUserApiUtils.java
> +        userApiCache.put(key, userApiResponse);
It appears that some SocialLoginConfig's have a clock skew.  For those ones that do should there be a call to the put method that pass in the clock skew?

2022-04-21 20:10 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +public class AccessTokenCacheKey {
I'm constructing `AccessTokenCacheKey`s in a separate test class (`com.ibm.ws.security.openidconnect.client.AccessTokenAuthenticatorTest`), so this would have to be public for me to continue to be able to do that.

2022-04-21 23:00 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +public class AccessTokenCacheKey {
Unless you moved the test to the same package i.e. com.ibm.ws.security.openidconnect.client.internal

2022-04-25 15:28 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +public class AccessTokenCacheKey {
Not so simple. It makes sense for `AccessTokenAuthenticatorTest` to be in the same package as its corresponding product code class, and moving it to a different package adds a host of other issues with the visibility of methods being called.

2022-04-25 20:05 UTC, ayoho commented
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2

2022-04-25 20:13 UTC, jhanders34 commented on dev/com.ibm.ws.security.fat.common.mp.jwt/src/com/ibm/ws/security/fat/common/mp/jwt/actions/MpJwtFatActions.java
> +        Thread.sleep(1000);
With the way that clock stuff works with Java, you may want to do 1100 to avoid timing issues.

2022-04-25 20:21 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +public class AccessTokenCacheKey {
I guess the question is why is AccessTokenAuthenticator not in client.internal?

2022-04-25 21:01 UTC, jhanders34 approved these changes
I am marking it approved.  There are still two review comments, but could live without them in order to deliver this change.

2022-04-25 21:21 UTC, ayoho commented
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.jwt_fat.builder,com.ibm.ws.security.jwt_fat.consumer,com.ibm.ws.security.jwtsso_fat.mpJwt-1.1,com.ibm.ws.security.jwtsso_fat.mpJwt-1.2,com.ibm.ws.security.jwtsso_fat.mpJwt-2.0,com.ibm.ws.security.jwtsso_fat.noMpJwt,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.1,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.1_fat.mpJwt-2.0,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-1.2,com.ibm.ws.security.mp.jwt.1.2_fat.mpJwt-2.0,com.ibm.ws.security.oidc.client_fat.1,com.ibm.ws.security.oidc.client_fat.2,com.ibm.ws.security.oidc.client_fat.config,com.ibm.ws.security.oidc.client_fat.e2e,com.ibm.ws.security.oidc.client_fat.jaxrs,com.ibm.ws.security.oidc.client_fat.saml,com.ibm.ws.security.oidc.client_fat.spnego,com.ibm.ws.security.oidc.server_fat,com.ibm.ws.security.oidc.server_fat.app-passwords,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-passwords.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.DerbyDB.opaque,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.jwt,com.ibm.ws.security.oidc.server_fat.app-tokens.LocalStore.opaque,com.ibm.ws.security.oidc.server_fat.clientregistration,com.ibm.ws.security.oidc.server_fat.config,com.ibm.ws.security.oidc.server_fat.config.oauth,com.ibm.ws.security.oidc.server_fat.config.oidc,com.ibm.ws.security.oidc.server_fat.endpoint.authorize,com.ibm.ws.security.oidc.server_fat.endpoint.coveragemap,com.ibm.ws.security.oidc.server_fat.endpoint.discovery,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.endpoint.introspect,com.ibm.ws.security.oidc.server_fat.endpoint.revoke,com.ibm.ws.security.oidc.server_fat.endpoint.token,com.ibm.ws.security.oidc.server_fat.endpoint.userinfo,com.ibm.ws.security.oidc.server_fat.feature,com.ibm.ws.security.oidc.server_fat.granttype.jwt,com.ibm.ws.security.oidc.server_fat.gui.tokenMgmt,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.jaxrs.config,com.ibm.ws.security.oidc.server_fat.oauth,com.ibm.ws.security.oidc.server_fat.oidc,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.social_fat,com.ibm.ws.security.social_fat.LibertyOP.1,com.ibm.ws.security.social_fat.LibertyOP.2

2022-04-25 21:27 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/OidcClientAuthenticator.java
> +    public ProviderAuthenticationResult fixSubject(ProviderAuthenticationResult result) {
This method should be static.  Also not sure why this class couldn't move as well.

2022-04-25 21:29 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheKey.java
> +    public AccessTokenCacheKey(@Sensitive String accessToken, String configId) {
Similarly should this be default protected instead of public?

2022-04-25 21:29 UTC, jhanders34 commented on dev/com.ibm.ws.security.openidconnect.client/src/com/ibm/ws/security/openidconnect/client/internal/AccessTokenCacheValue.java
> +    public AccessTokenCacheValue(String uniqueID, ProviderAuthenticationResult result) {
Similarly should this be default protected instead of public

2022-04-28 14:51 UTC, ayoho commented
Just waiting on a change to propagate to `release` in WebSphere Liberty and then this should be ready for a new personal build.

2022-04-29 10:23 UTC, jhanders34 commented
#libby

2022-04-29 10:23 UTC, merged