Split javaeesec2 bucket to avoid Win timeouts
OpenLiberty/open-liberty pull request #20758
Opened 2022-04-08 17:55 UTC by kristip17

The `com.ibm.ws.security.javaeesec_fat.2` is timing out on some OSs. Split the bucket -- there's already a bucket 3, so added a bucket 4.

RTC 287939

2022-04-08 17:56 UTC, kristip17 commented
#build

2022-04-11 15:44 UTC, kristip17 commented
#build

2022-04-12 22:12 UTC, kristip17 commented
#build

2022-04-14 02:28 UTC, kristip17 commented
#libby

2022-04-14 12:57 UTC, jvanhill requested changes

2022-04-14 12:57 UTC, jvanhill commented on dev/com.ibm.ws.security.javaeesec_fat.4/bnd.bnd
> +# Copyright (c) 2019, 2021 IBM Corporation and others.
```suggestion
# Copyright (c) 2022 IBM Corporation and others.
```

2022-04-14 12:57 UTC, jvanhill commented on dev/com.ibm.ws.security.javaeesec_fat.4/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
```suggestion
 * Copyright (c) 2022 IBM Corporation and others.
```

2022-04-14 13:07 UTC, kristip17 commented on dev/com.ibm.ws.security.javaeesec_fat.4/bnd.bnd
> +# Copyright (c) 2019, 2021 IBM Corporation and others.
Added

2022-04-14 13:07 UTC, kristip17 commented on dev/com.ibm.ws.security.javaeesec_fat.4/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
Added

2022-04-14 13:30 UTC, jvanhill approved these changes

2022-04-14 13:30 UTC, kristip17 commented
#libby

2022-04-14 13:31 UTC, kristip17 commented
Last push was updating the copyright date in two files, not rerunning PB.

2022-04-14 13:32 UTC, merged