Update CDI APIs
OpenLiberty/open-liberty pull request #20791
Opened 2022-04-12 20:41 UTC by benjamin-confino

2022-04-12 20:41 UTC, benjamin-confino commented
#build

2022-04-14 10:41 UTC, Azquelt requested changes

2022-04-14 10:41 UTC, Azquelt commented on dev/cnf/oss_dependencies.maven
>  jakarta.enterprise:jakarta.enterprise.lang-model:4.0.0-RC3
the `lang-model` artifact should be updated at the same time as the `cdi-api`

2022-04-14 15:22 UTC, benjamin-confino commented
#build

2022-04-14 16:06 UTC, Azquelt approved these changes

2022-04-19 09:32 UTC, Azquelt commented
#libby

2022-04-21 09:50 UTC, merged