JAX-RS + JAX-WS: Remove CXF client bundle
OpenLiberty/open-liberty pull request #20856
Opened 2022-04-18 19:07 UTC by neuwerk

This pull request removes the `com.ibm.ws.cxf.client` bundle that was used to minimize code duplication across jaxrs-2.1 and jaxrs-2.0, by putting the code in `com.ibm.ws.jaxws.2.0.common` and `com.ibm.ws.org.apache.cxf.cxf.core.3.2`, as the code is dependent on `org.apache.cxf.message.Message` and each version of the JAX-RS feature needs to have the cxf.client apis use the applicable version of CXF.

2022-04-18 19:09 UTC, neuwerk commented
#build

2022-04-18 19:13 UTC, WhiteCat22 requested changes

2022-04-18 19:13 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.0.common/bnd.bnd
> +    com.ibm.ws.cxf.client.component
fix indentation please

2022-04-18 19:13 UTC, WhiteCat22 commented on dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.overrides
> + 	com.ibm.ws.cxf.client.component.*
indented too far ;)

2022-04-19 15:06 UTC, WhiteCat22 approved these changes

2022-04-19 16:28 UTC, neuwerk commented
#run-libby-bot

2022-04-19 16:34 UTC, merged