Test Spring Boot 2.6.x application
OpenLiberty/open-liberty pull request #20862
Opened 2022-04-18 21:19 UTC by anjumfatima90

2022-04-18 21:19 UTC, anjumfatima90 commented
#build

2022-04-19 14:40 UTC, anjumfatima90 commented
#build

2022-05-05 21:10 UTC, anjumfatima90 commented
#build

2022-05-05 21:16 UTC, anjumfatima90 commented
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_MzIvAMywEeyhmZ5zGPuLaA&tab=com.ibm.team.build.web.ui.internal.editors.result.overview.OverviewPage

2022-05-06 17:43 UTC, anjumfatima90 commented
#build

2022-05-06 19:14 UTC, dazavala requested changes
FYI @anjumfatima90, I posted a few review concerns.

2022-05-06 19:14 UTC, dazavala commented on dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
>      public static final String SPRING_BOOT_20_APP_WEBFLUX_WRONG_VERSION = "com.ibm.ws.springboot.support.version20.test.webflux.wrong.version.app-0.0.1-SNAPSHOT.jar";
Isn't the v2.0 webflux "wrong version" application removed from the suite?

2022-05-06 19:14 UTC, dazavala commented on dev/com.ibm.ws.springboot.support.version20.test.actuator.app/build.gradle
> +apply from: '../wlp-gradle/subprojects/maven-central-mirror.gradle'
I don't understand why this directive was added. What does "apply from" do here?

2022-05-06 19:14 UTC, dazavala commented on dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
> +            if (version.get() == null || container.get() == null) {
If both version.get() and container.get() return null, container and embeddedContainer will not be set.  Is that intended?

2022-05-06 19:24 UTC, anjumfatima90 commented on dev/com.ibm.ws.app.manager.springboot/src/com/ibm/ws/app/manager/springboot/util/SpringBootThinUtil.java
> +            if (version.get() == null || container.get() == null) {
Yes, that is intended. If that is null the `embeddedConatinerPrefix` will be set to an empty string.

2022-05-06 19:25 UTC, anjumfatima90 commented on dev/com.ibm.ws.springboot.support.version20.test.actuator.app/build.gradle
> +apply from: '../wlp-gradle/subprojects/maven-central-mirror.gradle'
This will allow us to download artifacts from maven central and we won't have to upload the artifacts on artifactory.

2022-05-06 19:28 UTC, anjumfatima90 commented on dev/com.ibm.ws.springboot.support_fat/fat/src/com/ibm/ws/springboot/support/fat/AbstractSpringTests.java
>      public static final String SPRING_BOOT_20_APP_WEBFLUX_WRONG_VERSION = "com.ibm.ws.springboot.support.version20.test.webflux.wrong.version.app-0.0.1-SNAPSHOT.jar";
Removed. thanks!

2022-05-06 19:57 UTC, dazavala approved these changes

2022-05-06 20:05 UTC, anjumfatima90 commented
#build

2022-05-06 21:11 UTC, anjumfatima90 commented
#build

2022-05-09 15:02 UTC, anjumfatima90 commented
#build

2022-05-09 17:28 UTC, anjumfatima90 commented
#build

2022-05-09 20:50 UTC, anjumfatima90 commented
#build

2022-05-10 08:27 UTC, anjumfatima90 commented
#build

2022-05-10 19:12 UTC, anjumfatima90 commented
#build

2022-05-11 17:21 UTC, tjwatson approved these changes

2022-05-11 17:21 UTC, tjwatson commented
#libby

2022-05-11 17:29 UTC, anjumfatima90 commented
#libby

2022-05-11 18:31 UTC, merged