Skip some WC FAT 3.1 and FAT 4 on EE10
OpenLiberty/open-liberty pull request #20872
Opened 2022-04-20 01:37 UTC by pmd1nh

2022-04-20 03:40 UTC, pmd1nh commented
#build

2022-04-20 15:44 UTC, pnicolucci approved these changes

2022-04-20 15:45 UTC, pnicolucci commented on dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerHttpUnit.java
> +    public void testrelativeredirectwithpathinfo() throws Exception {
Why is this test method renamed?

2022-04-20 15:48 UTC, pnicolucci requested changes
Revert the change to the test method name. Thanks!

2022-04-20 15:49 UTC, pmd1nh commented on dev/com.ibm.ws.webcontainer.servlet.3.1_fat/fat/src/com/ibm/ws/webcontainer/servlet31/fat/tests/WCServerHttpUnit.java
> +    public void testrelativeredirectwithpathinfo() throws Exception {
eclipse auto correction.  good catch

2022-04-20 23:25 UTC, pnicolucci approved these changes

2022-04-20 23:32 UTC, pnicolucci commented
#libby

2022-04-20 23:33 UTC, pnicolucci commented
#build

2022-04-21 13:15 UTC, pnicolucci commented
#build

2022-04-22 02:30 UTC, pmd1nh commented
#build

2022-04-23 16:06 UTC, pmd1nh commented
#build

2022-04-25 14:14 UTC, merged

2022-04-28 13:39 UTC, pmd1nh commented
Part2:
https://github.com/OpenLiberty/open-liberty/pull/20932