Update JSF Variable Name
OpenLiberty/open-liberty pull request #20993
Opened 2022-05-03 16:00 UTC by volosied

For issue #20992

2022-05-05 20:31 UTC, volosied commented
#build

2022-05-11 18:43 UTC, pnicolucci requested changes
This PR does not match the commit in the open source. You are missing the changes in `impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java` :  https://github.com/apache/myfaces/commit/31e3705688534332b0e06a77faee5c11f9e99e12

2022-05-11 18:46 UTC, pnicolucci approved these changes

2022-05-12 00:57 UTC, volosied commented
#libby

2022-05-12 01:00 UTC, merged