Update JPA Entity bucket's Postgres DDL files
OpenLiberty/open-liberty pull request #21359
Opened 2022-06-06 17:44 UTC by jgrassel

The Postgresql DDL files for the JPA Entity bucket needed to take advantage of "CREATE TABLE IF NOT EXISTS" and "DROP TABLE IF EXISTS" as Postgresql is a bit less forgiving than other databases, and will mark the transaction for rollback on any failure.  This causes test cases to fail due to missing tables.

2022-06-06 17:44 UTC, jgrassel commented
#build

2022-06-07 15:51 UTC, dazey3 requested changes, later dismissed
It looks like the HIBERNATE DDL files were missed. Otherwise, LGTM

2022-07-25 14:41 UTC, jgrassel commented
#run-libby-bot

2022-07-25 14:43 UTC, tkburroughs approved these changes

2022-07-25 14:46 UTC, merged