decode encoded passwords from properties file
OpenLiberty/open-liberty pull request #21853
Opened 2022-07-25 20:37 UTC by jjiwooLim

Fixes #21845

2022-07-25 20:37 UTC, jjiwooLim commented
#build

2022-07-25 22:16 UTC, veenarm requested changes
Currently doesn't look like the current PR will fix the issue as it's no longer put in the map.

2022-07-25 22:16 UTC, veenarm commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
> +						.getLogMessage("ERROR_TOOL_PROXY_PWD_CRYPTO_UNSUPPORTED"),
Should this log message match the one above on line 173?

2022-07-25 22:16 UTC, veenarm commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
> +
Missing 
```suggestion
         repoMap.get(repoName).put(option, decodedPwd);
```

2022-07-25 22:16 UTC, veenarm commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/props/FeatureUtilityProperties.java
> +				logger.log(Level.FINE,
Invalid password should follow same pattern as other places? to set decodedPwd back to the plain text from `value.toString()`

2022-07-27 21:45 UTC, jjiwooLim commented
#build

2022-07-28 22:17 UTC, jacobwdv requested changes
I think we need to reconsider being so passive about `InvalidPasswordDecodingException`. We will likely break something down the chain if we pass it along 100% of the time. Instead I was thinking of a change like the one below. I have commented out creating the PasswordAuthentication object if we hit the InvalidPasswordDecodingException and instead throwing an InstallException but I will leave that up to you to consider.

 

```
    private void configureAuthentication(final MavenRepository repository) throws InstallException {

        if (repository.getUserId() != null && repository.getPassword() != null &&
            envMap.get("https.proxyUser") == null && envMap.get("http.proxyUser") == null) {
            final PasswordAuthentication auth = getPasswordAuthenticationFromRepository(repository);
            Authenticator.setDefault(new Authenticator() {
                @Override
                protected PasswordAuthentication getPasswordAuthentication() {
                    return auth;
                }
            });
        }
    }

    /**
     * @param repository - The repository to get the encoded password from
     * @return a PasswordAuthentication object with the username and decoded passwords saved within it
     * @throws InstallException if decoding the password fails due to an unsupported algorithm or invalid password.
     */
    private PasswordAuthentication getPasswordAuthenticationFromRepository(MavenRepository repository) throws InstallException {
        String encodedPassword = repository.getPassword();
        if (!encodedPassword.startsWith("{")) {
            encodedPassword = "{}" + encodedPassword;
        }
        PasswordAuthentication pa;
        try {
            pa = new PasswordAuthentication(repository.getUserId(), PasswordUtil.decode(encodedPassword).toCharArray());

        } catch (InvalidPasswordDecodingException ipde) {
            logger.log(Level.FINE, Messages.INSTALL_KERNEL_MESSAGES.getLogMessage("ERROR_TOOL_PWD_NOT_ENCRYPTED")
                                   + InstallUtils.NEWLINE,
                       ipde);
//            pa = new PasswordAuthentication(repository.getUserId(), repository.getPassword().toCharArray());
            throw new InstallException(Messages.INSTALL_KERNEL_MESSAGES.getLogMessage("ERROR_TOOL_PWD_NOT_ENCRYPTED"));

        } catch (UnsupportedCryptoAlgorithmException ucae) {
            logger.log(Level.SEVERE,
                       Messages.INSTALL_KERNEL_MESSAGES.getLogMessage("ERROR_TOOL_PWD_NOT_ENCRYPTED")
                                     + InstallUtils.NEWLINE,
                       ucae);
            throw new InstallException(Messages.INSTALL_KERNEL_MESSAGES.getLogMessage("ERROR_TOOL_PWD_CRYPTO_UNSUPPORTED"));
        }
        return pa;
    }

```

2022-07-28 22:17 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +    private void configureAuthentication(final MavenRepository repository) throws InstallException {
have you tested the scenario where the InstallException is thrown? I'm worried about throwing exceptions in methods that didn't throw them beforehand.

2022-07-28 22:17 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +                decodedPwd = repository.getPassword();
I think it's too assumptive that if we get InvalidPasswordDecodingException that it's just something we can ignore and assume that it's an unencoded password. From the API: 
```
If the encoded_string is null or invalid. Or the decoded_string is null.
```

Also from the API: 
```
Decode the provided string. The string should consist of the algorithm to be used for decoding and encoded string. For example, {xor}CDo9Hgw=. Use this method unless the encryption key needs to be specified for the AES encryption. 

 An empty algorithm "{}" is treated as not encoded. However, a missing algorithm will trigger the InvalidPasswordDecodingException.
```
I think we're assuming if we see this exception that the user provided a plain text password without the `{}`. But we instead detect that case and add them before hand easily: 
```
String encodedPassword = repository.getPassword();
        if (!encodedPassword.startsWith("{")) {
            encodedPassword = "{}" + encodedPassword;
        }
```

2022-07-28 22:17 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +            final String pwd = decodedPwd;
I'm not a fan of saving passwords in plain text variables. That might be a standard higher than we adhere to on open liberty but it's generally a safe practice to be scared of doing such a thing.

2022-07-28 22:20 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +                decodedPwd = repository.getPassword();
Maybe we can't check for `{}` if it's AES encrypted, in which case we can't add the `{}`. Not sure, we would need to test it.

2022-07-28 22:22 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +                decodedPwd = repository.getPassword();
Maybe we need to use `passwordDecode()` to support AES? either way both show that the algorithm should be provided in between `{` and `}` and unencoded passwords should still have `{}` in front to signal they are not encoded.

2022-08-04 22:03 UTC, jjiwooLim commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +    private void configureAuthentication(final MavenRepository repository) throws InstallException {
catching the exception in `testConnection(MavenRepository repository)` - line 341

2022-08-04 22:04 UTC, jjiwooLim commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> -        checkValidProxy();
Authentications will be configured in line 92 (when we call `testConnection(repository)`).

2022-08-04 22:05 UTC, jjiwooLim commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> -        checkValidProxy();
Authentications will be configured in line 198 (when we call `testConnection(repository)`).

2022-08-05 17:50 UTC, jacobwdv approved these changes
Thank you, looks great!

2022-08-05 17:54 UTC, jjiwooLim commented
#build

2022-08-05 17:54 UTC, jjiwooLim commented
#libby-bot

2022-08-08 14:46 UTC, merged