Add JCache serialization tests
OpenLiberty/open-liberty pull request #21869
Opened 2022-07-26 14:11 UTC by ryanesch

2022-07-26 14:11 UTC, ryanesch commented
#build

2022-07-26 14:11 UTC, ryanesch commented
https://github.com/OpenLiberty/open-liberty/issues/20568

2022-09-06 20:39 UTC, jvanhill requested changes

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> + * This is necessary for the distributed cache.
```suggestion
 * This is necessary to maintain version to version compatibility for the distributed authentication cache.
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +            assertEquals((short) 1, value);
Global comment: add failure/expecation messages so we know what is wrong in the failed test.

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +            assertTrue("There should be two lookup keys.", keys.size() == 2);
```suggestion
            assertEquals("There should be two lookup keys.", 2, keys.size());
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +            assertTrue("There should be one principal.", principals.size() == 1);
```suggestion
            assertEquals("There should be one principal.", 1, principals.size());
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +            assertTrue("There should be one private credential.", privateCreds.size() == 1);
```suggestion
            assertEquals("There should be one private credential.", 1, privateCreds.size());
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +            assertTrue("There should be one public credential.", publicCreds.size() == 1);
```suggestion
            assertEquals("There should be one public credential.", 1, publicCreds.size());
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +            fail(ioe.toString());
I am not a fan of catching exceptions in unit tests. I typically think the exception being reported in the JUnit results is better as you get the entire stack trace etc.

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/test/com/ibm/ws/security/util/CacheObjectSerializationTest.java
> +    public void writeCacheObject() {
Do we call this from anywhere?

If not, could this not be a main method? If so update the comments to include steps on when / how to run it. Might also want to change the name of the file produced so it doesn't overwrite the existing file.

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.authentication/bnd.bnd
> +	com.ibm.ws.security.credentials;version=latest
This shouldn't need to be added.

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.social/test/com/ibm/websphere/security/social/TestJwtToken.java
> +		// TODO Auto-generated method stub
```suggestion
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.social/test/com/ibm/websphere/security/social/TestJwtToken.java
> +		// TODO Auto-generated method stub
```suggestion
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.social/test/com/ibm/websphere/security/social/UserProfileSerializationTest.java
> + * This is necessary for the distributed cache.
```suggestion
 * This is necessary to maintain version to version compatibility for the distributed authentication cache.
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.token.ltpa/test/com/ibm/ws/security/token/ltpa/internal/LTPAToken2SerializationTest.java
> + * This is necessary for the distributed cache.
```suggestion
 * This is necessary to maintain version to version compatibility for the distributed authentication cache.
```

2022-09-06 20:39 UTC, jvanhill commented on dev/com.ibm.ws.security.token/test/com/ibm/ws/security/token/internal/SerializationTest.java
> + * This is necessary for the distributed cache.
```suggestion
 * This is necessary to maintain version to version compatibility for the distributed authentication cache.
```

2022-09-06 21:50 UTC, ryanesch commented
#build

2022-09-07 13:12 UTC, ryanesch commented
#build

2022-09-07 13:22 UTC, ryanesch commented
#build

2022-09-08 16:47 UTC, jvanhill approved these changes

2022-09-08 17:52 UTC, ryanesch commented
#build

2022-09-13 14:58 UTC, ryanesch commented
#build

2022-09-15 14:29 UTC, ryanesch commented
#run-libby-bot

2022-09-19 13:45 UTC, merged