AdminCenter accessibility fixes to preference page
OpenLiberty/open-liberty pull request #21898
Opened 2022-07-27 22:10 UTC by lavenal

With the latest deployment accessibility checker rule, there are three sets of violation on the perference page of Admin Center:
- insufficient contrast color on "Text direction" with background color
- should not use the aria-checked attribute on input type=radio elements
- invalid "contextual" value for dir attribute

This PR fixes the accessibility violations on the perference page.

2022-07-27 22:10 UTC, lavenal commented
#build

2022-07-28 19:47 UTC, lavenal commented
This requires changes to the Admin Center UI test.

2022-08-02 13:32 UTC, lavenal commented
#build

2022-08-03 19:32 UTC, lavenal commented
![image](https://user-images.githubusercontent.com/25039033/182693453-d7a14a06-0e4f-4fd9-a2b6-0dd56e31eb5d.png)

![image](https://user-images.githubusercontent.com/25039033/182693737-dcf97ed8-3d0f-4b95-b134-1cfb99042aed.png)

2022-08-04 13:07 UTC, lavenal commented
Once batchscan fix is in the release branch, need one more PB to get all the com.ibm.ws.ui_fat.gui tests passed.

2022-08-04 13:14 UTC, k8vance88 requested changes
Changes look good, but copywrites should be updated.

2022-08-04 14:15 UTC, k8vance88 approved these changes

2022-08-05 12:52 UTC, lavenal commented
#build

2022-08-05 13:27 UTC, lavenal commented
#run-libby-bot

2022-08-08 13:06 UTC, lavenal commented
com.ibm.ws.ui_fat.gui passed with batchscan test temporarily disabled.

2022-08-08 13:06 UTC, merged