Change workarea for application containers to the application ID, if available.
OpenLiberty/open-liberty pull request #22025
Opened 2022-08-09 17:47 UTC by tbitonti

2022-08-09 17:48 UTC, tbitonti commented
#build

2022-08-09 17:59 UTC, brenthdaniel reviewed
Deletion of the cache directories also needs to be handled (eg ApplicationConfigurator.uninstallApp() , ApplicationConfigurator.readyForAppsToStop())

2022-08-10 02:35 UTC, tbitonti commented
The last commit also updated the state machine to handle the ID based directories during cleanup.

2022-08-10 02:35 UTC, tbitonti commented
#build

2022-08-10 15:36 UTC, tbitonti commented
Overall, FATs ran with few failures:
```
Tests Failures Errors Time Taken Run Order		
no component
84975 1 4
```
	
However, there are a number of FAT test failures which seem most probably related to the update:
```
Tests Failures Errors Time Taken Run Order		

com.ibm.ws.jca_fat_derbyra FAT tests
33 0 1
com.ibm.ws.jca.fat.derbyra.LoginModuleInStandaloneResourceAdapterTest
1 0 1 0s 1

com.ibm.ws.jca_fat_embeddedrar FAT tests
17 0 1
com.ibm.ws.jca.fat.embedded.app.EmbeddedJCATest
1 0 1 0s 1

com.ibm.ws.jca_fat_enterpriseApp FAT tests
12 0 1
com.ibm.ws.jca.fat.enterpriseApp.EnterpriseAppTest
1 0 1 0s 1

com.ibm.ws.jca_fat_enterpriseApp FAT tests
12 0 1
com.ibm.ws.jca.fat.enterpriseApp.EnterpriseAppTest
1 0 1 0s 1

java.lang.Exception: Errors/warnings were found in server com.ibm.ws.jca.fat.derbyra.loginModuleInRA logs:
 <br>[8/9/22, 21:03:52:655 PDT] 00000040 com.ibm.ws.classloading.internal.AppClassLoader              E CWWKL0002E: The system could not read class [org.apache.derby.jdbc.EmbeddedDataSource40] as resource [org/apache/derby/jdbc/EmbeddedDataSource40.class].
 <br>[8/9/22, 21:03:52:726 PDT] 00000040 com.ibm.ws.classloading.internal.AppClassLoader              E CWWKL0002E: The system could not read class [org.apache.derby.iapi.store.access.xa.XAXactId] as resource [org/apache/derby/iapi/store/access/xa/XAXactId.class].
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3003)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2862)
```

There is an additional undetermined failure from microprofile which also looks related to the update.  This may a test error.
```
io.openliberty.microprofile.openapi.2.0.internal_fat FAT tests
26 1 0
io.openliberty.microprofile.openapi20.fat.deployments.DeploymentTest
testEar_EE9_FEATURES_MicroProfile_50_MpOpenApi_31
1 1 0 5s 1

junit.framework.AssertionFailedError: 2022-08-10-08:14:25:365 
Expected: is an empty collection
     got: <[[8/10/22, 8:14:23:901 UTC] 0000002c id=00000000 liberty.microprofile.openapi20.internal.ApplicationProcessor 3 Using OpenAPI model loaded from cache]>
	at io.openliberty.microprofile.openapi20.fat.deployments.DeploymentTest.assertCache(DeploymentTest.java:331)
	at io.openliberty.microprofile.openapi20.fat.deployments.DeploymentTest.testEar(DeploymentTest.java:143)
```

2022-08-10 18:29 UTC, tbitonti commented
The test failures were from the first, incompletely coded, build.
The second build sees only the single failure of 
```
io.openliberty.microprofile.openapi20.fat.deployments.
DeploymentTest.testEar_EE9_FEATURES_MicroProfile_50_MpOpenApi_31
```
That test was coded to work around the cache location bug!  The test code is being updated.

Net: The second build is usable for testing.

2022-08-10 19:13 UTC, tbitonti commented
#build

2022-08-12 00:25 UTC, jhanders34 requested changes

2022-08-12 00:25 UTC, jhanders34 commented on dev/com.ibm.ws.app.manager.war/src/com/ibm/ws/app/manager/ear/internal/EARDeployedAppInfoFactoryImpl.java
> +import com.ibm.wsspi.adaptable.module.UnableToAdaptException;
You shouldn't duplicate the exception import.

2022-08-12 00:25 UTC, jhanders34 commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/DownloadFileAction.java
> +            buf = new byte[32 * 1024]; //you can change the 1024 to a different size value
This change is out of left field it seems.  What is the reason for it?

2022-08-12 00:25 UTC, jhanders34 commented on dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java~
> +/*******************************************************************************
This looks like an unintended file in this PR.

2022-08-21 03:37 UTC, closed without merging