PR for Issue 21159: Nonce/request URL storage and OP discovery enhancements
OpenLiberty/open-liberty pull request #22142
Opened 2022-08-17 14:38 UTC by ayoho

- Update authentication dialog to use storage subsystem for nonce and original request URL values
- Jakarta authentication dialog discovery enhancements:
    - Adds a caching mechanism for OP metadata to avoid sending discovery requests too often
    - Adds the bulk of the remaining code to perform OP discovery
- Added code to Jakarta authentication dialog to redirect to the authorization endpoint with all appropriate request parameters included
    - Includes required parameters (scope, response type, client ID, redirect URI, and state)
    - Includes optional parameters depending on the OIDC client config (nonce, prompt, response mode, display, extra parameters)

For #21159

2022-08-17 14:39 UTC, ayoho commented
Good personal build: https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_ZE9WEB16Ee2b2O1gXXKb4w. Had child builds fail due to some infrastructure issues, but as far as I can tell all OIDC tests ran and passed.

2022-08-17 15:06 UTC, dmuelle requested changes
ID review- let me know if any questions, thanks

2022-08-17 15:06 UTC, dmuelle commented on dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
> +DISCOVERY_EXCEPTION=CWWKS2403E: The {0} OpenID Connect client encountered an error while discovering metadata for the OpenID Connect provider from the [{1}] URL. {2}
```suggestion
DISCOVERY_EXCEPTION=CWWKS2403E: The {0} OpenID Connect client encountered the following error during discovery of metadata for the OpenID Connect provider from the [{1}] URL: {2}
```

2022-08-17 15:15 UTC, ayoho commented on dev/io.openliberty.security.oidcclientcore.internal/resources/io/openliberty/security/oidcclientcore/internal/resources/OidcClientCoreMessages.nlsprops
> +DISCOVERY_EXCEPTION=CWWKS2403E: The {0} OpenID Connect client encountered an error while discovering metadata for the OpenID Connect provider from the [{1}] URL. {2}
Update pushed 👍

2022-08-17 15:19 UTC, ayoho commented
#libby

2022-08-17 16:48 UTC, dmuelle approved these changes
LGTM, thanks

2022-08-19 14:08 UTC, teddyjtorres approved these changes
Thank you very much for these changes.

2022-08-19 15:57 UTC, merged