Order same-factory batches of configurations; generate PIDs with a counter for each factory PID.
OpenLiberty/open-liberty pull request #22200
Opened 2022-08-21 03:35 UTC by tbitonti

2022-08-21 03:36 UTC, tbitonti commented
#build

2022-08-22 15:24 UTC, tbitonti commented
Test failures:

```
Name
Tests Failures Errors Time-Taken Run-Order

no component
82867 1 4

com.ibm.ws.microprofile.openapi_fat FAT tests
50 1 3
  com.ibm.ws.microprofile.openapi.fat.annotations.AnnotationProcessingTest
  3 1 2 12m07s 1
    testPrivateFieldVisibility_EE10_FEATURES_MicroProfile_60
    1 0 1 6m02s 1 (*1.1)
    testNonPublicFieldVisibility_EE10_FEATURES_MicroProfile_60
    1 1 0 3s 2 (*1.2)
    testRequiredCustomNameField_EE10_FEATURES_MicroProfile_60
    1 0 1 6m02s 3 (*1.3)
  junit.framework.TestSuite
  1 0 1 0s 2
    com.ibm.ws.microprofile.openapi.fat.annotations.AnnotationProcessingTest
    1 0 1 0s 1 (*1.4)

io.openliberty.jcache.internal_fat.infinispan FAT tests
10 0 1
  junit.framework.TestSuite
  1 0 1 0s 8
    io.openliberty.jcache.internal.fat.FATSuite
    1 0 1 0s (*2)

(*1.1)
java.lang.RuntimeException: 2022-08-21-06:56:38:404 Timed out waiting for testPrivateFieldVisibility to be in state STARTED. Actual state: STOPPED, Last log message:null
	at componenttest.topology.impl.LibertyServer.waitForAppState(LibertyServer.java:6027)
	at componenttest.topology.impl.LibertyServer.addInstalledAppForValidation(LibertyServer.java:6039)
	at com.ibm.websphere.simplicity.ShrinkHelper.exportDropinAppToServer(ShrinkHelper.java:197)
	at com.ibm.ws.microprofile.openapi.fat.annotations.AnnotationProcessingTest.testPrivateFieldVisibility(AnnotationProcessingTest.java:82)

(*1.2)
junit.framework.AssertionFailedError: 2022-08-21-06:56:41:514 Expected: schema named NonPublicFieldVisibilityDataObject to exist
but openApi document was: { ... }
	at com.ibm.ws.microprofile.openapi.fat.annotations.AnnotationProcessingTest.assertDataMatchesSchema(AnnotationProcessingTest.java:165)
	at com.ibm.ws.microprofile.openapi.fat.annotations.AnnotationProcessingTest.testNonPublicFieldVisibility(AnnotationProcessingTest.java:110)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

(*1.3)
java.lang.RuntimeException: 2022-08-21-07:02:43:781 Timed out waiting for testRequiredCustomNameField to be in state STARTED. Actual state: STOPPED, Last log message:null
	at componenttest.topology.impl.LibertyServer.waitForAppState(LibertyServer.java:6027)
	at componenttest.topology.impl.LibertyServer.addInstalledAppForValidation(LibertyServer.java:6039)
	at com.ibm.websphere.simplicity.ShrinkHelper.exportDropinAppToServer(ShrinkHelper.java:197)
	at com.ibm.ws.microprofile.openapi.fat.annotations.AnnotationProcessingTest.testRequiredCustomNameField(AnnotationProcessingTest.java:123)

(*1.4)
java.lang.Exception: Errors/warnings were found in server AnnotationProcessingServer logs:
 <br>[8/21/22, 6:50:41:043 PDT] 00000029 com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0002E: An exception occurred while starting the application testPrivateFieldVisibility. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException
 <br>[8/21/22, 6:56:42:274 PDT] 0000002b com.ibm.ws.app.manager.AppMessageHelper                      E CWWKZ0002E: An exception occurred while starting the application testRequiredCustomNameField. The exception message was: com.ibm.ws.container.service.state.StateChangeException: org.jboss.weld.exceptions.DefinitionException
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3003)

(*2)
java.lang.IllegalStateException: Used testcontainer image(s) [infinispan/server:13.0.10.Final] were not found in the fat.test.container.images property! To correct this, add fat.test.container.images: infinispan/server:13.0.10.Final to the bnd.bnd file for this FAT so that a testcontainer image graph can be generated in the future.
	at componenttest.containers.ImageVerifier.assertImages(ImageVerifier.java:66)
	at componenttest.containers.TestContainerSuite.teardownTestContainers(TestContainerSuite.java:53)
```

Rerunning personal build.

2022-08-22 15:24 UTC, tbitonti commented
#build

2022-08-22 15:27 UTC, tbitonti commented
Failure 1.1 matches RTC defect 292234.

2022-08-22 15:30 UTC, tbitonti commented
Failure 2 is similar but not exactly the same as RTC defect 291450.

2022-08-24 04:36 UTC, tbitonti commented
#build

2022-08-31 23:12 UTC, jhanders34 requested changes

2022-08-31 23:12 UTC, jhanders34 commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/ApplicationConfigurator.java
> +
```suggestion            
```

2022-08-31 23:12 UTC, jhanders34 commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/CacheUtils.java
> +        return urlEncode((pid == null) ? id : pid);
```suggestion
        return urlEncode((id == null) ? pid : id);
```

2022-08-31 23:12 UTC, jhanders34 commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
> +                                resolveFileAction = new DownloadFileAction(_locAdmin, configId, configPid, location, resolveFileCallback, _handler);
```suggestion
                                resolveFileAction = new DownloadFileAction(_locAdmin, configPid, configId, location, resolveFileCallback, _handler);
```

2022-08-31 23:12 UTC, jhanders34 commented on dev/com.ibm.ws.app.manager/src/com/ibm/ws/app/manager/internal/statemachine/ApplicationStateMachineImpl.java
> +                                resolveFileAction = new ResolveFileAction(_ctx, appMonitorConfig.getPollingRate(), appMonitorConfig.getUpdateTrigger(), _locAdmin, appConfig.getName(), configId, confi
```suggestion
                                resolveFileAction = new ResolveFileAction(_ctx, appMonitorConfig.getPollingRate(), appMonitorConfig.getUpdateTrigger(), _locAdmin, appConfig.getName(), configPid, configId, location, resolveFileCallback, _handler);
```

2022-08-31 23:12 UTC, jhanders34 commented on dev/io.openliberty.microprofile.openapi.2.0.internal_fat/fat/src/io/openliberty/microprofile/openapi20/fat/deployments/DeploymentTest.java
> +                                                        OpenApiActions.MP_OPENAPI_31, // mpOpenAPI-3.1, LITE
This merge didn't go well.  It should be the previous code now.

2022-09-13 02:38 UTC, tbitonti commented
FAT Tests Added:

- test.server.config.CacheIdRestartTest.testCacheIds_Restart()
  - Verify default cache ID assignment.  Verify use of explicit application IDs as cache IDs.
- test.server.config.CacheIdUpdateTest.testCacheIds_Update()
  - Update application configuration to add explicit IDs.  Verify the change of IDs from default IDs to explicit IDs.
- test.server.config.CacheIdRearrangeTest.testCacheIds_Rearrange()
  - Update application configuration to change the order of application configurations.  Verify the correct application function despite the exchange of default ID assignments across server restarts.

2022-09-13 02:39 UTC, tbitonti commented
#build

2022-09-13 02:39 UTC, tbitonti commented
#libby

2022-09-13 22:58 UTC, jhanders34 approved these changes
I am approving it since the review comments I added are not required for the code, but should be made regardless.

2022-09-13 22:58 UTC, jhanders34 commented on dev/com.ibm.ws.config_fat/test-applications/cacheid1/resources/META-INF/permissions.xml
> +    Copyright (c) 2017 IBM Corporation and others.
```suggestion
    Copyright (c) 2022 IBM Corporation and others.
```

2022-09-13 22:58 UTC, jhanders34 commented on dev/com.ibm.ws.config_fat/test-applications/cacheid0/resources/META-INF/permissions.xml
> +    Copyright (c) 2017 IBM Corporation and others.
```suggestion
    Copyright (c) 2022 IBM Corporation and others.
```

2022-09-13 22:58 UTC, jhanders34 commented on dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.cacheid.update/bootstrap.properties
> +# Copyright (c) 2017 IBM Corporation and others.
```suggestion
# Copyright (c) 2022 IBM Corporation and others.
```

2022-09-13 22:58 UTC, jhanders34 commented on dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.cacheid.restart/bootstrap.properties
> +# Copyright (c) 2017 IBM Corporation and others.
```suggestion
# Copyright (c) 2022 IBM Corporation and others.
```

2022-09-13 22:58 UTC, jhanders34 commented on dev/com.ibm.ws.config_fat/publish/servers/com.ibm.ws.config.cacheid.rearrange/bootstrap.properties
> +# Copyright (c) 2017 IBM Corporation and others.
```suggestion
# Copyright (c) 2022 IBM Corporation and others.
```

2022-09-13 22:58 UTC, jhanders34 commented on dev/com.ibm.ws.config_fat/fat/src/test/server/config/CacheIdUpdateTest.java
> +//    verifyCacheIds(server, testName, "revert-1", ids_update1);
Is this commented out code needed?
```suggestion
```

2022-09-14 03:06 UTC, tbitonti commented
One build failure, which appears to be an infrastructure problem:
```
io.openliberty.microprofile.telemetry.1.0.internal.jaeger_fat FAT tests | 2 | 0 | 1 |   |  
junit.framework.TestSuite | 1 | 0 | 1 | 0 s | 2
io.openliberty.microprofile.telemetry.internal.tests.AutoInstrumentationTest

```

2022-09-14 03:09 UTC, tbitonti commented
#build

2022-09-14 03:09 UTC, tbitonti commented
#libby

2022-09-15 15:51 UTC, tbitonti commented
#build

2022-10-14 16:28 UTC, tbitonti commented
Successful field test.  Merging.

2022-10-14 16:28 UTC, merged