Make Global Handlers optional in restfulWS-3.1 and xmlWS-4.0
OpenLiberty/open-liberty pull request #22383
Opened 2022-09-02 22:49 UTC by WhiteCat22

This PR is a proof of concept to remove Global Handlers from the EE10 web services features (`restfulWS-3.1` and `xmlWS-4.0`). This is a legacy API that is rendered obsolete by Filters in the EE specs.

We are still going to support Global Handlers, but they will no longer be enabled by default. Users will need to explicitly enable the `globalHandler-2.0` feature.

2022-09-02 22:58 UTC, WhiteCat22 commented
#libby #build

2022-09-06 19:30 UTC, posmith commented
L2 message review not required

2022-09-08 21:19 UTC, WhiteCat22 commented
#libby #build

2022-09-09 19:06 UTC, WhiteCat22 commented
#libby #build

2022-09-12 17:28 UTC, WhiteCat22 commented
#libby #build

2022-09-20 22:23 UTC, WhiteCat22 commented
#build

2022-10-06 04:29 UTC, WhiteCat22 commented
#build

2022-10-06 21:40 UTC, WhiteCat22 commented
#build

2022-10-07 20:26 UTC, WhiteCat22 commented
#build

2022-10-10 20:08 UTC, WhiteCat22 commented
#build

2022-10-11 15:17 UTC, WhiteCat22 commented
Build failed with a ConnectionTimeout
#Libby #Build

2022-10-11 20:54 UTC, WhiteCat22 commented
#build

2022-10-12 15:40 UTC, WhiteCat22 commented
#libby

2022-10-12 18:35 UTC, neuwerk submitted a review, later dismissed
Changes look good to me!

2022-10-13 15:56 UTC, jim-krueger commented on dev/io.openliberty.jaxws.globalhandler.internal/src/com/ibm/ws/jaxws/globalhandler/GlobalhandlerSOAPMessageContextImpl.java
> +
This java file does not need to be included in this PR if all you are doing is adding spaces.

2022-10-13 15:57 UTC, jim-krueger submitted a review, later dismissed
Approving with one minor comment.

2022-10-17 21:01 UTC, jhanders34 requested changes
There is no way to have user feature use globalhandler since it isn't moved to be protected so this PR seems incomplete.  com.ibm.websphere.appserver.globalhandler-1.0 should be moved to be a protected feature.  I would actually prefer for it to be renamed to io.openliberty.globalhandler-1.0 when that happens.  I can't believe that no FATs fail as a result of this change.  Do we not have repeats for EE10 in the globalhandler tests?  I know that Berksan is working in EE10 repeats for XML WS 4.0.  Not sure if that will cause tests to start failing.  Are there RESTful WS 3.1 tests for global handler that need to be updated to do repeats?

2022-10-17 21:01 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-2.0.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=io.openliberty.mpJwt-2.0)))"
```suggestion
 osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.mpJwt-2.0))"
```

2022-10-17 21:01 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.mpJwtPropagation-2.1.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(|(osgi.identity=io.openliberty.mpJwt-2.1)))"
```suggestion
IBM-Provision-Capability: osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.restfulWSClient-3.1))", \
 osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.mpJwt-2.1))"
```

2022-10-17 21:01 UTC, jhanders34 commented on dev/io.openliberty.jaxws.globalhandler.internal/bnd.bnd
> + com.ibm.ws.jaxws.globalhandler;version="2.3", \
split package?  You export it with one version and import it with another version.  Very odd.

2022-10-17 21:01 UTC, jhanders34 commented on dev/io.openliberty.jaxws.globalhandler.internal/.gitignore
> +/bootstrapping.properties
This file makes no sense.  There should be no dropins or bootstrapping.properties for this project.  I think it should be deleted.

2022-10-17 21:01 UTC, jhanders34 commented on dev/io.openliberty.jaxws.globalhandler.internal/.classpath
> +	<classpathentry kind="src" path="fat/src"/>
```suggestion
```

2022-10-17 21:01 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlWS4.0-globalHandler1.0.feature
> +edition=full
```suggestion
kind=beta
edition=base
```

2022-10-17 21:01 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlWS4.0-globalHandler1.0.feature
> +  io.openliberty.globalhandler1.0.internal.ee-10.0
```suggestion
IBM-Provision-Capability: osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.xmlWS-4.0))", \
 osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=com.ibm.websphere.appserver.globalhandler-1.0))"
```

2022-10-17 21:01 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.restfulWS3.1-globalHandler1.0.feature
> +  io.openliberty.globalhandler1.0.internal.ee-10.0
```suggestion
IBM-Provision-Capability: osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.restfulWS-3.1))", \
 osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.globalhandler-1.0))"
```

2022-12-01 05:00 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/protected/io.openliberty.globalhandler-1.0.feature
> +kind=ga
```suggestion
kind=beta
```

2022-12-01 05:02 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlWS4.0-globalHandler1.0.feature
> +IBM-Provision-Capability: osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.restfulWS-3.1))", \
```suggestion
IBM-Provision-Capability: osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.xmlWS-4.0))", \
```

2022-12-01 05:03 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/auto/io.openliberty.xmlWS4.0-globalHandler1.0.feature
> + osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=com.ibm.websphere.appserver.globalhandler-1.0))"
```suggestion
 osgi.identity; filter:="(&(type=osgi.subsystem.feature)(osgi.identity=io.openliberty.globalhandler-1.0))"
```

2023-02-03 21:30 UTC, jhanders34 commented
The commits in this PR were merged in with PR #24040.  As such I am closing out this PR as well.

2023-02-03 21:30 UTC, closed without merging