Change to no longer transform the idp application 3 times.
OpenLiberty/open-liberty pull request #22524
Opened 2022-09-15 21:46 UTC by jhanders34

- Update to put the idp wars in an idp-tests instead of test-apps directory so that the apps isn't transformed 3 times
- Update the copy of the right app to use idp-apps to copy from when copying to the test-apps dir.

2022-09-15 21:46 UTC, jhanders34 commented
#build

2022-09-15 22:44 UTC, c00crane requested changes
chooseIdpWarVersion is called before the transform is done, so the 4.1.0 or 3.3.1 versions of the war will have been copied from the idp-apps dir to the test-apps dir and will be transformed.
I think the transform needs to run before the 
 if (serverType.equals(SAMLConstants.IDP_SERVER_TYPE)) { 
that contains the call to 
shibbolethHelpers.setShibbolethPropertiesForTestMachine(aTestServer);

2022-09-15 23:12 UTC, jhanders34 commented
> chooseIdpWarVersion is called before the transform is done, so the 4.1.0 or 3.3.1 versions of the war will have been copied from the idp-apps dir to the test-apps dir and will be transformed. I think the transform needs to run before the if (serverType.equals(SAMLConstants.IDP_SERVER_TYPE)) { that contains the call to shibbolethHelpers.setShibbolethPropertiesForTestMachine(aTestServer);

Right now the 3.3.1, 4.1.0 and copied version are in the test-apps directory.  With this change only the copied one will be in the test-apps directory.  We want to transform the application, we just don't want to transform the 3.3.1 and 4.1.0 as well since that is not necessary.  If the application didn't contain any javax. classes we wouldn't need to transform it, but it clearly does.  In the end it would be ideal to only do this as part of the FATSuite in a BeforeClass and AfterClass so that on each repeat it will do it just once and we don't end up transforming it but once.  That will take some more time to get right so I was trying to do this as a simple change to allow builds to pass more consistently.

2022-09-16 13:43 UTC, c00crane commented
It's probably better to continue transforming the shibboleth jar (and only transforming 1 jar is much better than transforming all 3)

2022-09-16 13:43 UTC, c00crane approved these changes

2022-09-16 14:35 UTC, ayoho approved these changes

2022-09-16 14:54 UTC, merged