use explicit version for hamcrest
OpenLiberty/open-liberty pull request #22636
Opened 2022-09-23 14:39 UTC by benjamin-confino

This test works with hamcrest 2.1 and throws a class not found exception on hamcrest 1.1

Without an explicit dependency it uses whatever it finds in .m2 and falls back to 1.1

2022-09-23 14:39 UTC, benjamin-confino commented
#build

2022-09-23 15:09 UTC, benjamin-confino commented
#build

2022-09-26 09:20 UTC, Azquelt commented
This shouldn't be necessary, the TCK already has a dependency on hamcrest which lists the version: https://github.com/eclipse/microprofile-fault-tolerance/blob/3.0/tck/pom.xml#L108-L113

2022-09-26 09:21 UTC, Azquelt requested changes
This shouldn't be needed

2022-09-26 09:50 UTC, benjamin-confino commented
Andrew is going to fix this by fixing the build environment instead.

2022-09-26 09:50 UTC, closed without merging