featureUtility ordered list for install
OpenLiberty/open-liberty pull request #22789
Opened 2022-10-03 19:35 UTC by jjiwooLim

2022-10-03 19:48 UTC, jacobwdv requested changes

2022-10-03 19:48 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloader.java
> +        this.mavenCoordMap = new HashMap<>();
This should be a HashTable instead of HashMap since HashMap is not thread safe.

2022-10-03 20:34 UTC, jjiwooLim commented
#build

2022-10-04 15:29 UTC, jjiwooLim commented
#libby-bot

2022-10-04 20:28 UTC, jacobwdv approved these changes
LGTM

2022-10-04 21:19 UTC, merged