Add Spec multipart providers and ensure historic internal multipart s…
OpenLiberty/open-liberty pull request #23113
Opened 2022-10-25 20:11 UTC by jim-krueger

This PR adds the new spec multipart providers to the service loader.  This adds corresponding MBR/MBW providers, including a few that specifically handle Lists.  This causes a problem with the historic IBM internal multipart support and requires that the IBMMultipartProvider, that specifies <Object>, to be split off with the creation of a new IBMMultipartListProvider MBR/MBW to  handle Lists of IAttachment objects.

2022-10-25 20:12 UTC, jim-krueger commented
#run-libby-bot

2022-10-25 20:14 UTC, jim-krueger commented
Currently existing FAT tests ensure that the historic internal multipart function will continue to work.    A follow-on PR will be created containing new FAT for the new spec defined multipart capability.

2022-10-25 20:14 UTC, jim-krueger commented
#build

2022-10-25 20:31 UTC, WhiteCat22 requested changes

2022-10-25 20:31 UTC, WhiteCat22 commented on dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/providers/multipart/IBMMultipartListProvider.java
> +        System.out.println("Jim... IBMMultipartProvider.isSupported() returning: " + (mediaTypeSupported(mt)
debug statement

2022-10-25 20:35 UTC, jim-krueger commented on dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/plugins/providers/multipart/IBMMultipartListProvider.java
> +        System.out.println("Jim... IBMMultipartProvider.isSupported() returning: " + (mediaTypeSupported(mt)
thanks

2022-10-25 20:35 UTC, jim-krueger commented
#run-libby-bot

2022-10-25 20:37 UTC, jim-krueger commented
#build

2022-10-25 20:42 UTC, WhiteCat22 approved these changes

2022-10-26 13:09 UTC, jim-krueger commented
The only failure was trace related and not testing the function added.  Merging.

2022-10-26 13:09 UTC, merged