Reduce calls to getHeader in WebRequestImpl.determineIfRequestHasAuthenticationData
OpenLiberty/open-liberty pull request #23144
Opened 2022-10-27 13:02 UTC by uberskigeek

Performance improvement by reducing calls to getHeader in WebRequestImpl.determineIfRequestHasAuthenticationData

2022-10-27 13:03 UTC, uberskigeek commented
#build

2022-10-27 14:28 UTC, dettmoney reviewed
The old code had null checks around hdrValue - is that not necessary anymore?

2022-10-27 14:53 UTC, jhanders34 requested changes

2022-10-27 14:53 UTC, jhanders34 commented on dev/com.ibm.ws.webcontainer.security/src/com/ibm/ws/webcontainer/security/WebRequestImpl.java
> +            return false;
```suggestion
    private boolean isBasicOrBearerAuthHeaderInRequest(String authHeaderValue) {
        return authHeaderValue != null && (authHeaderValue.startsWith(BASIC_AUTHORIZATION_METHOD) || authHeaderValue.startsWith(BEARER_AUTHORIZATION_METHOD));
```

2022-10-27 23:00 UTC, jhanders34 submitted a review, later dismissed

2022-10-28 11:44 UTC, jhanders34 commented
#build

2022-10-28 13:36 UTC, jhanders34 approved these changes, later dismissed

2022-10-28 13:40 UTC, uberskigeek commented
#build

2022-10-30 12:44 UTC, uberskigeek commented
#build

2022-10-31 12:20 UTC, jhanders34 submitted a review, later dismissed

2022-10-31 12:59 UTC, uberskigeek commented
#build

2022-10-31 13:02 UTC, uberskigeek commented
#libby

2022-10-31 14:39 UTC, jhanders34 approved these changes

2022-10-31 15:14 UTC, una-tapa approved these changes
Refactoring looks good.  Thanks for letting us know.

2022-10-31 15:15 UTC, merged