23110 add jakarta.xml.ws.spi.provider lookup test
OpenLiberty/open-liberty pull request #23412
Opened 2022-11-18 17:33 UTC by BerksanAtes

Fixes #23110

2022-11-18 17:34 UTC, BerksanAtes commented
#build

2022-11-18 18:29 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/fat/src/com/ibm/ws/jaxws/fat/PureCXFTest.java
> +//@SkipForRepeat({ SkipForRepeat.NO_MODIFICATION, JakartaEE9Action.ID })
Is a fix for a defect? Or related to this change?

2022-11-18 18:33 UTC, neuwerk requested changes
Changes look good other than the question I have with PureCXFTest. Also, could you squash some of your commits in order to keep the minimum number of commits beneath 5. I think that's OL best practice for PRs (I may or may not have gotten called out on this myself over time haha).

2022-11-18 18:57 UTC, BerksanAtes commented
#build

2022-11-18 19:22 UTC, neuwerk submitted a review, later dismissed

2022-11-21 20:16 UTC, BerksanAtes commented
#build

2022-11-21 20:54 UTC, neuwerk approved these changes
Changes look good, thank you!

2022-11-22 14:58 UTC, BerksanAtes commented
#run-libby-bot

2022-11-22 15:09 UTC, merged