Don't reject URIs with encoded '/' with servlet 6
OpenLiberty/open-liberty pull request #23573
Opened 2022-12-02 14:14 UTC by idlewis

first part of the fix for #23570

2022-12-02 14:15 UTC, idlewis commented
#build

2022-12-15 16:52 UTC, idlewis commented
#build

2022-12-16 11:29 UTC, idlewis commented
#build

2022-12-22 10:40 UTC, idlewis commented
#build

2022-12-22 11:18 UTC, idlewis commented
Previous build timed out.
new build:
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_tgFE4IHfEe257ttQcLfLow

2023-01-04 14:17 UTC, idlewis commented
#libby-bot

2023-01-04 14:18 UTC, idlewis commented
#build

2023-01-06 15:07 UTC, posmith commented
L2 message review completed

2023-01-06 16:02 UTC, idlewis commented
#build

2023-01-11 16:36 UTC, dmuelle requested changes
ID review, a couple minor suggestions

2023-01-11 16:36 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +skipEncodedCharVerification.name=Skip verification of encoded characters in URI
```suggestion
skipEncodedCharVerification.name=Skip verification of encoded characters in the request URI.
```

2023-01-11 16:36 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +# Copyright (c) 1997, 2022 IBM Corporation and others.
should this be 2023?

2023-01-11 16:36 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +bad.request.uri\:.{0}=CWWWC0005I: The request URI has invalid or improperly encoded characters: [{0}]
is [{0}] a list of encoded characters? If so, 

```suggestion
bad.request.uri\:.{0}=CWWWC0005I: The request URI includes the following invalid or improperly encoded characters: [{0}]
```

also, avoid using brackets on the variable unless needed for readability

2023-01-11 16:37 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +bad.request.uri\:.{0}=CWWWC0005I: The request URI has invalid or improperly encoded characters: [{0}]
Sorry- just noticed this is a draft PR, I'm removing my request for changes so as not to block it prematurely

2023-01-11 16:37 UTC, dmuelle approved these changes

2023-01-25 09:54 UTC, closed without merging