Reintroduce command line server stop timeout option
OpenLiberty/open-liberty pull request #23645
Opened 2022-12-08 23:29 UTC by jimblye

.

2022-12-08 23:51 UTC, jimblye commented
#build

2022-12-09 13:36 UTC, jimblye commented
#build

2022-12-09 13:37 UTC, hlhoots submitted a review, later dismissed
LGTM

2022-12-09 15:39 UTC, dmuelle requested changes

2022-12-09 15:39 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
> +error.optionNotApplicableToCommand=CWWKE0028E: The ({0}) option is not applicable for the command.
```suggestion
error.optionNotApplicableToCommand=CWWKE0028E: The {0} option is not applicable for the command.
```

2022-12-09 15:39 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
> +error.badOptionValue=CWWKE0024E: The ({0}) value for the ({1}) option is not valid.
```suggestion
error.badOptionValue=CWWKE0024E: The {0} value for the {1} option is not valid.
```

2022-12-09 15:49 UTC, dmuelle approved these changes
LGTM

2022-12-09 15:54 UTC, hlhoots approved these changes
LGTM

2022-12-09 16:23 UTC, jimblye commented
#libby

2022-12-12 16:09 UTC, merged

2022-12-13 11:40 UTC, Azquelt commented
Reverted because this breaks server startup.

The server hangs after
```
[13/12/2022, 11:04:11:044 GMT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           A CWWKE0001I: The server defaultServer has been launched.
[13/12/2022, 11:04:11:287 GMT] 00000001 com.ibm.ws.kernel.launch.internal.FrameworkManager           I CWWKE0002I: The kernel started after 0.313 seconds
```

An equinox.log is found in the workarea directory which shows
```
org.osgi.framework.BundleException: Could not resolve module: com.ibm.ws.kernel.service [5]
  Unresolved requirement: Import-Package: com.ibm.ws.kernel.boot.internal; version="[1.0.0,2.0.0)"
```
There are then more failures but I think they're all consequences of `com.ibm.ws.kernel.service` not resolving.

In the build, this manifests as the failure
```
Execution failed for task ':build.image:packageOpenLibertyBeta'.
> java.nio.file.NoSuchFileException: /home/jazz_build/Build/jbe/build/open-liberty/dev/build.image/build/libs/openliberty/wlp/README.TXT
```
I think this is because the bundle resolution problem also breaks server packaging and the first thing we happen to notice is that the beta doesn't have a README.

This failure can be seen in the personal build for this PR.