Disable config update to SmallryeMetricsCDIMetadata and issue Info message.
OpenLiberty/open-liberty pull request #23693
Opened 2022-12-14 18:50 UTC by Channyboy

Update service-component to use @Modified annotation over the atomic boolean and issue info about libraryRef changes only taking effect after server restart

#build

2022-12-14 19:37 UTC, fmhwong submitted a review, later dismissed
LGTM

2022-12-14 19:58 UTC, donbourne requested changes

2022-12-14 19:58 UTC, donbourne commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.explanation=A configuration change was detected for the MicroProfile Metrics feature. If a changes was made to the libraryRef attribute then a server restart is re
a changes -> a change
the changes -> the change

2022-12-14 19:58 UTC, donbourne commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.explanation=A configuration change was detected for the MicroProfile Metrics feature. If a changes was made to the libraryRef attribute then a server restart is re
explanation should say something about how the mpMetrics feature does not allow for dynamic replacement of the library as applications could have registered metrics at app startup time.

2022-12-14 19:58 UTC, donbourne commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.useraction=Restart the server if the libraryRef attribute was modified for the changes to take effect.
the changes -> the change

2022-12-15 17:50 UTC, dmuelle requested changes
ID review

2022-12-15 17:50 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I=CWMMC0007I: A configuration change was detected for the MicroProfile Metrics feature. If a change was made to the libraryRef attribute then a server restart is req
```suggestion
configurationChange.info.CWMMC0007I=CWMMC0007I: A configuration change was detected for the MicroProfile Metrics feature. If a change was made to the libraryRef attribute, a server restart is required for the change to take effect.
```

2022-12-15 17:50 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.explanation=Due to the nature of how the MicroProfile Metrics feature loads the implementation binaries, a configuration change to the libraryRef attribute during
```suggestion
configurationChange.info.CWMMC0007I.explanation=Due to the way that the MicroProfile Metrics feature loads the implementation binary files, a configuration change to the libraryRef attribute is not possible during run time. Reloading the library and its contents that are specified by the libraryRef attribute during run time erases all metric data. A change to the libraryRef attribute requires a server restart for the change to take effect.
```

2022-12-15 17:50 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.useraction=Restart the server if the libraryRef attribute was modified for the changes to take effect.
```suggestion
configurationChange.info.CWMMC0007I.useraction=If the libraryRef attribute was modified, restart the server for the change to take effect.
```

2022-12-15 18:20 UTC, Channyboy commented
#build 
#libby

2022-12-15 18:43 UTC, Channyboy commented
#build
#libby

2022-12-15 19:20 UTC, dmuelle submitted a review, later dismissed
LGTM thanks

2022-12-15 21:51 UTC, donbourne commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.explanation=Due to the way that the MicroProfile Metrics feature loads the implementation binary files, a configuration change to the libraryRef attribute is not p
The reason we can't change the library on the fly is also that the metrics are registered at app startup.

2022-12-15 21:56 UTC, donbourne approved these changes, later dismissed
Just had one comment for you to consider.

2022-12-16 00:40 UTC, Channyboy commented
@dmuelle Changed the explanation of the nls pops file.

2022-12-16 00:41 UTC, Channyboy commented
#build #libby

2022-12-16 01:47 UTC, donbourne commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.explanation=A dynamic reloading of the files referenced by the libraryRef attribute would not invoke a reprocessing of MicroProfile Metrics classes as CDI beans. T
maybe something like...?
configurationChange.info.CWMMC0007I.explanation=MicroProfile Metrics requires a server restart in order to change libraries referenced by libraryRef.

2022-12-16 16:17 UTC, dmuelle requested changes
minor suggestion for concision

2022-12-16 16:17 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.metrics.common/resources/com/ibm/ws/microprofile/metrics/resources/Metrics.nlsprops
> +configurationChange.info.CWMMC0007I.explanation=MicroProfile Metrics requires a server restart in order to change libraries referenced by libraryRef.
```suggestion
configurationChange.info.CWMMC0007I.explanation=MicroProfile Metrics requires a server restart to change libraries referenced by libraryRef.
```

2022-12-16 16:21 UTC, posmith commented
L2 message review completed

2022-12-19 16:56 UTC, Channyboy commented
#build #libby

2022-12-19 19:52 UTC, dmuelle submitted a review, later dismissed
LGTM

2022-12-27 19:15 UTC, Channyboy commented
#build #libby
Build after resolving merge conflict with https://github.com/OpenLiberty/open-liberty/pull/23699

2022-12-29 18:14 UTC, zhang-ca approved these changes
Looks good.

2022-12-29 18:42 UTC, merged