Repeat jaxrs.2.0.cdi.1.2 test for EE10
OpenLiberty/open-liberty pull request #23726
Opened 2022-12-16 19:37 UTC by jim-krueger

The purpose of this PR is to repeat the 2.0 cdi tests for EE10:
Note one change due to CDI behavior change in EE10:  See comment in beans.xml in beanvalidation application:
```

```

2022-12-16 19:58 UTC, jim-krueger commented
#run-libby-bot

2022-12-16 19:58 UTC, jim-krueger commented
#build

2022-12-19 16:31 UTC, jhanders34 requested changes

2022-12-19 16:31 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/resources/WEB-INF/beans.xml
> +In EE10 and beyond and empty beans.xml means "all" mode. Another option would have been to leave
```suggestion
Prior to EE10 an empty Beans.xml file meant "all" mode.  
In EE10 and beyond and empty beans.xml means "annotated" mode. Another option would have been to leave 
```

2022-12-19 16:36 UTC, jhanders34 approved these changes

2022-12-19 16:38 UTC, jhanders34 commented
#libby

2022-12-19 19:19 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/DependentIntoJaxTest.java
> +@SkipForRepeat({"EE9_FEATURES", "EE10_FEATURES"}) //The fact this doesn't work on EE9 is probably a bug and needs investigating
FYI, I opened https://github.com/OpenLiberty/open-liberty/issues/23743 to track this

2022-12-19 19:19 UTC, WhiteCat22 approved these changes

2022-12-19 19:28 UTC, merged