Phase 3 updates to FATs for Jakarta EE 10 for unchanged EE features
OpenLiberty/open-liberty pull request #23754
Opened 2022-12-20 18:39 UTC by jhanders34

Update tests to have EE10 repeats for features that are the same between EE9 and EE10.
- beanValidation-3.0
- managedBeans-2.0
- mdb-4.0
- messagingSecurity-3.0
- appClientSupport-2.0
- jakartaeeClient-10.0

Updates to mail logic to not create a Session when creating the builder, but to only create it when the factory is called.

2022-12-20 18:40 UTC, jhanders34 commented
#build

2022-12-20 20:07 UTC, jhanders34 commented
#libby #build

2022-12-21 01:17 UTC, jhanders34 commented
#libby #build

2022-12-21 16:17 UTC, jhanders34 commented
#libby #build

2023-01-06 17:34 UTC, jhanders34 commented
#build

2023-01-07 19:37 UTC, jhanders34 commented
#libby #build

2023-01-09 15:20 UTC, njr-11 reviewed
Updates to the com.ibm.ws.context_fat* tests look fine, except the copyright year should be 2023 instead of 2022.

2023-01-09 15:23 UTC, njr-11 approved these changes
Jared pointed out the changes were actually made in 2022, so the copyright year is correct.

2023-01-09 15:24 UTC, jhanders34 commented
> Updates to the com.ibm.ws.context_fat* tests look fine, except the copyright year should be 2023 instead of 2022.

I actually made all these changes in 2022 except for a few beans.xml files.

2023-01-09 15:29 UTC, tkburroughs requested changes
mdb & managedbeans changes all look good except for the copyright year; 2023 instead of 2022.

2023-01-09 15:29 UTC, tkburroughs commented on dev/com.ibm.ws.ejbcontainer.remote.client_fat/bnd.bnd
> +# Copyright (c) 2020, 2022 IBM Corporation and others.
2023

2023-01-09 15:29 UTC, tkburroughs commented on dev/com.ibm.ws.ejbcontainer.remote.client_fat/fat/src/com/ibm/ws/ejbcontainer/remote/client/fat/tests/EjbLinkTest.java
> + * Copyright (c) 2020, 2022 IBM Corporation and others.
2023

2023-01-09 15:29 UTC, tkburroughs commented on dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeanBindingsEJBTest.java
> + * Copyright (c) 2013, 2022 IBM Corporation and others.
2023

2023-01-09 15:29 UTC, tkburroughs commented on dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeansCdiTest.java
> + * Copyright (c) 2015, 2022 IBM Corporation and others.
2023

2023-01-09 15:29 UTC, tkburroughs commented on dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeansEjbTest.java
> + * Copyright (c) 2012, 2022 IBM Corporation and others.
2023

2023-01-09 15:29 UTC, tkburroughs commented on dev/com.ibm.ws.managedbeans_fat/fat/src/com/ibm/ws/managedbeans/fat/tests/ManagedBeansWebTest.java
> + * Copyright (c) 2012, 2022 IBM Corporation and others.
2023

2023-01-09 15:38 UTC, tkburroughs approved these changes
Since the updates were made in 2022; approving.

2023-01-09 16:02 UTC, AndrewDJBanks approved these changes

2023-01-09 16:03 UTC, nmittles approved these changes
Bean Validation changes look good to me.

2023-01-09 16:26 UTC, BerksanAtes approved these changes
Looks good to me!

2023-01-09 17:34 UTC, jvanhill approved these changes

2023-01-09 17:38 UTC, merged