Move exported classes out of internal package
OpenLiberty/open-liberty pull request #23855
Opened 2023-01-10 18:51 UTC by Channyboy

#build #libby
fixes #22819

2023-01-11 19:02 UTC, Channyboy commented
#build

2023-01-12 17:27 UTC, Channyboy commented
#build #libby

2023-01-17 18:50 UTC, Channyboy commented
Rebuild as the last (and successful) build is 4 days old . #build

2023-01-18 22:41 UTC, Channyboy commented
#build #libby

2023-01-19 18:55 UTC, fmhwong commented on dev/io.openliberty.microprofile.faulttolerance.4.0.internal.metrics.5.0/src/io/openliberty/microprofile/faulttolerance40/internal/metrics/integration/MetricRecorderProvider30Metrics50Impl.java
> -import io.openliberty.microprofile.metrics50.internal.SharedMetricRegistries;
You need to rename the file to match the package.

2023-01-19 18:57 UTC, fmhwong commented on dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/package-info.java
> + * Copyright (c) 2023 IBM Corporation and others.
This is the old license

2023-01-19 18:58 UTC, fmhwong commented on dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/rest/package-info.java
> + * Copyright (c) 2023 IBM Corporation and others.
Update the license

2023-01-19 18:59 UTC, fmhwong requested changes
Please update license to Eclipse Public License 2.0.

2023-01-19 19:17 UTC, Channyboy commented
#build #libby

2023-01-19 22:29 UTC, fmhwong approved these changes
LGTM

2023-01-23 19:07 UTC, merged