Add message to show only added features and always show full list of …
OpenLiberty/open-liberty pull request #23861
Opened 2023-01-10 22:05 UTC by brenthdaniel

…installed features

Implementation of #20372

2023-01-10 22:05 UTC, brenthdaniel commented
#pb

2023-01-10 22:07 UTC, brenthdaniel commented
#build

2023-01-11 16:45 UTC, dmuelle requested changes
ID review, lmk if you have any questions, thanks

2023-01-11 16:45 UTC, dmuelle commented on dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
> +FEATURES_ADDED_DELTA=CWWKF1037I: The server added features {0} to the existing feature set.
if {0}  is a list of added features:

```suggestion
FEATURES_ADDED_DELTA=CWWKF1037I: The server added the {0} features to the existing feature set.
```

2023-01-11 16:45 UTC, dmuelle commented on dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
> +FEATURES_ADDED_DELTA.explanation=The server has installed a set of new features in addition to previously installed features.
```suggestion
FEATURES_ADDED_DELTA.explanation=The server installed a set of new features in addition to previously installed features.
```

2023-01-11 16:45 UTC, dmuelle commented on dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
> +FEATURES_ADDED_CLIENT_DELTA=CWWKF1038I: The client added features {0} to the existing feature set.
```suggestion
FEATURES_ADDED_CLIENT_DELTA=CWWKF1038I: The client added the {0} features to the existing feature set. 
```

2023-01-11 16:45 UTC, dmuelle commented on dev/com.ibm.ws.kernel.feature.core/resources/com/ibm/ws/kernel/feature/internal/resources/ProvisionerMessages.nlsprops
> +FEATURES_ADDED_CLIENT_DELTA.explanation=The client has installed a set of new features in addition to previously installed features.
```suggestion
FEATURES_ADDED_CLIENT_DELTA.explanation=The client installed a set of new features in addition to previously installed features.
```

2023-01-11 18:21 UTC, brenthdaniel commented
#build

2023-01-11 19:36 UTC, dmuelle submitted a review, later dismissed
LGTM, thanks

2023-01-13 20:18 UTC, posmith commented
L2 message review completed

2023-01-23 15:03 UTC, brenthdaniel commented
#build

2023-01-23 15:06 UTC, hlhoots approved these changes, later dismissed
LGTM

2023-01-23 15:52 UTC, jimblye submitted a review, later dismissed

2023-01-24 17:03 UTC, brenthdaniel commented
#build

2023-01-25 16:37 UTC, hlhoots approved these changes
LGTM

2023-01-25 16:43 UTC, jimblye approved these changes

2023-01-25 16:44 UTC, brenthdaniel commented
#run-libby-bot

2023-01-25 16:56 UTC, merged