Add tests for updated bell properties with checkpoint/restore.
OpenLiberty/open-liberty pull request #24060
Opened 2023-01-25 20:27 UTC by anjumfatima90

2023-01-25 21:59 UTC, anjumfatima90 commented
#build

2023-01-25 22:06 UTC, dazavala requested changes
@anjumfatima90 There are few changes to assertion messages I need you to examine.  The checkpoint setup and verification for each test LGTM.

2023-01-25 22:06 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/test-applications/bells/src/bells/TestInterfaceImpl.java
> +    public TestInterfaceImpl() {
Log a system.out in the service impl constructors to help track when the service consumer calls getService(service-intf). The info would be handy when debugging a build break.

2023-01-25 22:06 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> +        assertTrue("Expected message for injected bell properties found", !server.findStringsInLogs("Updated bell properties: \\{bProp=orig_val\\}").isEmpty());
I think the message should read NOT found.

Optional: Your discovery indicates the service is consumed on restore after checkpoint-at-deployment, and  we expect bell config properties to inject immediately after the service impl is created (consumed).  Since the assertion verifies both, this message could read "Bell service should have been consumed and injected with [original|updated] properties".  And the messages could identify the actual service for improved readability.

2023-01-25 22:06 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> -        assertTrue("Expected message for bell service registration not found", !server.findStringsInLogs("CWWKL0050I").isEmpty());
There are now more two bells and two libraries in use.  Assertions for bell service registration must now search for message CWWKL0050I containing the referenced library and/or the service interface.  That means we need a message for each bell to verify each registration event occurred -- if that matters to the test.

2023-01-25 22:06 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
>          assertTrue("Expected message for bell service registration not found", !server.findStringsInLogs("CWWKL0050I").isEmpty());
Comments for testBellsCheckpointAtDeployment() apply here as well.

2023-01-25 22:06 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> +        assertTrue("Expected message for injected bell properties found", !server.findStringsInLogs("Updated bell properties: \\{bProp=orig_val\\}").isEmpty());
Again, the message should be NOT found, yes?

2023-01-26 16:33 UTC, anjumfatima90 commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> +        assertTrue("Expected message for injected bell properties found", !server.findStringsInLogs("Updated bell properties: \\{bProp=orig_val\\}").isEmpty());
Done, thanks!

2023-01-26 16:34 UTC, anjumfatima90 commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> -        assertTrue("Expected message for bell service registration not found", !server.findStringsInLogs("CWWKL0050I").isEmpty());
Checked for two service registrations. Thanks!

2023-01-26 16:34 UTC, anjumfatima90 commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
>          assertTrue("Expected message for bell service registration not found", !server.findStringsInLogs("CWWKL0050I").isEmpty());
Done, thanks!

2023-01-26 16:43 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> +        assertTrue("Expected message for injected bell properties found", !server.findStringsInLogs("Updated bell properties: \\{bProp=orig_val\\}").isEmpty());
LFTM

2023-01-26 16:46 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> -        assertTrue("Expected message for bell service registration not found", !server.findStringsInLogs("CWWKL0050I").isEmpty());
That was interesting interpretation.  I'm OK with it.

2023-01-26 16:46 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/fat/src/io/openliberty/checkpoint/fat/BellsTest.java
> +        assertTrue("Expected message for injected bell properties found", !server.findStringsInLogs("Updated bell properties: \\{bProp=orig_val\\}").isEmpty());
Approved.  Thanks, @anjumfatima90

2023-01-26 16:47 UTC, dazavala approved these changes, later dismissed

2023-01-26 17:36 UTC, anjumfatima90 commented
#build

2023-01-26 18:53 UTC, anjumfatima90 commented
#build

2023-01-26 19:26 UTC, tjwatson approved these changes
Minor question about `tested.features`.  I'm pretty you don't need to list the new test feature there.  I'm also not sure why you can enable the user features without the `usr:` prefix.

2023-01-26 19:26 UTC, tjwatson commented on dev/io.openliberty.checkpoint_fat/bnd.bnd
> +	user.feature.checkpoint.bells-1.0
I would only expect to list things here if the features are enabled programmatically.  For example: `config.getFeatureManager().getFeatures().add("osgiConsole-1.0");`

2023-01-26 19:26 UTC, tjwatson commented on dev/io.openliberty.checkpoint_fat/publish/servers/checkpointBells/server.xml
> +        <feature>user.feature.checkpoint.bells-1.0</feature>
I'm not sure why you don't need `usr:` prefix here to enable the user feature:

`<feature>user.feature.checkpoint.bells-1.0</feature>`

Like this other user feature from our tests: https://github.com/OpenLiberty/open-liberty/blob/57e5fb01a3a1f05f9b771a94c5b54e3a5e5fa166/dev/io.openliberty.checkpoint_fat/publish/servers/TestSPIConfig/server.xml#L19

2023-01-27 17:24 UTC, anjumfatima90 commented
#libby

2023-01-27 18:30 UTC, merged