Telemetry misconfiguration test
OpenLiberty/open-liberty pull request #24074
Opened 2023-01-26 17:02 UTC by yasmin-aumeeruddy

For issue #24073

2023-01-26 22:03 UTC, yasmin-aumeeruddy commented
#libby
#build

2023-01-27 11:05 UTC, yasmin-aumeeruddy commented
#build
#libby

2023-01-27 11:06 UTC, benjamin-confino approved these changes, later dismissed

2023-01-27 11:08 UTC, Azquelt requested changes

2023-01-27 11:08 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
> +    }
Should each of these tests not be looking for an error message in the logs?

2023-01-27 11:09 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
> +    }
I can't see where anything is testing for an expected error message.

2023-01-27 11:53 UTC, Azquelt commented
That's much better thank you. However, I notice that your invalid endpoints are strings like "INVALID_ENDPOINT" - could you add a test where the endpoint looks valid but there's no server listening there?

Given the error messages we're expecting, I think that would be handled differently.

2023-01-27 15:24 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrsmisconfig/JaxRsMisConfigEndpoints.java
> + * Copyright (c) 2022 IBM Corporation and others.
Copyright date

2023-01-27 15:27 UTC, yasmin-aumeeruddy commented
#libby
#build

2023-01-27 15:30 UTC, Azquelt submitted a review, later dismissed

2023-01-30 11:09 UTC, yasmin-aumeeruddy commented
The build failed as the [NotKnownEndpointTest](https://github.com/yasmin-aumeeruddy/open-liberty/blob/telemetry-misconfiguration-test/dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java#L184) checked for an error message that changed depending on the OS used. The test has been updated

2023-01-30 11:09 UTC, yasmin-aumeeruddy commented
#libby
#build

2023-01-31 09:39 UTC, benjamin-confino approved these changes

2023-01-31 09:40 UTC, merged