Release CreationContexts in a JAX-RS request error path
OpenLiberty/open-liberty pull request #24156
Opened 2023-02-01 20:51 UTC by WhiteCat22

This solves a memory leak in `JaxRsFactoryImplicitBeanCDICustomizer` where `CreationContext`s were not released

2023-02-01 20:51 UTC, WhiteCat22 commented
Fixes: https://github.com/OpenLiberty/open-liberty/issues/24155

2023-02-01 21:18 UTC, jhanders34 requested changes

2023-02-01 21:18 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/BeanValidation12Test.java
> +        System.gc();
The GC needs to happen on the server side, not the test side.
```suggestion
```

2023-02-01 21:18 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/BeanValidation12Test.java
> +        assertTrue(Integer.valueOf(result) < 10000);
```suggestion
        assertEquals(0, Integer.parseInt(result));
```

2023-02-01 21:18 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BookStoreWithValidationPerRequestLeak.java
> + *     IBM Corporation - initial API and implementation
```suggestion
```

For new files, you shouldn't add this.

2023-02-01 21:18 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BookStoreWithValidationPerRequestLeak.java
> +        int size = map.size();
Here is where you would put the GC logic.
```suggestion
        int size = map.size();
        for (int i = 0; i < 10; ++i) {
            if (size == 1) {
                break;
            }
            System.out.println("calling system gc");
            System.gc();
            try {
                Thread.sleep(1000);
            } catch (Exception e) {
            }
            size = map.size();
        }
```

2023-02-01 21:18 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/test-applications/beanvalidation/src/com/ibm/ws/jaxrs20/cdi12/fat/beanvalidation/BookStoreWithValidationPerRequestLeak.java
> +    static WeakHashMap<BookStoreWithValidationPerRequestLeak, String> map = new WeakHashMap<BookStoreWithValidationPerRequestLeak, String>();
```suggestion
    static WeakHashMap<BookStoreWithValidationPerRequestLeak, String> map = new WeakHashMap<>();
```
This is a nit, but might as well do it the simpler way that was added in Java 7.

2023-02-08 20:27 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.common/src/com/ibm/ws/jaxrs20/injection/LibertyClearInjectRuntimeCtxOutInterceptor.java
> +    @Override
Copyright update?

2023-02-08 20:28 UTC, jhanders34 commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.frontend.jaxrs.3.2/src/com/ibm/ws/jaxrs20/injection/LibertyClearInjectRuntimeCtxOutInterceptor.java
> +    @Override
copyright date update?

2023-02-08 20:34 UTC, jhanders34 approved these changes

2023-02-09 15:56 UTC, WhiteCat22 commented
#build #libby

2023-02-09 19:29 UTC, WhiteCat22 commented
network blip in my previous #build

2023-02-10 16:26 UTC, merged