UnsupportedClassVersionError in test init
OpenLiberty/open-liberty pull request #24173
Opened 2023-02-03 15:26 UTC by njr-11

fixes #24171

2023-02-03 15:51 UTC, KyleAure requested changes

2023-02-03 15:51 UTC, KyleAure commented on dev/com.ibm.ws.concurrent.mp_fat_jakarta/fat/src/com/ibm/ws/concurrent/mp/fat/jakarta/MPContextProp1_3_EE10_Test.java
>  public class MPContextProp1_3_EE10_Test extends FATServletClient {
I think the issue here is that even though the test class has the `@MinimumJavaLevel` annotation junit processes tests by creating a list of test methods, and then filtering them out. Our custom FATRunner uses the `@TestServlet` annotation to grab the servlet class and find additional test methods. 

I did some digging and I think the solution would be to add the `@MinimumJavaLevel(javaLevel = 11)` to the servlet class which also contains `@Test` annotations. 

Your solution also works, but I think the additional annotation change might be the actual solution here.  This obviously doesn't work if two test classes share the same servlet, and that might be a situation for the build team to look at.

2023-02-03 16:19 UTC, KyleAure approved these changes
Approved, I think this is actually happening when creating a list of methods.  My previous suggestion won't work. This fix looks good.

2023-02-03 16:20 UTC, njr-11 commented
#build

2023-02-06 14:22 UTC, njr-11 commented
#build

2023-02-07 14:11 UTC, njr-11 commented
#build

2023-02-08 15:35 UTC, njr-11 commented
#build

2023-02-09 14:14 UTC, merged