Jakarta faces rename
OpenLiberty/open-liberty pull request #24330
Opened 2023-02-16 00:07 UTC by pnicolucci

Latest schema from: https://jakarta.ee/xml/ns/jakartaee/

2023-02-16 00:08 UTC, pnicolucci commented
#libby #build

2023-02-16 00:29 UTC, pnicolucci commented
#libby #build

2023-02-16 11:11 UTC, pnicolucci commented
#libby #build

2023-02-17 19:21 UTC, posmith commented
L2 message review not required.

2023-02-20 12:26 UTC, pnicolucci commented
#libby #build

2023-02-21 12:35 UTC, pnicolucci commented
#libby #build

2023-02-22 01:39 UTC, isaacrivriv submitted a review, later dismissed
Updates look good to me, thanks!

2023-02-22 02:37 UTC, volosied approved these changes, later dismissed

2023-02-22 14:25 UTC, dmuelle requested changes
ID review- minor edit suggestion for misplaced "only"

2023-02-22 14:25 UTC, dmuelle commented on dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.0/resources/l10n/io.openliberty.facesContainer-4.0.properties
> + 4.0 framework. This feature only includes container integration code for Jakarta Faces but does not \
```suggestion
 4.0 framework. This feature includes only container integration code for Jakarta Faces but does not \
```

2023-02-22 14:34 UTC, pnicolucci commented on dev/com.ibm.websphere.appserver.features/visibility/public/facesContainer-4.0/resources/l10n/io.openliberty.facesContainer-4.0.properties
> + 4.0 framework. This feature only includes container integration code for Jakarta Faces but does not \
fixed! Thanks for the review!

2023-02-22 14:36 UTC, dmuelle approved these changes
LGTM thanks

2023-02-22 14:36 UTC, pnicolucci commented
#libby #build

2023-02-22 18:21 UTC, tbitonti approved these changes

2023-02-23 12:39 UTC, merged