Fix RTC294574
OpenLiberty/open-liberty pull request #24337
Opened 2023-02-16 15:43 UTC by jgrassel

The com.ibm.ws.jpa.tests.javasupport_fat bucket needed a little more work to be friendlier with Java 8.

2023-02-16 15:43 UTC, jgrassel commented
#build

2023-02-16 20:27 UTC, tkburroughs requested changes
Java level is set incorrectly for the "09" test.... also for both the JPA30 and JPA31 servers, there is an oddly named app in the apps directory that should probably be removed:

JakartaSupportTest_111.war

2023-02-16 20:27 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA31_JavaSourceLevel.java
> +    @MinimumJavaLevel(javaLevel = 1)
Should this be "11" instead of "1"?

2023-02-17 14:08 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA31_JavaSourceLevel.java
> +    @MinimumJavaLevel(javaLevel = 1)
good catches, I'll fix that and push.

2023-02-17 14:13 UTC, jgrassel commented on dev/com.ibm.ws.jpa.tests.javasupport_fat/fat/src/io/openliberty/jpa/test/javasupport/TestJPA31_JavaSourceLevel.java
> +    @MinimumJavaLevel(javaLevel = 1)
fixed, please review again

2023-02-17 14:14 UTC, jgrassel commented
#run-libby-bot

2023-02-17 15:10 UTC, tkburroughs approved these changes

2023-02-17 17:04 UTC, merged