Fix IBMi username issue
OpenLiberty/open-liberty pull request #24386
Opened 2023-02-20 18:56 UTC by KyleAure

When running our Database Container test suites we often set environment variables on the server to pass the programmatically constructed container variables to the server.

The problem is that in some instances we are clashing with environment variables set on the OS and picked up by the Liberty server at runtime. Namely: `USER` and `PASSWORD`

Avoid this by using the more specific `ORACLE_USER` and `SQL_USER` variable names. 
Note that OS environment variables are non-mutable at runtime.

2023-02-20 19:31 UTC, nmittles requested changes

2023-02-20 19:31 UTC, nmittles commented on dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleTest.java
> + *
Copyright date here and other files as well.

2023-02-20 19:31 UTC, nmittles commented on dev/com.ibm.ws.jdbc_fat_oracle/fat/src/com/ibm/ws/jdbc/fat/oracle/OracleSSLTest.java
> + *
copyright date

2023-02-20 20:42 UTC, KyleAure commented
@nmittles updated copyright headers and force pushed an update.

2023-02-20 20:47 UTC, nmittles approved these changes, later dismissed

2023-02-20 20:48 UTC, KyleAure commented
#libby - check headers
#build

2023-02-20 23:51 UTC, jmstephensgit approved these changes, later dismissed

2023-02-21 00:05 UTC, KyleAure commented
Had to resolve merge conflicts: 
#libby - recheck headers
#build - restart the build
@nmittles @jmstephensgit  - need to re-review

2023-02-21 00:07 UTC, jmstephensgit approved these changes

2023-02-22 21:59 UTC, KyleAure commented
Traditional personal build passed with no errors. 
Still waiting on IBMi build to complete.

2023-02-23 16:25 UTC, KyleAure commented
IBMi build had a failure in com.ibm.ws.jdbc_fat_sqlserver: 
```
java.lang.Exception: Errors/warnings were found in server com.ibm.ws.jdbc.fat.sqlserver logs:
 <br>[22/02/23 09:50:40:981 UTC] 00000058 com.ibm.ws.jdbc.internal.JDBCDriverService                   W DSRA8020E: Warning: The property 'authenticationScheme' does not exist on the DataSource class com.ibm.db2.jdbc.app.UDBConnectionPoolDataSource.
	at componenttest.topology.impl.LibertyServer.checkLogsForErrorsAndWarnings(LibertyServer.java:3024)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2883)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2766)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2675)
	at componenttest.topology.impl.LibertyServer.stopServer(LibertyServer.java:2650)
	at com.ibm.ws.jdbc.fat.sqlserver.SQLServerTest.tearDown(SQLServerTest.java:92)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at componenttest.custom.junit.runner.FATRunner$2.evaluate(FATRunner.java:364)
	at componenttest.custom.junit.runner.FATRunner.run(FATRunner.java:178)
```

This is a separate defect that needs to be fixed. We've gone from all tests failing down to 1 so that is great!

2023-02-23 16:26 UTC, merged