RTC294172 RTC293474 RTC294307 Build break fixes
OpenLiberty/open-liberty pull request #24390
Opened 2023-02-20 23:22 UTC by benjamin-confino

This PR contains fixes for 

RTC294172 - a follow up to #23816 updating a file that was overlooked in that 23816. This fixes a **REGRESSION**

RTC293474 - This validates an app on startup. It is unlikely to fix the error, but tidies the test a little

RTC294307 - This fixes a test failure by merging two methods annotated AfterClass into one method. This fixes a bug that occurs if they run in the wrong order.

2023-02-20 23:22 UTC, benjamin-confino commented
#build

2023-02-21 10:54 UTC, Azquelt commented on dev/com.ibm.ws.cdi.visibility_fat/fat/src/com/ibm/ws/cdi/visibility/tests/vistest/VisTest.java
> -    public static void cleanupFeatures() throws Exception {
Revert this change. Doing it as separate methods ensures the uninstall of features is still done even if the `stopServer()` throws an exception.

2023-02-21 10:54 UTC, Azquelt requested changes

2023-02-21 10:54 UTC, Azquelt commented on dev/com.ibm.ws.org.jboss.weld/bnd.overrides
> -  org/jboss/weld/context=${bin}/org/jboss/weld/context
Please do this in a separate change.

2023-02-21 17:25 UTC, Azquelt approved these changes
Comments can be addressed in a follow up PR.

2023-02-21 17:30 UTC, merged