Activation 2.1: Split the Eclipse Angus Reference Implementation into separate bundle
OpenLiberty/open-liberty pull request #24447
Opened 2023-02-24 03:44 UTC by neuwerk

This pull requests splits the Activation 2.1 RI into a separate bundle, now that the specification APIs are no longer dependent on the RI.

2023-02-24 03:45 UTC, neuwerk commented
#build

2023-02-24 03:46 UTC, neuwerk commented
@jhanders34 if you wouldn't mind reviewing this for me, one question I had is if its alright to leave the RI bundle in the what could become just the spec private feature.

2023-02-25 01:08 UTC, jhanders34 requested changes

2023-02-25 01:08 UTC, jhanders34 commented on dev/io.openliberty.org.eclipse.angus.activation/bnd.bnd
> +#     IBM Corporation - initial API and implementation
```suggestion
```

We are not including this in new files.

2023-02-25 21:34 UTC, neuwerk commented
#build

2023-02-27 14:44 UTC, jhanders34 requested changes

2023-02-27 14:44 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.jakarta.restfulWS-3.1.feature
>    io.openliberty.jaxrs30; location:="dev/api/ibm/,lib/", \
```suggestion
```
Also `-files` .  Both should be moved to restfulWSClient-3.1 public feature.

2023-02-27 14:44 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/mail-2.1/io.openliberty.mail-2.1.feature
> +  jakarta.activation; type="spec", \
```suggestion
```
Put this in io.openliberty.activation.internal-2.1

2023-02-27 14:44 UTC, jhanders34 commented on dev/com.ibm.websphere.appserver.features/visibility/public/restfulWSClient-3.1/io.openliberty.restfulWSClient-3.1.feature
> + jakarta.ws.rs; type="spec", \
```suggestion
IBM-API-Package: jakarta.ws.rs; type="spec", \
```

2023-02-27 15:47 UTC, neuwerk commented
#build

2023-02-27 16:03 UTC, jhanders34 commented on dev/io.openliberty.org.eclipse.angus.activation/bnd.bnd
> +  io.openliberty.jakarta.activation_2_1_${replace;${bVersion};\\.;_}.ResourceProvider; \
Do you want to change this name to match the bundle name?

2023-02-27 16:04 UTC, jhanders34 approved these changes, later dismissed

2023-02-27 16:22 UTC, jhanders34 approved these changes

2023-02-27 16:27 UTC, neuwerk commented
#build

2023-02-27 16:31 UTC, WhiteCat22 approved these changes

2023-02-27 18:12 UTC, jhanders34 commented
#libby

2023-02-28 16:49 UTC, neuwerk commented
Failure is unrelated to these changes, was a infrastructure timeout in one of the FAT child builds.

2023-02-28 16:50 UTC, merged