Avoid tests buckets timing out by changing to allow only a sub-set of the tests to run on slow hardware.
OpenLiberty/open-liberty pull request #24554
Opened 2023-03-05 17:54 UTC by jim-krueger

Change  com.ibm.ws.jaxrs.2.0.client_fat to run all tests on only a subset of Liberty versions when running on slower test hardware (Windows, AIX, ISeries).  On that hardware only the EE7 and EE10 versions will run during official builds.

2023-03-05 17:58 UTC, jim-krueger commented
#libby #build

2023-03-06 13:48 UTC, jim-krueger commented
#libby #build

2023-03-06 22:54 UTC, jhanders34 requested changes

2023-03-06 22:54 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
> +    private static final boolean isISeries = System.getProperty("os.name").toLowerCase(Locale.ENGLISH).contains("iseries");
```suggestion
    private static final boolean isISeries = System.getProperty("os.name").toLowerCase(Locale.ENGLISH).contains("os/400");
```

I believe that is correct, but @gjwatts would know for sure.

2023-03-06 22:54 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
> +    // To avoid going over 3 hour test limit on slow hardware, run only the first an last versions
```suggestion
    // To avoid going over 3 hour test limit on slow hardware, run only the first and last versions
```

2023-03-06 22:54 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
> +            r = RepeatTests.withoutModificationInFullMode()
```suggestion
            r = RepeatTests.with(new EmptyAction().conditionalFullFATOnly(EmptyAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```

2023-03-06 22:54 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
> +import componenttest.custom.junit.runner.FATRunner;
```suggestion
import componenttest.custom.junit.runner.FATRunner;
import componenttest.rules.repeater.EmptyAction;
```

2023-03-07 00:27 UTC, jim-krueger commented
#libby #build

2023-03-07 00:38 UTC, jhanders34 approved these changes

2023-03-07 02:02 UTC, gjwatts commented
@jhanders34 You are correct Jared.  The value to check against for the IBM i `os.name` is `OS/400`.

```
[java] [echoproperties] os.name=OS/400
```

2023-03-07 14:10 UTC, merged