Upgrade to commons-io:2.11.0
OpenLiberty/open-liberty pull request #24570
Opened 2023-03-06 20:17 UTC by pmd1nh

this version is prereq for commons-fileupload:1.5

2023-03-06 20:18 UTC, pmd1nh commented
#build

2023-03-06 20:38 UTC, jhanders34 requested changes

2023-03-06 20:38 UTC, jhanders34 commented on dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
> +    <dependency>
This looks wrong.  It should have gotten generated with cnf:initialize and it shouldn't have duplicates or 2.8.0 any longer.

2023-03-06 20:38 UTC, jhanders34 commented on dev/cnf/oss_source_dependencies.maven
> +commons-io:commons-io:2.11.0
Did you do the source dependencies approach?  If not, then you should remove 2.8.0 and 2.11.0 from this file.

2023-03-06 20:38 UTC, jhanders34 commented on dev/com.ibm.ws.org.apache.commons.io/bnd.overrides
> +org.apache.commons.io.file.spi;version="2.11.0",org.apache.commons.io;version="2.11.0"
org.apache.commons.io package is the first one listed.  No reason to add it here a second time.  Just update the version appropriately above.

2023-03-06 20:38 UTC, jhanders34 commented on dev/com.ibm.ws.org.apache.commons.io/bnd.overrides
> +org.apache.commons.io.file.spi;version="2.11.0",org.apache.commons.io;version="2.11.0"
Not sure why org.apache.commons.io.comparator and org.apache.commons.io.filefilter is also duplicated.

2023-03-06 23:45 UTC, pmd1nh commented
@jhanders34 updated.  Also upgrade to commons-fileupload:1.5

2023-03-06 23:47 UTC, pmd1nh commented
#build

2023-03-07 00:34 UTC, jhanders34 approved these changes, later dismissed

2023-03-07 15:58 UTC, pmd1nh commented
#libby

2023-03-08 17:01 UTC, wraschke commented
#pbbeta

2023-03-08 18:49 UTC, pmd1nh commented
Updated com.ibm.ws.org.apache.commons.io/bnd.overrides to use Dynamic-Import to prevent "unresolved requirement for Import-Package: sun.nio.ch"

2023-03-08 18:50 UTC, pmd1nh commented
#build

2023-03-09 20:25 UTC, pmd1nh commented
failed tests that not related to this PR

no component | 76593 | 2 | 2 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.dynamic.routing.e2e.ihs_fat FAT tests | 1 | 0 | 1 |   |  
com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs FAT tests | 2 | 1 | 0 |   |  
com.ibm.ws.ui.tool.explore_fat.gui.nd.rw.ws FAT tests | 1 | 0 | 1 |   |  
com.ibm.ws.ui.tool.explore_fat.gui.nd.rw.ws timed out | 1 | 1 | 0 |   |  

2023-03-09 20:26 UTC, pmd1nh commented
#build
        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2023-03-09 20:46 UTC, jhanders34 approved these changes

2023-03-12 02:00 UTC, pmd1nh commented
previous pb was abandoned

#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2023-03-13 02:03 UTC, pmd1nh commented
All WC full fat passed. 
Unrelated failed tests:


  | 95990 | 3 | 0 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.security.utility_fat FAT tests | 3 | 3 | 0 |   |  
com.ibm.ws.security.utility.test.SecurityUtilityEncodeTest | 3 | 3 | 0 | 1 s | 1
testCustomHelp | 1 | 1 | 0 | 0 s | 1
testListCustom | 1 | 1 | 0 | 0 s | 2
testCustomEncode | 1 | 1 | 0 | 0 s | 3

2023-03-13 02:04 UTC, pmd1nh commented
#libby

2023-03-13 02:06 UTC, merged