Update Eclipselink to 4.0.1 for JPA 3.1 feature
OpenLiberty/open-liberty pull request #24597
Opened 2023-03-07 22:13 UTC by jgrassel

**Note: Do not merge until after 23.0.0.3 GAs**, since this update has ID changes that will need translation.

Updating the Eclipselink associated with the `persistence-3.1` feature to 4.0.1.  This includes the noteworthy "ASM Service", which allows for choosing between either the bundled Eclipselink ASM implementation, or the regular OW2 ASM implementation.

The default ASM implementation that is used is still the Eclipselink ASM.  To instruct Eclipselink to use the OW2 ASM, a user needs to add `-Declipselink.asm.service=ow2` to the server's `jvm.options` file.

FAT tests have been added to test this new capability added in Eclipselink 4.0.1.

2023-03-07 22:19 UTC, jgrassel commented
#run-libby-bot

2023-03-08 17:08 UTC, wraschke commented
#pb

2023-03-08 19:48 UTC, wraschke commented
#pbbeta

2023-03-09 16:34 UTC, wraschke commented
#build

2023-03-09 19:56 UTC, posmith commented
L2 message review completed

2023-03-13 13:45 UTC, jgrassel commented
#build

2023-03-15 14:11 UTC, dmuelle requested changes
ID review, let me know if you have any questions, thanks

2023-03-15 14:11 UTC, dmuelle commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
> +7357=URL [{0}] for resource [{1}] does not belong to a valid persistence root (as per JPA Specification)
```suggestion
7357=The [{0}] URL for the [{1}] resource does not belong to a valid persistence root, as defined by the JPA Specification.
```

2023-03-15 14:11 UTC, dmuelle commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
> +corrupt_object_referenced_through_mapping=corrupt object referenced through mapping: {0}
```suggestion
corrupt_object_referenced_through_mapping=The following corrupt object is referenced through mapping: {0}.
```

2023-03-15 14:11 UTC, dmuelle commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
>  verifiy_rows_read_locking_not_supported=Optimistic setting "Read" on "verify-rows" in entity ({0}) is not directly supported in EclipseLink CMP. See migration doc for details..
```suggestion
verifiy_rows_read_locking_not_supported=Optimistic setting "Read" on "verify-rows" in entity ({0}) is not directly supported in EclipseLink CMP. See migration doc for details.
```

2023-04-11 19:43 UTC, dmuelle commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
> +verifiy_rows_read_locking_not_supported=Optimistic setting "Read" on "verify-rows" in entity ({0}) is not directly supported in EclipseLink CMP. See migration doc for details.
```suggestion
verifiy_rows_read_locking_not_supported=Optimistic setting "Read" on "verify-rows" in the  ({0}) entity is not directly supported in EclipseLink CMP. See migration documentation for details.
```

2023-04-11 19:43 UTC, dmuelle commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
> +verifiy_rows_read_locking_not_supported=Optimistic setting "Read" on "verify-rows" in entity ({0}) is not directly supported in EclipseLink CMP. See migration doc for details.
Missed this the first time, other changes LGTM

2023-04-11 19:53 UTC, dmuelle approved these changes, later dismissed
LGTM thanks

2023-04-12 16:32 UTC, jgrassel commented
#build

2023-04-17 12:02 UTC, jgrassel commented
#build

2023-04-17 12:04 UTC, jgrassel commented
Looking at the build analysis (which hasn't been deleted), looks like just 2 buckets failed and they weren't related to JPA.  Think this safe to merge once a review is done.

2023-04-17 14:31 UTC, dazey3 approved these changes
LGTM

2023-04-17 15:04 UTC, jgrassel commented
#run-libby-bot

2023-04-17 16:03 UTC, merged