JAX-WS: Reveal masked exception
OpenLiberty/open-liberty pull request #24629
Opened 2023-03-08 22:39 UTC by BerksanAtes

Fixes #24625

2023-03-09 13:48 UTC, wraschke commented
#pbbeta

2023-03-10 18:21 UTC, wraschke commented
#build

2023-03-10 22:57 UTC, wraschke commented
Better?

2023-03-16 19:51 UTC, BerksanAtes commented
#build

2023-03-16 22:06 UTC, BerksanAtes commented
#build

2023-03-17 14:34 UTC, BerksanAtes commented
#run-libby-bot

2023-03-17 14:41 UTC, neuwerk requested changes

2023-03-17 14:41 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
> +            LOG.info("Fault occured, but exception message cause will be printed to trace only: ");
```suggestion
            LOG.fine("Fault occured, printing Exception cause to trace.");
```

2023-03-17 14:41 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
> +            LOG.info(stackTraceString);
```suggestion
            LOG.fine(stackTraceString);
```

2023-03-17 14:41 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
> +            LOG.info("Fault occured, but exception message cause will be printed to trace only: ");
Can't print this to Log.info as it will end up in the messaage.log file. We shouldn't intentionally add untranslated messages to the message.log file, and we should always minimize them where possible.

2023-03-17 14:41 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.bindings.soap.3.2/src/org/apache/cxf/binding/soap/interceptor/AbstractSoapInterceptor.java
> +            LOG.info(stackTraceString);
Same as above.

2023-03-17 14:41 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/HandlerChainWithWebServiceClientTest.java
> +        String expected = "Fault occured, but exception message cause will be printed to trace only:";
```suggestion
        String expected = "Fault occured, printing Exception cause to trace.";
```

2023-03-17 15:25 UTC, BerksanAtes commented
#build

2023-03-17 15:27 UTC, neuwerk approved these changes
Changes look good to me, thanks Berksan.

2023-03-17 15:35 UTC, BerksanAtes commented
#run-libby-bot

2023-03-20 14:12 UTC, BerksanAtes commented
#run-libby-bot

2023-03-20 14:18 UTC, merged

2023-03-20 15:35 UTC, tevans78 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/HandlerChainWithWebServiceClientTest.java
> - *
@BerksanAtes @neuwerk Please don't forget to update copyright dates