Use the application name in the cache name
OpenLiberty/open-liberty pull request #24620
Opened 2023-03-08 17:26 UTC by zhang-ca

Default unique per-application Session cache names build with the application context root for JCache session persistence.

Enable option to use additional application name in the session cache names.

2023-03-08 17:26 UTC, zhang-ca commented
#build

2023-03-08 17:27 UTC, zhang-ca commented
fixes #24585

2023-03-08 17:27 UTC, zhang-ca commented
for #24585

2023-03-08 20:12 UTC, jvanhill requested changes
I left a recommendation in the metatype description for appInCacheName.

I also do not see a unit test that tests this behavior.

2023-03-08 20:12 UTC, jvanhill commented on dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
> +appInCacheName.desc=Default unique per-application cache names build with the application context root. Set this property to "true" to use additional application name in the cache names.
Maybe something more specific.

```By default, per-application JCache session cache names are generated using the context root. When distributing the JCache seeion caches across multiple servers, it is possible to have multiple applications with the same context root that should not share a session cache. Enabling this option will result in the JCache cache names including the application name to help avoid conflicting JCache cache names. The default is "false".```

2023-03-08 20:22 UTC, zhang-ca commented on dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
> +appInCacheName.desc=Default unique per-application cache names build with the application context root. Set this property to "true" to use additional application name in the cache names.
Thanks, will update the description.

2023-03-09 20:00 UTC, posmith commented
L2 message review not required

2023-03-10 14:01 UTC, zhang-ca commented
#build

2023-03-12 00:58 UTC, zhang-ca commented
#build

2023-03-13 04:02 UTC, zhang-ca commented
#build

2023-03-13 04:03 UTC, zhang-ca commented
#run-libby-bot

2023-03-14 03:16 UTC, zhang-ca commented
#build

2023-03-15 14:19 UTC, dmuelle requested changes
ID review- let me know if you have any questions, thanks.

2023-03-15 14:19 UTC, dmuelle commented on dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
> +appInCacheName.desc=By default, per-application JCache session cache names are generated using the context root. When distributing the JCache session caches across multiple servers, it is possible to
```suggestion
appInCacheName.desc=By default, per-application JCache session cache names are generated by using the context root. When the JCache session caches are distributed across multiple servers, multiple applications with the same context root might exist that must not share a session cache. When this option is enabled, application names are included in JCache cache names to help avoid conflicting JCache cache names. The default value is false. 
```

2023-03-15 14:26 UTC, zhang-ca commented on dev/com.ibm.ws.session.cache/resources/OSGI-INF/l10n/metatype.properties
> +appInCacheName.desc=By default, per-application JCache session cache names are generated using the context root. When distributing the JCache session caches across multiple servers, it is possible to
Thanks Dave for the ID review and update, I will make the changes.

2023-03-15 14:45 UTC, jvanhill submitted a review, later dismissed

2023-03-15 23:36 UTC, zhang-ca commented
#build

2023-03-15 23:51 UTC, zhang-ca commented
#run-libby-bot

2023-03-16 13:15 UTC, dmuelle approved these changes
LGTM thanks

2023-03-16 13:21 UTC, merged