Add noship spring boot 3.0 features
OpenLiberty/open-liberty pull request #24665
Opened 2023-03-13 16:43 UTC by brenthdaniel

2023-03-13 16:43 UTC, brenthdaniel commented
#build

2023-03-14 02:42 UTC, brenthdaniel commented
#build

2023-03-15 14:21 UTC, dmuelle requested changes
ID review- minor edit per IBM style

2023-03-15 14:21 UTC, dmuelle commented on dev/com.ibm.websphere.appserver.features/visibility/public/springBoot-3.0/resources/l10n/com.ibm.websphere.appserver.springBoot-3.0.properties
> +description=This feature enables support for Spring Boot applications using Spring Boot \
```suggestion
description=This feature enables support for Spring Boot applications that use Spring Boot \
```

2023-03-15 15:52 UTC, brenthdaniel commented
#build

2023-03-15 15:55 UTC, dmuelle approved these changes
LGTM, thanks

2023-03-16 15:47 UTC, posmith commented
L2 message review not required

2023-06-22 13:44 UTC, hlhoots commented
Closing this PR, as it was picked up in the following PR with additional updates: https://github.com/OpenLiberty/open-liberty/pull/25329

2023-06-22 13:44 UTC, closed without merging