Enable @FormParam for EntityParts
OpenLiberty/open-liberty pull request #24714
Opened 2023-03-16 20:56 UTC by jim-krueger

2023-03-16 20:57 UTC, jim-krueger commented
#libby #build

2023-05-08 17:46 UTC, jim-krueger commented
#libby #build

2023-05-08 18:07 UTC, jim-krueger commented
#build

2023-05-08 20:32 UTC, jim-krueger commented
#build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps

2023-05-15 00:29 UTC, jim-krueger commented
#build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps

2023-05-16 14:40 UTC, jim-krueger commented
#libby

2023-05-16 14:41 UTC, jim-krueger commented
#libby

2023-05-16 14:42 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2023-05-16 21:01 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2023-05-16 21:08 UTC, jhanders34 requested changes

2023-05-16 21:08 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormParamInjector.java
> +       boolean debug = tc.isDebugEnabled() && TraceComponent.isAnyTracingEnabled();  //Liberty Change
```suggestion
       boolean debug = TraceComponent.isAnyTracingEnabled() && tc.isDebugEnabled();  //Liberty Change
```

2023-05-16 21:08 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormParamInjector.java
> +       List<String> list = null;
This should be lower after the EntityPart, List<EntityPart> and InputStream checks.

2023-05-16 21:08 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.server.ee10/src/io/openliberty/org/jboss/resteasy/server/component/RESTfulServletContainerInitializer.java
> +//import org.jboss.resteasy.plugins.server.servlet.HttpServlet30Dispatcher;
```suggestion
```

2023-05-16 21:08 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartResource.java
> + * Copyright (c) 2023 IBM Corporation and others.
```suggestion
 * Copyright (c) 2022, 2023 IBM Corporation and others.
```

2023-05-16 21:23 UTC, jhanders34 commented
You also should add a FormParam test with a mix of EntityPart and Strings.  Do you need more @PUT and @GET tests as well?

2023-05-17 12:55 UTC, jim-krueger commented on dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormParamInjector.java
> +       boolean debug = tc.isDebugEnabled() && TraceComponent.isAnyTracingEnabled();  //Liberty Change
Done

2023-05-17 12:56 UTC, jim-krueger commented on dev/io.openliberty.org.jboss.resteasy.common.ee10/src/org/jboss/resteasy/core/FormParamInjector.java
> +       List<String> list = null;
Done

2023-05-17 12:57 UTC, jim-krueger commented on dev/io.openliberty.org.jboss.resteasy.server.ee10/src/io/openliberty/org/jboss/resteasy/server/component/RESTfulServletContainerInitializer.java
> +//import org.jboss.resteasy.plugins.server.servlet.HttpServlet30Dispatcher;
Done.

2023-05-17 12:59 UTC, jim-krueger commented on dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartResource.java
> + * Copyright (c) 2023 IBM Corporation and others.
Done.

2023-05-18 21:26 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2023-05-18 22:30 UTC, WhiteCat22 submitted a review, later dismissed
I didn't walk through all the tests, but the product changes make sense to me

2023-05-19 15:12 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2023-05-22 14:02 UTC, jim-krueger commented
Added logic to FormParamInjector to account for @FormParam multipart parameters on resource methods (specifically EntityPart, String, and InputStream per the specification).

In addition:  For some aspects of multipart processing, RESTEasy appears to require the @MultipartConfig annotation on a servlet.   For Liberty that translates to adding that annotation to our IBMRestServlet.   This ended up causing some NPEs in beanvalidation FAT until I added default values (replacing null) to config in WebAppConfiguratorHelper.   The addition of the annotation may be something we will want to remove at some point in the future.

2023-05-22 14:11 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/multipart/MultipartTestServlet.java
> + * Copyright (c) 2023 IBM Corporation and others.
```suggestion
 * Copyright (c) 2022, 2023 IBM Corporation and others.
```

2023-05-22 14:19 UTC, jhanders34 approved these changes

2023-05-23 13:59 UTC, jim-krueger commented
#libby

2023-05-23 14:03 UTC, pmd1nh approved these changes

2023-05-23 14:26 UTC, jim-krueger commented
#run-libby-bot

2023-05-23 15:59 UTC, merged