Add new configurable property for fileUpload
OpenLiberty/open-liberty pull request #24722
Opened 2023-03-17 18:47 UTC by pmd1nh

2023-03-20 16:56 UTC, posmith commented
L2 message review completed

2023-03-20 22:23 UTC, pmd1nh commented
@dmuelle can you please review the messages in this PR?  Im trying to get them in for translation so they can be ready for 23.0.0.4 (translation Dcut is 3/31).  Thanks!

2023-03-21 15:50 UTC, dmuelle requested changes
ID review, let me know if you have any questions, thanks

2023-03-21 15:50 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +maxFileCount.desc=The maximum number of files being uploaded via the multipart/form-data request. The default is 5000.
```suggestion
maxFileCount.desc=The maximum number of files that can be uploaded by a multipart/form-data request. The default is 5000.
```

2023-03-21 15:50 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded=CWWWC0006E: The maximum permitted number of uploaded files, in a single request, has exceeded [{0}].
```suggestion
multipart.file.count.max.exceeded=CWWWC0006E: The number of uploaded files in the request exceeds maximum permitted number, which is [{0}].
```

Assuming [{0}] is the maximum

2023-03-21 15:50 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded.explanation=The files being uploaded via the multipart/form-data request exceeded the maximum.
```suggestion
multipart.file.count.max.exceeded.explanation=The number of files that are uploaded by the multipart/form-data request exceeded the maximum limit.
```

2023-03-21 15:50 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded.useraction=Increase the max file count by setting the webContainer custom property maxFileCount in the server.xml . The default is 5000.
```suggestion
multipart.file.count.max.exceeded.useraction=Increase the maximum file count by setting the maxFileCount webContainer custom property in the server.xml file. The default is maximum is 5000.
```

2023-03-21 18:19 UTC, pmd1nh commented
@dmuelle I updated as per your suggestion.  Please re-review.  Thanks!

2023-03-21 19:08 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded=CWWWC0006E: The number of uploaded files in the request exceeds maximum permitted number, which is [{0}].
```suggestion
multipart.file.count.max.exceeded=CWWWC0006E: The number of uploaded files in the request exceeds the maximum permitted number, which is [{0}]. 
```

2023-03-21 19:08 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded=CWWWC0006E: The number of uploaded files in the request exceeds maximum permitted number, which is [{0}].
@pmd1nh sorry, my suggestion introduced a typo, fixed here

2023-03-22 00:40 UTC, pmd1nh commented
#build
        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2023-03-23 02:17 UTC, pmd1nh commented
metatype name is longer than 50.  Adjusted.

2023-03-23 02:18 UTC, pmd1nh commented
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2023-03-23 21:40 UTC, pmd1nh commented
@dmuelle I added another text about the setting of -1.  Thanks!

2023-03-24 21:31 UTC, pmd1nh commented
#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2023-04-03 15:09 UTC, dmuelle requested changes
@pmd1nh sorry for the delay, I missed the notification for your updates. Made a few suggestions, let me know if you have any questions. Thanks

2023-04-03 15:09 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/OSGI-INF/l10n/metatype.properties
> +maxFileCount.desc=The maximum number of files that can be uploaded by a multipart/form-data request. The default is 5000; setting to -1 for unlimited files upload.
```suggestion
maxFileCount.desc=The maximum number of files that can be uploaded by a multipart/form-data request. The default is 5000. To enable unlimited file uploads, set this property to -1.
```

2023-04-03 15:09 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded.useraction=Increase the maximum file count by setting the maxFileCount webContainer custom property in the server.xml file. The default maximum is 5000; setting to -
```suggestion
multipart.file.count.max.exceeded.useraction=Increase the maximum file count by setting the maxFileCount webContainer custom property in the server.xml file. The default maximum is 5000.  To enable unlimited file uploads, set this property to -1. 
```

2023-04-03 15:09 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +multipart.file.count.max.exceeded.explanation=The number of files that are uploaded by the multipart/form-data request exceeded the maximum limit.
```suggestion
multipart.file.count.max.exceeded.explanation=The number of files that are uploaded by the multipart/form-data request exceeded the maximum limit, which is specified by the maxFileCount webContainer custom property.
```

2023-04-05 15:26 UTC, pmd1nh commented
messages https://github.com/OpenLiberty/open-liberty/pull/24820

2023-04-05 15:28 UTC, pmd1nh commented
clean up the FAT

#build
#spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2023-04-07 04:12 UTC, pmd1nh commented
All WC passed  including new tests

com.ibm.ws.fat.wc.tests.WCFileUpLoadFileCountMaxPropertyTest | 6 | 0 | 0 | 19 s | 9
-- | -- | -- | -- | -- | --
testFileUpload_overMaxFileCountWithProperty | 1 | 0 | 0 | 4 s | 1
testFileUpload_over10KWithProperty | 1 | 0 | 0 | 2 s | 2
testFileUpload_overMaxFileCountWithProperty_EE9_FEATURES | 1 | 0 | 0 | 4 s | 3
testFileUpload_over10KWithProperty_EE9_FEATURES | 1 | 0 | 0 | 2 s | 4
testFileUpload_overMaxFileCountWithProperty_EE10_FEATURES | 1 | 0 | 0 | 3 s | 5
testFileUpload_over10KWithProperty_EE10_FEATURES | 1 | 0 | 0 | 1 s | 6
 

com.ibm.ws.fat.wc.tests.WCFileUpLoadFileCountMaxTest | 6 | 0 | 0 | 15 s | 10
-- | -- | -- | -- | -- | --
testFileUpload_default5000Files | 1 | 0 | 0 | 3 s | 1
testFileUpload_overMaxFileCount | 1 | 0 | 0 | 1 s | 2
testFileUpload_default5000Files_EE9_FEATURES | 1 | 0 | 0 | 4 s | 3
testFileUpload_overMaxFileCount_EE9_FEATURES | 1 | 0 | 0 | 1 s | 4
testFileUpload_default5000Files_EE10_FEATURES | 1 | 0 | 0 | 3 s | 5
testFileUpload_overMaxFileCount_EE10_FEATURES | 1 | 0 | 0 | 1 s | 6
 

2 unrelated failed tests


no component | 92231 | 1 | 1 |   |  
-- | -- | -- | -- | -- | --
com.ibm.ws.jca_fat_regr.rar.beanVal FAT tests | 41 | 0 | 1 |   |  
com.ibm.ws.request.timing_fat FAT tests | 10 | 1 | 0 |   |  

2023-04-07 04:13 UTC, pmd1nh commented
#libby

2023-04-07 13:20 UTC, epj approved these changes
okay

2023-04-07 14:44 UTC, dmuelle approved these changes

2023-04-07 14:45 UTC, merged

2023-04-07 16:10 UTC, pmd1nh commented
Fixes #PH50863