24765 add support for enum props
OpenLiberty/open-liberty pull request #24781
Opened 2023-03-22 23:55 UTC by frowe

Issue #24765

2023-03-23 14:34 UTC, KyleAure requested changes

2023-03-23 14:34 UTC, KyleAure commented on dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
> +  <AD id="autosave"                      ibmui:group="Advanced" required="false" type="String"                         name="%autosave"             description="%sslMode.desc">
```suggestion
  <AD id="autosave"                      ibmui:group="Advanced" required="false" type="String"                         name="%autosave"             description="%autosave.desc">
```

2023-03-23 14:34 UTC, KyleAure commented on dev/com.ibm.ws.jdbc/src/com/ibm/ws/jdbc/internal/JDBCDriverService.java
> +                param = Enum.valueOf((Class<Enum>)paramType, value.toUpperCase());
Should we add some exception handling here? 
It is possible enum values could be removed in future driver updates which will result in an `IllegalArgumentException` being thrown. We should handle that exception and perhaps add a warning that `this version of the JDBC driver doesn't support value x`

2023-03-24 13:35 UTC, posmith commented
L2 message review not required.

2023-03-27 15:59 UTC, KyleAure commented
Closing in favor of #24834 
We had some issues with remote forks and need to abandon this PR.

2023-03-27 15:59 UTC, closed without merging