24765 add support for enum props
OpenLiberty/open-liberty pull request #24834
Opened 2023-03-27 15:54 UTC by frowe

more updates

2023-03-27 15:56 UTC, frowe commented
#build

2023-03-27 16:01 UTC, KyleAure commented
@jantley-ibm @posmith I added the ID and L2 labels that were on the previous PR.  Sorry for the confusion.

2023-03-27 16:05 UTC, KyleAure requested changes

2023-03-27 16:05 UTC, KyleAure commented on dev/com.ibm.ws.jdbc.metatype/resources/OSGI-INF/metatype/metatype.xml
> +   <Option value="bogus"        label="bogus"/>
Remove this bogus option (looks like it was only for testing)

2023-03-27 16:16 UTC, KyleAure approved these changes, later dismissed

2023-03-29 13:53 UTC, posmith commented
L2 message review completed

2023-03-29 13:58 UTC, jantley-ibm commented
@KyleAure LGTM

2023-03-29 15:14 UTC, KyleAure submitted a review, later dismissed

2023-03-30 14:09 UTC, frowe commented
#build

2023-03-30 14:36 UTC, KyleAure approved these changes

2023-04-01 16:13 UTC, frowe commented
#libby

2023-04-01 16:14 UTC, merged