Update artifactory image name substitutor
OpenLiberty/open-liberty pull request #24920
Opened 2023-04-03 20:43 UTC by KyleAure

2023-04-03 21:04 UTC, KyleAure commented
#build

2023-04-04 14:58 UTC, mswatosh requested changes

2023-04-04 14:58 UTC, mswatosh commented on dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
> +        do {
Instead of a loop, I would recommend using `if / else if / else` for the different priorities and default case.

2023-04-04 14:58 UTC, mswatosh commented on dev/fattest.simplicity/src/componenttest/containers/TestContainerSuite.java
> +        Log.info(TestContainerSuite.class, "before", "Setting up testcontainers");
Since this isn't in a method named `before` it should be changed. I would move the Log statement to `setupTestcontainers()`

2023-04-05 15:39 UTC, KyleAure commented on dev/fattest.simplicity/src/componenttest/containers/ArtifactoryImageNameSubstitutor.java
> +        do {
So I modeled this after how we do some of these complex heuristics elsewhere in the containers project: 
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/fattest.simplicity/src/componenttest/containers/ExternalTestServiceDockerClientStrategy.java#L379

I'd like to keep this consistent.  
Additionally, more than 3 consecutive if/else statements can often be hard to logically follow. As opposed to if/break where you have a visual cue for the control-flow.

2023-04-05 17:50 UTC, mswatosh approved these changes

2023-04-05 18:28 UTC, KyleAure commented
#build

2023-04-05 18:35 UTC, KyleAure commented
#libby

2023-04-06 19:22 UTC, merged