Fix SSLHandshakeException while closing HTTPConduit
OpenLiberty/open-liberty pull request #24993
Opened 2023-04-12 19:54 UTC by sawadood

Fixes #24986

2023-04-12 20:10 UTC, sawadood commented
#build let's do a personal build!

2023-04-12 20:27 UTC, sawadood commented
#build Let's do a personal build!

2023-04-12 20:48 UTC, neuwerk requested changes

2023-04-12 20:48 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
> +        LOG.fine("Create HttpURLConnection to:  " + url);
```suggestion
        LOG.fine("Create HttpURLConnection to:  " + url); // Liberty Change 
```

Can you append the `// Liberty Change` comment to all the `LOG.fine(*)` lines you've added?

2023-04-12 20:48 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
> +	        if (tlsClientParameters.getTrustManagers() != null &&
```suggestion
                // Liberty Change Start 
	        if (tlsClientParameters.getTrustManagers() != null && 
```

2023-04-12 20:48 UTC, neuwerk commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.3.2/src/org/apache/cxf/transport/https/HttpsURLConnectionFactory.java
> +                   socketFactory = HttpsURLConnection.getDefaultSSLSocketFactory();
```suggestion
                   socketFactory = HttpsURLConnection.getDefaultSSLSocketFactory();
                   // Liberty Change End
```

2023-04-13 12:57 UTC, sawadood commented
#build Starting personal build after code review updates

2023-04-13 13:28 UTC, neuwerk approved these changes
LGTM!

2023-04-13 14:22 UTC, sawadood commented
#build trying PB again

2023-04-14 19:18 UTC, neuwerk commented
Failures in the PB are definitely caused by this change, we will need to reevaluate how to manage this. Probably need to emulate what the JAX-RS team is doing in the SSLManager code to fix this without causing this regression.

2023-04-30 14:27 UTC, closed without merging