implement maxInUseTime and tests
OpenLiberty/open-liberty pull request #24996
Opened 2023-04-12 21:24 UTC by tabishop

Implement maxInUseTime for connections, and tests. Create a separate maintenance thread to handle cleaning up maxInUseTime connections so that the maint thread can run in millisecond intervals

2023-04-13 02:15 UTC, tabishop commented
#build

2023-04-13 14:09 UTC, dmuelle requested changes
ID review

2023-04-13 14:09 UTC, dmuelle commented on dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
> +maxInUseTime=Remove long running in use connections
```suggestion
maxInUseTime=Remove long running in-use connections
```

2023-04-13 14:09 UTC, dmuelle commented on dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
> +maxInUseTime.desc=This property is a temporary workaround for application code that does not close connections. It configures an amount of time after which pool maintenance can invoke Connection.abor
```suggestion
maxInUseTime.desc=This property is a temporary workaround for application code that does not close connections. It configures an amount of time after which pool maintenance can invoke the Connection.abort method on a connection that the application is using. Stopping connections that are in use might result in unexpected and unpredictable threading errors. The proper solution is to update the application to always close connections and not use this property. If you must configure this property as a workaround, choose a value of 20 minutes or more, depending on the normal application transaction times. If transaction times are high, 10 minutes or more, then double your longest running transaction time for this value. A value of -1 disables this timeout.
```

not sure if Connection.abort is a method or property, adjust as needed. Providing a noun identifier for each code entity is helpful for translations.

2023-04-13 14:15 UTC, tabishop commented on dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
> +maxInUseTime=Remove long running in use connections
good suggestion

2023-04-13 14:15 UTC, tabishop commented on dev/com.ibm.ws.jca.cm/resources/OSGI-INF/l10n/metatype.properties
> +maxInUseTime.desc=This property is a temporary workaround for application code that does not close connections. It configures an amount of time after which pool maintenance can invoke Connection.abor
yep, it is a method. Thanks for the suggestions.

2023-04-13 14:16 UTC, tabishop commented
#build

2023-04-13 15:08 UTC, dmuelle submitted a review, later dismissed
LGTM, thanks

2023-04-14 01:19 UTC, tabishop commented
#build

2023-04-14 16:28 UTC, tabishop commented
The latest build failures are unrelated to the changes in this PR. #libby

2023-04-14 17:22 UTC, jmstephensgit approved these changes

2023-04-14 17:36 UTC, merged