Make TCK build cache location configurable
OpenLiberty/open-liberty pull request #25393
Opened 2023-06-01 15:03 UTC by Azquelt

Allow the build system to supply a location to use for caching artifacts for the life of the build. This is used for storing the temporary maven home directory for TCK tests.

Fixes #25392

2023-06-01 15:03 UTC, Azquelt commented
#build
#pb

2023-06-01 15:57 UTC, websterc87 requested changes

2023-06-01 15:57 UTC, websterc87 commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKUtilities.java
> +        if (!buildCacheDirPath.isEmpty()) {
Should also have a null check incase the property is not set

2023-06-01 15:59 UTC, tevans78 commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKUtilities.java
> +        if (!buildCacheDirPath.isEmpty()) {
null check needed

2023-06-01 16:06 UTC, tevans78 approved these changes, later dismissed

2023-06-13 09:53 UTC, Azquelt commented
#build
#pb

2023-06-13 09:54 UTC, Azquelt commented
#libby

2023-06-14 16:49 UTC, Azquelt commented
Rebased on #25422 to pick up that configuration change.

2023-06-14 16:50 UTC, Azquelt commented
#pb

2023-06-14 16:52 UTC, Azquelt commented
#libby

2023-06-16 15:01 UTC, Azquelt commented
Failures in the build are known issues not related to this change.

2023-06-16 16:07 UTC, websterc87 commented
#pbbeta Requesting one more build so we can see the changes running the children in jenkins.

2023-06-16 16:09 UTC, websterc87 reviewed
Changes look good but would like to run it via the Jenkins Children to make sure they dont break again. I should have just requested it is github events are working.

2023-06-21 07:30 UTC, websterc87 submitted a review, later dismissed
Changes look good and pass happily run in jenkins children.

This issues in the latest build are unrelated to this PR and related to a Java17 change and defect: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=296309

A fix for this was delivered on the 15th but wouldnt have been pulled into this PR.

2023-06-21 11:29 UTC, websterc87 submitted a review, later dismissed
Happy to merge

2023-06-21 12:41 UTC, Azquelt commented
Not sure why github is immediately knocking off the review. It may be because the first commit was already merged in #25422?

Rebased on integration to see if that fixes it.

2023-06-21 12:42 UTC, websterc87 approved these changes

2023-06-21 12:43 UTC, Azquelt commented
#libby

2023-06-21 12:44 UTC, merged