Redeliver MP Reactive Streams 3.0
OpenLiberty/open-liberty pull request #25503
Opened 2023-06-15 12:14 UTC by tevans78

#build

2023-06-15 12:27 UTC, Azquelt submitted a review, later dismissed
New changes to exclude this feature from the EE10 compatibility test look good.

The test exclusions for this feature will be removed when compatibility with EE10 is done and working.

2023-06-15 15:56 UTC, dmuelle requested changes
ID review- add period to properties file description

2023-06-15 15:56 UTC, dmuelle commented on dev/com.ibm.websphere.appserver.features/visibility/public/mpReactiveStreams-3.0/resources/l10n/io.openliberty.mpReactiveStreams-3.0.properties
> +description=This feature provides support for the MicroProfile Reactive Streams 3.0 API
```suggestion
description=This feature provides support for the MicroProfile Reactive Streams 3.0 API.
```

2023-06-15 17:11 UTC, posmith commented
L2 message review not required

2023-06-19 09:38 UTC, Azquelt approved these changes

2023-06-19 09:39 UTC, tevans78 commented
#libby

2023-06-19 09:41 UTC, merged