jNoSQL Jakarta data MongoContainer and test
OpenLiberty/open-liberty pull request #25624
Opened 2023-07-04 02:29 UTC by mswatosh

Adding the MongoContainer to test jNoSQL with, and a basic test using jNoSQL as a Jakarta Data implementation.

2023-07-05 15:14 UTC, helyarp commented
@mswatosh `CWWKDMessages.nlsprops` does not have new or changed strings. Unless there are message strings to review, pls add the **ID review not needed** label.

2023-07-05 19:18 UTC, mswatosh commented
#build

2023-07-06 16:48 UTC, KyleAure requested changes

2023-07-06 16:48 UTC, KyleAure commented on dev/io.openliberty.data.internal_fat_nosql/bnd.bnd
> -	io.openliberty.org.eclipse.jnosql.1.0
You'll want to add the following line to this file:

fat.test.container.images: mongo:6.0.6

2023-07-06 16:48 UTC, KyleAure commented on dev/io.openliberty.data.internal_fat_nosql/fat/src/test/jakarta/data/nosql/FATSuite.java
>  public class FATSuite {
Add `extends TestContainerSuite` to make sure the remote docker host is set up before this bucket runs.

2023-07-06 18:36 UTC, KyleAure approved these changes

2023-07-06 18:45 UTC, mswatosh commented
#build

2023-07-07 22:20 UTC, mswatosh commented
#libby

2023-07-07 22:21 UTC, merged