oidc logout to initiate saml SLO request
OpenLiberty/open-liberty pull request #25622
Opened 2023-07-03 18:56 UTC by arunavemulapalli

Changes to support saml SLO when rp initiated logout using the OP's logout ep (we already have this support with the end_session ep requests).

2023-07-05 18:56 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.oidc

2023-09-06 17:41 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.oidc

2023-09-06 17:41 UTC, arunavemulapalli commented
#libby

2023-09-14 18:58 UTC, arunavemulapalli commented
#libby

2023-09-14 18:58 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.oidc

2023-09-27 18:28 UTC, ayoho requested changes

2023-09-27 18:28 UTC, ayoho commented on dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/utils/ForwardRequestInfo.java
> +            req.removeAttribute("OIDC_LOGOUT_REDIRECT_PAGE");
```suggestion
            req.removeAttribute("OIDC_LOGOUT_REDIRECT_URL");
```

2023-09-27 18:28 UTC, ayoho commented on dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
> +            request.setAttribute("OIDC_LOGOUT_REDIRECT_PAGE", new LogoutPages().getDefaultLogoutPage(request.getLocales()));
Does the value of this attribute actually need to be anything? It doesn't look like the value is used for anything other than essentially a present/not present flag. Could the value just be an empty string or a boolean or something simple to indicate the default logout page would be used?

2023-09-27 18:28 UTC, ayoho commented on dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/SAMLRequestTAI.java
> +            }
Would be cleaner to have all this in its own method.

2023-09-27 18:28 UTC, ayoho commented on dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/SAMLRequestTAI.java
> +    }
Is there a benefit to having this new method instead of just invoking `spCookieRetriever.getSubjectFromSpCookie()` directly?

2023-09-27 18:28 UTC, ayoho commented on dev/com.ibm.ws.security.oauth/src/com/ibm/ws/security/oauth20/web/OAuth20EndpointServices.java
> +            request.setAttribute("OIDC_LOGOUT_REDIRECT_PAGE", new LogoutPages().getDefaultLogoutPage(request.getLocales()));
Just noticed the `getRedirectPageAfterSPLogout()` method you added to `HttpRequestInfo` and its usage in `SLOHandler`, so you can disregard that comment.

2023-09-27 19:11 UTC, arunavemulapalli commented on dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/SAMLRequestTAI.java
> +    }
you are absolutely right about this . There is no benefit of having this new method here. will clean this up now

2023-09-27 19:12 UTC, arunavemulapalli commented on dev/com.ibm.ws.security.saml.websso.2.0/src/com/ibm/ws/security/saml/sso20/internal/SAMLRequestTAI.java
> +            }
agreed. maybe not with this PR?

2023-09-27 19:50 UTC, arunavemulapalli commented
#libby

2023-09-27 19:50 UTC, arunavemulapalli commented
#build
#spawn.fullfat.buckets=com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.security.saml.sso_fat,com.ibm.ws.security.saml.sso_fat.2,com.ibm.ws.security.saml.sso_fat.3,com.ibm.ws.security.saml.sso_fat.config,com.ibm.ws.security.saml.sso_fat.config.mapToUserRegistry,com.ibm.ws.security.saml.sso_fat.endpoint.samlmetadata,com.ibm.ws.security.saml.sso_fat.jaxrs,com.ibm.ws.security.saml.sso_fat.jaxrs.config,com.ibm.ws.security.saml.sso_fat.logout,com.ibm.ws.security.saml.sso_fat.logout.IDP_initiated,com.ibm.ws.security.saml.sso_fat.logout.httpServletRequest,com.ibm.ws.security.saml.sso_fat.logout.ibm_security_logout,com.ibm.ws.security.oidc.server_fat.saml,com.ibm.ws.security.oidc.server_fat.jaxrs,com.ibm.ws.security.oidc.server_fat.endpoint.end_session,com.ibm.ws.security.oidc.server_fat.app-tokens,com.ibm.ws.security.oidc.server_fat.oidc

2023-09-28 16:01 UTC, arunavemulapalli commented
#libby

2023-09-29 14:32 UTC, ayoho approved these changes

2023-09-29 14:35 UTC, merged