Readd Changes for 25167 and Cleanup of CXF Upgrade
OpenLiberty/open-liberty pull request #25736
Opened 2023-07-17 16:24 UTC by neuwerk

This PR readds the mistakenly undone #25167 and address clean up related comments in #25447

2023-07-17 18:52 UTC, jhanders34 commented on dev/com.ibm.ws.org.apache.cxf.cxf.core.3.2/bnd.bnd
> +# This needs to stay at 3.2.4 even though the bundle version is 3.5.5.
Did you try the feature checker ignore and it didn't work?

2023-07-17 18:54 UTC, jhanders34 commented on dev/com.ibm.ws.org.apache.cxf.cxf.rt.transports.http.hc.3.2/src/org/apache/cxf/transport/http/asyncclient/AsyncHTTPConduit.java
> -                    ctx.setAttribute("http.ioSession-factory-registry", regBuilder.build());
This is not a duplicate.  It says they are case sensitive and it is session vs Session.  I assumed this was supposed to stay?

2023-07-17 18:59 UTC, jhanders34 approved these changes

2023-07-17 19:49 UTC, jhanders34 reviewed
I removed approval based off of the comment I left where it seemed like it was supposed to leave the "duplicate" property name.

2023-07-17 19:49 UTC, jhanders34 requested changes
Now selecting request changes so that github sees what I want it to see.

2023-07-18 15:00 UTC, jhanders34 approved these changes

2023-07-18 15:00 UTC, jhanders34 commented
#libby

2023-07-18 15:21 UTC, neuwerk commented
#build

2023-07-19 12:57 UTC, merged