Add Java 21 specific test to FAT
OpenLiberty/open-liberty pull request #25751
Opened 2023-07-19 17:10 UTC by gjwatts

Add a Java 21 specific test to the `io.openliberty.java.internal_fat` FAT to ensure we are running on Java 21.

2023-07-19 18:37 UTC, KyleAure requested changes

2023-07-19 18:37 UTC, KyleAure commented on dev/io.openliberty.java.internal_fat/publish/servers/java21-server/apps/io.openliberty.java.internal_fat_21.war
Instead of uploading the binary to source control couldn't this be published on DHE + Artifactory?

2023-07-20 03:01 UTC, gjwatts commented
#build

2023-07-20 13:35 UTC, KyleAure approved these changes

2023-07-20 14:49 UTC, gjwatts commented
#libbybot

2023-07-20 16:31 UTC, gjwatts commented
FYI.  Normal build passed, Java 17 build passed and Java 21 build passed.  Just waiting for files to get pushed to DHE.

2023-07-24 17:26 UTC, gjwatts commented
#libbybot

2023-07-24 19:00 UTC, merged