Issue 21826: Update keyAliasName description for OIDC clients
OpenLiberty/open-liberty pull request #25750
Opened 2023-07-19 16:18 UTC by ayoho

Expands the metatype description to include how the alias is also used to point to the public key corresponding to the private key used to sign the JWT we create. Also clarifies where those keys are obtained from.

2023-07-19 16:18 UTC, ayoho commented
#build

2023-07-19 18:17 UTC, arunavemulapalli approved these changes, later dismissed

2023-07-24 14:35 UTC, dmuelle requested changes
ID review

2023-07-24 14:35 UTC, dmuelle commented on dev/com.ibm.ws.security.openidconnect.client/resources/OSGI-INF/l10n/metatype.properties
> +keyAliasName.desc=The alias for the private key that is used for signing tokens that are used for client authentication. This must also be the alias for the public key that corresponds to the private
```suggestion
keyAliasName.desc=The alias for the private key that is used for signing client authentication tokens. The public key that corresponds to the private key must also use this alias. The private key must be in the keystore that is specified by the SSL configuration that is referenced by the sslRef attribute. The public key must be in one of the following locations: the truststore that is specified by the trustStoreRef attribute, the truststore that is specified by the SSL configuration that is referenced by the sslRef attribute, or the keystore that is specified by the SSL configuration that is referenced by the sslRef attribute.
```

2023-07-24 14:35 UTC, dmuelle commented on dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
> +keyAliasName.desc=The alias for the private key that is used for signing tokens that are used for client authentication. This must also be the alias for the public key that corresponds to the private
```suggestion
keyAliasName.desc=The alias for the private key that is used for signing client authentication tokens. The public key that corresponds to the private key must also use this alias. The private key must be in the keystore that is specified by the SSL configuration that is referenced by the sslRef attribute. The public key must be in one of the following locations: the truststore that is specified by the trustStoreRef attribute, the truststore that is specified by the SSL configuration that is referenced by the sslRef attribute or the keystore that is specified by the SSL configuration that is referenced by the sslRef attribute.
```

2023-07-24 19:20 UTC, posmith commented
L2 message review not required

2023-07-26 14:32 UTC, ayoho commented
#libby

2023-07-26 14:51 UTC, arunavemulapalli approved these changes

2023-07-26 15:19 UTC, ayoho commented on dev/com.ibm.ws.security.social/resources/OSGI-INF/l10n/metatype.properties
> +keyAliasName.desc=The alias for the private key that is used for signing tokens that are used for client authentication. This must also be the alias for the public key that corresponds to the private
@dmuelle Thanks for the review. Changes pushed.

2023-07-26 16:18 UTC, dmuelle approved these changes
LGTM, thanks

2023-07-26 16:47 UTC, merged