Update JavaEESecTestBase.setServerConfiguration function
OpenLiberty/open-liberty pull request #25792
Opened 2023-07-21 21:41 UTC by adriankalafut

Remove if condition that checks for server configuration file changes. 
This condition is causing some EE9 tests to fail (when ran individually).

2023-07-21 21:41 UTC, adriankalafut commented
#build

2023-07-24 12:27 UTC, adriankalafut commented
#build

2023-07-24 17:02 UTC, adriankalafut commented
#build

2023-07-24 17:40 UTC, adriankalafut commented
#build

2023-07-25 12:05 UTC, adriankalafut commented
#build

2023-07-25 19:04 UTC, adriankalafut commented
#build

2023-07-26 16:30 UTC, Zech-Hein requested changes

2023-07-26 16:30 UTC, Zech-Hein commented on dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
> + *
```suggestion
 * 
```

We should remove this file from the commit, so that the history (if anyone ever looks at it) for the file, doesn't have a blank change

2023-07-26 17:04 UTC, adriankalafut commented on dev/com.ibm.ws.security.javaeesec_fat/fat/src/com/ibm/ws/security/javaeesec/fat_helper/JavaEESecTestBase.java
> + *
File has been removed from commit.

2023-07-26 17:05 UTC, adriankalafut commented
#build

2023-07-26 17:05 UTC, Zech-Hein approved these changes
LGTM!

2023-07-27 13:03 UTC, adriankalafut commented
#build

2023-07-27 14:00 UTC, adriankalafut commented
#build

2023-07-27 17:29 UTC, adriankalafut commented
#build

2023-07-27 19:25 UTC, adriankalafut commented
#build

2023-07-28 10:55 UTC, adriankalafut commented
#build

2023-07-31 12:33 UTC, adriankalafut commented
#build

2023-07-31 15:46 UTC, adriankalafut commented
#build

2023-08-01 14:14 UTC, adriankalafut commented
#libby

2023-08-09 15:01 UTC, merged