Use modern java idiom
OpenLiberty/open-liberty pull request #25831
Opened 2023-07-27 18:31 UTC by joe-chacko

#build

2023-07-27 18:32 UTC, joe-chacko commented
#build

2023-07-27 23:50 UTC, joe-chacko commented
That build failed checking out related source, so let's #build again.

2023-07-28 00:04 UTC, joe-chacko commented
Manually requested a build here: 
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_PNcWYCzREe6bFfaWrnDnjQ

2023-07-28 16:51 UTC, habiblawal1 approved these changes, later dismissed

2023-08-02 16:09 UTC, joe-chacko commented
#build

2023-08-05 21:48 UTC, joe-chacko commented
#build

2023-08-07 17:01 UTC, Azquelt requested changes
I think the copyright dates on these classes should be updated.

Otherwise it looks good though I've left a few comments for your consideration.

2023-08-07 17:01 UTC, Azquelt commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
> +
This is correct but I think I prefer the previous code.

2023-08-07 17:01 UTC, Azquelt commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
> +                        sslRefs, requiredSslRefs, containsAll, future != null);
This is correct, but in general I would leave the braces in.

2023-08-07 17:01 UTC, Azquelt commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/ssl/yoko/SSLSubsystemFactory.java
> +        return ((Map<?,?>)addrMap).keySet().size() != 1;
`Map` itself has a `size` method which I think would always return the same value as the size of the key set?

2023-08-07 17:01 UTC, Azquelt commented on dev/com.ibm.ws.security.csiv2/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactory.java
> +        //
Last line could be
```java
.collect(toCollection(HashSet::new))
```
using `Collections.toCollection`.

Also there's a stray empty comment here.

2023-08-09 12:16 UTC, joe-chacko commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
> +
reverted

2023-08-09 12:18 UTC, joe-chacko commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/AbstractCsiv2SubsystemFactory.java
> +                        sslRefs, requiredSslRefs, containsAll, future != null);
Done

2023-08-09 12:18 UTC, joe-chacko commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/ssl/yoko/SSLSubsystemFactory.java
> +        return ((Map<?,?>)addrMap).keySet().size() != 1;
Of course — will use that instead.

2023-08-09 12:23 UTC, joe-chacko commented on dev/com.ibm.ws.security.csiv2.common/src/com/ibm/ws/transport/iiop/security/config/ssl/yoko/SSLSubsystemFactory.java
> +        return ((Map<?,?>)addrMap).keySet().size() != 1;
Didn't reactor quite far enough…

2023-08-09 12:29 UTC, joe-chacko commented on dev/com.ibm.ws.security.csiv2/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactory.java
> +        //
That's handy! Done.

2023-08-09 12:31 UTC, joe-chacko commented on dev/com.ibm.ws.security.csiv2/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactory.java
> +        //
**`Collectors.`**`toCollection()` though.
That foxed me briefly.

2023-08-09 13:05 UTC, joe-chacko commented
Made reviewer-requested changes.
#build and #run-libby-bot again

2023-08-09 13:25 UTC, Azquelt commented on dev/com.ibm.ws.security.csiv2/src/com/ibm/ws/transport/iiop/server/security/CSIv2SubsystemFactory.java
> +        //
Ack, sorry :(

2023-08-09 13:25 UTC, Azquelt approved these changes
Looks good :+1:

2023-08-10 01:28 UTC, joe-chacko commented
#build again — the previous one had environmental issues

2023-08-14 10:30 UTC, merged