xmlWS-4.0: Enable Woodstox 6.5 as StAX Provider
OpenLiberty/open-liberty pull request #25996
Opened 2023-08-18 23:39 UTC by neuwerk

This pull request does the following: 

1.) Add two new bundles `dev/io.openliberty.com.fasterxml.woodstox.core` and `io.openliberty.org.codehaus.woodstox.stax2.api`. A StAX provider and the StAX2 APIs. 
2.) Add these bundles to the xmlWS-4.0 feature.
3.) Adds an EE level check to the `StAXUtils` class, that checks which version of the StAX provider to load from the classloader. (This check uses a check for the JAXB Validator API that was renamed in EE9 and removed in EE10)
4.) Add support for the CXF configuration for enabling or disabling Woodstox. 
5) Adds two additional checks to the LibertyCXFPropertiesTest classes to verify that the Woodstox Provider is enabled/disabled with configuration.

2023-08-18 23:42 UTC, neuwerk commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxrs.2.1_fat, com.ibm.ws.jaxrs.2.1_fat_executor, io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.ws.jaxrs.global.handler.internal_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, com.ibm.ws.wsat_fat.db,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.4,com.ibm.ws.wssecurity_fat.wsscxf,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml,com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_client, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl

2023-08-19 20:25 UTC, neuwerk commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxrs.2.1_fat, com.ibm.ws.jaxrs.2.1_fat_executor, io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.ws.jaxrs.global.handler.internal_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, com.ibm.ws.wsat_fat.db,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl

2023-08-21 16:32 UTC, jhanders34 requested changes
Does the client container StAXUtils class also need to be updated and the xml ws client feature updated to include woodstox?

2023-08-21 16:32 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
> +cxf.ignore.unsupported.policy=true
Why are these two added?

2023-08-21 16:32 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +    private static Boolean isEE10 = false;
```suggestion
    private static boolean isEE10 = false;
```

No reason for it to be a primitive wrapper since a null state is not one of the options in the logic.

2023-08-21 16:32 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +    private static Boolean isEE8 = false;
```suggestion
    private static boolean isEE9 = false;
    private static boolean isEE8 = false;
```

Same

2023-08-21 16:32 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +    private static final String JAVA_EE_JAXB_VALIDATOR = "javax.xml.bind.Validator";
javax.xml.bind.Validator will get transformed to jakarta.xml.bind.Validator when transformation happens.  That may mess with your logic below.

2023-08-21 16:32 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
>      public static ClassLoader getStAXProviderClassLoader() {
It might make sense for the EE8, 9, and 10 boolean settings at least to be in a static initializer instead.

2023-08-21 16:32 UTC, jhanders34 commented on dev/io.openliberty.com.fasterxml.woodstox.core/bnd.bnd
> +#     IBM Corporation - initial API and implementation
```suggestion
```

Not needed in new files.

2023-08-21 16:32 UTC, jhanders34 commented on dev/io.openliberty.com.fasterxml.woodstox.core/bnd.bnd
> +# Do not publish RI javax.xml.bind.JAXBContext
The property name I assume is wrong.

2023-08-21 16:32 UTC, jhanders34 commented on dev/io.openliberty.com.fasterxml.woodstox.core/bnd.bnd
> +  @${repo;com.fasterxml.woodstox:woodstox-core;6.5.1;EXACT}!/!(*/)?module-info.class
```suggestion
  @${repo;com.fasterxml.woodstox:woodstox-core;6.5.1;EXACT}!/!module-info.class)
```
Do you see multiple copies of module-info.class in the bundle?

2023-08-21 16:32 UTC, jhanders34 commented on dev/io.openliberty.org.codehaus.woodstox.stax2.api/bnd.bnd
> +#     IBM Corporation - initial API and implementation
```suggestion
```

2023-08-21 16:32 UTC, jhanders34 commented on dev/io.openliberty.org.codehaus.woodstox.stax2.api/bnd.bnd
> +  @${repo;org.codehaus.woodstox:stax2-api;${bVersion};EXACT}!/!(*/)?module-info.class
```suggestion
  @${repo;org.codehaus.woodstox:stax2-api;${bVersion};EXACT}!/!module-info.class
```

2023-08-22 16:07 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
> +cxf.ignore.unsupported.policy=true
The way the test is written, we can test all properties at once, and for EE10 all I wanted to do is add an additional property to the list that we're already testing. But you're right, it's not clear why I'm doing that, so I've updated the respective Test classes to include a comment explaining why we have a different bootsrap.properties for the EE10 runs.

2023-08-22 16:22 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
> +cxf.ignore.unsupported.policy=true
So should the false one have:

```
cxf.multipart.attachment=true
cxf.ignore.unsupported.policy=false
```
?

If `org.apache.cxf.stax.allowInsecureParser=false` is the same as the default and we aren't specifying the other ones, I am confused some on why we do org.apache.cxf.stax.allowInsecureParser in the false one.

2023-08-22 16:28 UTC, jhanders34 commented on dev/io.openliberty.com.fasterxml.woodstox.core/bnd.bnd
> +  @${repo;com.fasterxml.woodstox:woodstox-core;6.5.1;EXACT}!/module-info.class
```suggestion
  @${repo;com.fasterxml.woodstox:woodstox-core;6.5.1;EXACT}!/!module-info.class
```

2023-08-22 16:29 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
> +cxf.ignore.unsupported.policy=true
Fair point, setting the property to false is irrelevant for the Negative test suite, as it is the default and I am just confusing the issue by adding default configuration for one but not the others. I'll remove the file. Keeps the footprint down too.

2023-08-22 16:29 UTC, jhanders34 commented on dev/io.openliberty.com.fasterxml.woodstox.core/bnd.bnd
> +  @${repo;com.fasterxml.woodstox:woodstox-core;6.5.1;EXACT}!/!(*/)?module-info.class
You missed the second `!`.  I added another comment about that below.

2023-08-22 16:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
>      public static ClassLoader getStAXProviderClassLoader() {
I suggest changing the checkEELevel method to just be a static initializer and make the isEE9 and isEE10 field final.

2023-08-22 18:09 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
>      public static ClassLoader getStAXProviderClassLoader() {
Good point so I've incorporated your suggestion as an Enum.

2023-08-22 18:28 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.clientcontainer/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +    private static void checkEELevel() {
```suggestion
    private static EELevel checkEELevel() {
```

2023-08-22 18:28 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.clientcontainer/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +                eeLevel = EELevel.EE8;
```suggestion
            if (Class.forName(JAVA_EE_JAXB_VALIDATOR).getName().startsWith("jakarta")) {
                return EELevel.EE9;
            }
            return EELevel.EE8;
```

2023-08-22 18:28 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.clientcontainer/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +            eeLevel = EELevel.EE10;
```suggestion
            return EELevel.EE10;
```

2023-08-22 18:28 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.clientcontainer/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +    }
```suggestion
```

2023-08-22 18:28 UTC, jhanders34 commented on dev/com.ibm.ws.jaxws.2.3.clientcontainer/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +    private static EELevel eeLevel;
```suggestion
    private static final EELevel eeLevel = checkEELevel();
```

2023-08-22 18:51 UTC, sawadood commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/publish/files/LibertyCXFPropertiesTest/woodstox-true-bootstrap.properties
> +cxf.ignore.unsupported.policy=true
Why do we have cxf.ignore.unsupported.policy set to true as default?

2023-08-22 19:04 UTC, sawadood commented on dev/com.ibm.ws.jaxws.2.3.common/src/com/ibm/ws/jaxws/utils/StAXUtils.java
> +            eeLevel = EELevel.EE10;
Would be good to add some trace here to indicate how EELevel was set,

2023-08-22 19:25 UTC, sawadood submitted a review, later dismissed
Looks good, I have some minor comments about trace.

2023-08-22 21:29 UTC, neuwerk commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.2.2.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.ejb_fat, com.ibm.ws.jaxws.X.wsat_fat, com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jaxrs.2.1_fat, com.ibm.ws.jaxrs.2.1_fat_executor, io.openliberty.ws.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.ws.jaxrs.global.handler.internal_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, com.ibm.ws.wsat_fat.db,com.ibm.ws.wssecurity_fat.wsscxf.saml.3,com.ibm.ws.wssecurity_fat.wsscxf.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.2,com.ibm.ws.wssecurity_fat.wsscxf.saml.5,com.ibm.ws.wssecurity_fat.wsscxf.saml.6,com.ibm.ws.wssecurity_fat.wsscxf.saml.1,com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl

2023-08-23 16:15 UTC, jhanders34 approved these changes
You have addressed all of my comments.  It doesn't need to be in this PR, but a XML WS 4.0 client test updated to make sure that Woodstox is used would be a good addition.

2023-08-23 16:15 UTC, jhanders34 commented
#libby

2023-08-24 13:09 UTC, merged