Update security client fat timeout issue
OpenLiberty/open-liberty pull request #26007
Opened 2023-08-21 13:48 UTC by adriankalafut

Fix RTC 296796
Update the repeat rule for EE levels for com.ibm.ws.security.client_fat.

2023-08-21 13:48 UTC, adriankalafut commented
#build

2023-08-21 22:43 UTC, Zech-Hein requested changes

2023-08-21 22:43 UTC, Zech-Hein commented on dev/com.ibm.ws.security.client_fat/fat/src/com/ibm/ws/security/client/fat/FATSuite.java
>       * Run EE10 tests in LITE mode and run all tests in FULL mode.
```suggestion
     * On Windows, always run the default/empty/EE7/EE8 tests.
     * On other Platforms:
     * - if Java 8, run default/empty/EE7/EE8 tests.
     * - All other Java versions
     * -- If LITE mode, run EE9
     * -- If FULL mode, run EE10
```

2023-08-22 13:39 UTC, adriankalafut commented
#libby

2023-08-28 14:57 UTC, adriankalafut commented
#build

2023-08-29 13:32 UTC, Zech-Hein submitted a review, later dismissed
LGTM 👍

2023-08-29 13:36 UTC, adriankalafut commented
#libby

2023-08-29 14:26 UTC, Zech-Hein approved these changes

2023-08-29 14:27 UTC, adriankalafut commented
#libby

2023-08-29 15:06 UTC, merged