Add translatable messages for org.crac implementation
OpenLiberty/open-liberty pull request #26120
Opened 2023-08-30 17:02 UTC by tjwatson

2023-08-30 17:03 UTC, tjwatson commented
#build

2023-08-30 17:40 UTC, anjumfatima90 approved these changes, later dismissed

2023-08-31 15:52 UTC, tjwatson commented
#libby
#build

2023-09-01 14:37 UTC, posmith commented
L2 message review completed

2023-09-01 15:40 UTC, dmuelle requested changes
a few ID suggestions- in general we try to avoid gerund clauses like "while being" as they can be difficult to translate correctly in some cases

2023-09-01 15:40 UTC, dmuelle commented on dev/io.openliberty.org.crac/resources/io/openliberty/crac/resources/CRaCMessages.nlsprops
> +CRAC_RESOURCE_CHECKPOINT_FAIL_CWWKC0551=CWWKC0551E: The server checkpoint request failed because one or more resources threw an exception while being notified for the checkpoint request.
```suggestion
CRAC_RESOURCE_CHECKPOINT_FAIL_CWWKC0551=CWWKC0551E: The server checkpoint request failed because one or more resources threw an exception when they were notified for the checkpoint request.
```

2023-09-01 15:40 UTC, dmuelle commented on dev/io.openliberty.org.crac/resources/io/openliberty/crac/resources/CRaCMessages.nlsprops
> +CRAC_RESOURCE_CHECKPOINT_FAIL_CWWKC0551.explanation=One or more resource implementations registered threw an exception while being notified for a checkpoint request.
```suggestion
CRAC_RESOURCE_CHECKPOINT_FAIL_CWWKC0551.explanation=One or more registered resource implementations threw an exception when they were notified for a checkpoint request.
```

2023-09-01 15:40 UTC, dmuelle commented on dev/io.openliberty.org.crac/resources/io/openliberty/crac/resources/CRaCMessages.nlsprops
> +CRAC_RESOURCE_RESTORE_FAIL_CWWKC0552=CWWKC0552E: The server failed to restore because one or more resources threw an exception while being notified for the server restore from checkpoint.
```suggestion
CRAC_RESOURCE_RESTORE_FAIL_CWWKC0552=CWWKC0552E: The server failed to restore because one or more resources threw an exception when they were notified for the server restore from checkpoint.
```

2023-09-01 15:40 UTC, dmuelle commented on dev/io.openliberty.org.crac/resources/io/openliberty/crac/resources/CRaCMessages.nlsprops
> +CRAC_RESOURCE_RESTORE_FAIL_CWWKC0552.explanation=One or more resource implementations registered threw an exception while being notified for a server restore from checkpoint.
```suggestion
CRAC_RESOURCE_RESTORE_FAIL_CWWKC0552.explanation=One or more registered resource implementations threw an exception when they were notified for a server restore from checkpoint.
```

2023-09-01 15:40 UTC, dmuelle commented on dev/io.openliberty.org.crac/resources/io/openliberty/crac/resources/CRaCMessages.nlsprops
> +CRAC_RESOURCE_REQUEST_CHECKPOINT_CWWKC0553.explanation=Requests for checkpoint using the "org.crac" APIs are not supported by Liberty.
```suggestion
CRAC_RESOURCE_REQUEST_CHECKPOINT_CWWKC0553.explanation=Requests for checkpoint that use the org.crac APIs are not supported by Liberty. 
```

2023-09-01 15:53 UTC, tjwatson commented
#libby

2023-09-01 16:03 UTC, dmuelle approved these changes
LGTM, thanks

2023-09-05 14:42 UTC, merged