Telemetry-1.1 FAT
OpenLiberty/open-liberty pull request #26156
Opened 2023-09-04 11:19 UTC by yasmin-aumeeruddy

Add repeats for mpTelemetry-1.1

SPI and JaxRs tests are now present in the Telemetry-1.1 TCK so we don't need repeats for this feature.

2023-09-05 13:10 UTC, Azquelt commented
There are non-test changes in this PR. I assume these were needed to pass the newly added tests?

Please can you explain the non-test changes that were needed.

2023-09-05 14:31 UTC, Azquelt requested changes
In addition to the other review comments, I think the following tests should have repeats since they test reading config from different places which the TCK doesn't test:
- TelemetryConfigEnvOnlyTest
- TelemetryConfigEnvTest
- TelemetryConfigNullTest
- TelemetryConfigSystemPropTest

2023-09-05 14:31 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
> +        }
`waitForStringInLogUsingMark` returns `null` if the line is not found which would result in an NPE with the current code.

```suggestion
        if(RepeatTestFilter.isRepeatActionActive(MicroProfileActions.MP61_ID)){
            assertNotNull(server.waitForStringInLogUsingMark("Failed to export spans. Server responded with gRPC status code 2. Error message: " + INVALID_JAEGER_ENDPOINT.toLowerCase()));
        }
        else{
            assertNotNull(server.waitForStringInLogUsingMark("Failed to export spans. The request could not be executed. Full error message:.*" + INVALID_JAEGER_ENDPOINT.toLowerCase()));
        }
```

2023-09-05 14:31 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
> +        else{
Formatting

2023-09-05 14:31 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
> +            .isEmpty());
As above, `waitForStringInLogUsingMark` returns `null` if the line is not found.

2023-09-05 14:31 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
> +                          "SRVE0315E: .*configuration error"); //An exception occurred: ... Unexpected configuration error
Where does this new message come from?

2023-09-05 14:31 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryShimTest.java
> +
Should we be using the 1.29.0 version of the shim library when we're testing 1.1?

2023-09-05 14:31 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryConfigEnvTest.java
> +
Please remove the files like this one which don't have any real changes.

2023-09-05 14:34 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryShimTest.java
> +
I think we'd advise users to use the 1.29 version of the shim with 1.1? If so, we should test using that version.

You can add the 1.29 version of the shim as a new dependency configuration in the build.gradle, extract it to a different folder and the select the right folder in the test when you build the test app.

2023-09-06 15:53 UTC, Azquelt submitted a review, later dismissed

2023-09-06 15:54 UTC, yasmin-aumeeruddy commented
#build

2023-09-06 15:56 UTC, Azquelt commented
#libby

2023-09-08 09:29 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
> +	io.openliberty.microprofile.telemetry.common.*,\
This looks like a mistake.

2023-09-08 21:46 UTC, yasmin-aumeeruddy commented
#build

2023-09-11 08:32 UTC, Yas-Franco commented
#libby

2023-09-11 09:43 UTC, Azquelt commented on dev/com.ibm.ws.org.apache.servicemix.bundles.bcel/.project
> +	<projects>
Why is this file here, this isn't our project.

2023-09-11 09:44 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal/bnd.bnd
> +	*
This looks wrong? I thought we needed the specific import for `io.openliberty.microprofile.telemetry.internal.common.resources` to fix the messages.

2023-09-11 09:48 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.1.internal/src/io/openliberty/microprofile/telemetry11/internal/cdi/OpenTelemetryProducer.java
>  import io.opentelemetry.api.OpenTelemetry;
Spurious imports in this file.

2023-09-11 09:51 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
>                          .run(String.class);
Why are these changes needed?

2023-09-11 09:54 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
>                          .run(String.class);
I guess the `expectCode` change could be a result of #25626, but if that was the case, I'd have expected this test to fail in the PB for that build.

2023-09-11 09:56 UTC, Azquelt commented on dev/com.ibm.ws.org.apache.servicemix.bundles.bcel/.project
> +	<projects>
I assume this project was missing a .project file, which is bad, and it's not a bad thing to fix, but I wouldn't usually add this to one of our PRs because it could conflict with someone else's PR who is also trying to fix this problem (Jared is really good at proactively fixing things like this), thus delaying our change.

2023-09-11 10:34 UTC, Azquelt commented
There are some merge problems, it looks like the first commit 2f55d3e2 should be dropped and the branch rebased on integration.

2023-09-11 13:02 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/TelemetryMisconfigTest.java
>                          .run(String.class);
We checked and these tests _are_ failing in the build since #25626 was merged. The right tests were not requested for the personal build on that PR.

2023-09-11 13:20 UTC, Azquelt approved these changes
Looks good :+1:

2023-09-11 13:23 UTC, yasmin-aumeeruddy commented
#build
#libby

2023-09-12 07:26 UTC, merged