Resolve symbolic links when looking for java
OpenLiberty/open-liberty pull request #26197
Opened 2023-09-06 20:51 UTC by jimblye

#Fixes 18412

2023-09-07 12:38 UTC, jimblye commented
#build

2023-09-07 22:02 UTC, jimblye commented
#build

2023-09-08 12:46 UTC, tjwatson commented
> The whole point of doing this is to find out if we are using version 9 or above. I'm wondering why we can't just do this:

I think we avoid doing `java -version` to avoid invoking `java` as that takes extra time to do that.  But then again, that may be just as fast as the realpath implementation and the searching for the modules directory.  Besides that, this is a fallback when JAVA_HOME is not set.  If that is slow then the proper thing to do is set JAVA_HOME.  For our container images we always have JAVA_HOME set.

2023-09-08 13:39 UTC, tjwatson commented
I will say running `java -version` locally is not fast at all.  I think it takes 10s of millis.  That will not be acceptable for an InstantOn regression.  But then again this is for the case where JAVA_HOME is not set.  For InstantOn (in-container) we always have JAVA_HOME set.

2023-09-08 14:01 UTC, covener commented
Not working on zOS for me when running under /bin/sh -- on my system it falls back to `cd -P` and the builtin cd for /bin/sh doesn't know `-P`.

We have some similar stuff in IHS and we basically parse `ls -l` output.

```
\ls -l $F | sed -e "s#.*-> ##"

$ ls -l ~/.bash_profile
lrwxrwxrwx   1 WASTST1  WASUSER       28 Aug 29 13:01 /u/WASTST1/.bash_profile -> /u/WASTST1/bin/.bash_profile
WASTST1@BOSS0152:~/SRC/2.4.x (zformlogin) $ ls -l ~/.bash_profile | sed -e "s#.*-> ##"
/u/WASTST1/bin/.bash_profile
```

We do not have LANG=C or any locale stuff  --  it might be a risk.

2023-09-13 18:10 UTC, jimblye commented
#build

2023-09-14 23:34 UTC, jimblye commented
#build

2023-09-14 23:46 UTC, jimblye commented
Ready for another review.   The issue doesn't address Windows.  Probably because Windows doesn't pretend to use java9.options if JAVA_HOME is not set.  Well, until now.   I updated the server.bat script to derive JAVA_HOME from the PATH.   Unfortunately, I don't know if there is a way that we can resolve symbolic links on Windows without requiring PowerShell, and I'm not sure how easy that would be.    So now, at least some of the time we'll use java9.options on Windows without having JAVA_HOME set.   Though, at this point, I suspect most people are used to setting JAVA_HOME with Liberty.

On the non-Windows side of things I added a counter to bail out if we follow > 100 symbolic links.   If you get that far, I'm pretty there's a circular link.

2023-09-18 15:30 UTC, dmuelle requested changes
ID review

2023-09-18 15:30 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
> +warning.tooManySymbolicLinks=CWWKE0096W: Too many symbolic links encountered when trying to resolve a path ( {0} ).
```suggestion
warning.tooManySymbolicLinks=CWWKE0096W: Too many symbolic links were encountered when the system tried to resolve the following path: {0}.
```

2023-09-18 15:30 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
> +warning.tooManySymbolicLinks.explanation=Symbolic links are shortcuts that point to other files or directories. This error occurs when the system encounters too many symbolic links in a chain, making
```suggestion
warning.tooManySymbolicLinks.explanation=Symbolic links are shortcuts that point to other files or directories. This error occurs when the system encounters too many symbolic links in a chain and it is unable to resolve the path.
```

2023-09-18 15:30 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherMessages.nlsprops
> +warning.tooManySymbolicLinks.useraction=To resolve this issue, consider checking the symbolic links in the path, and ensure that they do not create circular references. You may also want to use the '
```suggestion
warning.tooManySymbolicLinks.useraction=To resolve this issue, check the symbolic links in the path and ensure that they do not create circular references. You might also use the 'readlink' command to inspect individual links in the chain.
```

2023-09-18 15:45 UTC, dmuelle approved these changes
LGTM

2023-09-18 18:14 UTC, jimblye commented
#libby

2023-09-18 20:02 UTC, hlhoots approved these changes
LGTM

2023-09-18 21:12 UTC, merged