Add support for nacks to the Kafka connector
OpenLiberty/open-liberty pull request #26351
Opened 2023-09-21 12:16 UTC by Azquelt

Outgoing Kafka connector will nack messages it cannot deliver.

Incoming Kafka connector will shut down and log an error if one of the messages it created is nacked.

Fixes #25969

2023-09-21 17:02 UTC, Azquelt commented
#build
#libby

2023-09-22 13:59 UTC, abutch3r commented
Overall looks good, need to investigate the test failures for common and the JSON-b tests which for some reason are now impacted by kafka

2023-09-22 16:47 UTC, Azquelt commented
The Json-B tests are likely impacted somehow by either the refactoring of the framework classes into a common package, or by the changes needed to common classes to accommodate testing the 3.0 API.

2023-09-22 17:17 UTC, Azquelt commented
`AbstractDeliveryBean` was updated so that it could report nacks so it now uses the new class `TestMessageImpl`.

I'd changed `JsonbTest` to include the whole package instead of just the two classes it needed, but hadn't realised that pulls in a bean that refers to Kafka classes which causes a class not found exception during CDI startup.

I should have split up the framework classes which need Kafka from those that don't. We should also probably consolidate some of the common app setup code into a utility method.

2023-09-22 17:17 UTC, Azquelt commented
#build
#libby

2023-10-02 16:25 UTC, posmith commented on dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
> +kafka.input.message.nacked.CWMRX1011E=CWMRX1011E: The nack method was called on a message created from a Kafka record, indicating that it was not be processed successfully. The reactive message strea
Extraneous word, 'be', in the statement, "indicating that it was not be processed successfully".  Please remove.

2023-10-06 13:35 UTC, dmuelle requested changes
ID review, let me know if you have any questions or if I've misinterpreted the meaning. Thanks

2023-10-06 13:35 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
> +kafka.input.message.nacked.CWMRX1011E=CWMRX1011E: The nack method was called on a message created from a Kafka record, indicating that it was not be processed successfully. The reactive message strea
```suggestion
kafka.input.message.nacked.CWMRX1011E=CWMRX1011E: The nack method was called on a message that was created from a Kafka record, which indicates that the message was not processed successfully. The reactive message stream is shut down. The record was: {0}. The exception was: {1}.
```

2023-10-06 13:35 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
> +kafka.input.message.nacked.CWMRX1011E.explanation=A message sent by the kafka connector caused a failure somewhere in the application which resulted in the message being negatively acknowledged. As t
```suggestion
kafka.input.message.nacked.CWMRX1011E.explanation=A message that was sent by the Kafka connector caused a failure somewhere in the application, which resulted in the message being negatively acknowledged. As this message was not successfully processed, the committed offset is not advanced for the partition that the message came from. As a result, no more messages can be processed from this partition.
```

2023-10-06 13:35 UTC, dmuelle commented on dev/com.ibm.ws.microprofile.reactive.messaging.kafka/resources/com/ibm/ws/microprofile/reactive/messaging/kafka/resources/ReactiveMessaging.nlsprops
> +kafka.input.message.nacked.CWMRX1011E.useraction=Review the error message and the messages.log file on the server to identify the problem. If stopping processing of messages is not the desired behavi
```suggestion
kafka.input.message.nacked.CWMRX1011E.useraction=Review the error message and the messages.log file on the server to identify the problem. If you want to continue to process more messages from a partition after a message processing failure, add logic in your application that provides alternative handling of messages that are negatively-acknowledged.
```

2023-10-09 10:22 UTC, Azquelt commented
The code changes were merged under #26385.

The ID comments will be addressed under #26428

2023-10-09 10:22 UTC, closed without merging