Enable localConnector-1.0 for InstantOn
OpenLiberty/open-liberty pull request #26543
Opened 2023-10-09 17:10 UTC by tjwatson

2023-10-09 17:10 UTC, tjwatson commented
#build

2023-10-09 21:42 UTC, dazavala requested changes
Looking GTM except for that one copyright date.

2023-10-09 21:42 UTC, dazavala commented on dev/io.openliberty.checkpoint_fat/com.ibm.ws.jmx.fat.jmxtest.bnd
> +#*******************************************************************************
Update copyright year

2023-10-10 14:26 UTC, tjwatson commented
#build

2023-10-11 14:14 UTC, dazavala commented
#libby

2023-10-11 14:16 UTC, dazavala approved these changes
LGTM. Hailed libby for you.

2023-10-11 14:58 UTC, merged