Make quiesce timeout configurable
OpenLiberty/open-liberty pull request #26554
Opened 2023-10-10 19:25 UTC by jimblye

2023-10-16 22:43 UTC, jimblye commented
#build

2023-10-24 03:05 UTC, jimblye commented
#build

2023-10-24 14:45 UTC, hlhoots submitted a review, later dismissed
LGTM pending id review.

2023-10-24 15:15 UTC, dmuelle requested changes
ID review

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
> +\tquiesce stage, default 30 seconds, allows services to perform        \n\
```suggestion
\tquiesce stage, which is 30 seconds by default, allows services to perform        \n\
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
> +quiesce.begin.explanation=The server waits for services to quiesce before proceeding with shutdown.
```suggestion
quiesce.begin.explanation=The server waits for services to quiesce before it proceeds with shutdown.
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
> +quiece.warning.useraction=You can safely ignore error messages that are the result of unavailable required services. If the problem persists, increase the 'quiesceTimeout' period by adding 'quiesceTi
```suggestion
quiece.warning.useraction=You can safely ignore error messages that are the result of unavailable required services. If the problem persists, increase the 'quiesceTimeout' duration by adding 'quiesceTimeout' attribute to the 'executor' element in the 'server.xml' file.
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.runtime.update/resources/com/ibm/ws/runtime/update/internal/resources/Messages.nlsprops
> +client.quiesce.begin.explanation=The client waits for services to quiesce before proceeding with shutdown.
```suggestion
client.quiesce.begin.explanation=The client waits for services to quiesce before it proceeds with shutdown.
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/OSGI-INF/l10n/metatype.properties
> +quiesce.timeout.desc=The quiesce timeout is the amount of time the server allows services to perform pre-shutdown work; for example inbound listeners are stopped, but existing requests are allowed to
```suggestion
quiesce.timeout.desc=The quiesce timeout is the amount of time the server allows services to perform pre-shutdown work. For example, inbound listeners are stopped, but existing requests are allowed to complete.
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1205.start.timeout.useraction=No action is necessary if the application expects some tasks to abort due to exceeding their startTimeout. Otherwise, take any combination of the following actions:
```suggestion
CWWKE1205.start.timeout.useraction=No action is necessary if the application expects some tasks to abort because they exceed the startTimeout duration. Otherwise, take any combination of the following actions: increase the startTimeout duration, increase the maxConcurrency value.
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid=CWWKE1206W: The ''{0}'' value specified for the ''quiesceTimeout'' attribute on the ''executor'' element in ''server.xml'' is not valid.  The default value of 30 s
```suggestion
CWWKE1206.quiesce.timeout.not.valid=CWWKE1206W: The ''{0}'' value that is specified for the ''quiesceTimeout'' attribute on the ''executor'' element in the ''server.xml'' file is not valid.  The default value of 30 seconds is used instead.
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid=CWWKE1206W: The ''{0}'' value specified for the ''quiesceTimeout'' attribute on the ''executor'' element in ''server.xml'' is not valid.  The default value of 30 s
why the double-single quotes here? The other messages in this set use a single set of single quotes, while messages in other files here don't use any quotes at all. The syntax should be consistent within each file, and across all files if possible.

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid.explanation=The 'quiesceTimeout' value represents a time duration and accepts values in the format XmXs, where 'X' is replaced by a number,'m' represents minutes,
```suggestion
CWWKE1206.quiesce.timeout.not.valid.explanation=The 'quiesceTimeout' value specifies a duration and accepts values in the format XmXs, where 'X' is replaced by a number,'m' represents minutes, and 's' represents seconds.  The default value is '30s' (30 seconds). A value of '1m30s' represents 90 seconds.  
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid.useraction=Edit the 'server.xml' file and change the ''quiesceTimeout'' attribute on the ''executor'' element to a valid time duration.
see previous comment re quotation syntax

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
> +\tless than the quiesceTimeout value might cause the stop command to   \n\
```suggestion
\tless than the quiesceTimeout value might cause the server stop command to   \n\
```

2023-10-24 15:15 UTC, dmuelle commented on dev/com.ibm.ws.kernel.boot/resources/com/ibm/ws/kernel/boot/resources/LauncherOptions.nlsprops
> +\tcomplete with an error code before the server process has begun to   \n\
```suggestion
\tcomplete with an error code before the server process begins to   \n\
```

2023-10-24 15:19 UTC, cbridgha approved these changes, later dismissed
Looks good

2023-10-24 17:03 UTC, jimblye commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid=CWWKE1206W: The ''{0}'' value specified for the ''quiesceTimeout'' attribute on the ''executor'' element in ''server.xml'' is not valid.  The default value of 30 s
There's a comment in the top of the file that gives guidance about using quotes:
#   Strings in this file which contain replacement variables are processed by the MessageFormat 
#   class (single quote must be coded as 2 consecutive single quotes ''). Strings in this file 
#   which do NOT contain replacement variables are NOT processed by the MessageFormat class 
#   (single quote must be coded as one single quote ').

2023-10-24 17:05 UTC, jimblye commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid=CWWKE1206W: The ''{0}'' value specified for the ''quiesceTimeout'' attribute on the ''executor'' element in ''server.xml'' is not valid.  The default value of 30 s
The comment in the file starts with a hash symbol, which apparently GiHub translates into some sort of heading.  If you were wondering why all of the large bold case.

2023-10-24 19:41 UTC, jimblye commented
#build

2023-10-24 20:06 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid.useraction=Edit the 'server.xml' file and change the ''quiesceTimeout'' attribute on the ''executor'' element to a valid time duration.
this one has mixed syntax

2023-10-24 20:07 UTC, dmuelle commented on dev/com.ibm.ws.threading/resources/com/ibm/ws/threading/internal/resources/ThreadingMessages.nlsprops
> +CWWKE1206.quiesce.timeout.not.valid.useraction=Edit the 'server.xml' file and change the ''quiesceTimeout'' attribute on the ''executor'' element to a valid time duration.
```suggestion
CWWKE1206.quiesce.timeout.not.valid.useraction=Edit the 'server.xml' file and change the 'quiesceTimeout' attribute on the 'executor' element to a valid duration.
```

2023-10-24 20:21 UTC, dmuelle submitted a review, later dismissed
LGTM, thanks

2023-10-25 03:15 UTC, jimblye commented
#build

2023-10-25 12:51 UTC, cbridgha approved these changes
Looks good

2023-10-25 13:19 UTC, jimblye commented
#libby

2023-10-26 13:40 UTC, merged