ASM cleanup
OpenLiberty/open-liberty pull request #26874
Opened 2023-11-08 21:50 UTC by gjwatts

Found a few old ASM8 references that needed to be updated as well as a few places where we might be able to use the `io.openliberty.asm.ASMHelper` class to replace hardcoded ASM versions with a call to a static method to get the latest ASM version.

2023-11-09 00:13 UTC, gjwatts commented
#build

2023-12-01 19:14 UTC, gjwatts commented
#build

2023-12-15 18:45 UTC, jhanders34 requested changes

2023-12-15 18:45 UTC, jhanders34 commented on dev/com.ibm.ws.org.objectweb.asm/src/io/openliberty/asm/ASMHelper.java
> +                                                          // Values from https://docs.oracle.com/javase/specs/jvms/se20/html/jvms-4.html#jvms-4.1
```suggestion
    private static final int CURRENT_MAX_JAVA_LEVEL = Opcodes.V22; // Update this to show the maximum version of Java we can run with
```

2023-12-15 18:54 UTC, gjwatts commented
#build

2023-12-15 18:55 UTC, gjwatts commented
#libbybot

2023-12-15 19:01 UTC, gjwatts commented
Last force push was just to remove a comment, so no need to rebuild.

2023-12-15 19:04 UTC, jhanders34 approved these changes

2023-12-15 19:06 UTC, gjwatts commented
#libbybot

2023-12-15 19:08 UTC, gjwatts commented
After talking to Jared, the code change I made before the comment removal was technically the same value as after the change I made (66 vs Opcodes.V22 which is also 66), so the bytecode would be the exact same.  Merging.

2023-12-15 19:09 UTC, merged