Improving the messages for LTPA
OpenLiberty/open-liberty pull request #26897
Opened 2023-11-09 19:26 UTC by mshah0722

LTPA Message updates to: 
1. metatype.properties
2. LTPAMessages.nlsprops

2023-11-09 19:34 UTC, Zech-Hein requested changes

2023-11-09 19:34 UTC, Zech-Hein commented on dev/com.ibm.ws.security.token.ltpa/resources/com/ibm/ws/security/token/ltpa/internal/resources/LTPAMessages.nlsprops
>  LTPA_UPDATE_TRIGGER_DISABLED_AND_MONITOR_VALIDATION_KEYS_DIR_TRUE=CWWKS4114W: The updateTrigger attribute is set to disabled and the monitorValidationKeysDir attribute is set to true. No dynamic relo
```suggestion
LTPA_UPDATE_TRIGGER_DISABLED_AND_MONITOR_VALIDATION_KEYS_DIR_TRUE=CWWKS4114W: The updateTrigger attribute is set to disabled and the monitorValidationKeysDir attribute is set to true. No dynamic reload occurs when LTPA key files are modified in the directory.
```

2023-11-09 19:34 UTC, Zech-Hein commented on dev/com.ibm.ws.security.token.ltpa/resources/com/ibm/ws/security/token/ltpa/internal/resources/LTPAMessages.nlsprops
>  LTPA_UPDATE_TRIGGER_DISABLED_AND_MONITOR_VALIDATION_KEYS_DIR_TRUE.explanation=When the updateTrigger attribute is set to disabled, the directory is not monitored for any create, delete, or modify act
```suggestion
LTPA_UPDATE_TRIGGER_DISABLED_AND_MONITOR_VALIDATION_KEYS_DIR_TRUE.explanation=When the updateTrigger attribute is set to disabled, the directory is not monitored for any modifications to files with the .keys suffix and dynamic reload does not occur. Even if the monitorValidationKeysDir attribute is set to true, the attribute is ignored, and the directory is not monitored.

2023-11-09 21:27 UTC, mshah0722 commented
#libby
#build
#spawn.fullfat.buckets=com.ibm.ws.security.token.ltpa_fat

2023-11-10 13:44 UTC, posmith commented
L2 message review completed.

2023-11-10 14:06 UTC, Zech-Hein approved these changes
LGTM

2023-11-10 14:07 UTC, merged