FeatureUtility fix proxy and remote repo auth
OpenLiberty/open-liberty pull request #26900
Opened 2023-11-09 21:08 UTC by jjiwooLim

- Fixed proxy host format when read from featureUtility.properties. It should exclude protocol and only include host. 
- Added test cases using proxy and nexus remote repo (test containers)

2023-11-09 21:09 UTC, jjiwooLim commented
#build

2023-11-10 19:08 UTC, jacobwdv requested changes
Looks good, a few comments

2023-11-10 19:08 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +                } catch (IOException | InstallException e) {
is it OK to swallow the InstallException and IOException here? Should we not re-throw?

2023-11-10 19:08 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +    public static void addBasicAuthentication(URL address, URLConnection conn, MavenRepository repository) throws IOException, InstallException {
can we remove `URL address` from the signature? I don't think it's used.

2023-11-10 19:08 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility/src/com/ibm/ws/install/featureUtility/FeatureUtility.java
> +			    // If protocol is not defined, assume http protocol.
it would be good to log the exception here even if we intend to ignore the result

2023-11-10 19:08 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
> +		  ExecResult lsResult = proxyContainer.execInContainer("cat", "/var/log/squid/access.log");
log the exception here even though we will ignore it.

2023-11-10 19:08 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
> +		  ExecResult lsResult = proxyContainer.execInContainer("cat", "/var/log/squid/access.log");
log the exception

2023-11-10 19:08 UTC, jacobwdv commented on dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallFeatureTest.java
> +		ExecResult lsResult = proxyContainer.execInContainer("cat", "/var/log/squid/access.log");
This code seems to be reused repeatedly, maybe create a method and add the exception tracing i've suggested in there

2023-11-14 03:47 UTC, jjiwooLim commented
#build

2023-11-16 20:07 UTC, jjiwooLim commented
#libby-bot

2023-11-17 15:16 UTC, jacobwdv requested changes

2023-11-17 15:16 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +            return pwd;
remove this return and use the one at the end of the method.

2023-11-17 15:16 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +        if (!pwd.startsWith("{")) {
what if the password actually starts with `{`?

We should just exhaustively check for each valid string at the start such as `{xor}`. 
It's still not perfect becuase I guess our users could have a password that starts with `{xor}` too but it's less likely i think.

2023-11-17 15:24 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +        if (!pwd.startsWith("{")) {
Also, i think if users hav ea password that happens to start with {xor} then liberty was never working for them to begin with

2023-11-20 18:22 UTC, jjiwooLim commented
#build

2023-11-22 06:41 UTC, jjiwooLim commented
#build

2023-11-23 15:48 UTC, jjiwooLim commented
#libby-bot

2023-11-23 15:49 UTC, jjiwooLim commented
Test failures not related to my changes

2024-03-21 18:19 UTC, jjiwooLim commented
Merged by https://github.com/OpenLiberty/open-liberty/pull/27110

2024-03-21 18:19 UTC, closed without merging