Create jakarta servlet 6.1 project
OpenLiberty/open-liberty pull request #27013
Opened 2023-11-21 20:50 UTC by pmd1nh

io.openliberty.jakarta.servlet.6.1

2023-11-21 20:54 UTC, pmd1nh commented
Note to self: When M1 is available, update the version accordingly:

dev/com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.1.feature
dev/wlp-jakartaee-transform/rules/jakarta-versions.properties

2023-11-21 21:13 UTC, pmd1nh commented
#build

2023-11-22 17:28 UTC, pmd1nh commented
ant_schemaValidator unittests	
	
	
com.ibm.ws.config.internal.featureListChecker.FeatureListValidatorTest
	
missingAPIJar0



junit.framework.AssertionFailedError: The api jar /home/jazz_build/Build/jbe/build/WS-CD-Open/dev/build.image/wlp/dev/api/spec/io.openliberty.jakarta.servlet.6.1_1.0.84.jar is not included in or mentioned by any feature.
	at com.ibm.ws.config.internal.featureListChecker.Issue.newFailure(Issue.java:47)
	at com.ibm.ws.config.internal.featureListChecker.FeatureListValidator.matchJars(FeatureListValidator.java:421)
	at com.ibm.ws.config.internal.featureListChecker.FeatureListValidator.matchJars(FeatureListValidator.java:423)
	at com.ibm.ws.config.internal.featureListChecker.FeatureListValidator.suite(FeatureListValidator.java:193)
	at com.ibm.ws.config.internal.featureListChecker.FeatureListValidator.<init>(FeatureListValidator.java:59)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

2023-11-27 17:57 UTC, pnicolucci commented
@pmd1nh  the Servlet 6.1 API jar is now available out on Maven central: https://central.sonatype.com/artifact/jakarta.servlet/jakarta.servlet-api/versions lets use this for this PR. Also if we don't expect to have overlays for the Servlet API it should be created here: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta/README.txt to try and cut down on the API projects when possible.

2023-11-27 19:31 UTC, pmd1nh commented
M1 jakarta.servlet is uploaded 
https://na.artifactory.swg-devops.com/ui/repos/tree/General/wasliberty-open-liberty/jakarta/servlet/jakarta.servlet-api/6.1.0-M1/jakarta.servlet-api-6.1.0-M1.jar

2023-11-27 21:12 UTC, pmd1nh commented
. removed io.openliberty.jakarta.servlet.6.1 folder
. created dev/io.openliberty.jakarta/servlet.6.1.bnd instead.

2023-11-27 21:13 UTC, pmd1nh commented
#build

2023-11-27 22:02 UTC, pmd1nh commented
Updated com.ibm.websphere.appserver.features/visibility/private/io.openliberty.servlet.api-6.1.feature

2023-11-27 22:03 UTC, pmd1nh commented
cancelled previous build

#build

2023-11-27 22:05 UTC, pmd1nh commented
What to do with 

dev/wlp-jakartaee-transform/rules/jakarta-versions.properties
and 
jakarta-versions-ee11.properties

2023-11-27 22:14 UTC, jhanders34 requested changes

2023-11-27 22:14 UTC, jhanders34 commented on dev/io.openliberty.jakarta/servlet.6.1.bnd
> +Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=17))"
```suggestion
Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=21))"
```

2023-11-27 22:14 UTC, jhanders34 commented on dev/io.openliberty.jakarta/servlet.6.1.bnd
> +   dep1;groupId=jakarta.servlet;artifactId=jakarta.servlet-api;version=6.1.0;scope=runtime
Should this say M1 since that is the actual maven dependency?

2023-11-27 22:14 UTC, jhanders34 commented on dev/io.openliberty.jakarta/servlet.6.1.bnd
> +  @${repo;jakarta.servlet:jakarta.servlet-api;6.1.0;EXACT}!/!(META-INF/maven/*|module-info.class)
Not sure how this is working without the update to `cnf/oss_dependencies.maven` update.

2023-11-28 04:04 UTC, pmd1nh commented
#build

2023-11-28 14:18 UTC, jhanders34 commented on dev/io.openliberty.jakarta/servlet.6.1.bnd
> +   dep1;groupId=jakarta.servlet;artifactId=jakarta.servlet-api;version=6.1.0.M1;scope=runtime
```suggestion
   dep1;groupId=jakarta.servlet;artifactId=jakarta.servlet-api;version=6.1.0-M1;scope=runtime
```
I believe this needs to be the maven coordinates, not the bundle coordinates.

2023-11-28 14:33 UTC, pnicolucci commented
> @pmd1nh the Servlet 6.1 API jar is now available out on Maven central: https://central.sonatype.com/artifact/jakarta.servlet/jakarta.servlet-api/versions lets use this for this PR. Also if we don't expect to have overlays for the Servlet API it should be created here: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/io.openliberty.jakarta/README.txt to try and cut down on the API projects when possible.

@pmd1nh I was just looking at the previous servlet projects and it looks like we do have overlays: https://github.com/OpenLiberty/open-liberty/tree/integration/dev/io.openliberty.jakarta.servlet.6.0/src/jakarta/servlet/resources it looks like there are a few resources that were not included in the Jakarta API that we need still. We'll want to somehow ensure that we do the same for EE11 either with our own API project or maybe a shared project that we can pull these resources from so we're not copying them into each project?

2023-11-28 18:53 UTC, pmd1nh commented
add resources for servlet-6.1 @pnicolucci 

#build

2023-11-28 20:55 UTC, jhanders34 approved these changes

2023-11-29 14:04 UTC, pmd1nh commented
#libby

2023-11-29 14:07 UTC, merged