fix JAX-RS SSL ciphers test config
OpenLiberty/open-liberty pull request #27066
Opened 2023-11-29 19:43 UTC by WhiteCat22

Fixing the test config for `MatchingSSLCiphersTest` and `MisMatchingSSLCiphersTest` in the `com.ibm.ws.jaxrs.2.0.client_fat` bucket.

2023-11-29 19:44 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.MisMatchingSSLCiphersTest/server.xml
> -        enabledCiphers=" TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA256 TLS_ECDH_RSA_WITH_AES_128_CBC_SHA256"/>
This space is the problem and causes errors from SSL.

Basically, SSL throws an exception because it splits the ciphers on ` ` and ends up with an invalid cipher of "".

2023-11-29 19:44 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/publish/servers/com.ibm.ws.jaxrs.2.0.client.fat.MatchingSSLCiphersTest/server.xml
> +    <quickStartSecurity userName="test" userPassword="testpwd" />
This is needed or the Security Service never starts.

2023-11-29 20:03 UTC, neuwerk approved these changes
Changes look good to me!

2023-11-29 20:03 UTC, neuwerk commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/test/MatchingSSLCiphersTest.java
> + *
Add that copyright update `2022, 2023`

2023-11-29 20:03 UTC, neuwerk requested changes
Looks like all the files need the copyright header update for 2023

2023-11-29 22:05 UTC, neuwerk approved these changes, later dismissed

2023-11-29 22:10 UTC, jim-krueger approved these changes, later dismissed
LGTM

2023-11-30 15:59 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0.client_fat

2023-12-05 22:52 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0.client_fat

2023-12-06 18:05 UTC, neuwerk approved these changes
LGTM!

2023-12-06 18:20 UTC, merged