Upgrade jackson 1x separate jsonsupport bundle
OpenLiberty/open-liberty pull request #27112
Opened 2023-12-07 17:27 UTC by WhiteCat22

OpenLiberty Pull Requester,

ATTENTION, READ THIS: Updated 4/11/2018 - Read and understand this completely,
then delete this entire template. If a reviewer or merger sees this template,
they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue mentioned in the PR text or description. That Issue also
MUST be labelled “release bug”

This directs automation to scrape this fix for inclusion in the next release's
list of bugs fixed.

If this code is NOT for fixing a released bug, for example new function, fixing
a bug in unreleased function, or other improvements that do not affect the
user-space, no label is needed. An issue could or could not be used based
on the developer’s discretion, but do still delete this text block.

For full details, please see this wiki page:

https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions

2023-12-07 20:43 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jmx.connector.server.rest_bvt,com.ibm.ws.microprofile.health_fat,com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,com.ibm.ws.ui_rest_fat,io.openliberty.microprofile.health.3.0.internal_fat,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.1.internal_fat,io.openliberty.microprofile.health.3.1.internal_fat_tck,com.ibm.ws.collective.plugins_test,com.ibm.ws.collective.rest_fat,com.ibm.ws.collective.rest.notify_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs,com.ibm.ws.install.utility_offline_fat,com.ibm.ws.jaxrs_fat

2023-12-08 16:50 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jmx.connector.server.rest_bvt,com.ibm.ws.microprofile.health_fat,com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,com.ibm.ws.ui_rest_fat,io.openliberty.microprofile.health.3.0.internal_fat,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.1.internal_fat,io.openliberty.microprofile.health.3.1.internal_fat_tck,com.ibm.ws.collective.plugins_test,com.ibm.ws.collective.rest_fat,com.ibm.ws.collective.rest.notify_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs,com.ibm.ws.install.utility_offline_fat,com.ibm.ws.jaxrs_fat

2023-12-11 16:19 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.microprofile.health_fat,com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,com.ibm.ws.ui_rest_fat,io.openliberty.microprofile.health.3.0.internal_fat,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.1.internal_fat,io.openliberty.microprofile.health.3.1.internal_fat_tck,com.ibm.ws.collective.plugins_test,com.ibm.ws.collective.rest_fat,com.ibm.ws.collective.rest.notify_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs,com.ibm.ws.install.utility_offline_fat,com.ibm.ws.jaxrs_fat

2023-12-12 16:47 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.microprofile.health_fat,com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,com.ibm.ws.ui_rest_fat,io.openliberty.microprofile.health.3.0.internal_fat,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.1.internal_fat,io.openliberty.microprofile.health.3.1.internal_fat_tck,com.ibm.ws.collective.plugins_test,com.ibm.ws.collective.rest_fat,com.ibm.ws.collective.rest.notify_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs,com.ibm.ws.install.utility_offline_fat,com.ibm.ws.jaxrs_fat

2023-12-12 19:41 UTC, posmith commented
Support message review completed

2023-12-19 19:18 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jmx.connector.server.rest_bvt,com.ibm.ws.microprofile.health_fat,com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,com.ibm.ws.ui_rest_fat,io.openliberty.microprofile.health.3.0.internal_fat,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.1.internal_fat,io.openliberty.microprofile.health.3.1.internal_fat_tck,com.ibm.ws.collective.plugins_test,com.ibm.ws.collective.rest_fat,com.ibm.ws.collective.rest.notify_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs,com.ibm.ws.install.utility_offline_fat,com.ibm.ws.jaxrs_fat

2023-12-20 16:02 UTC, neuwerk requested changes
Just need to modify the copyright for files in the new bundle.

2023-12-20 16:02 UTC, neuwerk commented on dev/io.openliberty.jsonsupport.internal/resources/com/ibm/websphere/jsonsupport/resources/JSONSupportMessages.nlsprops
> +# Copyright (c) 2015 IBM Corporation and others.
since this is technically "new", do you need to update the copyright?

2023-12-20 16:02 UTC, neuwerk commented on dev/io.openliberty.jsonsupport.internal/resources/com/ibm/websphere/jsonsupport/resources/JSONSupportMessages_zh_TW.nlsprops
> +# Contributors:
Also, if this is "new" then you'll want to remove the contributors part of the header.

2023-12-20 21:19 UTC, WhiteCat22 commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.microprofile.health_fat,com.ibm.ws.microprofile.health.2.0_fat,com.ibm.ws.microprofile.health.2.0_fat_tck,com.ibm.ws.ui_rest_fat,io.openliberty.microprofile.health.3.0.internal_fat,io.openliberty.microprofile.health.3.0.internal_fat_tck,io.openliberty.microprofile.health.3.1.internal_fat,io.openliberty.microprofile.health.3.1.internal_fat_tck,com.ibm.ws.collective.rest_fat,com.ibm.ws.collective.rest.notify_fat,com.ibm.ws.ui.collective_fat,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.liberty,com.ibm.ws.ui.tool.deploy_fat.gui.nd.rw.nodejs,com.ibm.ws.install.utility_offline_fat,com.ibm.ws.jaxrs_fat

2023-12-20 21:30 UTC, neuwerk approved these changes

2023-12-20 22:30 UTC, jim-krueger approved these changes

2023-12-21 17:30 UTC, merged