Telemetry: Adding in new test for JAX-RS annotated with withSpan
OpenLiberty/open-liberty pull request #27139
Opened 2023-12-11 16:07 UTC by jakub-pomykala

fixes #27111

2023-12-11 16:09 UTC, jakub-pomykala commented
#build

2023-12-11 16:12 UTC, yasmin-aumeeruddy approved these changes, later dismissed
Looks good

2023-12-11 16:12 UTC, jakub-pomykala commented
#build

2023-12-12 10:24 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
> +        assertNotNull(Span.current());
`Span.current()` will never return `null`

2023-12-12 10:29 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
> +        List<SpanData> spanData = spanExporter.getFinishedSpanItems(2, traceId);
Note that this class is not a test servlet so it doesn't nicely report errors and you have to go fishing in the log to find out what broke.

In future, don't add more tests to this class.

2023-12-12 10:30 UTC, Azquelt commented on dev/io.openliberty.microprofile.telemetry.1.0.internal_fat/fat/src/io/openliberty/microprofile/telemetry/internal_fat/apps/jaxrspropagation/JaxRsEndpoints.java
> +        assertEquals("http", firstURL.getAttributes().get(HTTP_SCHEME));
Use `SpanDataMatcher` instead of asserting individual attributes.

2023-12-12 10:31 UTC, Azquelt requested changes
Suggested several improvements. Also you need to update the commit message.

2023-12-12 14:02 UTC, Azquelt approved these changes
Looks good, thank you

2023-12-12 14:02 UTC, jakub-pomykala commented
#build

2023-12-13 09:32 UTC, jakub-pomykala commented
#libby

2023-12-13 09:37 UTC, yasmin-aumeeruddy approved these changes

2023-12-13 09:38 UTC, merged