Expand selenium OpenAPI UI tests
OpenLiberty/open-liberty pull request #27167
Opened 2023-12-13 14:51 UTC by ryan-storey

Expanding our OpenAPI UI selenium tests for mpOpenApi and public and private versions to reduce manual testing

2023-12-20 13:49 UTC, ryan-storey commented
#libby #build

2024-01-03 13:31 UTC, ryan-storey commented
#libby #build

2024-01-03 13:35 UTC, abutch3r commented on dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/tests/UIBasicTest.java
> +        System.out.println(headerbar.getAttribute("innerHTML"));
remove debug statement

2024-01-03 13:39 UTC, ryan-storey commented on dev/com.ibm.ws.openapi.ui_fat/fat/src/com/ibm/ws/openapi/ui/fat/tests/UIBasicTest.java
> +        System.out.println(headerbar.getAttribute("innerHTML"));
Completely missed that, thank you

2024-01-04 15:25 UTC, ryan-storey commented
#libby #build

2024-01-05 12:43 UTC, ryan-storey commented
#libby #build

2024-01-08 10:38 UTC, ryan-storey commented
#libby #build

2024-01-09 09:52 UTC, ryan-storey commented
#pbbeta

2024-01-10 10:28 UTC, abutch3r requested changes
The three bundle files need to be removed before this can be merged - i suspect there is a commit that hasn't been applied properly that would of removed these three files. 

The rest of the changes look good and ready to go.

2024-01-10 15:39 UTC, ryan-storey commented
#libby #build

2024-01-10 15:40 UTC, ryan-storey commented
#pbbeta

2024-01-11 14:10 UTC, abutch3r approved these changes
LGTM

2024-01-12 10:26 UTC, merged