JAX-WS: Add PartInfoNamespaceCorrectionTest for fixes to CXF's SoapBindingFactory
OpenLiberty/open-liberty pull request #27225
Opened 2023-12-27 19:54 UTC by neuwerk

This PR adds the following test `PartInfoNamespaceCorrectionTest` to the `com.ibm.ws.jaxws.2.2.webcontainer_fat` bucket.

2023-12-27 20:01 UTC, neuwerk commented
#build

2023-12-27 20:50 UTC, WhiteCat22 requested changes
I did a sweep of the namespace URLs and I didn't notice anything troublesome

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/servlet/PartInfoNamespaceCorrectionTestServlet.java
> +            // TODO Auto-generated catch block
auto generated comment

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainservice/CustomFaultDetail.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/importedserviceschema/PersonType.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/importedserviceschema/ObjectFactory.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/importedserviceschema/CustomHeaderType.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/importedserviceschema/CustomFaultType.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainservice/NameSpaceCheckPortType.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainservice/NameSpaceCheckService.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainservice/NameSpaceCheckService_NameSpaceCheckServicePortHttpImpl.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainserviceschema/DummyObjectTYPE.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainserviceschema/NameSpaceCheckMessage.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainserviceschema/NameSpaceCheckResponseMessage.java
> +
copyright header

2023-12-27 20:50 UTC, WhiteCat22 commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/namespaceCheck/src/com/ibm/ws/jaxws/namespacecheck/wsdl/mainserviceschema/ObjectFactory.java
> +
copyright header

2023-12-28 21:19 UTC, WhiteCat22 approved these changes

2023-12-28 22:52 UTC, neuwerk commented
#libby

2023-12-28 22:52 UTC, merged