Resolving NPE and adding a unit test to confirm expected behavior
OpenLiberty/open-liberty pull request #27259
Opened 2024-01-03 17:45 UTC by mshah0722

Resolving the Null Pointer Exception brought up in #27249

2024-01-03 17:51 UTC, Zech-Hein commented on dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
>              decoded_string = passwordDecode(decoded_string);
It is better performance to put the check before the passwordDecode

2024-01-03 20:32 UTC, mshah0722 commented
#libby
#build

2024-01-04 14:44 UTC, utle reviewed
You need to update the copyright to 2024.

2024-01-04 15:00 UTC, Zech-Hein requested changes

2024-01-04 15:00 UTC, Zech-Hein commented on dev/com.ibm.ws.crypto.passwordutil/src/com/ibm/websphere/crypto/PasswordUtil.java
> +                if (current_crypto_algorithm.contains("{") && current_crypto_algorithm.contains("}")){
```suggestion
                // The {<crypto algorithm>} tag must start at the beginning of the password(decoded_string) string
                if (current_crypto_algorithm.indexOf('{') == 0 && current_crypto_algorithm.indexOf('}') > 0){
```

2024-01-04 16:42 UTC, mshah0722 commented
#libby
#build

2024-01-04 19:53 UTC, bmarwell approved these changes
LGTM, exactly the change I had in mind! Thanks for bringing this up!

2024-01-05 17:47 UTC, mshah0722 commented
#libby
#build

2024-01-05 17:50 UTC, Zech-Hein approved these changes

2024-01-06 19:30 UTC, merged

2024-04-09 17:52 UTC, Zech-Hein commented
Fixes #PH59416