Test buckets added for Jakarta Persistence API 3.2 - M1
OpenLiberty/open-liberty pull request #27296
Opened 2024-01-08 09:18 UTC by ajaypaul-ibm

Test buckets added for Jakarta Persistence API 3.2 M1

2024-01-09 05:34 UTC, ajaypaul-ibm commented
for #27273

2024-01-09 05:34 UTC, ajaypaul-ibm commented
#libby
#build

2024-01-10 11:09 UTC, ajaypaul-ibm commented
#libby
#build

2024-01-11 14:14 UTC, ajaypaul-ibm commented
#libby
#build

2024-01-12 07:28 UTC, ajaypaul-ibm commented
#libby

2024-01-12 07:28 UTC, ajaypaul-ibm commented
#build

2024-01-16 06:28 UTC, ajaypaul-ibm commented
#libby

2024-01-16 06:29 UTC, ajaypaul-ibm commented
#build

2024-01-16 16:33 UTC, tkburroughs requested changes
Looking good; though some minor things to fix:
- Copyright year(s) for new files should be 2024, for modified files should be first ship year followed by 2024.
- org.eclipse.jdt.core.prefs files should all have targetPlatform, compliance, and source set to 21 instead of 11.
- ValidateJPAFeatureTest.java needs to be deleted/removed from the pull request, and instead the file by the same name in the "commons" project should be updated.  (The .gitignore file is supposed to prevent this from happening, but it looks like that was overriden).

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
Should be 21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
Should be 21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
Should be 21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2023 IBM Corporation and others.
Should be 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestAggregateLogic.java
> +            if (isUsingJPA31Feature() || isUsingJPA32Feature()) {
Copyright at top of file should be "2022, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestArithmeticLogic.java
> + *
Copyright should be "2022, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestComparisonLogic.java
> + *
Copyright should be "2022, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestFunctionLogic.java
> +            if (isUsingJPA31Feature() || isUsingJPA32Feature()) {
Copyright at top should be "2022, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestUpdateLogic.java
> +            if (isUsingJPA31Feature() || isUsingJPA32Feature()) {
Copyright at top should be "2022, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat/bnd.bnd
> +# Copyright (c) 2022 IBM Corporation and others.
Should be 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2022 IBM Corporation and others.
2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh8014/src/com/ibm/ws/jpa/olgh8014/testlogic/JPATestOLGH8014Logic.java
> +        if ((isUsingJPA30Feature() || isUsingJPA31Feature() || isUsingJPA32Feature())) {
Copyright at top should be "2019, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2022 IBM Corporation and others.
2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpaconfig_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2022 IBM Corporation and others.
2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.callback_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
Since new file, just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2023 IBM Corporation and others.
2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2022 IBM Corporation and others.
2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
Since new file, just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
Since new file, just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
Since new file, just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2022 IBM Corporation and others.
Since new file, just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.query_jpa_3.2_fat/fat/src/com/ibm/ws/jpa/tests/spec10/query/FATSuite.java
> + * Copyright (c) 2019, 2024 IBM Corporation and others.
Since new file, just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2019, 2021 IBM Corporation and others.
Just 2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
21

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2022 IBM Corporation and others.
2024

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/testlogic/AbstractTestLogic.java
> + *
Copyright should be "2020, 2024"

2024-01-16 16:33 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/fat/src/com/ibm/ws/jpa/tests/spec20/tests/ValidateJPAFeatureTest.java
> +/*******************************************************************************
Please delete this file / remove from the pull request.  Instead, update the file in the common project.
Copyright in the updated file in the commons project would be 2022, 2024.

2024-01-17 06:59 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
Resolved 👍

2024-01-17 06:59 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
Resolved 👍

2024-01-17 06:59 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
Resolved 👍

2024-01-17 06:59 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2023 IBM Corporation and others.
Resolved 👍

2024-01-17 07:00 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_fat.common/test-applications/olgh17837/src/com/ibm/ws/jpa/olgh17837/testlogic/TestAggregateLogic.java
> +            if (isUsingJPA31Feature() || isUsingJPA32Feature()) {
Resolved 👍

2024-01-17 07:08 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.compliance=11
Resolved 👍

2024-01-17 07:08 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/.settings/org.eclipse.jdt.core.prefs
> +org.eclipse.jdt.core.compiler.source=11
Resolved 👍

2024-01-17 07:08 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/build.gradle
> + * Copyright (c) 2022 IBM Corporation and others.
Resolved 👍

2024-01-17 07:08 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa_testframework/src/com/ibm/ws/testtooling/testlogic/AbstractTestLogic.java
> + *
Resolved 👍

2024-01-17 08:19 UTC, ajaypaul-ibm commented
#libby

2024-01-17 08:27 UTC, ajaypaul-ibm commented
#build

2024-01-17 22:08 UTC, tkburroughs requested changes
Still a few files (in common projects) that need copyright updated.

- Also due to change in direction for Jakarta EE 11, evertything needs to be moved to Java 17 instead of Java 21.  See the following PR which has already been merged : https://github.com/OpenLiberty/open-liberty/pull/27335

2024-01-17 22:08 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh8294/src/com/ibm/ws/jpa/olgh8294/testlogic/JPATestOLGH8294Logic.java
> +                    if (isUsingJPA31Feature() || isUsingJPA32Feature()) {
Copyright at top should be "2019, 2024"

2024-01-18 07:06 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.eclipselink_fat.common/test-applications/olgh8294/src/com/ibm/ws/jpa/olgh8294/testlogic/JPATestOLGH8294Logic.java
> +                    if (isUsingJPA31Feature() || isUsingJPA32Feature()) {
Resolved in common projects

2024-01-18 07:07 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.spec20_jpa_3.2_fat/fat/src/com/ibm/ws/jpa/tests/spec20/tests/ValidateJPAFeatureTest.java
> +/*******************************************************************************
Updated the copyright header in common projects

2024-01-18 07:08 UTC, ajaypaul-ibm commented
#libby

2024-01-18 07:10 UTC, ajaypaul-ibm commented
#build

2024-01-19 04:20 UTC, ajaypaul-ibm commented
#libby
#build

2024-01-19 04:27 UTC, ajaypaul-ibm commented
#libby

2024-01-19 04:30 UTC, ajaypaul-ibm commented
#libby

2024-01-19 05:20 UTC, tkburroughs approved these changes

2024-01-19 05:21 UTC, tkburroughs commented
One test failure is a know intermittent; ready to merge.

2024-01-19 05:21 UTC, merged