Re-introduce: update metatype name and desc for back-channel logout
OpenLiberty/open-liberty pull request #27324
Opened 2024-01-10 15:55 UTC by jimmy1wu

Reverts OpenLiberty/open-liberty#27300 for #27301

2024-01-10 20:53 UTC, jimmy1wu commented
#build

2024-01-10 21:32 UTC, dmuelle requested changes, later dismissed
ID review- minor edit suggestion

2024-01-10 21:32 UTC, dmuelle commented on dev/com.ibm.ws.security.openidconnect.server/resources/OSGI-INF/l10n/metatype.properties
> +backchannelLogoutRequestTimeout.desc=Specifies the amount of time after which a back-channel logout request to an OpenID Connect client times out.
```suggestion
backchannelLogoutRequestTimeout.desc=Specifies the amount of time before a back-channel logout request to an OpenID Connect client times out.
```

2024-01-11 03:20 UTC, jimmy1wu commented
#build

2024-01-11 19:13 UTC, jimmy1wu commented
#build

2024-01-11 19:26 UTC, ayoho approved these changes

2024-01-15 17:13 UTC, jimmy1wu commented
#libby

2024-01-15 17:14 UTC, jimmy1wu commented
it has already been ID reviewed

2024-01-15 17:14 UTC, merged