JAX-WS: Testing soap response encoding
OpenLiberty/open-liberty pull request #27347
Opened 2024-01-12 01:22 UTC by BerksanAtes

Fixes #27298

2024-01-12 01:22 UTC, BerksanAtes commented
#build

2024-01-12 17:04 UTC, neuwerk requested changes
Just a few suggestions.

2024-01-12 17:04 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/fat/src/com/ibm/ws/jaxws/fat/EncodingTest.java
> + * The purpose of this test is to check default encoding of
```suggestion
 * The purpose of this test is to check the encoding we set in the Response's HTTP Headers
```

2024-01-12 17:04 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat_extended/test-applications/encodingTest/src/com/ibm/ws/jaxws/test/wsr/test/servlet/EncodingHttpTestServlet.java
> +public class EncodingHttpTestServlet extends HttpServlet {
To following a convetion we've been using, could we rename the servlet to just be `junit test class name + servlet`?

```suggestion
public class EncodingTestServlet extends HttpServlet {
```

2024-01-12 18:07 UTC, BerksanAtes commented
#build

2024-01-16 14:50 UTC, neuwerk approved these changes

2024-01-16 15:03 UTC, BerksanAtes commented
#run-libby-bot

2024-01-16 15:07 UTC, merged