Using configAdmin to find undetected apps for mpHealth
OpenLiberty/open-liberty pull request #27360
Opened 2024-01-15 01:30 UTC by tonyreigns

2024-01-15 01:30 UTC, tonyreigns commented
#build

2024-01-15 19:11 UTC, tonyreigns commented
#build

2024-01-16 14:36 UTC, tonyreigns commented
#build

2024-01-17 21:04 UTC, tonyreigns commented
#build

2024-01-24 21:51 UTC, wraschke commented
#libby

2024-01-27 05:44 UTC, tonyreigns commented
#build

2024-01-30 01:01 UTC, tonyreigns commented
#build

2024-02-06 20:07 UTC, tonyreigns commented
#build

2024-02-12 16:54 UTC, tonyreigns commented
#build

2024-02-12 20:22 UTC, pgunapal requested changes
The code changes looks good, minor comments. 
A few suggestions for the tests:
- It would be good the first feature the tests run on would be mpHealth-3.x and then repeat it for the older versions.
- For the FailsToStartApp, is there a way to make the app more simpler, instead of using Kafka and importing all the deps?

2024-02-12 20:22 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
> +                    Tr.debug(tc, "In performHealthCheck(): configAdmin found an application that appTracker already found. configAdminAppName = " + nextAppName);
```suggestion
                    Tr.debug(tc, "In performHealthCheck(): configAdmin found an application that the applicationStateListener already found. configAdminAppName = " + nextAppName);
```

2024-02-12 20:22 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health.2.0/src/com/ibm/ws/microprofile/health20/internal/HealthCheck20ServiceImpl.java
> +                    Tr.debug(tc, "In performHealthCheck(): appTracker couldn't find application. configAdmin added appName = " + nextAppName);
```suggestion
                    Tr.debug(tc, "In performHealthCheck(): applicationStateListener couldn't find application. configAdmin added appName = " + nextAppName);
```

2024-02-12 20:22 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
> +                        //testMap.put((String) properties.get("name"), "test");
Is this needed?

2024-02-12 20:22 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
> +            e.printStackTrace();
Adding debug trace messages here would be more comprehensive, in addition to the stacktrace.

2024-02-12 20:22 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
> +            e.printStackTrace();
Adding debug trace messages here would be more comprehensive, in addition to the stacktrace.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30ServiceImpl.java
> +                    Tr.debug(tc, "In performHealthCheck(): configAdmin found an application that appTracker already found. configAdminAppName = " + nextAppName);
```suggestion
                    Tr.debug(tc, "In performHealthCheck(): configAdmin found an application that applicationStateListener already found. configAdminAppName = " + nextAppName);
```

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.0.internal/src/io/openliberty/microprofile/health30/internal/HealthCheck30ServiceImpl.java
> +                    Tr.debug(tc, "In performHealthCheck(): appTracker couldn't find application. configAdmin added appName = " + nextAppName);
```suggestion
                    Tr.debug(tc, "In performHealthCheck(): applicationStateListener couldn't find application. configAdmin added appName = " + nextAppName);
```

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/HealthCheck31ServiceImpl.java
> +                    Tr.debug(tc, "In performHealthCheck(): configAdmin found an application that appTracker already found. configAdminAppName = " + nextAppName);
```suggestion
                    Tr.debug(tc, "In performHealthCheck(): configAdmin found an application that applicationStateListener already found. configAdminAppName = " + nextAppName);
```

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal/src/io/openliberty/microprofile/health31/internal/HealthCheck31ServiceImpl.java
> +                    Tr.debug(tc, "In performHealthCheck(): appTracker couldn't find application. configAdmin added appName = " + nextAppName);
```suggestion
                    Tr.debug(tc, "In performHealthCheck(): applicationStateListener couldn't find application. configAdmin added appName = " + nextAppName);
```

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
> +	com.ibm.websphere.org.eclipse.microprofile.health.2.0;version=latest, \
Is this required?

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
> +    com.ibm.websphere.org.eclipse.microprofile.config.1.3;version=latest,\
Is this required?

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +//import org.testcontainers.containers.KafkaContainer;
is this line needed?

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    private final String HEALTH_ENDPOINT = "/health";
Need to test `/health/started' endpoint as well.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +        LIVE, READY, HEALTH;
Need to have STARTED, as well.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    public void testMatchingAppNamesDropinsTest() throws Exception {
Would be good if each test method had comments on what each test case tests for.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    @SkipForRepeat({ "mpHealth-3.0", "mpHealth-3.1" })
Since, these tests are in the MP Health 3.1 bucket, it would make sense for the tests to be skipped for mpHealth > 3.0, instead.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    @SkipForRepeat({ "mpHealth-3.0", "mpHealth-3.1" })
Since, these tests are in the MP Health 3.1 bucket, it would make sense for the tests to be skipped for mpHealth > 3.0, instead.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    @SkipForRepeat({ "mpHealth-3.0", "mpHealth-3.1" })
Since, these tests are in the MP Health 3.1 bucket, it would make sense for the tests to be skipped for mpHealth > 3.0, instead.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    @SkipForRepeat({ "mpHealth-3.0", "mpHealth-3.1" })
Since, these tests are in the MP Health 3.1 bucket, it would make sense for the tests to be skipped for mpHealth > 3.0, instead.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +        expectHealthCheck(server3, HealthCheck.HEALTH, Status.FAILURE, 0);
Need to test STARTED as well.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    @SkipForRepeat({ "mpHealth-3.0", "mpHealth-3.1" })
Since, these tests are in the MP Health 3.1 bucket, it would make sense for the tests to be skipped for mpHealth > 3.0, instead.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +                } else {
Need to test for STARTED.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    public void testReadinessEndpointOnServerStart() throws Exception {
I don't think this test is necessary. We already have an existing test case in the same bucket here: `SlowAppStartupHealthCheckTest.testStartupEndpointOnServerStart()`

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminDropinsCheck/server.xml
> +        <feature>mpHealth-2.0</feature>
the server.xml should be update to use mpHealth-3.1 feature, and then make sure some of the tests are repeated for the older feature versions.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminWrongAppCheck/server.xml
> +        <feature>mpHealth-2.0</feature>
the server.xml should be update to use mpHealth-3.1 feature, and then make sure some of the tests are repeated for the older feature versions.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/ConfigAdminXmlCheck/server.xml
> +        <feature>mpHealth-2.0</feature>
the server.xml should be update to use mpHealth-3.1 feature, and then make sure some of the tests are repeated for the older feature versions.

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminDropinsCheckApp/src/io/openliberty/microprofile/health31/config/admin/dropins/checks/app/TestLivenessCheck.java
> + * Copyright (c) 2020 IBM Corporation and others.
update copyright year

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminDropinsCheckApp/src/io/openliberty/microprofile/health31/config/admin/dropins/checks/app/TestReadinessCheck.java
> + * Copyright (c) 2020 IBM Corporation and others.
update copyright year

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminXmlCheckApp/src/io/openliberty/microprofile/health31/config/admin/xml/checks/app/TestLivenessCheck.java
> + * Copyright (c) 2020 IBM Corporation and others.
update copyright year

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/ConfigAdminXmlCheckApp/src/io/openliberty/microprofile/health31/config/admin/xml/checks/app/TestReadinessCheck.java
> + * Copyright (c) 2020 IBM Corporation and others.
update copyright year

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/test-applications/FailsToStartHealthCheckApp/src/io/openliberty/microprofile/health31/fails/to/start/health/check/app/FailingReadinessCheck.java
> + * Copyright (c) 2020 IBM Corporation and others.
update copyright year

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    public static RepeatTests r = RepeatTests.withoutModification()
should be repeated for the MPHealth versions < 3.0

2024-02-12 20:22 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    public void testAppDetectionServerXml() throws Exception {
Can we add another test case, where the name attribute in the application element, isn't the same as the WAR name, and see if the correct appName is registered by configAdmin and ASL?

2024-02-12 20:22 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
> +                        appName = appNameSplit[appNameSplit.length - 1].replace(".war", "");
Is there a test case that verifies this scenario, where the application is an EAR file, and it correctly parses the appName?

2024-02-14 15:49 UTC, tonyreigns commented
#build

2024-02-22 00:34 UTC, tonyreigns commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/bnd.bnd
> +    com.ibm.websphere.org.eclipse.microprofile.config.1.3;version=latest,\
Yes

2024-02-22 00:34 UTC, tonyreigns commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/ConfigAdminHealthCheckTest.java
> +    public void testReadinessEndpointOnServerStart() throws Exception {
This is testing two wars in an EAR file and also making sure configAdmin picks up the application when we have both slow and quick starting apps.

2024-02-22 00:34 UTC, tonyreigns commented
#build

2024-02-26 16:20 UTC, pgunapal requested changes
Looks good, minor comments to remove redundant debug msgs.

2024-02-26 16:20 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
> +            Tr.warning(tc, "Debug msg: WebSphere:service=com.ibm.websphere.application.ApplicationMBean,name=" + appName);
I don't think we need these debug msgs anymore.

2024-02-26 16:20 UTC, pgunapal commented on dev/com.ibm.ws.microprofile.health/src/com/ibm/ws/microprofile/health/internal/AppTrackerImpl.java
> +            System.out.println("Debug msg: WebSphere:service=com.ibm.websphere.application.ApplicationMBean,name=" + appName);
This one as well.

2024-02-27 15:46 UTC, pgunapal approved these changes
Looks good.

2024-02-28 22:07 UTC, pgunapal commented
@tonyreigns please make sure to squash the commits, before merging.

2024-03-04 19:05 UTC, tonyreigns commented
#libby

2024-03-04 19:10 UTC, merged