Update resteasy-tracing-api exports to correct version
OpenLiberty/open-liberty pull request #27540
Opened 2024-02-01 16:40 UTC by jim-krueger

It was brought to my attention that the EE9 and EE10 versions of Restful Web Services were exporting a  very old version of org.jboss.resteasy:resteasy-tracing-api.   It appears that the 1.0.0 was not updated to 1.1.0 in the exports when the RESTEasy version was updated to 4.7.0.

2024-02-01 16:43 UTC, jim-krueger commented
#libby

2024-02-01 16:43 UTC, jim-krueger commented
#build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-02-01 22:35 UTC, jhanders34 approved these changes

2024-02-01 23:15 UTC, jhanders34 requested changes

2024-02-01 23:15 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
> +  org.jboss.resteasy.tracing.api;version=version=${resteasy-tracing-api-version},\
```suggestion
  org.jboss.resteasy.tracing.api;version=${resteasy-tracing-api-version},\
```

2024-02-01 23:25 UTC, jim-krueger commented on dev/io.openliberty.org.jboss.resteasy.common/bnd.bnd
> +  org.jboss.resteasy.tracing.api;version=version=${resteasy-tracing-api-version},\
fixed

2024-02-01 23:26 UTC, jim-krueger commented
#libby

2024-02-01 23:26 UTC, jim-krueger commented
#build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-02-01 23:27 UTC, jhanders34 approved these changes, later dismissed

2024-02-02 14:23 UTC, jim-krueger commented
#libby

2024-02-02 14:26 UTC, jhanders34 approved these changes

2024-02-02 14:34 UTC, merged