Changes to handle circular static initialisation issue.
OpenLiberty/open-liberty pull request #27582
Opened 2024-02-06 12:54 UTC by anija-anil

Changes to handle circular static initialisation in the EclipseLink ASMFactory class.

2024-02-06 12:59 UTC, anija-anil commented
#build

2024-02-06 14:50 UTC, tkburroughs requested changes

2024-02-06 14:50 UTC, tkburroughs commented on dev/io.openliberty.persistence.3.1.thirdparty/src/org/eclipse/persistence/asm/ASMFactory.java
> +import org.eclipse.persistence.asm.internal.Util;
Copyright at top should include 2024:

Copyright (c) 2023, 2024 Oracle and/or its affiliates. All rights reserved.

2024-02-06 16:34 UTC, tkburroughs commented
New build needed with latest change:
#libby
#build

2024-02-07 13:59 UTC, tkburroughs approved these changes

2024-02-07 13:59 UTC, merged