NPE Fix for a test on z/OS
OpenLiberty/open-liberty pull request #27758
Opened 2024-02-27 15:37 UTC by BerksanAtes

Fixes #27755

2024-02-27 15:37 UTC, BerksanAtes commented
#build

2024-02-28 17:15 UTC, neuwerk requested changes

2024-02-28 17:15 UTC, neuwerk commented on dev/com.ibm.ws.jaxws.2.2.webcontainer_fat/test-applications/libertyCXFProperties/src/com/ibm/ws/properties/test/service/ImageServiceImpl.java
> +            serviceName = "ImageServiceImplService") // 27755 WSDL location is removed that might be causing NPE on z/OS
Need to change copyright year to `2023, 2024`

2024-02-28 17:29 UTC, BerksanAtes commented
#run-libby-bot

2024-02-28 17:58 UTC, neuwerk approved these changes

2024-02-28 17:59 UTC, merged