Update message ID
OpenLiberty/open-liberty pull request #27829
Opened 2024-03-04 18:34 UTC by pmd1nh

2024-03-04 18:35 UTC, pmd1nh commented
relate to https://github.com/OpenLiberty/open-liberty/pull/27494

Add message ID

#build        #spawn.fullfat.buckets=io.openliberty.webcontainer.servlet.6.1.internal_fat,io.openliberty.webcontainer.servlet.6.0.internal_fat,com.ibm.ws.webcontainer.servlet.6.0_fat_toleration.lWAS,com.ibm.ws.webcontainer_fat,com.ibm.ws.webcontainer.servlet.3.1_fat,com.ibm.ws.webcontainer.servlet.4.0_fat,com.ibm.ws.webcontainer_fat_part2,com.ibm.ws.webcontainer_fat_servlet31toleration,com.ibm.ws.webcontainer_fat_servlet31toleration_part2,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0_part2,com.ibm.ws.webcontainer_fat_lWAS,com.ibm.ws.webcontainer_fat_servlet31_webcontainerlWAS,com.ibm.ws.webcontainer.servlet.4.0_fat_toleration.3.0.lWAS

2024-03-05 14:51 UTC, dmuelle requested changes
ID review

2024-03-05 14:51 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +query.or.post.is.null=CWWWC0009E: Request query string or post data is null.
```suggestion
query.or.post.is.null=CWWWC0009E: The request query string or the post data is null.
```

2024-03-05 14:51 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +query.or.post.is.null.explanation=Application tries to parse a null request parameter or a post body.
```suggestion
query.or.post.is.null.explanation=The application tried to parse a null request parameter or an invalid post body.
```

2024-03-05 14:51 UTC, dmuelle commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +query.or.post.is.null.useraction=Client needs to send a non-null request parameters or a valid post body.
```suggestion
query.or.post.is.null.useraction=The client must send non-null request parameters and a valid post body.
```

2024-03-05 15:02 UTC, dmuelle submitted a review, later dismissed

2024-03-05 15:03 UTC, dmuelle commented
dismissing my review as I was unaware @is273 was already in process of reviewing

2024-03-05 15:28 UTC, is273 commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +query.or.post.is.null=CWWWC0009E: Request query string or post data is null.
Change "Request query string or post data is null." to "The HTTP request query string or the HTTP POST request data is null."

2024-03-05 15:28 UTC, is273 commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +query.or.post.is.null.explanation=Application tries to parse a null request parameter or a post body.
Change "Application tries to parse a null request parameter or a post body." to "The application tried to parse a null HTTP request parameter or a null HTTP POST request body."

2024-03-05 15:28 UTC, is273 commented on dev/com.ibm.ws.webcontainer/resources/com/ibm/ws/webcontainer/resources/Messages.nlsprops
> +query.or.post.is.null.useraction=Client needs to send a non-null request parameters or a valid post body.
Change "Client needs to send a non-null request parameters or a valid post body." to "The client must send a non-null HTTP request parameter or a non-null HTTP POST request body."

2024-03-06 01:35 UTC, pmd1nh commented
#libby
#build

2024-03-06 12:48 UTC, is273 commented
@pmd1nh Approved the message

2024-03-08 12:17 UTC, pnicolucci approved these changes

2024-03-08 17:27 UTC, pmd1nh commented
#libby

2024-03-08 17:30 UTC, pmd1nh commented
no component 91341 1 0
 com.ibm.ws.app.manager_fat FAT tests 33 1 0
  componenttest.application.manager.test.SharedLibUpdateJarTest 1 1 0 4 s 7
   testSharedLibUpdateJar 1 1 0 4 s 1

2024-03-08 17:30 UTC, merged