JAX-WS: Set minimum java level to 11 on our beanvalidation fat.
OpenLiberty/open-liberty pull request #27831
Opened 2024-03-04 21:04 UTC by neuwerk

This PR sets the minimum java level on the `io.openliberty.jaxws.beanvalidation_fat` to Java 11. This should resolve some build issues related to this bucket's dependency on `java.lang.invoke.StringConcatFactory`

2024-03-04 23:48 UTC, tkburroughs submitted a review, later dismissed
In addition to also setting source/target in bnd.bnd.... please also update:
- .classpath to indicate JavaSE-11 instead of JavaSE-1.8
- org.eclipse.jdt.core.prefs and replace the 3 java 17 settings to java 11

2024-03-04 23:48 UTC, tkburroughs commented on dev/io.openliberty.jaxws.beanvalidation_fat/bnd.bnd
> +fat.minimum.java.level: 11
Also add:

javac.source: 11
javac.target: 11

2024-03-06 00:29 UTC, jhanders34 requested changes
The only change needed is updating the org.eclipse.jdt.core.prefs to be 1.8 and the eclipse problem goes away.  You do not need to change things to Java 11 for this FAT project.

2024-03-06 00:57 UTC, jhanders34 approved these changes, later dismissed

2024-03-06 00:57 UTC, jhanders34 commented
#libby

2024-03-06 01:10 UTC, jhanders34 approved these changes

2024-03-06 01:11 UTC, jhanders34 commented
#libby

2024-03-06 01:12 UTC, merged