Resolved UUID not working as Generated ID
OpenLiberty/open-liberty pull request #27872
Opened 2024-03-08 04:59 UTC by Riva-Tholoor-Philip

Resolved UUID not working as Generated ID.
for #24925

2024-03-08 05:03 UTC, Riva-Tholoor-Philip commented
#build

2024-03-08 16:50 UTC, tkburroughs requested changes

2024-03-08 16:50 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestUUIDEntityIDServlet.java
> + *
Copyright needs to be updated to:  2022, 2024

2024-03-08 16:50 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestUUIDEntityIDServlet.java
> +            tem.merge(entity);
When using "merge", it would be more correct to use the return value, so please update this to:
entity = tem.merge(entity);

2024-03-08 16:50 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.jpa_31_fat/test-applications/jpa31/src/io/openliberty/jpa/tests/jpa31/web/TestUUIDEntityIDServlet.java
> +            tem.merge(entity);
When using "merge", it would be more correct to use the return value, so please update this to:
entity = tem.merge(entity);

2024-03-08 16:56 UTC, tkburroughs commented
@Riva-Tholoor-Philip Note that the test failures are due to the return value of `merge` not being used.... see code review comments.  When using `merge`, it is the returned value that has been merged and persisted; the passed in entity is unlikely to have been updated, so will likely not have the primary key set.

2024-03-09 11:41 UTC, Riva-Tholoor-Philip commented
#build

2024-03-09 13:02 UTC, Riva-Tholoor-Philip reviewed
Made the code-changes as recommended by Tracy

2024-03-11 04:23 UTC, Riva-Tholoor-Philip commented
#libby

2024-03-11 14:25 UTC, tkburroughs approved these changes

2024-03-11 15:27 UTC, merged