Initial GVT test bucket
OpenLiberty/open-liberty pull request #27913
Opened 2024-03-14 12:47 UTC by seethalm

fixes #27910

2024-03-14 14:01 UTC, websterc87 requested changes

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/bnd.bnd
> +# Copyright (c) 2021, 2024 IBM Corporation and others.
Not sure this was initially created in 2021

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/build.gradle
> + * Copyright (c) 2021, 2024 IBM Corporation and others.
Not sure this was initially created in 2021

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> + * Copyright (c) 2021, 2024 IBM Corporation and others.
Not sure this was initially created in 2021

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnectionForUTF(LibertyServer server) throws IOException {
Should this be moved into HttpUtils.

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnection(URL url, int timeout, HTTPRequestMethod requestMethod) throws IOException, ProtocolException {
Should this be moved into HttpUtils.

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/publish/servers/com.ibm.gvt.server/bootstrap.properties
> +# Copyright (c) 2021, 2022 IBM Corporation and others.
Wrong initial year.

2024-03-14 14:01 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/publish/servers/com.ibm.gvt.server/server.xml
> +    Copyright (c) 2021, 2024 IBM Corporation and others.
Wrong initial year.

2024-03-14 14:01 UTC, websterc87 commented on dev/fattest.simplicity/bnd.bnd
> +    com.ibm.ws.org.apache.httpcomponents;version=latest,\
Our builds should be using locked down versions rather than version=latest for any dependcy. Otherwise we dont have repeatable builds

2024-03-15 12:37 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/bnd.bnd
> +# Copyright (c) 2021, 2024 IBM Corporation and others.
Copyright updated to 2024

2024-03-15 12:37 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/build.gradle
> + * Copyright (c) 2021, 2024 IBM Corporation and others.
Copyright updated to 2024

2024-03-15 12:37 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> + * Copyright (c) 2021, 2024 IBM Corporation and others.
Copyright updated to 2024

2024-03-15 12:38 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnectionForUTF(LibertyServer server) throws IOException {
Moved to HttpUtils

2024-03-15 12:38 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnection(URL url, int timeout, HTTPRequestMethod requestMethod) throws IOException, ProtocolException {
Moved to HttpUtils

2024-03-15 12:38 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/publish/servers/com.ibm.gvt.server/bootstrap.properties
> +# Copyright (c) 2021, 2022 IBM Corporation and others.
Copyright updated to 2024

2024-03-15 12:38 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/publish/servers/com.ibm.gvt.server/server.xml
> +    Copyright (c) 2021, 2024 IBM Corporation and others.
Copyright updated to 2024

2024-03-15 12:44 UTC, seethalm commented on dev/fattest.simplicity/bnd.bnd
> +    com.ibm.ws.org.apache.httpcomponents;version=latest,\
com.ibm.ws.org.apache.httpcomponents;version=latest is used across all projects in OL. Like com.ibm.ws.grpc_fat, com.ibm.ws.jaxrs.2.0_fat, com.ibm.ws.jsf.2.2_fat. So, is it necessary to use a locked-down version?

2024-03-15 13:15 UTC, websterc87 requested changes

2024-03-15 13:15 UTC, websterc87 commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnectionForUTF(LibertyServer server) throws IOException {
Feels like there is no reason for this class to exist anymore. I would recommend having your test directly call HttpUtils.

2024-03-15 13:15 UTC, websterc87 commented on dev/fattest.simplicity/bnd.bnd
> +    com.ibm.ws.org.apache.httpcomponents;version=latest,\
I will raise it as a general issue rather than blocking this delivery.

2024-03-18 09:32 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnectionForUTF(LibertyServer server) throws IOException {
Refactored, so that GVT test cases directly call's Httputils.

2024-03-18 09:32 UTC, seethalm commented on dev/com.ibm.ws.gvt.rest_fat/fat/src/com/ibm/ws/gvt/rest/fat/GvtUtils.java
> +    public static HttpURLConnection getHttpConnection(URL url, int timeout, HTTPRequestMethod requestMethod) throws IOException, ProtocolException {
Refactored, so that GVT test cases directly call's Httputils.

2024-03-18 09:59 UTC, seethalm commented
#build

2024-10-03 09:05 UTC, closed without merging