Changes to remove TODOs
OpenLiberty/open-liberty pull request #28066
Opened 2024-04-02 05:26 UTC by anija-anil

To Remove TODOs for https://github.com/OpenLiberty/open-liberty/issues/27501

2024-04-02 05:26 UTC, anija-anil commented
#build

2024-04-03 08:47 UTC, anija-anil commented
#build

2024-04-03 09:08 UTC, anija-anil commented
#libby

2024-04-08 14:06 UTC, tkburroughs requested changes

2024-04-08 14:06 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
> +import javax.management.Query;
This is causing a compile failure... the class `Query` cannot be imported twice from 2 different packages.  The existing import on line 23 is correct, please remove this new one.

2024-04-08 14:06 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
>           * https://github.com/OpenLiberty/open-liberty/issues/23952
Please remove the TODO comment for 23952, as that is the TODO that is being fixed here.

2024-04-08 14:06 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
> -            && (isUsingJPA21Feature() || isUsingJPA31Feature())) {
This same TODO exists 2 more times in this file... all 3 TODOs need to be removed.

2024-04-08 14:06 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java
> -        // TODO: Disable until https://github.com/OpenLiberty/open-liberty/issues/23566 is delivered
This same TODO occurs 5 more times in this file.... all 6 need to be remove.

2024-04-09 05:58 UTC, anija-anil commented
#build

2024-04-09 15:01 UTC, tkburroughs requested changes
Still need to fix the imports for `javax.persistence.Query`. Not sure why your editor is trying to replace it, but `javax.management.Query` is not compatible with `javax.persistence.Query`... they are totally different things.

2024-04-09 15:01 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.spec10.entity_fat.common/test-applications/entity/src/com/ibm/ws/jpa/fvt/entity/testlogic/VersioningTestLogic.java
> +import javax.management.Query;
This is still a problem... the test requires `javax.persistence.Query`.... replacing it with `javax.management.Query` will not work, they are totally different things.  Need to remove `javax.management.Query` and restore the original `javax.persistence.Query`

2024-04-09 15:01 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java
> +import javax.management.Query;
The code is failing to compile... the test requires `javax.persistence.Query`.... replacing it with `javax.management.Query` will not work, they are totally different things.  Need to remove `javax.management.Query` and restore the original `javax.persistence.Query`

2024-04-09 15:04 UTC, tkburroughs commented
From the build; look in the `gradle_comipleTest.log` and there are compile failures like this:

```
> Task :com.ibm.ws.jpa.tests.eclipselink.query_jpa_2.1_fat:globalize NO-SOURCE
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:78: error: incompatible types: jakarta.persistence.Query cannot be converted to javax.management.Query
            Query query = em.createQuery("SELECT CEILING(?1) FROM JPA31Entity s WHERE s.intVal1 = ?2");
                                        ^
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:79: error: cannot find symbol
            query.setParameter(1, 1.1);
                 ^
  symbol:   method setParameter(int,double)
  location: variable query of type Query
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:80: error: cannot find symbol
            query.setParameter(2, 3);
                 ^
  symbol:   method setParameter(int,int)
  location: variable query of type Query
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:81: error: cannot find symbol
            query.getResultList();
                 ^
  symbol:   method getResultList()
  location: variable query of type Query
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:90: error: incompatible types: jakarta.persistence.Query cannot be converted to javax.management.Query
            query = em.createQuery("SELECT CEILING(1.1) FROM JPA31Entity s WHERE s.intVal1 = 3");
                                  ^
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:91: error: cannot find symbol
            query.getResultList();
                 ^
  symbol:   method getResultList()
  location: variable query of type Query
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:110: error: incompatible types: no instance(s) of type variable(s) T exist so that TypedQuery<T> conforms to Query
            query = em.createQuery(cquery);
                                  ^
  where T is a type-variable:
    T extends Object declared in method <T>createQuery(CriteriaQuery<T>)
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:111: error: cannot find symbol
            query.setParameter(floatParam1, 1.1f);
                 ^
  symbol:   method setParameter(ParameterExpression<Float>,float)
  location: variable query of type Query
/home/jazz_build/Build/jbe/build/open-liberty/dev/com.ibm.ws.jpa.tests.eclipselink.query_31_fat.common/test-applications/jpa31/src/com/ibm/ws/jpa/jpa31/testlogic/TestMathLogic.java:112: error: cannot find symbol
            query.setParameter(intParam1, 3);
                 ^
  symbol:   method setParameter(ParameterExpression<Integer>,int)
  location: variable query of type Query
```

The change to use `javax.management.Query` does not work; it is not compatible with `javax.persistence.Query`; the correct import needs to be restored.

2024-04-09 16:06 UTC, anija-anil commented
#build

2024-04-10 19:39 UTC, tkburroughs commented
The "import" statements are still incorrect.  The builds will continue to fail as long as the "[Files changed](https://github.com/OpenLiberty/open-liberty/pull/28066/files)" shows changes to the imports.

2024-04-12 04:56 UTC, anija-anil commented
#build

2024-04-12 13:51 UTC, tkburroughs commented
#libby

2024-04-15 05:47 UTC, anija-anil commented
#build

2024-04-15 13:09 UTC, tkburroughs approved these changes

2024-04-15 13:10 UTC, merged

2024-04-15 13:10 UTC, tkburroughs commented
The build had one test failure that is a known intermittent unrelated failure; merged.