FeatureUtility update response code validation
OpenLiberty/open-liberty pull request #28157
Opened 2024-04-15 20:59 UTC by jjiwooLim

2024-04-15 20:59 UTC, jjiwooLim commented
#build

2024-04-16 19:47 UTC, jacobwdv requested changes

2024-04-16 19:47 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +        //TODO add finest logging
complete the TODO here, maybe you're waiting logging changes discussed previously :) . Those likely wont get in before you merge so just remove the TODO. 

In general,  I prefer to have one return in a given method. it helps whenever debugging. I'll eave that up to you to decide though

2024-04-16 19:47 UTC, jacobwdv commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ArtifactDownloaderUtils.java
> +        //TODO add finest logging
For clarity I would check if it's 404 and return false otherwise true. just easier to read imo. Again, a nit. 
if (repoResponseCode == 404)

2024-04-16 19:50 UTC, jacobwdv commented on dev/com.ibm.ws.install/test/com/ibm/ws/install/internal/ArtifactDownloaderUtilsTest.java
> +    public void testCheckResponseCodeOK() {
glad to see unit tests for this, in the future people will hesitate to make changes to strengthen 'checkResponseCode' now that we group 400+ in with 200 in the passing tests

2024-04-16 20:24 UTC, jacobwdv approved these changes
LGTM!

2024-04-16 20:39 UTC, jjiwooLim commented
#build

2024-04-16 20:39 UTC, jjiwooLim commented
#libby-bot

2024-04-17 20:11 UTC, jjiwooLim commented
Build Failures are not related to my changes

2024-04-23 15:32 UTC, merged