Correct FipsUtils and add unit tests
OpenLiberty/open-liberty pull request #28300
Opened 2024-04-29 21:43 UTC by rlcundiff

2024-04-29 22:27 UTC, rlcundiff commented
#build

2024-04-30 15:17 UTC, Zech-Hein requested changes
the changes look good 👍 we just need to add the copyright header to the unit test class you added

2024-04-30 15:17 UTC, Zech-Hein commented on dev/com.ibm.ws.crypto.common/test/com/ibm/ws/crypto/common/FipsUtilsTest.java
> +package com.ibm.ws.crypto.common;
```suggestion
/*******************************************************************************
 * Copyright (c) 2024 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License 2.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 *******************************************************************************/
package com.ibm.ws.crypto.common;
```

2024-04-30 15:41 UTC, Zech-Hein approved these changes
LGTM

2024-04-30 18:30 UTC, rlcundiff commented
#libby

2024-04-30 18:56 UTC, rlcundiff commented
This is a new project that is still unused.  The build had a UI test failure that is unrelated.

2024-04-30 18:56 UTC, merged