Enable Jakarta Rest 4.0 (using RESTEasy 7.0.0.Alpha1)
OpenLiberty/open-liberty pull request #28312
Opened 2024-04-30 20:13 UTC by jim-krueger

Initial implementation of Jakarta Rest 4.0 (using RESTEasy 7.0.0.Alpha1)

2024-05-03 01:47 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-16 20:22 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-17 20:50 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-19 19:33 UTC, jhanders34 requested changes
In general I would like to see if there are common liberty files that can be moved to a restfulWS common bundle outside of the resteasy bundles and be brought into each version's bundle unless it can be standalone.  This can be done outside of this PR of course.  I would recommend adding the nls files in there as well when that work is done in a future PR.

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-core-spi:4.7.2.Final
```suggestion
org.jboss.resteasy:resteasy-client:7.0.0.Alpha1
```

Duplicate entries.

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-core:4.7.9.Final
```suggestion
org.jboss.resteasy:resteasy-core-spi:7.0.0.Alpha1
```
duplicate entries

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-jaxb-provider:4.7.2.Final
```suggestion
org.jboss.resteasy:resteasy-core:7.0.0.Alpha1
```
duplicate entries

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-multipart-provider:4.7.9.Final
```suggestion
org.jboss.resteasy:resteasy-jaxb-provider:7.0.0.Alpha1
```
duplicate entries

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-rxjava2:4.7.2.Final
```suggestion
org.jboss.resteasy:resteasy-multipart-provider:7.0.0.Alpha1
```
duplicate entries

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-servlet-initializer:4.7.2.Final
```suggestion
org.jboss.resteasy:resteasy-rxjava2:7.0.0.Alpha1
```
duplicate entries

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-tracing-api:1.1.0.Final
```suggestion
org.jboss.resteasy:resteasy-servlet-initializer:7.0.0.Alpha1
```
duplicate entries

2024-05-19 19:33 UTC, jhanders34 commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-validator-provider:4.7.2.Final
```suggestion
```
duplicate entry

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
> +                    .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                    .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/test/DependentIntoJaxTest.java
> + * Copyright (c) 2024 IBM Corporation and others.
```suggestion
 * Copyright (c) 2022, 2024 IBM Corporation and others.
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
> +                            .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").alwaysAddFeature("servlet-6.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_1
```suggestion
                            .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").alwaysAddFeature("servlet-6.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0.client_fat/fat/src/com/ibm/ws/jaxrs20/client/fat/FATSuite.java
> +                            .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").alwaysAddFeature("servlet-6.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_1
```suggestion
                            .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").alwaysAddFeature("servlet-6.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/CheckFeature12Test.java
> +@SkipForRepeat({"EE9_FEATURES", "EE10_FEATURES", "EE11_FEATURES"}) // this test is not applicable for EE9 because restfulWS-3.0 always enables cdi-3.0
This one you didn't update to the constants and just continued to use the string literals.

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/ExceptionMappingWithOTTest.java
> +@SkipForRepeat({SkipForRepeat.EE9_FEATURES, SkipForRepeat.EE10_FEATURES, SkipForRepeat.EE11_FEATURES}) //MP Open Tracing replace with MP Telemetry so this test is not valid beyond EE9
```suggestion
@SkipForRepeat({SkipForRepeat.EE10_FEATURES, SkipForRepeat.EE11_FEATURES}) //MP Open Tracing replace with MP Telemetry so this test is not valid beyond EE9
```
EE9 repeat should still be done based off of the old settings.

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
> +                             .removeFeature("microProfile-5.0").addFeature("microProfile-6.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                             .removeFeature("microProfile-5.0").addFeature("microProfile-6.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/RestMetricsTest.java
> +@SkipForRepeat(SkipForRepeat.EE11_FEATURES) // this test neeeds to be skipped until microprofile-7.0 there.
MP 7.0 will support EE 10.  It won't support EE 11.  Not sure which MP release will support EE 11.  It could be 8.0.

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.client_fat/fat/src/com/ibm/ws/jaxrs21/client/fat/FATSuite.java
> +                    .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                    .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/FATSuite.java
> +                    .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").alwaysAddFeature("xmlBinding-4.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                    .andWith(new JakartaEE10Action().alwaysAddFeature("jsonb-3.0").alwaysAddFeature("xmlBinding-4.0").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseClientBehaviorApp/src/jaxrs21sse/clientbehavior/SseClientBehaviorTestServlet.java
> +            executionLatch.await(30, TimeUnit.SECONDS);
This is run for EE 8 and EE 9 as well.  Do we need to test it the old way for those repeats?  Should this assertFalse for EE 10 and 11?

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseClientBehaviorApp/src/jaxrs21sse/clientbehavior/SseClientBehaviorTestServlet.java
> +            }
Does this need EE 8 / 9 difference to EE 10 / 11?

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1_fat/bnd.bnd
> +  appsecurity-5.0,\
appsecurity-5.0 is EE 10.  I am guessing you probably don't need that one added here.
```suggestion
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1_fat/fat/src/com/ibm/ws/jaxrs21/fat/FATSuite.java
> +        .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
        .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1_fat_executor/fat/src/com/ibm/ws/jaxrs/executor/fat/FATSuite.java
> +                  .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                  .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1_fat_extended/fat/src/com/ibm/ws/jaxrs21/fat/extended/FATSuite.java
> +                   .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                   .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.x.webcontainer_fat/fat/src/com/ibm/ws/jaxrs2x/fat/FATSuite.java
> +                    .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
                    .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common.ee11/build.gradle
> +           'org.jboss.resteasy:resteasy-core-spi:6.2.8.Final'
Shouldn't these be 7.0.0.Alpha1?

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common.ee11/resources/META-INF/beans.xml
> +       version="4.0">
```suggestion
        https://jakarta.ee/xml/ns/jakartaee/beans_4_1.xsd"
       bean-discovery-mode="annotated"
       version="4.1">
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common.ee11/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer.nlsprops
> +#COMPONENTNAMEFOR CWWKW io.openliberty.restfulWS-3.1
```suggestion
#COMPONENTNAMEFOR CWWKW io.openliberty.restfulWS-4.0
```

Also in the translated ones.  Or maybe you want it to still say 3.1 for a reason.

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.common.ee11/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer.nlsprops
> +#CMVCPATHNAME io.openliberty.org.jboss.resteasy.common.ee10/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWS.nlsprops
```suggestion
#CMVCPATHNAME io.openliberty.org.jboss.resteasy.common.ee11/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWSServer.nlsprops
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.server.ee11/resources/io/openliberty/org/jboss/resteasy/server/nls/RESTfulWSServer.nlsprops
> +#CMVCPATHNAME io.openliberty.org.jboss.resteasy.common.ee10/resources/io/openliberty/org/jboss/resteasy/common/nls/RESTfulWS.nlsprops
```suggestion
#CMVCPATHNAME io.openliberty.org.jboss.resteasy.server.ee11/resources/io/openliberty/org/jboss/resteasy/server/nls/RESTfulWSServer.nlsprops
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.org.jboss.resteasy.server.ee11/resources/io/openliberty/org/jboss/resteasy/server/nls/RESTfulWSServer.nlsprops
> +#COMPONENTNAMEFOR CWWKW io.openliberty.restfulWS-3.1
```suggestion
#COMPONENTNAMEFOR CWWKW io.openliberty.restfulWS-4.0
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.0.cdi.3.0_fat/fat/src/io/openliberty/restfulWS30/cdi30/fat/FATSuite.java
> +        .andWith(new JakartaEE10Action().withID("EE10").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
        .andWith(new JakartaEE10Action().withID("EE10").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/FATSuite.java
> +        .andWith(new JakartaEE10Action().withID("EE10").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
```suggestion
        .andWith(new JakartaEE10Action().withID("EE10").conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_17))
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.0.client_fat/fat/src/io/openliberty/restfulWS30/client/fat/RegisterRestClientTest.java
> +@SkipForRepeat(SkipForRepeat.EE11_FEATURES)
```suggestion
@SkipForRepeat(SkipForRepeat.EE11_FEATURES) // Skip until MicroProfile supports Jakarta EE 11
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.0_fat/bnd.bnd
> +  beanvalidation-3.1,\
```suggestion
```
duplicate entry.

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.restfulWS.3.1_fat/fat/src/io/openliberty/restfulWS31/fat/FATSuite.java
> +    public static RepeatTests r = RepeatTests.with(new JakartaEE10Action().withID("EE10"))
```suggestion
    public static RepeatTests r = RepeatTests.withoutModification()
```

2024-05-19 19:33 UTC, jhanders34 commented on dev/io.openliberty.threading.internal.java21/.project
> +<?xml version="1.0" encoding="UTF-8"?>
This should be removed.  Eclipse added it back to your environment and you added it to your PR erroneously.

2024-05-20 14:18 UTC, jim-krueger commented on dev/cnf/oss_dependencies.maven
> +org.jboss.resteasy:resteasy-core-spi:4.7.2.Final
Thanks, these were all merge conflict mistakes.

2024-05-20 14:34 UTC, jim-krueger commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
> +                    .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
Why change EE10 to greater than Java 17?

2024-05-20 14:43 UTC, jim-krueger commented on dev/com.ibm.ws.jaxrs.2.0.cdi.1.2_fat/fat/src/com/ibm/ws/jaxrs20/cdi12/fat/FATSuite.java
> +                    .andWith(new JakartaEE10Action().conditionalFullFATOnly(FeatureReplacementAction.GREATER_THAN_OR_EQUAL_JAVA_11))
nevermind.

2024-05-20 15:05 UTC, jim-krueger commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseClientBehaviorApp/src/jaxrs21sse/clientbehavior/SseClientBehaviorTestServlet.java
> +            executionLatch.await(30, TimeUnit.SECONDS);
Maybe, the question is if it is worth what it takes to detect that we are running in EE10 or EE11 on the server.

2024-05-21 21:17 UTC, jim-krueger commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseClientBehaviorApp/src/jaxrs21sse/clientbehavior/SseClientBehaviorTestServlet.java
> +            executionLatch.await(30, TimeUnit.SECONDS);
I'd say there is no need to test this for EE8 and EE9 since the spec wasn't clarified on this point until EE10.

2024-05-21 21:21 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,com.ibm.ws.jaxrs.defaultexceptionmapper_fat,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-22 23:06 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,com.ibm.ws.jaxrs.defaultexceptionmapper_fat,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-22 23:41 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,com.ibm.ws.jaxrs.defaultexceptionmapper_fat,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-23 13:43 UTC, jim-krueger commented
#libby #build #spawn.fullfat.buckets=com.ibm.ws.jaxrs.2.0_fat,com.ibm.ws.jaxrs.2.0.cdi.1.2_fat,com.ibm.ws.jaxrs.2.0.client_fat,com.ibm.ws.jaxrs.2.1_fat,com.ibm.ws.jaxrs.2.1_fat_executor,com.ibm.ws.jaxrs.2.1_fat_extended,com.ibm.ws.jaxrs.2.1.cdi.2.0_fat,com.ibm.ws.jaxrs.2.1.client_fat,com.ibm.ws.jaxrs.2.1.sse_fat,com.ibm.ws.jaxrs.2.x_fat_clientProps,com.ibm.ws.jaxrs.defaultexceptionmapper_fat,io.openliberty.restfulWS.3.0_fat,io.openliberty.restfulWS.3.0.cdi.3.0_fat,io.openliberty.restfulWS.3.0.client_fat,io.openliberty.restfulWS.3.1_fat

2024-05-24 15:57 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/BasicSseTest.java
> +    @SkipForRepeat(SkipForRepeat.EE11_FEATURES) // JAXB removed from Jakarta Rest in EE11
JAXB should still work with REST 4.0, just not JaxbLink used any longer.

2024-05-24 15:59 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
> +                                     .addFeature("mpMetrics-5.1").removeFeature("microProfile-5.0").addFeature("microProfile-6.0"));
```suggestion
                            .andWith(FeatureReplacementAction.EE11_FEATURES().alwaysAddFeature("jsonb-3.0").removeFeature("mpMetrics-2.3").removeFeature("microProfile-1.3")                                     .addFeature("mpMetrics-5.1").removeFeature("microProfile-5.0")
                            .addFeature("microProfile-6.1"));
```

2024-05-24 15:59 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/fat/src/com/ibm/ws/jaxrs21/sse/fat/SseJaxbTest.java
> +    @SkipForRepeat(SkipForRepeat.EE11_FEATURES) // JAXB removed from Jakarta Rest in EE11
JAXB should still work with REST 4.0, just not JaxbLink used any longer.

2024-05-24 16:03 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.1.sse_fat/test-applications/SseClientBehaviorApp/src/jaxrs21sse/clientbehavior/SseClientBehaviorTestServlet.java
> +                assertTrue("Completion listener runnable was not executed", executionLatch.await(30, TimeUnit.SECONDS));
It should be true for all of EE 8, 9 and 10.  This is changed to EE 11 behavior for all other EE levels.

2024-05-24 16:06 UTC, jhanders34 commented on dev/com.ibm.ws.jaxrs.2.0_fat/fat/src/com/ibm/ws/jaxrs20/fat/FATSuite.java
> +                             .addFeature("mpMetrics-5.1").removeFeature("microProfile-5.0").addFeature("microProfile-6.0"));
```suggestion
                             .addFeature("mpMetrics-5.1").removeFeature("microProfile-5.0").addFeature("microProfile-6.1"));
```

2024-05-24 16:06 UTC, jhanders34 approved these changes

2024-05-24 16:10 UTC, merged