Fix errors during Database Rotation
OpenLiberty/open-liberty pull request #28416
Opened 2024-05-13 22:42 UTC by KyleAure

failure_group-f6233dd1-21a0-4f6f-b70b-806aac880b47
W CWWJP9991W: [eclipselink.server] Failed to find MBean Server: null or empty List returned from MBeanServerFactory.findMBeanServer(null)

failure_group-c3b9f95b-2141-494c-8424-d1b759733dca
PostgreSQL
Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PGobject

failure_group-cc166913-e9d4-4038-a13d-561416c9cf10
PostgreSQL
Caused by: java.lang.ClassNotFoundException: org.postgresql.util.PGobject

2024-05-13 22:42 UTC, KyleAure commented
#build

2024-05-13 22:47 UTC, KyleAure commented
PosgreSQL SOE: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=460faad4-5171-4af6-b557-9812ec6dac92

Target locations of links might be accessible only to IBM employees.

2024-05-14 15:19 UTC, tkburroughs requested changes
Copyright in all files should end in 2024

2024-05-14 15:19 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.tests.beanvalidation_fat.common/fat/src/com/ibm/ws/jpa/tests/beanvalidation/tests/BeanValidation20_EJB.java
>   * are made available under the terms of the Eclipse Public License 2.0
Copyright should add 2024

2024-05-14 15:39 UTC, Riva-Tholoor-Philip submitted a review, later dismissed
Changes Approved

2024-05-15 14:43 UTC, KyleAure commented
RTC Build: Failed with known defects
Pipeline: Passed successfully
PostgreSQL: Failed with issues previously overshadowed by those issues fixed by the PR.

2024-05-15 15:46 UTC, tkburroughs approved these changes

2024-05-15 15:47 UTC, tkburroughs commented
#libby

2024-05-15 17:35 UTC, merged