don't use root tmp directory
OpenLiberty/open-liberty pull request #28410
Opened 2024-05-12 13:08 UTC by benjamin-confino

Resolves https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=300059

I'm informed that on AIX there's a problem with using /tmp so this PR dynamically modifies the permissions.xml file to use a directory inside the server.

2024-05-12 13:08 UTC, benjamin-confino commented
#build

2024-05-13 09:27 UTC, Azquelt requested changes
The approach is good. I've made a few suggestions but they're just small things.

2024-05-13 09:27 UTC, Azquelt commented on dev/com.ibm.ws.cdi.third.party_fat/publish/servers/cdi20HibernateSearchServer/persistence.xml
> +          value="SED-STRING"/>
Please change the placeholder name. Something like `INDEX-PATH` would better communicate what's going to be put in here.

2024-05-13 09:27 UTC, Azquelt commented on dev/com.ibm.ws.cdi.third.party_fat/fat/src/com/ibm/ws/cdi/thirdparty/tests/HibernateSearchTest.java
> +    static String readFile(String path, Charset encoding) throws IOException
```suggestion
    private static String readFile(String path, Charset encoding) throws IOException
```

2024-05-13 09:27 UTC, Azquelt commented on dev/com.ibm.ws.cdi.third.party_fat/fat/src/com/ibm/ws/cdi/thirdparty/tests/HibernateSearchTest.java
> +        //So we load the persistence.xml file, and give it a path from the server.
```suggestion
        //We used to use /tmp here, but we can't do that on some platforms which we build and test on
        //So we load the persistence.xml file, and give it a path from the server.
```
I don't think it's helpful to link to an internal defect in the code - it isn't accessible to anyone external and it'll go stale. Just include the relevant information in the comment. Someone can still track back through the PR if they really need to find more information on the problem.

2024-05-13 09:32 UTC, Azquelt approved these changes
Thanks

2024-05-13 09:42 UTC, benjamin-confino commented
#build

2024-05-13 21:31 UTC, benjamin-confino commented
#libby

2024-05-13 21:33 UTC, merged