Implementing callInTransaction method
OpenLiberty/open-liberty pull request #28433
Opened 2024-05-15 06:07 UTC by ajaypaul-ibm

This PR contains the implementation of  callInTransaction method which is introduced in persistence 3.2

2024-05-15 06:09 UTC, ajaypaul-ibm commented
#build

2024-05-15 22:32 UTC, tkburroughs requested changes

2024-05-15 22:32 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.container.v32/src/com/ibm/ws/jpa/container/v32/JPAEMFactoryV32.java
> +    public void callInTransaction(Function<EntityManager, R> work) {
Signature is not correct and doesn't compile.

2024-05-15 22:32 UTC, tkburroughs commented on dev/com.ibm.ws.jpa.container.v32/src/com/ibm/ws/jpa/container/v32/JPAEMFactoryV32.java
>      public void runInTransaction(Consumer<EntityManager> work) {
Copyright needs to include 2024

2024-05-16 07:07 UTC, ajaypaul-ibm commented
#libby

2024-05-16 07:07 UTC, ajaypaul-ibm commented
#build

2024-05-16 15:01 UTC, ajaypaul-ibm commented
#libby
#build

2024-05-16 15:05 UTC, ajaypaul-ibm commented
#libby

2024-05-16 15:08 UTC, ajaypaul-ibm commented
#build

2024-05-16 15:11 UTC, ajaypaul-ibm commented
#libby

2024-05-16 15:12 UTC, ajaypaul-ibm commented
#build

2024-05-16 15:17 UTC, ajaypaul-ibm commented
#build

2024-05-17 11:46 UTC, tkburroughs approved these changes

2024-05-17 11:46 UTC, merged