Install tools update feature product match logic
OpenLiberty/open-liberty pull request #28578
Opened 2024-05-28 21:32 UTC by jjiwooLim

Reverts and fixes  https://github.com/OpenLiberty/open-liberty/pull/28549

2024-05-28 21:33 UTC, jjiwooLim commented
#build
#create.im.repo=true
#create.pkg.images=true

2024-05-29 15:04 UTC, jjiwooLim commented
Build not triggered with properties, kicking off again manually:

2024-06-04 15:29 UTC, jjiwooLim commented
#libby-bot

2024-06-04 15:30 UTC, jjiwooLim commented
#build
create.im.repo=true
create.pkg.images=true

2024-06-05 18:09 UTC, jjiwooLim commented
create.im.repo
https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_LQui0CNeEe-4F592xetJGQ

2024-06-05 18:22 UTC, jacobwdv requested changes

2024-06-05 18:22 UTC, jacobwdv commented on dev/wlp.lib.extract/src/wlp/lib/extract/ProductMatch.java
> +                for (int startIndex = 0, endIndex = editionStr.indexOf(',');; startIndex = endIndex, endIndex = editionStr.indexOf(',', ++startIndex)) {
We can use Java API's to do this loop instead so it's a little more clear.

```
Collections.addAll(editions,editionStr.split(","));
```

2024-06-05 18:44 UTC, jacobwdv commented on dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
> +                            sb.append(atfi.getEditions().toString().replace("[", "").replace("]", "").replace(" ", ""));
```suggestion
                            sb.append(atfi.getEditions().toString().replace("[", "").replace("]", "").replace(" ", ""));
```
sb.append(atfi.getEditions().stream().map(String::strip).collect(Collectors.joining(","));

2024-06-10 15:06 UTC, jacobwdv approved these changes
LGTM, Thanks!

2024-06-10 15:10 UTC, jjiwooLim commented
#libby-bot

2024-06-10 16:19 UTC, merged