Include OpenJCE Plus in Path
OpenLiberty/open-liberty pull request #28586
Opened 2024-05-29 16:49 UTC by wrodrig

Starting in JDK 17.0.0.10 we need to include the openjceplus module in the script paths.

OpenLiberty Pull Requester,

ATTENTION, READ THIS: Updated 4/11/2018 - Read and understand this completely,
then delete this entire template. If a reviewer or merger sees this template,
they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue mentioned in the PR text or description. That Issue also
MUST be labelled “release bug”

This directs automation to scrape this fix for inclusion in the next release's
list of bugs fixed.

If this code is NOT for fixing a released bug, for example new function, fixing
a bug in unreleased function, or other improvements that do not affect the
user-space, no label is needed. An issue could or could not be used based
on the developer’s discretion, but do still delete this text block.

For full details, please see this wiki page:

https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions

2024-05-29 17:16 UTC, wrodrig commented
#build

#libby

2024-05-29 17:43 UTC, jhanders34 requested changes

2024-05-29 17:43 UTC, jhanders34 commented on dev/cnf/resources/bin/tool.bat
> +if exist "%JAVA_HOME%\lib\modules" set JVM_ARGS=--add-exports openjceplus/com.ibm.misc=ALL-UNNAMED !JVM_ARGS!
```suggestion
if exist "%JAVA_HOME%\jmods\openjceplus.jmod" set JVM_ARGS=--add-exports openjceplus/com.ibm.misc=ALL-UNNAMED !JVM_ARGS!
```

2024-05-29 17:45 UTC, jhanders34 commented
The `server` script does not use tool / tool.bat.  If this is needed for the server, that will require additional changes to both server and server.bat.  @jimblye should be involved with that change. 

As to this change I thought it only affected collective utility script.  Is there a need to have it for OL scripts as well?

2025-04-03 17:48 UTC, jhanders34 commented
Resolved with #32955.  Closing out this PR.

2025-04-03 17:48 UTC, closed without merging