Fix jsp_defaultHTML test to also check for 302
OpenLiberty/open-liberty pull request #28630
Opened 2024-06-03 20:22 UTC by Channyboy

#build

2024-06-04 19:54 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
> +            validatePrometheusHTTPMetric(getVendorMetrics(server), expectedRoute, responseStatus, requestMethod);
Is `assertTrue` missing here?

2024-06-04 19:57 UTC, fmhwong requested changes
Need a check for success or fail for this test case.

2024-06-04 20:06 UTC, Channyboy commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/JSPApplicationTest.java
> +            validatePrometheusHTTPMetric(getVendorMetrics(server), expectedRoute, responseStatus, requestMethod);
That would be important.

2024-06-04 20:06 UTC, Channyboy commented
#build #libby

2024-06-04 20:14 UTC, fmhwong reviewed
LGTM

2024-06-06 17:26 UTC, fmhwong approved these changes
LGTM

2024-06-06 17:27 UTC, merged