Add note about syncQueryTimeoutWithTransactionTimeout on the tranlog …
OpenLiberty/open-liberty pull request #28700
Opened 2024-06-10 14:32 UTC by jonhawkes

…dataSource

#build

2024-06-10 18:15 UTC, dmuelle requested changes, later dismissed
ID review

2024-06-10 18:15 UTC, dmuelle commented on dev/com.ibm.ws.transaction/resources/OSGI-INF/l10n/metatype.properties
> +dataSourceRef.desc=This is an optional property. By default the transaction service stores its recovery logs in files. As an alternative it is possible to store the logs in an RDBMS. This is achieved
```suggestion
dataSourceRef.desc=This attribute is optional. By default, the transaction service stores its recovery logs in files. Alternatively, you can store the logs in an RDBMS. Set this attribute to the ID value for a non-transactional data source where the transaction logs are stored. Do not change the syncQueryTimeoutWithTransactionTimeout value on this data source from the default, which is false.
```

2024-06-10 18:56 UTC, jonhawkes commented
#libby
#build

2024-06-11 08:48 UTC, djmatthews approved these changes

2024-06-12 06:07 UTC, merged