InstallRepoVersionless
OpenLiberty/open-liberty pull request #28763
Opened 2024-06-16 18:12 UTC by cbridgha

2024-06-16 18:12 UTC, cbridgha commented
#build

2024-06-16 18:39 UTC, tbitonti approved these changes, later dismissed
Looks good.  There are System.out's in two of the classes.  I can't tell if those need to be removed.

2024-06-16 18:39 UTC, tbitonti commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
Are the System.out's temporary?

2024-06-16 18:39 UTC, tbitonti commented on dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
More System.out's.

2024-06-16 23:11 UTC, cbridgha commented on dev/com.ibm.ws.install/src/com/ibm/ws/install/internal/ExceptionUtils.java
Thanks I'll remove - missed removing all of them....

2024-06-17 11:09 UTC, cbridgha commented
#build

2024-06-17 13:39 UTC, cbridgha commented on dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
fixed...

2024-06-17 14:02 UTC, cbridgha commented
Linking related issues: #28165 and #28321

2024-06-17 14:42 UTC, Azquelt reviewed
Needs tests added, I would expect
- unit tests added to `com.ibm.ws.repository.resolver.ResolutionTests`, covering all expected resolution scenarios including any error cases.
- a smaller set of realistic install scenarios added to the install tests

I note that there's no additional information being stored in the ESA or passed through to the kernel resolver. I suspect there are relevant methods in `com.ibm.ws.repository.resolver.internal.kernel.KernelResolverEsa` which need to be implemented and may require additions to the repository metadata. E.g. `getPlatforms`, `isVersionless` - stubs added in #28620. I would also expect tests for these to be added to `KernelResolverEsaTest`.

If there is additional metadata stored in the repository (i.e. new methods on `ESAResource`) then that would also need new tests.

2024-06-17 14:42 UTC, Azquelt commented on dev/com.ibm.ws.repository.resolver/src/com/ibm/ws/repository/resolver/RepositoryResolver.java
> +            requestedPlatformNames = platforms;
This doesn't really belong in `processNames`, there's no processing needed here, just set it in `resolve`

2024-06-17 14:43 UTC, Azquelt requested changes
Noting the above comments, I wouldn't expect this to be merged without changes.

2024-06-17 16:09 UTC, Azquelt commented
Taking a look at #28321, it looks like the data from the `WLP-Platform` header hasn't been added to the repository metadata. Once it is there, I think it would need to be returned from `KernelResolverEsa.getPlatforms`. I'm not sure how much of the rest of the code should be expected to work without this present.

2024-06-19 22:21 UTC, jjiwooLim requested changes
Install implementation looks good! I suggested some changes for the test.  Btw, should featureUtility read `PREFERRED_PLATFORM_VERSIONS` environment variable and pass it to the resolver?

2024-06-19 22:21 UTC, jjiwooLim commented on dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
> +     * resource.
```suggestion
     * Test the install of versionless servlet from maven central. "jakartaee-10.0" and "servlet" configuration should install servlet-6.0.
```

2024-06-19 22:21 UTC, jjiwooLim commented on dev/com.ibm.ws.install.featureUtility_fat/fat/src/com/ibm/ws/install/featureUtility/fat/InstallServerTest.java
> +	checkCommandOutput(po, 21, "CWWKF1405E", null);
```suggestion
 String[] filesList = { "/lib/features/com.ibm.websphere.appserver.servlet-6.0.mf" };
	checkCommandOutput(po, 0, null, filesList);
```

2024-06-20 15:34 UTC, cbridgha commented
@Azquelt - thank you for your comments, and first of all I didn't mean this to be merged - this was my experiment to see what changes were required to get some function working.....    There are many questions to answer - and I will try to setup a call next week.  I do question if the ESA needs to be changed to capture the new WLP-Platform Manifest header, but I also realize any API that may be needed during resolution needs to be provided by us.  the wlp-platform value is only used in a preprocessing step that allows some optimization before performing the actual resolution - but more to come here...  also working on the API docs you mentioned...

2024-06-20 15:41 UTC, cbridgha commented
@jjiwooLim thanks for taking a look, and as I mentioned to @Azquelt  - this was an experiment, not meant to be merged... but hopefully helpful in the changes that will be required.   Good question on the env variable, and yes we need to provide an api that helps pass this value (we do this internally, but will expose it as an spi...   ultimately we need to expose an API that determines a "target platform" that makes sense with the feature set specified, and rather than duplicating implmentation - we'll provide. - I'll setup a call late next week that explains some of these details.

2024-07-30 13:48 UTC, cbridgha commented
Closing this - Was used for prototyping purposes....

2024-07-30 13:48 UTC, closed without merging