FeatureUtility enable no proxy
OpenLiberty/open-liberty pull request #28782
Opened 2024-06-17 18:54 UTC by jjiwooLim

Add no_proxy property for featureUtility. 
To set `no_proxy` using the environment variable, use `no_proxy`. 
To set it using featureUtility.properties, use `http.nonProxyHosts` (name used by jvm system properties) 
Currently in beta mode for testing purpose.

2024-06-17 18:55 UTC, jjiwooLim commented
#build

2024-06-20 15:36 UTC, jjiwooLim commented
#build

2024-06-20 20:14 UTC, jjiwooLim commented
#build

2024-06-20 21:11 UTC, jjiwooLim commented
#build

2024-07-10 14:20 UTC, jjiwooLim commented
#build

2024-07-10 14:23 UTC, jjiwooLim commented
#libby-bot

2024-07-15 13:45 UTC, bensonlatibm requested changes
looks good, except for the bnd.bnd file copyright change.

2024-07-15 13:45 UTC, bensonlatibm commented on dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
the copyright date is changed, but I don't see any other changes to the bnd.bnd file?

2024-07-16 20:32 UTC, jjiwooLim commented on dev/com.ibm.ws.install.featureUtility_fat/bnd.bnd
not sure why I updated the copyright. Changing it back

2024-07-16 20:33 UTC, jjiwooLim commented
#build

2024-07-26 15:10 UTC, jjiwooLim commented
#build

2024-07-29 14:42 UTC, bensonlatibm approved these changes
LGTM!

2024-07-29 15:01 UTC, merged