HTTP Stat/metrics -> (MP)OpenTelemetry metrics
OpenLiberty/open-liberty pull request #28817
Opened 2024-06-19 19:30 UTC by Channyboy

#build

2024-06-19 19:57 UTC, Channyboy commented
#build

2024-06-19 19:57 UTC, Channyboy commented
#libby

2024-06-19 22:37 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/build.gradle
> + * Copyright (c) 2021 IBM Corporation and others.
2024

2024-06-19 22:44 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
> +    protected String requesContainerHttpServlet(String servletPath, String host, int port, String requestMethod, String query) {
`requestContainerHttpServlet`?

2024-06-19 22:46 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
> +            Log.info(c, "requesContainerHttpServlet", sURL);
`requestContainerHttpServlet`?

2024-06-20 02:35 UTC, Channyboy commented
#build #libby

2024-06-20 13:33 UTC, fmhwong requested changes
See my comments

2024-06-20 13:33 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/BaseTestClass.java
> +            count = "[0-9]+[.]*[0-9]*";
The decimal point should be 0-1 occurrence rather than 0-n occurrences.  `[.]?`

2024-06-20 13:33 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerJSPApplicationTest.java
> +                    .withFileSystemBind("config.yaml", "/etc/otelcol-contrib/config.yaml", BindMode.READ_WRITE)
Is BindMode read only enough?

2024-06-20 13:33 UTC, fmhwong commented on dev/io.openliberty.http.monitor_fat/fat/src/io/openliberty/http/monitor/fat/ContainerServletApplicationTest.java
> +        //assertTrue(validateMpMetricsHttp(getVendorMetrics(server), resolvedRoute, responseStatus, requestMethod));
Please remove commented out lines if they are not needed.

2024-06-20 13:33 UTC, fmhwong commented on dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/http/MPMetricsHTTPMetricsAdapterImpl.java
> +        Tag requestMethod = new Tag("http_request_method", httpStatAttributes.getRequestMethod());
Can you use the constants defined in https://github.com/open-telemetry/semantic-conventions-java/blob/release/v1.25.0/semconv/src/main/java/io/opentelemetry/semconv/HttpAttributes.java rather than hardcode them here?

2024-06-20 15:10 UTC, Channyboy commented
#build #libby

2024-06-20 15:12 UTC, Channyboy commented on dev/io.openliberty.microprofile.metrics.5.0.internal/src/io/openliberty/microprofile/metrics50/http/MPMetricsHTTPMetricsAdapterImpl.java
> +        Tag requestMethod = new Tag("http_request_method", httpStatAttributes.getRequestMethod());
Seems to be used for `AttributeKey` seems to be a pair object of some sort.
There is the OL `OpenTelemetryConstants` which isn't from Otel  (OL side).
There's this too :https://javadoc.io/doc/io.opentelemetry/opentelemetry-semconv/latest/index.html

But don't find the attribute names/ labels for http metrics.

2024-06-20 18:54 UTC, fmhwong submitted a review, later dismissed
LGTM

2024-06-20 20:25 UTC, Channyboy commented
#build #libby

2024-06-20 20:35 UTC, fmhwong submitted a review, later dismissed
LGTM

2024-06-21 15:56 UTC, Channyboy commented
#build #libby

2024-06-21 18:14 UTC, Channyboy commented
#build #libby

2024-06-21 19:54 UTC, fmhwong approved these changes
LGTM

2024-06-22 15:50 UTC, merged