Ensure fattest.simplicity is available to FAT suites after jar
OpenLiberty/open-liberty pull request #28846
Opened 2024-06-21 18:44 UTC by KyleAure

Currently, FAT suites point to `fattest.simplicity/build/libs/lib/` to get fattest.simplicy and it's dependencies at test runtime.

If I make a change to fattest.simplicity I'd expect that fattest.simplicity will be built and to run against my FAT Suite locally.
Right now that does not happen because fattest.simplicity is only copied to the aforementioned lib directory during the `assemble` task. So any intermediary builds of fattest.simplicity will never be picked up and used by FAT Suites.

Possible solutions:
1. users have to run `./gradlew fattest.simplicity:assemble` after every change.
2. finalize the `jar` task with a task that updates the version of fattest.simplicity in the `fattest.simplicity/build/libs/lib/` which is the goal of this PR.

2024-06-21 20:20 UTC, jhanders34 requested changes
`assembleBinaryDependencies` is what does what you are wanting to happen.  I keep forgetting about finalizedBy.  With this change you should remove `dependsOn assembleBinaryDependencies` from the assemble section of the build.gradle file and update the wlp-gradle/subprojects/fat.gradle to remove `dependsOn ':fattest.simplicity:assembleBinaryDependencies'`.  You are fixing to do things the right way from what I was attempting to do with PRs #28678 and #28722.  #28633 is where what you do here is what should have been done for fattest.simplicity to move it from a dependsOn to a finalizedBy like what it will do now.

2024-06-21 20:20 UTC, jhanders34 commented on dev/fattest.simplicity/build.gradle
> +    finalizedBy assembleSimplicity
```suggestion
    finalizedBy assembleBinaryDependencies
```

2024-06-21 20:20 UTC, jhanders34 commented on dev/fattest.simplicity/build.gradle
> +
```suggestion
```

2024-06-21 21:12 UTC, KyleAure commented
#libby - recheck headers
#build - personal build

2024-06-21 21:13 UTC, jhanders34 approved these changes

2024-06-22 17:45 UTC, KyleAure commented
Pipeline Build: Failed with two known defects
RTC Build: Failed with 3 known defects and a fyre networking issue

2024-06-22 17:45 UTC, merged