Use env values to configure DS after checkpoint
OpenLiberty/open-liberty pull request #28884
Opened 2024-06-25 17:42 UTC by tjwatson

2024-06-25 17:42 UTC, tjwatson commented
#build

2024-06-25 19:30 UTC, KyleAure requested changes

2024-06-25 19:30 UTC, KyleAure commented on dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
> +        }
```suggestion

```

We don't need to worry about the connection properties.  That is already taken care of when we `modifyDataSourcePropsForDatabase` is called.

2024-06-25 19:30 UTC, KyleAure commented on dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
> +        }
```suggestion
        File serverEnvFile;
        if (serv.fileExistsInLibertyServerRoot("server.env")) {
            serverEnvFile = new File(serv.getFileFromLibertyServerRoot("server.env").getAbsolutePath());
        } else {
            serverEnvFile = new File(serv.getInstallRoot() + "/" + "server.env");
            serverEnvFile.createNewFile();
        }

        try (OutputStream out = new FileOutputStream(serverEnvFile)) {
            envProps.store(out, "");
        }
```

I think from earlier testing `serv.getFileFromLibertyServerRoot("server.env")` will throw FileNotFoundException if the file doesn't already exist.
We should handle preemptively handle that.

2024-06-25 19:30 UTC, KyleAure commented on dev/fattest.simplicity/src/componenttest/topology/database/container/DatabaseContainerUtil.java
> +    private static final String DB_PORT = "DB_PORT";
```suggestion
```

2024-07-05 13:05 UTC, tjwatson commented
Not planned

2024-07-05 13:05 UTC, closed without merging