28892 archive weaving
OpenLiberty/open-liberty pull request #28903
Opened 2024-06-26 15:59 UTC by benjamin-confino

fixes #28902

This PR:

- Modifies the fattest.simplicty code for weaving into the TCK test apps so it can add jars, classes, or string files. Previously it could only do string files. 
- Uses the new feature to add a class and a string file to the Telemetry TCKs, this lets the tck use our ManagedExecutorService.
- Updates the pom.xml to for the telemetry TCK to include the stuff I needed to run the tests.

2024-06-27 08:42 UTC, benjamin-confino commented
#build

2024-06-27 10:14 UTC, yasmin-aumeeruddy requested changes

2024-06-27 10:14 UTC, Yas-Franco commented on dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/tckRunner/tck/pom.xml
Remove changes to the TCK. We will make a separate PR when it is staged

2024-06-27 10:14 UTC, Yas-Franco commented on dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/java/io/openliberty/microprofile/telemetry/test/ArquillianLoadableExtension.java
Remove changes to the TCK. We will make a separate PR when it is staged

2024-06-27 10:14 UTC, Yas-Franco commented on dev/io.openliberty.microprofile.telemetry.2.0.internal_fat_tck/publish/tckRunner/tck/src/test/resources/META-INF/services/org.jboss.arquillian.core.spi.LoadableExtension
Remove changes to the TCK. We will make a separate PR when it is staged

2024-06-27 10:17 UTC, yasmin-aumeeruddy commented on dev/fattest.simplicity/src/com/ibm/ws/fat/util/tck/OrgJsonArchiveProcessor.java
> + * Copyright (c) 2024 IBM Corporation and others.
Should be 2019, 2024

2024-06-27 10:38 UTC, benjamin-confino commented
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck

2024-06-27 14:53 UTC, benjamin-confino commented
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck

2024-06-27 20:42 UTC, benjamin-confino commented
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck

2024-06-28 11:20 UTC, benjamin-confino commented
#build

2024-06-29 08:01 UTC, benjamin-confino commented
#build

2024-07-01 08:48 UTC, yasmin-aumeeruddy approved these changes

2024-07-01 08:49 UTC, benjamin-confino commented
#libby

2024-07-01 09:59 UTC, merged