ensure core dumps created in fat tests that go to /var are available …
OpenLiberty/open-liberty pull request #28977
Opened 2024-07-03 08:16 UTC by benjamin-confino

…for debugging

fixes #28976

2024-07-03 08:16 UTC, benjamin-confino commented
#build

2024-07-03 10:26 UTC, websterc87 requested changes
Overrides the existing move of core dumps we need this to be additional.

2024-07-03 10:26 UTC, websterc87 commented on dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
> +		<fileset id="javacores.test" dir="/var/lib/apport/coredump/">
You will need to make different refids and then add them to the move down below

2024-07-03 10:26 UTC, websterc87 commented on dev/fattest.simplicity/autoFVT-defaults/src/ant/launch.xml
> +		<fileset id="javacores.test" dir="/var/crash/">
You will need to make different refids and then add them to the move down below approx line 702

2024-07-03 10:29 UTC, websterc87 approved these changes, later dismissed
Happy assuming it doesnt break during test due to those directories not existing.

2024-07-03 10:30 UTC, benjamin-confino commented
#build

2024-07-03 12:59 UTC, benjamin-confino commented
#build

2024-07-03 13:00 UTC, benjamin-confino commented
Sadly the assumption was not true, after testing, I rewrote with uglier code that checks for those directories explicitly.

2024-07-03 13:36 UTC, websterc87 requested changes
total.length.of.all.javacores is being overloaded and will no longer be accurate

2024-07-03 14:04 UTC, websterc87 approved these changes

2024-07-04 06:58 UTC, benjamin-confino commented
Three test failures. None of them look related to core dump files, but one was related to filepaths. This directory was not found `extractDir:/home/jazz_build/wlpExtract/runnableTestServer_25914883716460/wlp`

I think its unrelated but to be sure I'll run a second build and see if it happens again. 

The other two were an assertion failure in BatchPartitionOldDBTablesTest.testRemotablePartitionOlderTables and an java.lang.IllegalStateException: Bundle has been uninstalled

2024-07-04 06:58 UTC, benjamin-confino commented
#build

2024-07-05 08:48 UTC, benjamin-confino commented
Only one consistent failure across the builds and it matches a pre-existing defect: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=295756

2024-07-05 08:48 UTC, benjamin-confino commented
#libby

2024-07-05 15:33 UTC, merged