Install errors and messages
OpenLiberty/open-liberty pull request #29060
Opened 2024-07-13 01:54 UTC by cbridgha

2024-07-13 01:58 UTC, cbridgha commented
#build

2024-07-13 23:30 UTC, cbridgha commented
#build

2024-07-14 12:42 UTC, cbridgha commented
#build

2024-07-15 13:06 UTC, dmuelle requested changes
ID review

2024-07-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
> +ERROR_MISSING_PLATFORM_NAME=CWWKF1515E: The platform {0} couldn't be found, no versionless features will be installed.
```suggestion
ERROR_MISSING_PLATFORM_NAME=CWWKF1515E: The {0} platform couldn't be found. No versionless features can be installed.
```

2024-07-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
> +ERROR_MISSING_PLATFORM_NAME.explanation=The platform name passed by the config or Env Var wasn't found.
```suggestion
ERROR_MISSING_PLATFORM_NAME.explanation=The platform name that is specified by the configuration or environment variable wasn't found.
```

2024-07-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
> +ERROR_MISSING_PLATFORM_NAME.useraction=Check the spelling of the platform name-version.
```suggestion
ERROR_MISSING_PLATFORM_NAME.useraction=Check the spelling of the platform name and version, for example, microProfile-6.1.
```

2024-07-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
> +ERROR_NO_DERIVED_PLATFORM=CWWKF1516E: Platform couldn't be determined, the following versionless features won't be installed: {0}.
```suggestion
ERROR_NO_DERIVED_PLATFORM=CWWKF1516E: The platform couldn't be determined. The following versionless features can't be installed: {0}.
```

2024-07-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
> +ERROR_NO_DERIVED_PLATFORM.explanation=Platform was not set, or couldn't be derived from existing versioned features.
```suggestion
ERROR_NO_DERIVED_PLATFORM.explanation= The platform was not set or couldn't be derived from existing versioned features. 
```

2024-07-15 13:06 UTC, dmuelle commented on dev/com.ibm.ws.install/resources/com/ibm/ws/install/internal/resources/InstallKernel.nlsprops
> +ERROR_NO_DERIVED_PLATFORM.useraction=Add platform for versionless features
```suggestion
ERROR_NO_DERIVED_PLATFORM.useraction=Add a platform for versionless features.
```

2024-07-16 14:29 UTC, cbridgha commented
#build

2024-07-16 16:06 UTC, dmuelle submitted a review, later dismissed
LGTM, thanks

2024-07-18 15:43 UTC, cbridgha commented
Latest build with all changes: https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.build.viewResult&id=_7eea0ES2Ee-ngPvsOTExmw

2024-07-18 20:24 UTC, jjiwooLim approved these changes
lgtm!

2024-07-18 21:23 UTC, cbridgha commented
#libby

2024-07-18 21:51 UTC, merged