JAX-WS: Timeout added for SSL
OpenLiberty/open-liberty pull request #29156
Opened 2024-07-22 21:51 UTC by BerksanAtes

Timeout added to resolve `junit.framework.AssertionFailedError: SSL Service is not ready.` issue.

2024-07-22 21:51 UTC, BerksanAtes commented
#build

2024-07-23 15:58 UTC, neuwerk approved these changes

2024-07-23 15:59 UTC, neuwerk requested changes
Update copyright header

2024-07-23 16:57 UTC, sawadood approved these changes
Looks good.

2024-07-24 15:21 UTC, neuwerk approved these changes

2024-07-24 15:22 UTC, merged