Code cleanup, debug traces added and reenabling FAT
OpenLiberty/open-liberty pull request #29181
Opened 2024-07-24 19:47 UTC by tonyreigns

Fixes #29169

2024-07-24 19:47 UTC, tonyreigns commented
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.microprofile.telemetry.1.0.internal.container_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat_tck,io.openliberty.microprofile.telemetry.1.1.internal_fat_tck,io.openliberty.microprofile.telemetry.2.0.internal_fat_tck,io.openliberty.http.monitor_fat,io.openliberty.microprofile.telemetry.2.0.logging.internal_fat

2024-07-24 19:57 UTC, pgunapal requested changes
Minor comment update

2024-07-24 19:57 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal/src/io/openliberty/microprofile/telemetry20/logging/internal/MpTelemetryLogMappingUtils.java
> +    //Removes leading new line spaces from strings
Can you make this comment wrapped around /**/ instead, to make it consistent.

2024-07-24 20:05 UTC, pgunapal submitted a review, later dismissed
LGTM

2024-07-24 20:05 UTC, tonyreigns commented
#build

2024-07-25 15:35 UTC, tonyreigns commented
#build

2024-07-26 13:22 UTC, tonyreigns commented
None of the test failures are related to these changes. Message verification was resolved after this build started.

2024-07-26 13:23 UTC, pgunapal approved these changes
Looks good!

2024-07-26 13:29 UTC, merged