JAX-WS: Add enableSchemaValidation tests
OpenLiberty/open-liberty pull request #29182
Opened 2024-07-24 20:24 UTC by neuwerk

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

This PR does the following:

Corrects the resolution of the Port name in the beta method within `AbstractJaxWsWebEndpoint` 
Adds tests for the beta `webService enableSchemaValidation` configuration  to `io.openliberty.jaxws.config_fat`

2024-07-24 20:28 UTC, neuwerk commented
#build

2024-07-26 16:36 UTC, BerksanAtes requested changes
Except timeout comment, others are about one assertion message repeated multiple times.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +    private final static int REQUEST_TIMEOUT = 10;
Is the timeout milliseconds?

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 16:36 UTC, BerksanAtes commented on dev/io.openliberty.jaxws.config_fat/fat/src/io/openliberty/jaxws/config/fat/EnableSchemaValidationWebServiceTest.java
> +        assertTrue("Expected pass response from server, but was " + response, response.contains("echo"));
Expected pass response(echo) doesn't seem like stated in assertion failure.

2024-07-26 18:43 UTC, neuwerk commented
#build

2024-07-26 19:06 UTC, BerksanAtes approved these changes
Look good to me!

2024-07-29 13:16 UTC, neuwerk commented
Failures are unrelated to these changes.

2024-07-29 13:17 UTC, merged