Update EclipseLink 4.0.3 -> 4.0.4
OpenLiberty/open-liberty pull request #29276
Opened 2024-08-05 09:33 UTC by anija-anil

Updating EclipseLink 4.0.3 -> 4.0.4.
for : https://github.com/OpenLiberty/open-liberty/issues/29275

2024-08-05 09:34 UTC, anija-anil commented
#build

2024-08-05 19:36 UTC, tkburroughs commented
Need to run JPA 3.1 tests in full mode...
#build
#spawn.fullfat.buckets = com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec20_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec20_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

2024-08-05 19:42 UTC, tkburroughs requested changes
See io.openliberty.persistence.3.1.thirdparty/build.gradle  There are a couple of message files that should be removed from the `exclude` lists.

If the message changes haven't been contributed back to EclipseLink yet, then that should be done, and the build.gradle file updated to indicate the excludes should be removed in 4.0.5.

Also, since these are excluded, it is possible new messages have been added that have been missed.  At least try to remove them from exclude to see if there are any new or newly changed messages.

2024-08-07 09:18 UTC, anija-anil commented
#build
#spawn.fullfat.buckets = com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec20_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec20_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

2024-08-08 13:47 UTC, tkburroughs requested changes
Please remove the message file changes.... these changes will undo the changes requested by ID during the last up date from 4.0.2 to 4.0.3.... see comments in : https://github.com/OpenLiberty/open-liberty/pull/28824

It appears the changes requested by ID were never contributed back to EclipseLink or did not make it into 4.0.4. Hopefully they can be contributed back to EclipseLink and be included for the 4.0.5 release.  The excludes can then be removed at that time.

2024-08-08 13:47 UTC, tkburroughs commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/exceptions/i18n/ValidationExceptionResource.nlsprops
> +7360=Database password was encrypted by deprecated algorithm.
Please remove this change.... this change will undo the changes requested by ID during the last up date from 4.0.2 to 4.0.3.... see comments in : https://github.com/OpenLiberty/open-liberty/pull/28824

2024-08-08 13:47 UTC, tkburroughs commented on dev/io.openliberty.persistence.3.1.thirdparty/resources/org/eclipse/persistence/internal/localization/i18n/LoggingLocalizationResource.nlsprops
> +encryptor_script_description=This application internally decrypt old encrypted password used by some previous version EclipseLink and encrypt it by latest algorithm.
Please remove this change.... this change will undo the changes requested by ID during the last up date from 4.0.2 to 4.0.3.... see comments in : https://github.com/OpenLiberty/open-liberty/pull/28824

2024-08-08 13:47 UTC, tkburroughs commented on dev/io.openliberty.persistence.3.1.thirdparty/build.gradle
> -          exclude(name: '**/*Resource_*.nlsprops')
Please keep these excludes, but change the comments to indicate they need to be removed with 4.0.0.5 update

2024-08-09 16:04 UTC, anija-anil commented
#build

2024-08-11 21:16 UTC, tkburroughs commented
#build
#spawn.fullfat.buckets = com.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, com.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, com.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, com.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, cnreleastescom.ibm.ws.jpa.tests.spec20_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.query_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.oneXone_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.beanvalidation_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.jpaconfig_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.eclipselink_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.container.checkpoint_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.entitymanager_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.oneXmany_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.packaging_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.entity_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, cnlocatescom.ibm.ws.jpa.tests.spec20_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.inheritance_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.manyXmany_jpa_3.1_fat, com.ibm.ws.jpa.tests.eclipselink.query_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.callback_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.relationships.manyXone_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec10.embeddable_jpa_3.1_fat, com.ibm.ws.jpa.tests.spec20_jpa_3.1_fat

2024-08-12 18:27 UTC, helyarp commented
@tkburroughs Should this PR have the **ID review not needed** label?

2024-08-12 19:01 UTC, tkburroughs commented
@helyarp Correct; I've added "ID review not needed".  There will be no ID changes with this PR.

2024-10-03 05:18 UTC, closed without merging