Moving ESA parse - compare json tests to OL
OpenLiberty/open-liberty pull request #29273
Opened 2024-08-03 17:22 UTC by cbridgha

- [ x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Moving ESA parse sensitive tests to be co-located with source in OL.

2024-08-03 17:25 UTC, cbridgha commented
#libby

2024-08-03 17:25 UTC, cbridgha commented
#build

2024-08-06 13:10 UTC, Azquelt requested changes
Can't merge this with binary .esas.

They would either need to be stored in artifactory and be made available to the test in the bnd or gradle file, or we would need to pull out the important text files from within the .esa, commit that instead and have the test reconstruct the binary archive.

2024-08-06 14:22 UTC, Azquelt commented on dev/com.ibm.ws.repository.parsers/test/com/ibm/ws/repository/parsers/internal/CreateJsonRepositoryFilesTest.java
> +    File baseDir = new File("../com.ibm.ws.repository.parsers");
Wouldn't this just be the current directory?

2024-08-06 14:28 UTC, Azquelt commented on dev/com.ibm.ws.repository.parsers/test/com/ibm/ws/repository/parsers/internal/CreateJsonRepositoryFilesTest.java
> +        createdFile.delete();
Cleanup should be done in a try-finally or in an `@After` method. As it is, the cleanup won't happen if the test fails.

2024-08-06 14:29 UTC, Azquelt commented on dev/com.ibm.ws.repository.parsers/test/com/ibm/ws/repository/parsers/internal/CreateJsonRepositoryFilesTest.java
> +    public void testJsonWithSpecifiedMetadata() throws IOException {
Weird blank line, also on `testEsaJson`

2024-08-06 14:32 UTC, Azquelt commented on dev/com.ibm.ws.repository.test.utils/bnd.bnd
> +				com.ibm.ws.repository.base*; version=1.0
Weird indentation, maybe tabs instead of spaces by accident?

2024-08-06 14:34 UTC, Azquelt commented on dev/io.openliberty.org.testcontainers/cache/projects
> +com.ibm.ws.wsat.recovery_fat.multi.8
The changes in this file do not look related. I would drop them to avoid risk of a conflict with another PR.

2024-08-06 14:40 UTC, Azquelt commented on dev/com.ibm.ws.repository.parsers/resources/esa/esaJsonOnly/com.ibm.websphere.appserver.anno-1.0.esa.json
The location of the test files is questionable.

Usually `resources` is used for files which should be included directly in the product bundle. I'm not sure whether that's going to happen here, but to avoid confusion please move any test files into another directory (e.g. `test-resources`).

2024-08-06 14:40 UTC, Azquelt commented on dev/com.ibm.ws.repository.parsers/bnd.bnd
> +    com.ibm.ws.componenttest;version=latest
Bad formatting

2024-08-15 17:03 UTC, cbridgha commented
closing - using https://github.com/OpenLiberty/open-liberty/pull/29401 to continue work...

2024-08-15 17:03 UTC, closed without merging