Telemetry logging updated fat
OpenLiberty/open-liberty pull request #29298
Opened 2024-08-06 00:29 UTC by tonyreigns

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-08-06 00:29 UTC, tonyreigns commented
#build

2024-08-07 16:06 UTC, tonyreigns commented
#build

2024-08-08 02:59 UTC, tonyreigns commented
#build

2024-08-08 16:18 UTC, tonyreigns commented
#build

2024-08-08 17:15 UTC, tonyreigns commented
#build

2024-08-09 03:18 UTC, tonyreigns commented
#build

2024-08-09 17:26 UTC, pgunapal requested changes
looks good, minor comments

2024-08-09 17:26 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryApplicationConfigTest.java
> +    public static final String SERVER_XML_ALL_SOURCES = "allSources.xml";
I don't think these are used anywhere in this class.

2024-08-09 17:26 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
> +    public static final String APP_NAME = "MpTelemetryLogApp";
Not used.

2024-08-09 17:26 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryFFDCTest.java
> +        Thread.sleep(2000);
Is this still needed?

2024-08-09 19:12 UTC, tonyreigns commented
#build

2024-08-09 19:49 UTC, pgunapal requested changes

2024-08-09 19:49 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
> +        WebArchive app = ShrinkWrap
should we wait till the server is started before dropping in?

2024-08-09 19:49 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
> +        WebArchive app = ShrinkHelper.buildDefaultApp(APP_NAME, "io.openliberty.microprofile.telemetry.logging.internal.fat.MpTelemetryLogApp");
shouldn't we wait till server is started?

2024-08-11 00:56 UTC, tonyreigns commented
#build

2024-08-12 12:53 UTC, tonyreigns commented
#build

2024-08-12 14:53 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
> +        WebArchive app = ShrinkWrap
Will be covered in a follow on PR.

2024-08-12 14:53 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal_fat/TelemetryDropinsTest.java
> +        WebArchive app = ShrinkHelper.buildDefaultApp(APP_NAME, "io.openliberty.microprofile.telemetry.logging.internal.fat.MpTelemetryLogApp");
Will be covered in a follow on PR.

2024-08-12 14:54 UTC, pgunapal approved these changes
Looks good, some minor TO-DOs to be added in a follow on PR.

2024-08-13 01:24 UTC, merged