virtual true not ignored for ManagedThreadFactoryDefinition on Java 17
OpenLiberty/open-liberty pull request #29294
Opened 2024-08-05 20:22 UTC by njr-11

fixes #29292

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-08-05 20:22 UTC, njr-11 commented
#build

2024-08-05 20:26 UTC, njr-11 commented
#libby

2024-08-06 13:50 UTC, dmuelle requested changes
ID review

2024-08-06 13:50 UTC, dmuelle commented on dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
> +CWWKC1217.no.virtual.threads.useraction=Update to Java 21 or higher to enable the \
```suggestion
CWWKC1217.no.virtual.threads.useraction=Update to Java 21 or later to enable the \
```

2024-08-06 13:50 UTC, dmuelle commented on dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
> +CWWKC1217.no.virtual.threads.explanation=Virtual threads are not available prior \
```suggestion
CWWKC1217.no.virtual.threads.explanation=Virtual threads are available only \
```

2024-08-06 13:50 UTC, dmuelle commented on dev/io.openliberty.concurrent.internal/resources/io/openliberty/concurrent/internal/resources/CWWKCMessages.nlsprops
> + to Java 21.
```suggestion
 in Java 21 and later.
```

2024-08-06 13:59 UTC, dmuelle approved these changes
LGTM thanks

2024-08-06 13:59 UTC, njr-11 commented
#build

2024-08-06 22:02 UTC, merged