Ignore test failures when there are network errors
OpenLiberty/open-liberty pull request #29409
Opened 2024-08-15 16:40 UTC by Azquelt

On some test systems we're seeing intermittent network issues. Ignore test failures that are caused by these (unless there's a lot of them).

For RTC 300349

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-08-15 16:40 UTC, Azquelt commented
#build

Still needs testing on the platforms where we're seeing the failures.

2024-08-16 10:19 UTC, Azquelt commented
#build

2024-08-19 14:16 UTC, Azquelt commented
#build

2024-08-19 16:45 UTC, Azquelt commented
Attempt some z/OS builds: https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=235342ec-eabb-4770-8f55-7043bdd0303b

2024-08-20 10:53 UTC, Azquelt commented
There's an error appearing in the build that didn't appear in my local testing.

In the new test, sometimes we see `Caused by: java.lang.ClassNotFoundException: jakarta.servlet.descriptor.JspConfigDescriptor cannot be found by io.openliberty.org.jboss.weld4_1.0.93.202408191140` when the server tries to serialize the session.

2024-08-21 12:16 UTC, Azquelt commented
#libby

2024-08-21 16:01 UTC, benjamin-confino requested changes

2024-08-21 16:01 UTC, benjamin-confino commented on dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/connectivity/ConnectionErrorWatcher.java
> +        failureRatioThreshold = 0.05;
I would suggest changing this to 

`failureRatioThreshold = (System.getProperty("personalBuild") == null) ? 0.05 : 0.00`

I found that property in SOEHttpPostUtil.java. 

That way if we create a legitimate product bug that causes `GrpcExporter - Failed to export spans` we'll see it even if only one test catches it. 

(I plan to verify this by running a test PR that asserts that property is null and see if I get lots of failures)

2024-08-22 08:37 UTC, benjamin-confino commented on dev/io.openliberty.microprofile.telemetry.internal_fat.common/src/io/openliberty/microprofile/telemetry/internal_fat/shared/connectivity/ConnectionErrorWatcher.java
> +        failureRatioThreshold = 0.05;
https://github.com/OpenLiberty/open-liberty/pull/29462 - `System.getProperty("personalBuild")` works as advertised.

2025-01-23 17:24 UTC, Azquelt commented
Decided that the risk of this causing us to miss an actual problem which resulted in a network failure was too great and so we pursued other avenues to avoid these failures.

2025-01-23 17:24 UTC, closed without merging