Add to thread-local oidc client id
OpenLiberty/open-liberty pull request #29435
Opened 2024-08-19 17:01 UTC by wrodrig

There is a need to make the client-id available in the thread running the oidc code.

FIXES PH61850

- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [X] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

# Delete this section and fill in the remaining info from the template

ATTENTION, READ THIS: Updated July 2024 

Read and understand this completely, then delete the static part of the template. 

If a reviewer or merger sees this template, they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue **mentioned in the PR text or description**.  
 
   - That Issue also MUST be labelled “release bug”

     This directs automation to scrape this fix for inclusion in the next release's
     list of bugs fixed.

   - The linkage between PR and Issue should use the `Fixes #...` syntax rather than a manual
     link via the Development widget.

Otherwise, a link to an issue or specific issue labels are optional.

For full details, please see this wiki page: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions
################################################################################################

2024-08-21 14:40 UTC, ayoho requested changes

2024-08-21 14:40 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
> +        setThreatClientId(clientConfig.getClientId());
```suggestion
        setThreadClientId(clientConfig.getClientId());
```

2024-08-21 14:40 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
> +        }
Should never happen since you initialize `threadClientID` when you declare the static variable.

2024-08-21 14:40 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
> +        System.out.println("Setting client id on thread: " + threadClientID.get());
```suggestion
```
We shouldn't be delivering changes with `System.out` statements.

2024-08-21 14:40 UTC, ayoho commented on dev/com.ibm.ws.security.openidconnect.clients.common/src/com/ibm/ws/security/openidconnect/clients/common/OIDCClientAuthenticatorUtil.java
> +        System.out.println("returning client id on thread: " + threadClientID.get());
```suggestion
```
We shouldn't be delivering changes with `System.out` statements.

2024-09-04 20:47 UTC, wrodrig commented
#build
#Libby

2024-09-04 20:48 UTC, wrodrig commented
#build
#Libby

2024-09-04 21:38 UTC, ayoho approved these changes

2024-09-05 19:13 UTC, wrodrig commented
#run-libby-bot

2024-09-06 13:51 UTC, merged