Resolving test timing bug
OpenLiberty/open-liberty pull request #29509
Opened 2024-08-28 15:12 UTC by tonyreigns

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

Fixes RTC: 301419 and 301563

2024-08-28 15:12 UTC, tonyreigns commented
#build

2024-08-29 21:03 UTC, pgunapal requested changes

2024-08-29 21:03 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/TestUtils.java
> +     * Ensure that the container was successfully started.
It would be good to add comments on what this method does, and how long it waits and retries for.

2024-08-29 23:22 UTC, pgunapal approved these changes

2024-08-30 13:59 UTC, tonyreigns commented
#libby

2024-08-30 14:10 UTC, tonyreigns commented
Pipeline errors are unrelated.

2024-08-30 14:10 UTC, merged