Only print container logs when tests fail
OpenLiberty/open-liberty pull request #29569
Opened 2024-09-04 18:42 UTC by tonyreigns

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

2024-09-04 18:42 UTC, tonyreigns commented
#build

2024-09-04 19:56 UTC, pgunapal requested changes

2024-09-04 19:56 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/TestUtils.java
> +        boolean messageExists = expected == actual;
```suggestion
        boolean messageExists = (expected == actual);
```

2024-09-04 19:56 UTC, pgunapal commented on dev/io.openliberty.microprofile.telemetry.2.0.logging.internal.container_fat/fat/src/io/openliberty/microprofile/telemetry/logging/internal/container/fat/LoggingServletTest.java
> +        assertTrue("Log type messagecould not be found.", TestUtils.assertLogContains("testMessageLogs", logs, "io.openliberty.type: Str(liberty_message)"));
```suggestion
        assertTrue("Log type message could not be found.", TestUtils.assertLogContains("testMessageLogs", logs, "io.openliberty.type: Str(liberty_message)"));
```

2024-09-05 13:23 UTC, pgunapal approved these changes
Looks good!

2024-09-05 15:39 UTC, tonyreigns commented
#libby

2024-09-05 17:53 UTC, tonyreigns commented
#libby

2024-09-05 19:24 UTC, merged