29788 use raw tccl
OpenLiberty/open-liberty pull request #29791
Opened 2024-10-04 19:38 UTC by benjamin-confino

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

Currently just for running PBuilds, may turn into a real PR later.

2024-10-04 19:38 UTC, benjamin-confino commented
#build #spawn.fullfat.buckets=com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.jbatch.cdi_fat,io.openliberty.microprofile.metrics.internal.3.0_fat,com.ibm.ws.concurrent_fat_cdi,io.openliberty.data.internal_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,io.openliberty.microprofile.metrics.internal.3.0_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.restfulWS.3.0_fat,io.openliberty.security.jakartasec.3.0.internal_fat

2024-10-05 09:15 UTC, benjamin-confino commented
#build #spawn.fullfat.buckets=com.ibm.ws.cdi.extension_fat,com.ibm.ws.cdi.visibility_fat,com.ibm.ws.jbatch.cdi_fat,io.openliberty.microprofile.metrics.internal.3.0_fat,com.ibm.ws.concurrent_fat_cdi,io.openliberty.data.internal_fat,com.ibm.ws.microprofile.faulttolerance.cdi_fat,io.openliberty.microprofile.metrics.internal.3.0_fat,io.openliberty.microprofile.telemetry.1.0.internal_fat,io.openliberty.restfulWS.3.0_fat,io.openliberty.security.jakartasec.3.0.internal_fat

2024-10-07 12:29 UTC, benjamin-confino commented
#build

2024-10-10 13:11 UTC, Azquelt commented on dev/com.ibm.ws.cdi.weld/src/com/ibm/ws/cdi/impl/weld/WebSphereCDIDeploymentImpl.java
> +                    }
```suggestion
                    //We had a customer who wishes to ensure the TCCL is the same in the constructor and in the observer methods.
                    //This is only possible for one TCCL per application due to limitations in weld.
                    boolean matchesAppTCCL = classLoadingServiceCaller.run((@SuppressWarnings("rawtypes") LibertyClassLoadingService cl) -> {
                        return cl.isThreadContextClassLoaderForAppClassLoader(application.getTCCL(), classLoader);
                    }).orElseThrow(() -> new IllegalStateException("ClassLoadingService missing"));

                    ClassLoader newTCCL = classLoader;
                    if (matchesAppTCCL) {
                        newTCCL = application.getTCCL();
                    }
```

2024-10-10 13:19 UTC, Azquelt approved these changes

2024-10-10 13:19 UTC, Azquelt commented
Please add a more descriptive title to the PR.

2024-10-10 13:21 UTC, Azquelt requested changes
Please update the PR title and the commit description.

Usually I'm not too fussed about the commit description, but this one says it's just adding tests while it actually includes implementation changes.

2024-10-10 21:09 UTC, benjamin-confino commented
#build

2024-10-11 09:17 UTC, Azquelt approved these changes
Looks good, thanks

2024-10-11 14:30 UTC, benjamin-confino commented
#libby

2024-10-11 14:30 UTC, benjamin-confino commented
Only test failure was an intermittent `Another server (cloud0021) has locked the HA lock row` in com.ibm.ws.transaction.cloud_fat.oracle.0. I think that's unrelated.

2024-10-12 19:18 UTC, merged