Refactor TCK Runner and ensure TCK result files are well formed
OpenLiberty/open-liberty pull request #29817
Opened 2024-10-09 22:41 UTC by KyleAure

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-10-09 22:42 UTC, KyleAure commented
#build - run personal build as proof of concept

2024-10-10 14:56 UTC, KyleAure commented
#build - personal build
#libby - check headers

2024-10-11 16:21 UTC, Azquelt requested changes
This looks like an excellent improvement to the usability of `TCKRunner`, thank you!

My only comments are small formatting issues (likely caused by older projects without good project formatting settings) and a few typos.

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.graphql_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
> +        	.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.openapi.1.1_fat_tck/fat/src/org/eclipse/microprofile/openapi/fat/tck/OpenAPITckTest.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.openapi_fat_tck/fat/src/org/eclipse/microprofile/openapi/fat/tck/OpenAPITckTest.java
> +        	.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.opentracing.1.1_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing11/tck/OpentracingTCKLauncher.java
> +    		.runTCK();
Tab-space mix (in fairness this one had a tab in it already)

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.opentracing.1.2_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing12/tck/OpentracingTCKLauncher.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing13/tck/OpentracingRestClientTCKLauncher.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing13/tck/OpentracingTCKLauncher.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.opentracing.1.3_fat_tck/fat/src/com/ibm/ws/microprofile/opentracing13/tck/OpentracingTCKLauncherMicroProfile.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.opentracing_fat_tck/fat/src/org/eclipse/microprofile/opentracing/fat/tck/OpentracingTCKLauncher.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.rest.client11_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +            	.runTCK();
Tab-space mix - this one was already a mess, but could we clean it up please?

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.rest.client12_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +            	.runTCK();
Tab-space mix (previously a mess)

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.rest.client13_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +            	.runTCK();
Tab-space mix (previously a mess)

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.rest.client14_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +            	.runTCK();
Tab-space mix (previously a mess)

2024-10-11 16:21 UTC, Azquelt commented on dev/com.ibm.ws.microprofile.rest.client_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +            	.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.graphql.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/graphql/tck/GraphQLTckPackageTest.java
> +        	.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.health.3.0.internal_fat_tck/fat/src/io/openliberty/microprofile/health30/tck/Health30TCKLauncher.java
> +                        .runTCK();
Copyright date not updated

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingRestClientTCKLauncher.java
> +        	.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncher.java
> +	}
Converting this whole file to tabs is certainly better than leaving it as a mix, but I'm unsure if it was deliberate as the other files in the project appear to use spaces.

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.opentracing.2.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncherMicroProfile.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingRestClientTCKLauncher.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncher.java
> +	}
Is the change to all-tabs deliberate here too?

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.opentracing.3.0.internal_fat_tck/fat/src/io/openliberty/microprofile/opentracing/internal/tck/OpentracingTCKLauncherMicroProfile.java
> +    		.runTCK();
Tab-space mix

2024-10-11 16:21 UTC, Azquelt commented on dev/io.openliberty.microprofile.rest.client.2.0.internal_fat_tck/fat/src/org/eclipse/microprofile/rest/client/tck/RestClientTckPackageTest.java
> +            	.runTCK();
Tab-space mix (previously a mess)

2024-10-11 16:21 UTC, Azquelt commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
> +                return "Microprofile " + specName + " " + getSpecVersion();
```suggestion
                return "MicroProfile " + specName + " " + getSpecVersion();
```

2024-10-11 16:21 UTC, Azquelt commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
> +                return "UKNOWN";
```suggestion
                return "UNKNOWN";
```

2024-10-11 16:21 UTC, Azquelt commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
> +    }
Should this method be either public or private?

2024-10-11 16:21 UTC, Azquelt commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
> +        String redeableRepeatName = getRepeat();
`redeableRepeatName` -> `readableRepeatName`

2024-10-11 22:24 UTC, KyleAure commented
@Azquelt - Thanks for the thorough review.  I suffered through and updated my eclipse and re-built everything to get the formatting issues resolved. 🎊

2024-10-11 22:24 UTC, KyleAure commented
#build - personal build
#libby - re-check headers

2024-10-14 13:40 UTC, KyleAure commented
#build - redo personal build after rebase and fix
#libby - recheck headers

2024-10-14 13:57 UTC, Azquelt approved these changes
Looks great, thanks :+1:

2024-10-14 14:58 UTC, jakub-pomykala approved these changes
LGTM!

2024-10-14 22:34 UTC, KyleAure commented
Pipeline: passed
RTC Build: pending

ready to merge once build con improves.

2024-10-16 13:31 UTC, KyleAure commented
Double checked to ensure no new TCK projects were pushed to Integration prior to merging this PR. 
🤞🏼 This does not end up causing a soft merge conflict.

2024-10-16 13:31 UTC, merged