Fix test_SPNEGO_OIDC_CreateClientWithEveryParamVariation1
OpenLiberty/open-liberty pull request #29886
Opened 2024-10-17 16:26 UTC by wrodrig

Failure is seeing that looks like this:
test_SPNEGO_OIDC_CreateClientWithEveryParamVariation1:java.lang.NoSuchFieldError: 2024-08-16-09:07:21:909 INSTANCE     at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:53)     at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<init>(DefaultHttpRequestWriterFactory.java:57)     at org.apache.http.impl.io.DefaultHttpRequestWriterFactory.<clinit>(DefaultHttpRequestWriterFactory.java:47)     at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:83)     at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:96)     at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<init>(ManagedHttpClientConnectionFactory.java:105)     at org.apache.http.impl.conn.ManagedHttpClientConnectionFactory.<clinit>(ManagedHttpClientConnectionFactory.java:63)     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$InternalConnectionFactory.<init>(PoolingHttpClientConnectionManager.java:620)     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:181)     at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.<init>(PoolingHttpClientConnectionManager.java:165)     at com.gargoylesoftware.htmlunit.HttpWebConnection.createConnectionManager(HttpWebConnection.java:1183)     at com.gargoylesoftware.htmlunit.HttpWebConnection.reconfigureHttpClientIfNeeded(HttpWebConnection.java:652)     at com.gargoylesoftware.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:172)     at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1536)     at com.gargoylesoftware.htmlunit.WebClient.loadWebResponse(WebClient.java:1459)     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:447)     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:368)     at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:536)

This is because the bnd.bnd is pulling two versions of the httpcore bundle. This change fixes that

- [X] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-10-17 16:27 UTC, wrodrig commented
#build
#Libby

2024-10-17 18:19 UTC, wrodrig commented
#build
#Libby

2024-10-17 19:25 UTC, ayoho requested changes

2024-10-17 19:25 UTC, ayoho commented on dev/com.ibm.ws.security.oidc.server_fat.spnego/bnd.bnd
> +# Copyright (c) 2024 IBM Corporation and others.
```suggestion
# Copyright (c) 2021, 2024 IBM Corporation and others.
```

2024-10-17 19:27 UTC, ayoho approved these changes

2024-10-17 19:45 UTC, wrodrig commented
#Libby

2024-10-17 21:52 UTC, wrodrig commented
#build
#Libby

2024-10-23 17:13 UTC, wrodrig commented
#build
#Libby

2024-10-24 15:15 UTC, merged