chore: enable database rotation for Jakarta Data DDLGen testing
OpenLiberty/open-liberty pull request #29968
Opened 2024-10-25 22:24 UTC by KyleAure

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

- Enable DatabaseRotation for DDL Gen testing
- Create a common DDL Generation helper class
- Execute DDL file on servlet
- Create a database user and schema on databases for testing

2024-10-25 22:24 UTC, KyleAure commented
#build - personal build
#libby - check headers

2024-10-25 22:29 UTC, KyleAure commented
DB Rotation Pipeline: https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=80a50c93-ba04-4f7d-9b41-32b2e27cfd6f

Target locations of links might be accessible only to IBM employees.

2024-10-27 19:05 UTC, KyleAure commented
RTC Build: Passed
Pipeline: Failed with 1 known z/OS defect
DB Rotation: Failed with 5 known JPA defects

2024-10-28 13:22 UTC, njr-11 requested changes
This looks great!  I spotted one minor bug in a test utility method and added a suggestion for it.

2024-10-28 13:22 UTC, njr-11 commented on dev/fattest.simplicity/src/componenttest/topology/utils/DDLGenScript.java
> +            assertEquals("Expected number of ddl files did not match actual number of files", expectedFileNames.size(), getFileNames());
This was comparing a number of files to a list of files. In the suggestion to correct that, I also added the list of observed files to the error message to help with debugging.
```suggestion
            List<String> observedFileNames = getFileNames();
            assertEquals("Expected number of ddl files did not match actual number of files " + observedFileNames,
                         expectedFileNames.size(),
                         observedFileNames.size());
```

2024-10-28 16:00 UTC, KyleAure commented
#build

2024-10-28 16:01 UTC, njr-11 approved these changes

2024-10-30 13:14 UTC, KyleAure commented
Pipeline: Failed with 1 known defect
RTC Build: Failed with 1 known build time error

2024-10-30 13:14 UTC, merged