test: finish unit testing TCKResultInfo
OpenLiberty/open-liberty pull request #29971
Opened 2024-10-27 21:32 UTC by KyleAure

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

Previous changes to TCKResultInfo were not fully unit tested because we had no method to mock a Liberty server.
- Introduced mockito to the fattest.simplicity unit tests
- Finished writing unit tests
- Modified to the readable repeat name method to avoid duplicate seperators
  - used to return: `_remove_persistence-3.1-_jpa-2.2-_jpa-2.1-_persistence-3.0_add_persistence-3.2`
  - will not return: `_remove_persistence-3.1-jpa-2.2-jpa-2.1-persistence-3.0_add_persistence-3.2`

2024-10-27 21:32 UTC, KyleAure commented
#build

2024-10-28 14:34 UTC, Azquelt commented
For reference: this is following on from the changes in #29817

2024-10-28 14:37 UTC, Azquelt commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
>          }
The need to change this highlights an issue - this was added in the previous PR, but it's not clear from the method name what it's really for. I'm unsure it does make the repeat name any more readable - but it looks like it's used as part of the directory and filename for the results?

We should probably rename the method and add some Javadoc to explain what it's supposed to do. As it stands, someone could come along and change it to make the output "more readable" and likely break something.

2024-10-28 14:39 UTC, Azquelt commented on dev/fattest.simplicity/src/componenttest/topology/utils/tck/TCKResultsInfo.java
>          }
It might have been easier to extract this logic out into its own static method so that you could unit test it directly rather than using mockito. However, since you need mockito _anyway_ to test the filename construction, it's fine like this.

2024-10-28 14:43 UTC, Azquelt requested changes
Please consider renaming and documenting `getReadableRepeatName()`

2024-10-28 15:57 UTC, KyleAure commented
@Azquelt - Thanks for the feedback.  I updated the method name to be `getDirectoryName()` because the repeat is used to construct a unique directory between repeats for runs.  Let me know if that works as a good compromise.

2024-10-28 16:20 UTC, Azquelt approved these changes
Yep, that looks good to me, thanks.

2024-10-28 18:01 UTC, KyleAure commented
#build - redo personal build
#libby - check headers

2024-10-30 13:12 UTC, KyleAure commented
Pipeline: Failed with 6 known defects
RTC Build: Failed with 1 known defect, and 1 infrastructure issue

2024-10-30 13:12 UTC, merged