Ws32050 remove beta
OpenLiberty/open-liberty pull request #30032
Opened 2024-11-01 10:20 UTC by benjamin-confino

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-11-01 10:22 UTC, benjamin-confino commented on dev/io.openliberty.microprofile.telemetry.internal.common/src/io/openliberty/microprofile/telemetry/internal/interfaces/OpenTelemetryAccessor.java
> -        //TOOD when the SPI is out of beta, make this a redirect to the SPI accessor to avoid code duplication
I did this inverted, as most calls will come through this class so redirecting into it saves one more hop for the most used path.

2024-11-01 10:22 UTC, benjamin-confino commented
#build

2024-11-03 20:13 UTC, benjamin-confino commented
#build

2024-11-05 13:11 UTC, Azquelt requested changes
Changes in this PR look ok, but we can't consider merging it at the moment because the related tests are only testing against `mpTelemetry-2.0` and not `1.0` or `1.1`.

2024-11-05 13:27 UTC, benjamin-confino commented
#build

2024-11-12 10:18 UTC, benjamin-confino commented
The force push was removing the commit to update the repeat tests, that was delivered under https://github.com/OpenLiberty/open-liberty/pull/30071

2024-11-12 10:18 UTC, benjamin-confino commented
#build

2024-11-12 10:18 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=40d149bb-45e6-472c-a242-8933b7a74c9e

Target locations of links might be accessible only to IBM employees.

2024-11-12 11:17 UTC, Azquelt approved these changes

2024-11-12 19:28 UTC, benjamin-confino commented
The lite fats have finished with no failures in the telemetry fats.

2024-11-12 19:28 UTC, merged

2024-11-12 19:52 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=40d149bb-45e6-472c-a242-8933b7a74c9e has errors/failures.