JAX-WS: SAAJ update
OpenLiberty/open-liberty pull request #30119
Opened 2024-11-08 21:53 UTC by BerksanAtes

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-11-08 22:02 UTC, BerksanAtes commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.ejb_fat, io.openliberty.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.jaxws_fat, io.openliberty.jaxws.beanvalidation_fat, io.openliberty.jaxws.config_fat, io.openliberty.jaxws.executor_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl, io.openliberty.ws.jaxws.tools_fat, io.openliberty.jaxws.wsat_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6

2024-11-08 22:02 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b4e9ce48-9486-4d69-8ecd-2c7ab9989463

Target locations of links might be accessible only to IBM employees.

2024-11-08 22:13 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 1 product code files were changed.

2024-11-08 22:14 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=b4e9ce48-9486-4d69-8ecd-2c7ab9989463 has errors/failures.

2024-11-08 22:14 UTC, BerksanAtes commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.ejb_fat, io.openliberty.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.jaxws_fat, io.openliberty.jaxws.beanvalidation_fat, io.openliberty.jaxws.config_fat, io.openliberty.jaxws.executor_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl, io.openliberty.ws.jaxws.tools_fat, io.openliberty.jaxws.wsat_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6

2024-11-08 22:15 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=a829a101-3f23-4af7-bba5-eac9ee02cc42

Target locations of links might be accessible only to IBM employees.

2024-11-08 22:22 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 1 product code files were changed.

2024-11-09 05:07 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=a829a101-3f23-4af7-bba5-eac9ee02cc42 has errors/failures.

2024-11-09 17:16 UTC, BerksanAtes commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.ejb_fat, io.openliberty.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.jaxws_fat, io.openliberty.jaxws.beanvalidation_fat, io.openliberty.jaxws.config_fat, io.openliberty.jaxws.executor_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl, io.openliberty.ws.jaxws.tools_fat, io.openliberty.jaxws.wsat_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6

2024-11-09 17:16 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ac28c6ce-4eea-4d93-8367-1fe896987df2

Target locations of links might be accessible only to IBM employees.

2024-11-10 02:57 UTC, BerksanAtes commented
#build
#spawn.fullfat.buckets=com.ibm.ws.jaxws.webcontainer_fat, com.ibm.ws.jaxws.2.2.webcontainer_fat_extended, com.ibm.ws.jaxws.cdi_fat, com.ibm.ws.jaxws.clientcontainer_fat, com.ibm.ws.jaxws.ejb_fat, io.openliberty.jaxrs.2.1.jaxws.2.2_fat, io.openliberty.jaxws_fat, io.openliberty.jaxws.beanvalidation_fat, io.openliberty.jaxws.config_fat, io.openliberty.jaxws.executor_fat, io.openliberty.ws.jaxws.global.handler.internal_fat, io.openliberty.jaxws.security_fat, io.openliberty.jaxws.security_fat.1, io.openliberty.jaxws.security_fat.ssl, io.openliberty.ws.jaxws.tools_fat, io.openliberty.jaxws.wsat_fat, com.ibm.ws.wssecurity_fat.wsscxf.1, com.ibm.ws.wssecurity_fat.wsscxf.2, com.ibm.ws.wssecurity_fat.wsscxf.3, com.ibm.ws.wssecurity_fat.wsscxf.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.1, com.ibm.ws.wssecurity_fat.wsscxf.saml.2, com.ibm.ws.wssecurity_fat.wsscxf.saml.3, com.ibm.ws.wssecurity_fat.wsscxf.saml.4, com.ibm.ws.wssecurity_fat.wsscxf.saml.5, com.ibm.ws.wssecurity_fat.wsscxf.saml.6

2024-11-10 02:58 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=52d6df02-2264-4fe6-9270-b6473966a097

Target locations of links might be accessible only to IBM employees.

2024-11-10 03:05 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 3 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 1 product code files were changed.

2024-11-10 09:24 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ac28c6ce-4eea-4d93-8367-1fe896987df2 has errors/failures.

2024-11-10 10:44 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=52d6df02-2264-4fe6-9270-b6473966a097 completed successfully!

2024-11-10 13:51 UTC, contbld commented
The build BerksanAtes-30119-20241109-1813
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_38zhUJ7_Ee-kGLEyqlUFUA
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_38zhUJ7_Ee-kGLEyqlUFUA

2024-11-10 16:54 UTC, contbld commented
The build BerksanAtes-30119-20241109-1636
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_K1r8MJ6aEe-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_K1r8MJ6aEe-M9e5esDPP_g

2024-11-10 17:33 UTC, contbld commented
The build BerksanAtes-30119-20241109-1636
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_75etgJ6XEe-M9e5esDPP_g
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_75etgJ6XEe-M9e5esDPP_g

2024-11-10 21:34 UTC, contbld commented
The build BerksanAtes-30119-20241109-2354
https://wasrtc.hursley.ibm.com:9443/jazz/resource/itemOid/com.ibm.team.build.BuildResult/_Xm5wMJ8vEe-kGLEyqlUFUA
completed and has errors or failures.

For help analyzing your personal build, go to https://libh-proxy1.fyre.ibm.com/cognitive/buildAnalysis.html?uuid=_Xm5wMJ8vEe-kGLEyqlUFUA

2024-11-12 23:31 UTC, BerksanAtes commented
#build

2024-11-12 23:32 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=85f39a64-2f7a-4ea5-a251-bf1575851e98

Target locations of links might be accessible only to IBM employees.

2024-11-12 23:39 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 10 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 1 product code files were changed.

2024-11-13 09:57 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=85f39a64-2f7a-4ea5-a251-bf1575851e98 has errors/failures.

2024-11-13 16:49 UTC, neuwerk requested changes

2024-11-13 16:49 UTC, neuwerk commented on dev/io.openliberty.jaxws_fat/fat/src/com/ibm/ws/jaxws22/fat/SAAJBasicTest.java
> + * Migrated from tWAS based com.ibm.ws.jaxws_fat jaxws22/mtom/** bucket
You should clean these comments up since they may or may not apply

2024-11-13 16:49 UTC, neuwerk commented on dev/io.openliberty.jaxws_fat/test-applications/saajclient/src/fats/cxf/jaxws22/saaj/client/SAAJTestServlet.java
> +        assertFalse("Duplicated namespace in SOAP Body!", soapMessageString.contains("<ns0:getEcho xmlns=\"http://objects.get.echo.io\" xmlns:ns0=\"http://objects.get.echo.io\">"));
We've had a lot of test failures around how XML is serialized, we need to change the assert to something that doesn't rely on namespace ordering an specific prefixes.

2024-11-13 21:41 UTC, BerksanAtes commented
#build

2024-11-13 21:41 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3fc39eda-932c-4faa-8f31-f2eee60bda22

Target locations of links might be accessible only to IBM employees.

2024-11-13 21:48 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 10 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

- 2 product code files were changed.

2024-11-14 08:17 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=3fc39eda-932c-4faa-8f31-f2eee60bda22 completed successfully!

2024-11-15 15:22 UTC, neuwerk requested changes

2024-11-15 15:22 UTC, neuwerk commented on dev/cnf/dependabot/check_this_in_if_it_changes/pom.xml
> +    <dependency>
Does this entry need to be here if we've updated the old one to the new version?

2024-11-15 15:50 UTC, neuwerk approved these changes

2024-11-15 15:53 UTC, merged