Fix premature startup mode exit - issue 29944
OpenLiberty/open-liberty pull request #30116
Opened 2024-11-08 16:43 UTC by gjdeval

- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

`Fixes #29944`

Two problems are addressed by these changes:
1) The first call to `CpuInfo.getJavaCpuUsage()` always returns 0, so we should not look at that first reading as an indicator that "no cpu was used in the prior thread pool controller cycle"
2) CICS replaces the original Liberty thread pool after Liberty launches, during the startup process, so watching the thread pool too closely immediately after launch can show unexpected behavior

2024-11-11 23:11 UTC, jhanders34 requested changes

2024-11-11 23:11 UTC, jhanders34 commented on dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
> +        controllerCycle++;
Updating it here changes its definition from what is in the javadoc.  I think it is wrong to set it here based off of its current meaning.  Maybe you need a separate variable or maybe we check to see if the previous processCpuUtil is -1?  Also there is some other discussion regarding when cpu usage is called in a later comment which may make checking cycle count moot.

2024-11-11 23:11 UTC, jhanders34 commented on dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
> +                processCpuUtil = CpuInfo.getJavaCpuUsage();
When you said you were getting it earlier, I thought it meant that you were calling it before the initial run of the task, like in the constructor.  I would think that both the system and process cpu should be done at that time to prime them both.  Also when restoring from checkpoint I am guessing we should update them at the time as well.  Do not that you will want to rebase your branch on the latest code to pick up Tom's recent changes in this class.

2024-11-11 23:11 UTC, jhanders34 commented on dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
> +                processCpuUtil = CpuInfo.getJavaCpuUsage();
I do wonder though for processCpuUtil and systemCpuUtil on whether both should be called above the try to always be calculated.

2024-11-12 14:07 UTC, gjdeval commented on dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
> +                processCpuUtil = CpuInfo.getJavaCpuUsage();
I agree with both suggestions - had debated similar options without coming to a strong opinion.
So I will add calls to get process and system CPU to the constructor for early initialization, and move the calls for each cycle to before the try block.

2024-11-12 14:14 UTC, gjdeval commented on dev/com.ibm.ws.threading/src/com/ibm/ws/threading/internal/ThreadPoolController.java
> +        controllerCycle++;
The primary purpose of `startupHangControllerCyclesSkip` is to allow for the CICS thread pool manipulation to complete before we start checking whether the thread pool has hung during startup, though I think there is no harm to letting the first couple of cycles go unchecked for other environments as well.

I'll move `controllerCycle++` back to its prior location, and just decrement  `startupHangControllerCyclesSkip` (have to remove `final` attribute) each time through the `if (!initialStartupCompleted) {` block until it is 0, at which point the logic for checking hang during startup can run.

2024-11-12 17:51 UTC, gjdeval commented
#build

2024-11-12 17:51 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ceef6eb3-53b7-4104-8ad2-5444621ed16c

Target locations of links might be accessible only to IBM employees.

2024-11-12 17:58 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

2024-11-13 00:57 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=ceef6eb3-53b7-4104-8ad2-5444621ed16c has errors/failures.

2024-11-13 17:27 UTC, gjdeval commented
#libby

2024-11-13 17:27 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=79cdaedc-988c-4971-8ed6-671f7ce0753e

Target locations of links might be accessible only to IBM employees.

2024-11-13 17:35 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

2024-11-13 17:35 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=79cdaedc-988c-4971-8ed6-671f7ce0753e completed successfully!

2024-11-13 22:11 UTC, jhanders34 approved these changes

2024-11-13 22:16 UTC, gjdeval commented
#libby

2024-11-13 22:17 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9aeb8fd9-7f67-4b1f-8fc0-ef44f749e234

Target locations of links might be accessible only to IBM employees.

2024-11-13 22:24 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 1 product code files were changed.

2024-11-13 22:25 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=9aeb8fd9-7f67-4b1f-8fc0-ef44f749e234 completed successfully!

2024-11-13 22:51 UTC, merged