Upgrading jackson
OpenLiberty/open-liberty pull request #30148
Opened 2024-11-13 10:24 UTC by i004ncc

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

# Delete this section and fill in the remaining info from the template

ATTENTION, READ THIS: Updated July 2024 

Read and understand this completely, then delete the static part of the template. 

If a reviewer or merger sees this template, they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue **mentioned in the PR text or description**.  
 
   - That Issue also MUST be labelled “release bug”

     This directs automation to scrape this fix for inclusion in the next release's
     list of bugs fixed.

   - The linkage between PR and Issue should use the `Fixes #...` syntax rather than a manual
     link via the Development widget.

Otherwise, a link to an issue or specific issue labels are optional.

For full details, please see this wiki page: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions
################################################################################################

2024-12-16 15:11 UTC, WhiteCat22 requested changes

2024-12-16 15:11 UTC, WhiteCat22 commented on dev/io.openliberty.jsonsupport.internal/src/com/ibm/ws/jsonsupport/internal/JSONJacksonImpl.java
> +            System.out.println("The value from stringify is" + s);
You'll want to remove this or make it a debug statement :)

2024-12-16 15:11 UTC, WhiteCat22 commented on dev/io.openliberty.jsonsupport.internal/src/com/ibm/ws/jsonsupport/internal/JSONJacksonImpl.java
> +            System.out.println("=====    Inclusion is Always    =====");
You'll want to remove this or make it a debug statement :)

2024-12-16 15:11 UTC, WhiteCat22 commented on dev/io.openliberty.jsonsupport.internal/src/com/ibm/ws/jsonsupport/internal/JSONJacksonImpl.java
> +            System.out.println("=====    Inclusion is Non Null    =====");
You'll want to remove this or make it a debug statement :)

2024-12-16 15:46 UTC, WhiteCat22 submitted a review, later dismissed

2024-12-16 17:14 UTC, jhanders34 requested changes

2024-12-16 17:14 UTC, jhanders34 commented on dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/repository.xml
> +            <version-range>[2.0.0,3.0.0)</version-range>
```suggestion
            <version-range>[1.0.0,1.1.0)</version-range>
```
The bundle version is still 1.0

2024-12-16 17:14 UTC, jhanders34 commented on dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/repository.xml
> +            <version-range>[2.0.0,3.0.0)</version-range>
```suggestion
            <version-range>[1.0.0,1.1.0)</version-range>
```
The bundle version is still 1.0

2024-12-16 17:14 UTC, jhanders34 commented on dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/repository_WL.xml
> +            <version-range>[2.0.0,3.0.0)</version-range>
```suggestion
            <version-range>[1.0.0,1.1.0)</version-range>
```
The bundle version is still 1.0

2024-12-16 17:14 UTC, jhanders34 commented on dev/com.ibm.ws.kernel.feature.resolver_fat/publish/verify/repository_WL.xml
> +            <version-range>[2.0.0,3.0.0)</version-range>
```suggestion
            <version-range>[1.0.0,1.1.0)</version-range>
```
The bundle version is still 1.0

2024-12-16 17:14 UTC, jhanders34 commented on dev/com.ibm.ws.ui/main.bnd
> +  io.openliberty.jsonsupport.internal.*;version='[2.0,3.0)', \
```suggestion
  com.ibm.websphere.jsonsupport.*;version='[2.0,3.0)', \
```
The exported package name did not change.

2024-12-16 18:12 UTC, i004ncc commented
!build
git.clone.checkout.branch=upgrade_jackson_1x_WS_CD_part
git.clone.repository.sshUrl=git@github.ibm.com:NANDAKRISHNANPN/WS-CD-Open.git
git.clone.repository.username=NANDAKRISHNANPN
fat.buckets.to.run=all

2024-12-16 19:16 UTC, jhanders34 approved these changes

2024-12-17 16:12 UTC, i004ncc commented
!build
git.clone.checkout.branch=upgrade_jackson_1x_WS_CD_part
git.clone.repository.sshUrl=git@github.ibm.com:NANDAKRISHNANPN/WS-CD-Open.git
git.clone.repository.username=NANDAKRISHNANPN
fat.buckets.to.run=all

2024-12-19 13:01 UTC, merged