Added test case for recreating OL issue 29781
OpenLiberty/open-liberty pull request #30179
Opened 2024-11-14 09:08 UTC by ajaypaul-ibm

This PR contains the test case for recreating the OL issue #29781 
- [x] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [x] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [x] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-11-14 09:11 UTC, ajaypaul-ibm commented
#libby
#build

2024-11-14 09:11 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=1d831969-9197-4a5e-b148-3bae47310792

Target locations of links might be accessible only to IBM employees.

2024-11-14 09:11 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=dcda4c8f-50a7-4cb7-b2e7-747ec512c167

Target locations of links might be accessible only to IBM employees.

2024-11-14 09:19 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

2024-11-14 09:19 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

2024-11-14 09:20 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=1d831969-9197-4a5e-b148-3bae47310792 completed successfully!

2024-11-14 12:27 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=dcda4c8f-50a7-4cb7-b2e7-747ec512c167 has errors/failures.

2024-11-14 15:50 UTC, KyleAure requested changes

2024-11-14 15:50 UTC, KyleAure commented on dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
> +    @Ignore("Reference issue : https://github.com/OpenLiberty/open-liberty/issues/29781)
```suggestion
    @Ignore("Reference issue : https://github.com/OpenLiberty/open-liberty/issues/29781")
```

Compile error: forgot closing `"`

2024-11-14 15:54 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
> +    @Ignore("Reference issue : https://github.com/OpenLiberty/open-liberty/issues/29781)
oops ! Will fix that now . Thanks

2024-11-14 16:31 UTC, ajaypaul-ibm commented on dev/com.ibm.ws.jpa.tests.jpa_32_fat/test-applications/jakartadata/src/io/openliberty/jpa/data/tests/web/JakartaDataRecreateServlet.java
> +    @Ignore("Reference issue : https://github.com/OpenLiberty/open-liberty/issues/29781)
@KyleAure I have removed the ignore since 29781 is passing now.

2024-11-14 17:27 UTC, KyleAure commented
#build - start new personal build
#libby - recheck headers

2024-11-14 17:27 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=258fc045-d0df-471f-9956-8d4467d7f9cf

Target locations of links might be accessible only to IBM employees.

2024-11-14 17:27 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bfbd9b60-6955-45c8-be3c-3d972277a9ca

Target locations of links might be accessible only to IBM employees.

2024-11-15 00:14 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

2024-11-15 00:25 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=258fc045-d0df-471f-9956-8d4467d7f9cf completed successfully!

2024-11-15 01:10 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 2 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

2024-11-15 04:34 UTC, contbld commented
https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=bfbd9b60-6955-45c8-be3c-3d972277a9ca completed successfully!

2024-11-15 15:14 UTC, KyleAure commented
Personal Database SOE (all databases): https://libh-proxy1.fyre.ibm.com/cognitive-dev/pipelineAnalysis.html?pipelineId=4c9ae640-3f57-4ef7-8ccb-47101205af2b

Target locations of links might be accessible only to IBM employees.

2024-11-15 15:15 UTC, KyleAure commented
### Build Status
Pipeline: Completed, no failures
RTC Build: (in progress)
Database SOE: (in progress)

Wait to merge until all build results are obtained

2024-11-15 15:16 UTC, KyleAure approved these changes

2024-11-18 14:59 UTC, ajaypaul-ibm commented
@KyleAure Can we merge  this PR ?

2024-11-18 15:41 UTC, merged