Modify mpHealth delayedServlet mechanism to reduce time.
OpenLiberty/open-liberty pull request #30224
Opened 2024-11-18 22:24 UTC by Channyboy

Update delayed servlet to only wait 15 seconds. We will not deploy it in dropins in after server is started to mock the scenario where the server has started but the app is still struggling to start. This is better than a blind 90 second wait

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

2024-11-18 22:24 UTC, Channyboy commented
#build

2024-11-18 22:25 UTC, contbld commented
Your personal pipeline request is at https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?uuid=90d6ce83-529b-4602-b3da-b3d65aaa2145

Target locations of links might be accessible only to IBM employees.

2024-11-18 22:31 UTC, contbld commented
<h3>Code analysis and actions</h3>
DO NOT DELETE THIS COMMENT.

- 7 FAT files were changed, added, or removed.
 - Check that the build did not break the affected FAT suite(s).

2024-11-19 16:31 UTC, Channyboy commented
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.health.3.1.internal_fat

2024-11-20 22:56 UTC, Channyboy commented
#build
#spawn.fullfat.buckets=io.openliberty.microprofile.health.3.1.internal_fat

2024-11-21 19:36 UTC, pgunapal requested changes
minor comments

2024-11-21 19:36 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/DefaultOverallStartupStatusUpAppStartupFastTest.java
> +        //ShrinkHelper.exportAppToServer(server, app, DeployOptions.DISABLE_VALIDATION, DeployOptions.SERVER_ONLY);
can we can remove this?

2024-11-21 19:36 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckTest.java
> -        server1.setMarkToEndOfLog();
Don't we need this, if we are using `waitForStringInLogUsingMark` to search, throughout the test class?

2024-11-21 19:36 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/DefaultStartupOverallStatusHealthCheckFast/server.xml
> +	<logging traceSpecification="*=info:HEALTH=all:logservice=all=enabled:io.openliberty.org.eclipse.microprofile.health.3.1.*=all=enabled"/>
formatting

2024-11-21 19:36 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/InvalidDefaultStartupOverallStatusPropertyFast/server.xml
> +	<logging traceSpecification="*=info:HEALTH=all:logservice=all=enabled:io.openliberty.org.eclipse.microprofile.health.3.1.*=all=enabled"/>
formatting

2024-11-21 19:36 UTC, pgunapal commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/publish/servers/SlowAppStartupHealthCheckFast/server.xml
> +	<logging traceSpecification="*=info:HEALTH=all:logservice=all=enabled:io.openliberty.org.eclipse.microprofile.health.3.1.*=all=enabled"/>
formatting

2024-11-21 20:32 UTC, Channyboy commented on dev/io.openliberty.microprofile.health.3.1.internal_fat/fat/src/io/openliberty/microprofile/health31/fat/SlowAppStartupHealthCheckTest.java
> -        server1.setMarkToEndOfLog();
The Previous `waitForStringInLog` or `waitForStringInLogUsingMark` will update the marks the if it has found the message.

See:
https://github.com/OpenLiberty/open-liberty/blob/integration/dev/fattest.simplicity/src/componenttest/topology/impl/LogMonitor.java#L223

2024-11-21 20:35 UTC, Channyboy commented
#libby

2024-11-25 16:09 UTC, pgunapal approved these changes
LGTM

2024-11-25 18:58 UTC, merged