Switching Libby to be run via manual trigger
OpenLiberty/open-liberty pull request #30248
Opened 2024-11-20 10:54 UTC by websterc87

Delivery validation checks are now included in every personal build. This target should only be used in extreme circumstances where waiting for a personal build is not sensible. Developers we running these delivery checks too often and causing confusion sometimes delivering without a passing PB. This change migrates this rarely used function to be a CI orchestrator manual trigger launchable via our cognitive ui.

2024-11-20 10:55 UTC, websterc87 commented
~!pbbeta~ This failed due to bad yml (missing quotes) fixed now

2024-11-21 18:53 UTC, wraschke commented
@websterc87 that keyword didn't trigger a beta pipeline and anyway, wouldn't test the config file you changed.

I'd like to wait on making such a change--removing long-existing functionality of user commenting with Libby keyword, then seeing work done in the PR--until I can get feedback from users at the upcoming EOI meeting. Or, at the very least, give them enough notice of this change. If I merged this now, it would abruptly stop that expected behavior (or until the users' feature branches get the commit) and introduce confusion.

2024-11-22 18:51 UTC, wraschke reviewed
I'm not taking any action on PR until discussion at the upcoming EOI meeting.

2024-11-27 16:25 UTC, websterc87 commented
!build@dev

2024-11-28 09:30 UTC, websterc87 commented
!build

2025-07-02 20:58 UTC, wraschke requested changes
Chris, can you add to the description to make clear it is not a replacement for the "Open Liberty Personal Build?"

For example:

"Examines Open Liberty code changes for delivery standards compliance. Not a replacement for the Open Liberty Personal Build."

Something like that.

2025-07-03 07:19 UTC, websterc87 commented
!build

2025-07-03 13:49 UTC, wraschke approved these changes

2025-07-03 13:49 UTC, merged