AES256 password encoding - FAT test updates
OpenLiberty/open-liberty pull request #30259
Opened 2024-11-20 18:28 UTC by Zech-Hein

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

2024-11-20 18:32 UTC, Zech-Hein commented
#build

2024-11-20 19:50 UTC, mshah0722 commented on dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
> +                fail("decode AES256 encoded password should have failed with InvalidPasswordDecodingException when beta is disabled.");
fail("Expected InvalidPasswordDecodingException when decoding an AES-256 password with beta disabled.");

2024-11-20 20:07 UTC, mshah0722 requested changes

2024-11-20 20:07 UTC, mshah0722 commented on dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
> +                fail("decode AES256 encoded password should have failed with InvalidPasswordDecodingException when beta is disabled.");
fail("Expected InvalidPasswordDecodingException when decoding an AES-256 password with beta disabled.");

2024-11-20 20:10 UTC, mshah0722 commented on dev/com.ibm.ws.crypto.passwordutil/test/com/ibm/websphere/crypto/PasswordUtilTest.java
> +                fail("decode AES256 encoded password should have failed with InvalidPasswordDecodingException when beta is disabled.");
```suggestion
                fail("Expected InvalidPasswordDecodingException when decoding an AES-256 password with beta disabled.");
```

2024-11-20 20:13 UTC, Zech-Hein commented
#build

2024-11-20 20:16 UTC, mshah0722 approved these changes, later dismissed
LGTM!

2024-11-23 22:09 UTC, Zech-Hein commented
#build

Added jvm.options updates for enabling beta mode

2024-11-25 00:51 UTC, mshah0722 approved these changes
LGTM!

2024-11-25 14:14 UTC, merged