Enable the J2EE Management feature to use the Checkpoint Rule
OpenLiberty/open-liberty pull request #30299
Opened 2024-11-26 20:18 UTC by SmithaSubbarao

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

################################################################################################

# Delete this section and fill in the remaining info from the template

ATTENTION, READ THIS: Updated July 2024 

Read and understand this completely, then delete the static part of the template. 

If a reviewer or merger sees this template, they should fail the review or merge.

If this code change is fixing a user-visible bug in previously released code, it MUST
have an associated issue **mentioned in the PR text or description**.  
 
   - That Issue also MUST be labelled “release bug”

     This directs automation to scrape this fix for inclusion in the next release's
     list of bugs fixed.

   - The linkage between PR and Issue should use the `Fixes #...` syntax rather than a manual
     link via the Development widget.

Otherwise, a link to an issue or specific issue labels are optional.

For full details, please see this wiki page: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions
################################################################################################

2025-01-30 18:38 UTC, SmithaSubbarao commented
Local Testing is completed for the EJBJ2EEManagementTest.java class, the full bucket and Checkpoint tests

2025-01-30 18:39 UTC, SmithaSubbarao commented
#build

2025-01-31 05:10 UTC, SmithaSubbarao commented
The [build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=d7b6dc48-e168-43d0-b05a-c02a8486c643&tab=Tests
) has an error in the bucket, ```unit_com.ibm.ws.messaging.msgstore```:
```
java.lang.Exception: RollbackException occurred with unexpected causal exception
	at com.ibm.ws.sib.msgstore.test.persistence.objectManager.PersistenceFullTest.testPersistenceFull(PersistenceFullTest.java:115)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:575)
	at junit.framework.TestCase.runTest(TestCase.java:168)
	at com.ibm.js.test.LoggingTestCase.runTest(LoggingTestCase.java:359)
	at junit.framework.TestCase.runBare(TestCase.java:134)
	at junit.framework.TestResult$1.protect(TestResult.java:110)
	at junit.framework.TestResult.runProtected(TestResult.java:128)
	at junit.framework.TestResult.run(TestResult.java:113)
	at junit.framework.TestCase.run(TestCase.java:124)
	at junit.framewo
```

2025-02-03 17:26 UTC, SmithaSubbarao commented
#build

2025-02-03 20:36 UTC, tjwatson requested changes

2025-02-03 20:36 UTC, tjwatson commented on dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/fat/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/tests/EJBJ2EEManagementTest.java
> -    public static RepeatTests r = RepeatTests.with(FeatureReplacementAction.EE7_FEATURES().fullFATOnly().forServers("com.ibm.ws.ejbcontainer.management.j2ee.fat")).andWith(FeatureReplacementAction.EE
We should not disable the repeat of EE7_FEATURES here.  Instead we should add the EE7 repeat ID to the `addUnsupportedRepeatIDs` of the checkpoint rule.  You already added the `EmptyAction.ID` there, but I am unclear which run that is skipping since you updated the base server to use EE7 features.

2025-02-03 20:38 UTC, tjwatson commented on dev/fattest.simplicity/src/componenttest/rules/repeater/CheckpointRule.java
> +    public CheckpointRule setAssertNoAppRestartOnRestore(boolean checkrestart) {
This new method is never called?

2025-02-04 19:52 UTC, tjwatson requested changes

2025-02-04 19:52 UTC, tjwatson commented on dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/fat/src/com/ibm/ws/ejbcontainer/management/j2ee/fat/tests/EJBJ2EEManagementTest.java
> -    public static RepeatTests r = RepeatTests.with(FeatureReplacementAction.EE7_FEATURES().fullFATOnly().forServers("com.ibm.ws.ejbcontainer.management.j2ee.fat")).andWith(FeatureReplacementAction.EE
This still needs to be addressed.

2025-02-04 19:52 UTC, tjwatson commented on dev/com.ibm.ws.ejbcontainer.management.j2ee_fat/publish/servers/com.ibm.ws.ejbcontainer.management.j2ee.fat/server.xml
> +        <feature>servlet-4.0</feature>
We should not update the base `server.xml` here.  It should stay with the EE7 feature set since we skip EE7 in the `CheckpointRule`

2025-02-04 20:47 UTC, SmithaSubbarao commented
#build

2025-02-06 22:39 UTC, SmithaSubbarao commented
#build

2025-02-17 16:29 UTC, tjwatson approved these changes

2025-02-17 19:29 UTC, merged