Update CDITestCheckpoint to remove incorrect server configuration
OpenLiberty/open-liberty pull request #30401
Opened 2024-12-11 21:11 UTC by SmithaSubbarao

- [ ] I have considered the risk of behavior change or other zero migration impact (https://github.com/OpenLiberty/open-liberty/wiki/Behavior-Changes).
- [ ] If this PR fixes an Issue, the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN" (verify `release bug` label if applicable: https://github.com/OpenLiberty/open-liberty/wiki/Open-Liberty-Conventions).
- [ ] If this PR resolves an external Known Issue (including APARS), the description includes "Fixes #FILLMEIN" or "Resolves #FILLMEIN".

2024-12-12 19:15 UTC, SmithaSubbarao commented
Test info:

1. CDITestCheckpoint:
```
 [startAnt]     [mkdir] Created dir: /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html
 [startAnt] [junitreport] Processing /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit/TESTS-TestSuites.xml to /tmp/null1783655175
 [startAnt] [junitreport] Loading stylesheet jar:file:/usr/share/java/ant-junit-1.10.12.jar!/org/apache/tools/ant/taskdefs/optional/junit/xsl/junit-frames.xsl
 [startAnt] [junitreport] Transform time: 887ms
 [startAnt] [junitreport] Deleting: /tmp/null1783655175
 [startAnt]      [echo] HTML report is available at /root/open-liberty-instanton-setup/ub2204/open-liberty/dev/com.ibm.ws.jbatch.open_fat/build/libs/autoFVT/results/junit.html/index.html
 [startAnt] 
 [startAnt] BUILD SUCCESSFUL
 [startAnt] Total time: 1 second

archiveReports:

execute:

BUILD SUCCESSFUL
Total time: 1 minute 16 seconds

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.1/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD SUCCESSFUL in 5m 9s
358 actionable tasks: 69 executed, 289 up-to-date
```

2024-12-12 20:47 UTC, SmithaSubbarao commented
#build

2024-12-13 15:50 UTC, tjwatson requested changes

2024-12-13 15:50 UTC, tjwatson commented on dev/com.ibm.ws.jbatch.open_fat/fat/src/batch/fat/junit/CDITestCheckpoint.java
>          BatchFATHelper.setConfig("CDITestCheckpoint/server.xml", testClass);
Originally I had suggested that we continue to use the `checkpointbatchFAT` server but move the file `dev/com.ibm.ws.jbatch.open_fat/publish/files/CDITestCheckpoint/server.xml` to `dev/com.ibm.ws.jbatch.open_fat/publish/servers/checkpointbatchFAT/server.xml` and remove this `setConfig` call.

I think that would be more clean than copying the config over into the `batchFAT` server assigned by the super class.

2024-12-13 18:13 UTC, SmithaSubbarao commented
#build ([view Open Liberty Personal Build](https://libh-proxy1.fyre.ibm.com/cognitive/pipelineAnalysis.html?pipelineId=f4ba31a4-8bac-4b40-88af-e3b342cf3d5a) - :white_check_mark: completed successfully!)

_Note: Target locations of links might be accessible only to IBM employees._

2024-12-13 19:47 UTC, tjwatson commented on dev/com.ibm.ws.jbatch.open_fat/publish/servers/checkpointbatchFAT/server.xml
> +    <include location="../fatTestPorts.xml" />
You should delete the original file at `dev/com.ibm.ws.jbatch.open_fat/publish/files/CDITestCheckpoint/server.xml`

2024-12-13 19:58 UTC, tjwatson approved these changes

2024-12-13 20:33 UTC, SmithaSubbarao commented
#build

2024-12-16 19:50 UTC, closed without merging